### ISSUE TITLE
Default ES heap size is too high

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#100]
@sharand reported in Gitter that his ES instance was being killed automatically (`dockerelk_elasticsearch_1 exited with code 137`).

I've seen that happening myself in Docker for Mac, which has only 2GB of RAM available by default. With the default set to `ES_JAVA_OPTS: "-Xms1g -Xmx1g"` we're already reserving half of the total memory for ES alone.

I've been experimenting myself with `ES_JAVA_OPTS: "-Xms256m -Xmx256m"` and never had any issue so far. While these values are definitely too low for production, I would suggest we make it the default in the repo and add instructions in the README for people who would want to increase it.

See also: https://www.elastic.co/guide/en/elasticsearch/guide/master/heap-sizing.html

@deviantony thoughts?

**Comment by deviantony** [comment]
@antoineco +1, this repo is aimed to help people who are starting to learn/play with ELK and not to be a production ready solution. Lowering the default ES heap size and adding instructions to increase it is a good solution.
