### ISSUE TITLE
Unable to generate CSV Reports - failed to decrypt - 8.14.1

### ISSUE THREAD

**Issue by boredchilada** [deviantony/docker-elk#1003]
### Problem description

So I recently setup the docker-elk followed  the guide as best as i understood it. I'm currently facing an issue where i try to generate reports but im met with this error

ReportingError(code: unknown_error) "Failed to decrypt report job data. Please ensure that xpack.reporting.encryptionKey is set and re-generate this report. Error: Unsupported state or unable to authenticate data"

I have run the docker-compose setup command already and i downgraded to the basic license.

#### Stack configuration

No information was changed from the default (which may be why)

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:29 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:29 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker-compose version

Docker Compose version v2.23.3
```

#### Container logs

full output doesnt fit here...

```console
$ docker-compose logs
see file included
```
[elasticsearch-1timestamp2024.txt](https://github.com/user-attachments/files/16146956/elasticsearch-1timestamp2024.txt)

![image](https://github.com/deviantony/docker-elk/assets/82670806/32ae62e8-8501-4260-961e-c93fbecc4f58)

![image](https://github.com/deviantony/docker-elk/assets/82670806/31499c84-fed4-4ad4-bc24-29909e829d20)

![image](https://github.com/deviantony/docker-elk/assets/82670806/658dd1d4-9676-4d74-9b5a-deae74742803)

**Comment by antoineco** [comment]
Have you tried generating a key as described in the sample Kibana config (see below), and restarted Kibana for the changes to effect?

https://github.com/deviantony/docker-elk/blob/6bf8feaebbdc0ef2a55b8654ee7d41c020504a6f/kibana/config/kibana.yml#L17-L28

**Comment by antoineco** [comment]
Closing because the issue has to do with the usage of Elastic products, and is not an issue specific to docker-elk.
Besides, a solution was provided.
