### ISSUE TITLE
Kibana fails to auth on fresh git clone docker compose up

### ISSUE THREAD

**Issue by jseifeddine** [deviantony/docker-elk#1023]
### Problem description

Kibana fails to authenticate after a a fresh `git clone` && `docker compose up` 
I set the passwords in `.env` 

#### Stack configuration

git clone 
`commit 4cc9ac726283af10d11e96aef3b5dd7df7ce3548 (HEAD -> main, origin/main, origin/HEAD)`

#### Docker setup

```console
$ docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker-compose version

Docker Compose version v2.29.7
```

#### Container logs

```console
$ docker-compose logs
elasticsearch-1  | {"@timestamp":"2024-10-07T23:34:10.414Z", "log.level": "INFO", "message":"Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","trace.id":"8bcb4ae09459b2c757721a16e74cb331","elasticsearch.cluster.uuid":"f0ehae7cTZmy2LupeZh9Ag","elasticsearch.node.id":"DIAvNaMXSoSFytHFFJMyTQ","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
kibana-1  |     Root causes:
kibana-1  |             security_exception: unable to authenticate user [kibana_system] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]
```

**Comment by jseifeddine** [comment]
Figured it out - I had to do this

`docker compose --profile setup up -d` 

PS. Had a little help from ChatGPT. 

The issue with the `setup` container not starting on `docker compose up -d` is likely because it's tied to a non-default profile called `setup`. Docker Compose will not automatically start services associated with non-default profiles unless you explicitly specify the profile or the service.

### To fix this:
- Run the following command to include the `setup` profile:

```bash
docker compose --profile setup up -d
```

Alternatively, if you want to run just the `setup` service, use:

```bash
docker compose up setup
```

This behavior is by design, as outlined in the comments of your `docker-compose.yml` file. The `setup` service is only meant to be run during the initial startup or when resetting credentials.

**Comment by jseifeddine** [comment]
Figured it out - I had to do this

`docker compose --profile setup up -d` 

PS. Had a little help from ChatGPT. 

The issue with the `setup` container not starting on `docker compose up -d` is likely because it's tied to a non-default profile called `setup`. Docker Compose will not automatically start services associated with non-default profiles unless you explicitly specify the profile or the service.

### To fix this:
- Run the following command to include the `setup` profile:

```bash
docker compose --profile setup up -d
```

Alternatively, if you want to run just the `setup` service, use:

```bash
docker compose up setup
```

This behavior is by design, as outlined in the comments of your `docker-compose.yml` file. The `setup` service is only meant to be run during the initial startup or when resetting credentials.

**Comment by antoineco** [comment]
The command is given clearly right at the beginning of the README, why all those efforts asking ChatGPT'?

**Comment by jseifeddine** [comment]
@antoineco  not in the order that is in the README ...

Just sharing my issue with the exact git clone, copy paste didn't work outcome. 

I even tried on another server entirely - same issue.

**Comment by antoineco** [comment]
![Screenshot_20241008-065007](https://github.com/user-attachments/assets/332abfe4-0e51-4a0b-a538-8dbeb0b741ed)
