### ISSUE TITLE
docker consider file as a directory?!

### ISSUE THREAD

**Issue by mireczatko** [deviantony/docker-elk#103]
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/usr/share/logstash/config, exception=Errno::EISDIR, message=>Is a directory - /usr/share/logstash/config/logstash.yml

**Comment by antoineco** [comment]
@mireczatko when the target file doesn't exist Docker creates it as a directory.
Stop your containers and create the `/usr/share/logstash/config/logstash.yml` file before mounting it.

**Comment by mireczatko** [comment]
@antoineco thank you

**Comment by antoineco** [comment]
Glad you solved it!
