### ISSUE TITLE
Xpack images license issue

### ISSUE THREAD

**Issue by theduke** [deviantony/docker-elk#107]
The images this project uses are the new official, custom hosted images by Elastic.

Those all contain XPack and are therefore not free to use but require a license.

**Comment by floragunncom** [comment]
You can use this branch https://github.com/deviantony/docker-elk/tree/searchguard
Search Guard is free and Apache 2 licensed.

**Comment by antoineco** [comment]
@theduke this repo doesn't include any code from X-Pack, it uses the artefacts (Docker images) from Elastic. Besides, X-Pack works in trial mode if you don't own a license, and all X-Pack features are *disabled* by default on the master branch.

**Comment by theduke** [comment]
@antoineco the new official images on their custom container registry do contain X-Pack automatically.

**Comment by antoineco** [comment]
Yes, I got you, but what's the problem with that? As I said, it's installed by default but *disabled* in this repo.

**Comment by deviantony** [comment]
X-Pack comes with a free trial license model, I too don't see what is the problem here.

**Comment by antoineco** [comment]
@theduke could you clarify the issue so that we can decide whether we close this or take actions?
