### ISSUE TITLE
Should we default to single node and avoid bootsrap checks?

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#108]
### Situation

Recently two users reported their Elasticsearch crashed on startup because they forgot to tune their kernel as mentioned in the README.

In the old Docker Elasticsearch image the `zen` plugin was disabled by default in order to prevent the bootstrap check (see docker-library/elasticsearch#153). This was not ideal because one couldn't just use `docker-compose scale` to create an Elasticsearch cluster, on the other hand it removed the necessity to tune the `vm.max_map_count` kernel parameter to use this project.

### Proposal

I'm wondering if we shouldn't either:

  * default to single-node mode and redirect users to the [Wiki page](https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster) if they want to enable clustering

or

  * use [`http/transport.host` instead of `network.host`](https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml#L2) in order to disable the bootstrap check, as described in [Bootstrap checks](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/bootstrap-checks.html) (last sentence).

Opinions wanted :)

**Comment by deviantony** [comment]
I agree with the first proposal, this repo was created to introduce users to the usage of Elasticsearch and do not propose any production ready setup. Having them being able to play with it by removing this prerequisite would be even simpler to them, hence my +1.

Of course, adding a line in the README to point out to the docs for clustering is mandatory in that case.

If I understand correctly, ES should start in development mode with the default configuration, thus it should disable the bootstrap checks?

**Comment by antoineco** [comment]
Yes by default it starts in development mode **but** is accessible on localhost only, which is problematic if you want to plug Kibana or Logstash to it. However if you configure it with

```
transport.host = 0.0.0.0
http.host = 0.0.0.0
```

instead of


```
network.host = 0.0.0.0
```

the bootstrap checks will be bypassed (at your own risk). It's kind of counter intuitive but it's the only way to disable the checks without having ES listening on localhost only.

**Comment by deviantony** [comment]
Ok, then I'd go for this option with an updated README specifying that the stack will start Elasticsearch in development mode with bootstrap checks disabled and some instructions to switch back to production mode (Wiki link is fine).

**Comment by antoineco** [comment]
This trick doesn't seem to work unfortunately:
`[pwAI_xB] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks`
