### ISSUE TITLE
installing plugin and java.net.UnknownHostException: artifacts.elastic.co

### ISSUE THREAD

**Issue by murdav** [deviantony/docker-elk#111]
Dear All,

I added in elasticsearch/DockerFile:
RUN elasticsearch-plugin install analysis-icu
and I got a 

```
Building elasticsearch
Step 1/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0
 ---> ccec59a7dd84
Step 2/2 : RUN elasticsearch-plugin install analysis-icu
 ---> Running in 3f0a4184fbc0
-> Downloading analysis-icu from elastic

Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
```

It's clear a proxy or DNS related issue (again). 

As suggested https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html I tried:
```
docker exec -it dockerelk_elasticsearch_1 bash
export HTTP_PROXY=http://IP_PROXY:PORT
bin/elasticsearch-plugin install analysis-phonetic
```

But it doesn't work, the same if adding https://docs.docker.com/engine/admin/systemd/#http-proxy

What is the best practice to solve this?

D

**Comment by antoineco** [comment]
@murdav can you resolve `artifacts.elastic.co` from your host?

Example:
```
❯ nslookup artifacts.elastic.co

Non-authoritative answer:
artifacts.elastic.co	canonical name = dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com.
Name:	dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com
Address: 54.243.211.74
Name:	dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com
Address: 107.21.249.70
Name:	dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com
Address: 107.22.208.105
```

**Comment by murdav** [comment]
@antoineco thanks for replying.
No, I cannot, it's again a DNS problem after a Docker update. 
Basically --dns doesn't work while using run, having DOCKER_OPTS the same,  the same having the dns: in the compose, bah...

Now I'm trying to understand where is my issue in this list of issues:
https://github.com/docker/docker/search?q=dns&type=Issues&utf8=%E2%9C%93

It's not strictly related to docker-elk, as I was initially thinking.

**Comment by murdav** [comment]
I didn't have time to dig why Docker still has DNS problems.

I solved like:

Download the plugins
https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-5.3.0.zip
https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-phonetic/analysis-phonetic-5.3.0.zip

copy the files to the host machine, e.g. /

docker cp analysis-icu-5.3.0.zip dockerelk_elasticsearch_1:/analysis-icu-5.3.0.zip
docker cp analysis-phonetic-5.3.0.zip dockerelk_elasticsearch_1:/analysis-phonetic-5.3.0.zip

docker exec -it dockerelk_elasticsearch_1 bash
bin/elasticsearch-plugin install file:/analysis-icu-5.3.0.zip
bin/elasticsearch-plugin install file:/analysis-phonetic-5.3.0.zip

D

**Comment by antoineco** [comment]
Not ideal but glad it works!

**Comment by arsen-kha** [comment]
Hi! I have elk of version 6.0.0 and got the same problem, that was solved by adding variable `ES_JAVA_OPTS` with http and https proxy settings  to dockerfile 
```
ENV ES_JAVA_OPTS="$ES_JAVA_OPTS -Dhttp.proxyHost=host -Dhttp.proxyPort=port -Dhttps.proxyHost=host -Dhttps.proxyPort=port"
```

**Comment by jieyangCarenity** [comment]
> Hi @murdav, @antoineco ! I have elk of version 6.0.0 and got the same problem, that was solved by adding variable `ES_JAVA_OPTS` with http and https proxy settings to elasticsearch dockerfile
> 
> ```
> ENV ES_JAVA_OPTS="$ES_JAVA_OPTS -Dhttp.proxyHost=host -Dhttp.proxyPort=port -Dhttps.proxyHost=host -Dhttps.proxyPort=port"
> ```

This solved my probem . Thanks
