### ISSUE TITLE
depreciation warning running log stash

### ISSUE THREAD

**Issue by scanlonjts** [deviantony/docker-elk#114]
sending apache log in via nc - 

elasticsearch_1  | [2017-04-24T10:52:02,571][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.

**Comment by antoineco** [comment]
It's an expected deprecation message, which will hopefully disappear after the next logstash update.
