### ISSUE TITLE
works with swarm?

### ISSUE THREAD

**Issue by leon-wu** [deviantony/docker-elk#118]
can i run it on swarm?

**Comment by antoineco** [comment]
It should, can you try and provide feedback?

**Comment by deviantony** [comment]
It should work well on Swarm Standalone. To be deployed as a Swarm service (using Swarmkit) the compose file might need to be upgraded to v3.

**Comment by antoineco** [comment]
@leon-wu did you have time to try this? Can we close this?

**Comment by dschaper** [comment]
Would be interested in running Swarm/Stack. Does this still need to be addressed?

**Comment by deviantony** [comment]
@dschaper try it and let us know :-)
