### ISSUE TITLE
logstash  exited with code 0 just after started

### ISSUE THREAD

**Issue by chaokunyang** [deviantony/docker-elk#119]
I just clone the docker-elk repository, and exec with docker-compose up. The elasticsearch and kibana works, but logstash exited with code 0 just after started. I noticed there is already in issue: https://github.com/deviantony/docker-elk/issues/35, but seems didn't solve it, so I issue it.

Here are the logs:
```
logstash_1       | Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
logstash_1       | 03:34:46.728 [main] INFO  logstash.setting.writabledirectory - Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
logstash_1       | 03:34:46.798 [LogStash::Runner] INFO  logstash.agent - No persistent UUID file found. Generating new UUID {:uuid=>"f64c648c-a8b9-4e39-a0a7-e01d172413b0", :path=>"/var/lib/logstash/uuid"}
logstash_1       | 03:34:47.310 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>125}
logstash_1       | 03:34:47.379 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started
logstash_1       | 03:34:47.553 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
logstash_1       | 03:34:50.439 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}
dockerelk_logstash_1 exited with code 0
```
Any ideas?

**Comment by antoineco** [comment]
It stops before any input is enabled (tcp:5000 by default), did you delete the pipeline file?

**Comment by chaokunyang** [comment]
I use to command 'docker exec -it $containerId /bin/sh'  into the logstash_container, but the dir /usr/share/logstash/pipeline doesn't exist. So I do the same to elasticsearch and kibana container. And the same result. It seems neither volume mounted. I'm using Docker version 17.03.0-ce, build 60ccb22. It shouldn't work like this, I will try to figure it out

**Comment by antoineco** [comment]
Could you share your docker-compose file and the content of your local `logstash/` directory?

**Comment by chaokunyang** [comment]
Sorry for replying so late. I clone the docker-elk repository and made some changes. Here is the complete code  that I used to run elk: https://github.com/chaokunyang/docker-elk. As you can see,  I didn't delete the pipeline file.

**Comment by antoineco** [comment]
@chaokunyang you're using [**deprecated** images](https://hub.docker.com/_/logstash/). Please revert chaokunyang/docker-elk@2ba45e870376f0b209b769cbee251dfcf83c5cf2 and reopen this issue if the problem surfaces again.

**Comment by chaokunyang** [comment]
It works correct now, thank you
