### ISSUE TITLE
elasticsearch does not seem like like the suggested "volumes"

### ISSUE THREAD

**Issue by kootenpv** [deviantony/docker-elk#122]
Could you confirm that it is not working? I'm following the readme's suggestion.

**Comment by antoineco** [comment]
What's your error exactly? What volume are you referring to?

Attempt to reproduce after a complete reset:
```
❯ docker-compose up elasticsearch
Creating network "dockerelk_elk" with driver "bridge"
Building elasticsearch
WARNING: Image for service elasticsearch was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating dockerelk_elasticsearch_1
Attaching to dockerelk_elasticsearch_1
elasticsearch_1  | [2017-05-10T15:13:18,426][INFO ][o.e.n.Node               ] [] initializing ...
[...]
elasticsearch_1  | [2017-05-10T15:13:22,712][INFO ][o.e.n.Node               ] [6lwru58] started
```

No error.

```
❯ curl localhost:9200
{
  "name" : "6lwru58",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "DW-YuAbvQuObi9cXyGYwFA",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by kootenpv** [comment]
Sorry, I meant the adding of a volume under elasticsearch (it's mentioned in the README). It first complained about not having permissions to write to the folder, and then I couldn't see a clear error in the logs, but it certainly wasn't working (container exits).

**Comment by antoineco** [comment]
So you must be referring to this?
```yaml
  volumes:
    - /path/to/storage:/usr/share/elasticsearch/data
```

ref. https://github.com/deviantony/docker-elk/issues/115#issuecomment-299910194

#### On Linux

In this example the `/path/to/storage` must be owned by the `elasticsearch` user (uid:1000/gid:1000) otherwise ES can't create its data directories.

#### On macOS

Docker for Mac maps the directory permissions for you between the moby VM and your local filesystem so you don't have anything to do here. However, the local volume **must be within the /Users filetree**.

**Comment by kootenpv** [comment]
@antoineco Wow, I did not see that coming. It seems weird that the elasticsearch user in the container would have to "exist" on the host as well? I'll try this out. Thanks a lot :)!

Also funny that you've discussed this only 2 days ago...

**Comment by antoineco** [comment]
Glad to help :)
The elasticsearch user does not need to exist on the host, you only need to `chown -R 1000:1000` the data directory on your host so that the uid:gid matches the user inside the container :ok_hand:

**Comment by kootenpv** [comment]
Yea, it worked :) Great!

**Comment by rong0312** [comment]
> So you must be referring to this?
> 
> ```yaml
>   volumes:
>     - /path/to/storage:/usr/share/elasticsearch/data
> ```
> 
> ref. [#115 (comment)](https://github.com/deviantony/docker-elk/issues/115#issuecomment-299910194)
> 
> #### On Linux
> In this example the `/path/to/storage` must be owned by the `elasticsearch` user (uid:1000/gid:1000) otherwise ES can't create its data directories.
> 
> #### On macOS
> Docker for Mac maps the directory permissions for you between the moby VM and your local filesystem so you don't have anything to do here. However, the local volume [must be within the `/Users` or `/tmp` filetree](https://docs.docker.com/docker-for-mac/osxfs/).
> 
> eg. `- ./esdata:/usr/share/elasticsearch/data`

Hey, i believe this answer should be mentioned in the wiki page, just waster an hour
wondering why my elastic search containers are down (no logs ofc)

**Comment by antoineco** [comment]
@rong0312 it is mentioned in clear text in the README.
