### ISSUE TITLE
Current Elasticsearch 5.4.0 JAVA_HOME variable not correct

### ISSUE THREAD

**Issue by jbaig** [deviantony/docker-elk#123]
Posted here: https://discuss.elastic.co/t/elasticsearch-docker-5-4-0-image-using-the-wrong-java-env-variable/85275

It appears that the environment variable is wrong and might have to be jre-1.8.0-openjdk.
running 
docker exec dockerelk_elasticsearch_1 bin/init_sg.sh 
for the searchguard is actually saying that it can't find java.

It can be worked around by adding to the Dockerfile: 
ENV JAVA_HOME /usr/lib/jvm/jre-1.8-openjdk
but probably best to wait for elastic to fix the image.

**Comment by antoineco** [comment]
Thanks for reporting that @jbaig, it might be worth opening an issue at https://github.com/elastic/elasticsearch-docker so that the maintainers see it and push a fix. I'll take care of it.

**Comment by antoineco** [comment]
Upstream merged the PR and rebuilt the image with the correct path:
```
❯ docker run --rm \
     docker.elastic.co/elasticsearch/elasticsearch:5.4.0 \
     printenv 'JAVA_HOME'

/usr/lib/jvm/jre-1.8.0-openjdk
```
Closing!
