### ISSUE TITLE
Unable to fetch mapping. Do you have indices matching the pattern?

### ISSUE THREAD

**Issue by yudar1024** [deviantony/docker-elk#125]
when i use docker-compose up -d to start elk . the index is missing. it ask me create an index, but there is a message in bottom Unable to fetch mapping. Do you have indices matching the pattern?

**Comment by antoineco** [comment]
Kibana expects some index to be present in Elasticsearch, which happens automatically as soon as you send something to Logstash.

Quoting the README:
> Now that the stack is running, you'll want to inject logs in it. The shipped Logstash configuration allows you to send content via TCP:
>
> `~$ nc localhost 5000 < /path/to/logfile.log`
>
> And then access Kibana UI by hitting http://localhost:5601 with a web browser.

Note that you can also send a random string to Logstash instead of a real logfile:
```bash
~$ echo "abc" | nc localhost 5000
```

**Comment by antoineco** [comment]
ping @yudar1024, should we close this?
