### ISSUE TITLE
bin/init_sg.sh not found

### ISSUE THREAD

**Issue by romanb52** [deviantony/docker-elk#126]
Hello,
when we run
**docker exec dockerelk_elasticsearch_1 bin/init_sg.sh**

we get:
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bin/init_sg.sh\": stat bin/init_sg.sh: no such file or directory"

Any problem on our side? 

Thanks in advance!

**Comment by antoineco** [comment]
Did you forget to checkout the 'searchguard' branch?

```
git checkout searchguard
```

**Comment by romanb52** [comment]
Oh sorry, yeah I am quite new here. I checked out searchguard, it changed branch or what and then I wanted to "docker-compose up". Unfortunately elasticsearch won't start now. SO I cannot exec that bin/init...

 docker-compose up
Creating network "dockerelk_elk" with driver "bridge"
Creating dockerelk_elasticsearch_1 ...
Creating dockerelk_elasticsearch_1 ... done
Creating dockerelk_logstash_1 ...
Creating dockerelk_kibana_1 ...
Creating dockerelk_logstash_1
Creating dockerelk_kibana_1 ... done
Attaching to dockerelk_elasticsearch_1, dockerelk_logstash_1, dockerelk_kibana_1
elasticsearch_1  | [2017-05-18T11:23:43,202][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2017-05-18T11:23:43,318][INFO ][o.e.e.NodeEnvironment    ] [jV7baWf] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [121.8gb], net total_space [136.7gb], spins? [unknown], types [rootfs]
elasticsearch_1  | [2017-05-18T11:23:43,319][INFO ][o.e.e.NodeEnvironment    ] [jV7baWf] heap size [247.5mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2017-05-18T11:23:43,321][INFO ][o.e.n.Node               ] node name [jV7baWf] derived from node ID [jV7baWfyRuqyxsihMguVsA]; set [node.name] to override
elasticsearch_1  | [2017-05-18T11:23:43,321][INFO ][o.e.n.Node               ] version[5.4.0], pid[1], build[780f8c4/2017-04-28T17:43:27.229Z], OS[Linux/3.16.0-4-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [ingest-common]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [lang-expression]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [lang-groovy]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [lang-mustache]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [lang-painless]
elasticsearch_1  | [2017-05-18T11:23:45,375][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [percolator]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [reindex]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [transport-netty3]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded module [transport-netty4]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded plugin [ingest-geoip]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2017-05-18T11:23:45,376][INFO ][o.e.p.PluginsService     ] [jV7baWf] loaded plugin [x-pack]
elasticsearch_1  | [2017-05-18T11:23:46,997][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [searchguard.authcz.admin_dn.0] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  | Caused by: java.lang.IllegalArgumentException: unknown setting [searchguard.authcz.admin_dn.0] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
elasticsearch_1  |      at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:342) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
elasticsearch_1  |      ... 6 more
elasticsearch_1  |      Suppressed: java.lang.IllegalArgumentException: unknown setting [searchguard.ssl.transport.enforce_hostname_verification] please check that any required plugins are installed, or check the breaking changes documentation for removed settings

**Comment by antoineco** [comment]
Don't be sorry, we're here to help :)

The following message makes me believe that you're still using an image without Searchguard:
```
elasticsearch_1 | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [searchguard.authcz.admin_dn.0] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

First of all make sure that `~ ❯ git branch` returns:
```
  master
* searchguard
  x-pack
```

Then try this:
```
~ ❯ docker-compose down -v
~ ❯ docker-compose build --no-cache 
```

**Comment by romanb52** [comment]
Antoine rocks!
It works great. Sorry, I am dumbo. 

I had correct branch after your initial comment but did not know "build" was required.

**Comment by antoineco** [comment]
In theory it's not required, Docker should see that something changed and bust the cache accordingly. Maybe Compose doesn't do if it sees there is already an image with the expected tag.

**Comment by romanb52** [comment]
probably, right!
