### ISSUE TITLE
Container doesn't get any logs

### ISSUE THREAD

**Issue by Daggerlands** [deviantony/docker-elk#127]
I tweaked this image so that I can monitor pfSense logs. My conainter is listening on port 5140 and pfSense is sending logs to the ip adress of the machine running the container on port 5140 but nothing get there.

**Comment by antoineco** [comment]
> My conainter is listening on port 5140

What container? What input?

**Comment by Daggerlands** [comment]
Container running ELK stack configured to monitor pfSense logs.

Input tcp/udp on 5140

**Comment by antoineco** [comment]
ELK means Elasticsearch/Logstash/Kibama, it's 3 containers here, I just wanted to make sure we were talking about the same thing :)

Is your stack running on a different machine? If yes, did you [expose the TCP/UDP port 5140](https://github.com/deviantony/docker-elk/blob/586302bf4e43a474ab7dbbbcafbd033f2b150589/docker-compose.yml#L22-L23)?

**Comment by Daggerlands** [comment]
No it's one container running the whole stack as services.

The stack and pfSense are running on different machine and I exposed the ports in the Dockerfile

(EXPOSE 5140)

**Comment by Daggerlands** [comment]
I send data to the container when I'm on the machine running it btw (echo "test" | nc localhost 5140)

**Comment by antoineco** [comment]
> No it's one container running the whole stack as services.

It's not, it's 3 separate containers started together, and configured to work together.

> I exposed the ports in the Dockerfile

`EXPOSE` does not actually expose any port, it's purely metadata to indicate what port your service uses. If you want to properly expose a port to the outside you have to bind it to your host. Check the link I posted above and add your own ports please.
