### ISSUE TITLE
Bind mounts do not work with remote Docker deamon

### ISSUE THREAD

**Issue by darshanchaudhary** [deviantony/docker-elk#134]
I am getting this when I do `docker-compose up`
```
 logger (master) ✗ dc up
Creating logger_elasticsearch_1 ... 
Creating logger_elasticsearch_1 ... error

ERROR: for logger_elasticsearch_1  Cannot start service elasticsearch: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/Users/foo/bar/logger/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/0b7be06fbdsadsadds5f8e14dddf0d6c632370b4299300efe5\\\" at \\\"/var/lib/docker/aufs/mnt/0b7bdsadsadasdd2235c5f8e14dddf0d6c632370b4299300efe5/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for elasticsearch  Cannot start service elasticsearch: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/Users/darshanchoudhary/zinnov/logger/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/0b7be06fbd6ef6b20adc69235bd2235c5f8e14dddf0d6c632370b4299300efe5\\\" at \\\"/var/lib/docker/aufs/mnt/0b7be06fbd6ef6b20adc69235bd2235c5f8e14dddf0d6c632370b4299300efe5/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by antoineco** [comment]
@darshanchaudhary did you manage to solve this? If not could you please tell us more about your environment?

**Comment by darshanchaudhary** [comment]
I just cloned the repo and did `docker-compose up`ed and got this error. 
I resolved it by moving all the volume statements to the in individual Dockerfiles.

**Comment by antoineco** [comment]
On which OS / distribution are you running Docker?

If Redhat/CentOS/Fedora it *could* be related to SELinux. The README provides guidance in order to deal with this.

**Comment by darshanchaudhary** [comment]
I was running it on Ubuntu, 16.04

**Comment by antoineco** [comment]
`/Users/darshanchoudhary/zinnov/logger` looks like a macOS path to me, not Linux.

Long story short, Docker is trying to mount a file it can not access. The information provided is insufficient for me to figure out the actual reason I'm afraid.

**Comment by darshanchaudhary** [comment]
The file resides on my mac, and I am [mounting it on my container](https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml#L8) which runs on Linux.
There isn't much info to give really, I created a Ubuntu machine using `docker-machine` and did a `docker-compose up` and got this error.

**Comment by antoineco** [comment]
Mounts will not work in this context, unless the /Users mountpoint is synced with your Linux machine. This can be configured in Virtualbox as far as I remember.

**Comment by darshanchaudhary** [comment]
Huh? 🤔  
I moved the mount statements to `Dockerfile`s and it worked. 

Can you explain what you are proposing?

**Comment by antoineco** [comment]
Of course, but then please let me remind you the importance of being fair to the people trying to help you, and avoid the thumb down reactions. Mentioning the `docker-machine` setup from the beginning could have saved me some confusion and give you the right pointers right away.

---

Docker is running on an Operating System (Ubuntu) which is itself running inside a VM powered by your host (Mac).

The files present on your Mac are not visible from your Linux virtual machine, they reside on a file system which is not accessible by the Docker daemon. Therefore mounting `/Users` will fail because this path does not exist from the standpoint of the Ubuntu box (take a look inside your VM).

Virtualbox has a feature called "Shared Folders" which lets you sync folders between your host machine (Mac) and guest machine (Ubuntu): https://www.virtualbox.org/manual/ch04.html#sharedfolders. I remember that `docker-machine` has a flag that allows you to configure such a folder during the VM creation process, it's called `--virtualbox-share-folder` (source: [Docker Machine VirtualBox drive](https://docs.docker.com/machine/drivers/virtualbox/)).

**Comment by darshanchaudhary** [comment]
Thank you for the pointers, I have since removed the thumbs down. I thought it was a thoughtless comment on your part (about the path being a macOS path)

Also, I agree that I did not provide complete information about my setup. One detail I missed is that I am using docker machine not to create a machine on my PC, but on AWS. I used the `amazonec2` adapter to spawn up an Ubuntu instance there and `docker-compose`ed. 

The directory would not exist there (as you pointed out), but that is the reason we are mounting it in the docker-compose.yml file, isn't it?
The reason I opened the issue is, I cloned the repo, spun up an amazon ec2 ubuntu instance and did `dc up` and it did not work. It failed with the error I pasted 🔝

**Comment by antoineco** [comment]
Great, much clearer now, I appreciate the details :+1:

As you said mounting the files on a remote machine makes it even more complicated than on the local host. Unfortunately docker `volumes` do not work like the `COPY` statement you probably used in your `Dockerfile`. Volumes are created/mounted during the container creation (`docker create/run`), as opposed to the image creation, so the files must really be physically accessible to the Docker daemon at any time.

Some solutions like `rsync` or [`sshfs`](https://github.com/libfuse/sshfs) exist, but I'd rather push the config to the image directly like you did, or use some configuration management system to keep the conf in sync if you run at larger scale.

**Comment by deviantony** [comment]
> The reason I opened the issue is, I cloned the repo, spun up an amazon ec2 ubuntu instance and did dc up and it did not work. It failed with the error I pasted

The goal of this repository is to manage a local ELK stack. I'd recommend the automation of git clone + docker-compose on the remote instance if you want to use this repository.

@antoineco this might need some clarification in the README indeed.

**Comment by brianjill** [comment]
please help i got this error too. i am running docker in windows 7

container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/c/appl/jill/docker-elk/docker-elk/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/da9207cefa5d09a1bc0214938296659e0c6f9f8b7bee13fc39e4922459ad4f40/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/da9207cefa5d09a1bc0214938296659e0c6f9f8b7bee13fc39e4922459ad4f40/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""

**Comment by brianjill** [comment]
did this inside the docker terminal

$ docker-compose up
Starting dockerelk_elasticsearch_1 ...
Starting dockerelk_elasticsearch_1 ... error

ERROR: for dockerelk_elasticsearch_1  Cannot start service elasticsearch: oci ru
ntime error: container_linux.go:262: starting container process caused "process_
linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/c/appl/j
ill/docker-elk/docker-elk/elasticsearch/config/elasticsearch.yml\\\" to rootfs \
\\"/mnt/sda1/var/lib/docker/overlay2/da9207cefa5d09a1bc0214938296659e0c6f9f8b7be
e13fc39e4922459ad4f40/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/da9207
cefa5d09a1bc0214938296659e0c6f9f8b7bee13fc39e4922459ad4f40/merged/usr/share/elas
ticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the
specified host path exists and is the expected type

**Comment by antoineco** [comment]
@brianjill this is a different issue, please continue the discussion in #135

**Comment by ianseyer** [comment]
@deviantony are you saying that deploying this to AWS ECS is a bad idea?

I am attempting to do this very thing - I have compiled each individual Dockerfile into an image, pushed it to a registry, and have created an ecs task definition from the compose file. however, I get this same error when attempting to launch the containers.

Any idea how I would go about launching this on AWS? I understand why this doesn't work, but can't come up with a solution.

**Comment by antoineco** [comment]
Either:

* Bake the configuration files inside the images
* Push the configuration files to your remote Docker hosts

**Comment by deviantony** [comment]
@ianseyer as @antoineco said, I'd clone the git repository directly on the Docker host.

**Comment by dcunited08** [comment]
Any interest in a production version of this that copies the files to the images rather than linking the files using volume?

**Comment by antoineco** [comment]
@dcunited08 not sure if that would make it "production-ready", Docker Compose is a tool for prototyping, not managing the build of Docker images.

The purpose of this repo is exactly to be hackable/extendable, for the case you're describing it should be enough to add a COPY statement inside the provided Dockerfiles. Of course you have to tag and push the images yourself afterwards.

**Comment by vignesh380** [comment]
[Windows] So I had the same issue. This is caused sometimes because of some weird docker error. I did the following to make it working again: 

Under the settings section of the docker windows software, you may have to unshare, share the drive again, re-enter credentials.

**Comment by antoineco** [comment]
Closing this old issue as we now have a stack example that leverages Swarm `configs`.
Additionally, I just added a note clarifying the repo is supposed to be cloned on the target Docker host.

**Comment by abdennour** [comment]
try to use docker context with SSH not tcp
