### ISSUE TITLE
Searchguard branch doesn't work

### ISSUE THREAD

**Issue by hiephm** [deviantony/docker-elk#136]
I encountered this error when using latest searchguard branch:

```
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [searchguard]. Expected [5.4.1]; found [5.4.0]"
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.4.0/searchguard-kibana-5.4.0-2.zip' returned a non-zero code: 70
```

Unfortunately the latest version of search-guard-kibana-plugin is 5.4.0, seem that we need to wait til 5.4.1 is released.

**Comment by antoineco** [comment]
Thanks for reporting this, I assumed this would work regardless of the patch version. I'll revert the Kibana version to 5.4.0 to keep it working.

Pinging @floragunncom for info.

**Comment by jochenkressin** [comment]
No, ES and KI are very very picky about the versions. All versions need to be the same, down to the patch level. This applies for KI, ES, SG and the SG Kibana plugin. In some cases, mixing KI and ES versions work, but I've not figured out the logic behind this yet. So, you should always use the same versions to avoid issues and confusion. BTW - The Kibana plugin for 5.4.1 and also 5.4.2 is already out.
