### ISSUE TITLE
Change default searchguard password

### ISSUE THREAD

**Issue by saggiyogesh** [deviantony/docker-elk#138]
How to change all default passwords on the first initialization.

**Comment by antoineco** [comment]
The procedure is explained here: [Internal users](https://github.com/floragunncom/search-guard-docs/blob/master/internalusers.md). The users are created when you execute the init command described in the README.

Searchguard also has a [management API](https://github.com/floragunncom/search-guard-rest-api/blob/master/README.md) which you can install.

**Comment by floragunncom** [comment]
@saggiyogesh best is to ask searchguard related questions here https://groups.google.com/forum/#!forum/search-guard

**Comment by saggiyogesh** [comment]
Thanks, guys.
