### ISSUE TITLE
documentation error: wrong kibana version

### ISSUE THREAD

**Issue by cjdcordeiro** [deviantony/docker-elk#141]
on the default index example, it should curl against version 5.4.0 and not 5.4.1

**Comment by antoineco** [comment]
Did you mean "5.4.2" instead of "5.4.1" maybe?
If you use the Kibana UI to create your index pattern it generates this:

`❯ curl 'http://localhost:9200/.kibana/_search?pretty'`
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {...},
      {
        "_index" : ".kibana",
        "_type" : "config",
        "_id" : "5.4.2",
        "_score" : 1.0,
        "_source" : {
          "buildNum" : 15117,
          "defaultIndex" : "logstash-*"
        }
      }
    ]
  }
}
```

Anyway, nice catch! 👍  I'll fix that later today.

**Comment by antoineco** [comment]
Closed in 5d5cb49

**Comment by cjdcordeiro** [comment]
actually no, for me it only works with 5.4.0, which kinda makes sense since that's the Kibana version you're pulling in the Dockerfile. All other version will not trigger an error but will also not do anything

**Comment by antoineco** [comment]
You're probably using an old commit then, the current version is 5.4.3:
https://github.com/deviantony/docker-elk/blob/36ca7e52a56f2cb83377682743d233c2ffdd0050/kibana/Dockerfile

**Comment by cjdcordeiro** [comment]
that's true! should've have looked at the history ;)

Best regards,

*Cristóvão Cordeiro*
R&D Project Manager


*8 Rue du Bois-du-Lan*
*1217 Meyrin*
*Geneva*
*Switzerland*
