### ISSUE TITLE
you need to run docker-compose build after modifying Dockerfile

### ISSUE THREAD

**Issue by TomonoriSoejima** [deviantony/docker-elk#143]
I added below in Dockerfile

`RUN elasticsearch-plugin install analysis-kuromoji`

then I ran 
`docker-compose up` 
But the plugin was never added until I ran
`docker-compose build` 

I suppose mentioning this last step in your readme will make your content appealing to docker newbies.

**Comment by antoineco** [comment]
You're right, Docker Compose doesn't automatically catches these changes unfortunately. Thanks for the addition.

**Comment by antoineco** [comment]
Closed by #144
