### ISSUE TITLE
Logstash logs

### ISSUE THREAD

**Issue by MarStarck** [deviantony/docker-elk#145]
My logstash always stops, I wanna see logs, where can I find it?

**Comment by antoineco** [comment]
`docker-compose logs logstash`

**Comment by MarStarck** [comment]
Thanks, I see a lot of logs using this command. I wanna can I enter the place store the logs and manage them manually?

**Comment by antoineco** [comment]
Actually Logstash logs everything to the console, you won't find any log file in your container.

This behaviour is configured in the [Log4j](https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/log4j2.properties) configuration the ships with the official `logstash` image.

If you're familiar with Log4j, you can drop [your own log4j2.properties file](https://github.com/deviantony/docker-elk/blob/ba1acc1fe58071b04fae8f16c9781913da6e895b/README.md#how-can-i-tune-the-logstash-configuration) inside the logstash/config directory and edit the `docker-compose.yml` file accordingly. This way you can alter the default login behaviour in a way which is more suited to your needs.

**Comment by brunsgaard** [comment]
@antoineco Nice reply 👍

**Comment by antoineco** [comment]
@brunsgaard glad it helped!
@MarStarck did this answer your question?

**Comment by MarStarck** [comment]
Yes, it helped a lot! Thanks! And how about elasticsearch?
