### ISSUE TITLE
Can not access kibana ui

### ISSUE THREAD

**Issue by ypwu1** [deviantony/docker-elk#147]
I can not access kibana ui,  also try change the host port mapping, not working either.  Environment: mac osx, docker for mac CE.

**Comment by deviantony** [comment]
Can you give us more information? Such as:

* What branch of this project are you using?
* Docker version
* Compose version
* The output of `docker-compose logs`

**Comment by antoineco** [comment]
Kibana takes a LOT of time to initialize during the first start. Did you give it 2 to 3 full minutes?

**Comment by ypwu1** [comment]
@antoineco, yes, you are right. Thanks for help.
