### ISSUE TITLE
Compose build fails on logspout build

### ISSUE THREAD

**Issue by timelf123** [deviantony/docker-elk#148]
set up a new droplet, ran docker-compose build:
```
package github.com/fsouza/go-dockerclient
        imports context: unrecognized import path "context"
ERROR: Service 'logspout' failed to build: The command '/bin/sh -c go get && go build -ldflags "-X main.Version dev" -o /bin/logspout' returned a non-zero code: 1
```

**Comment by deviantony** [comment]
@timelf123 What command are you using to build it?

**Comment by timelf123** [comment]
`docker-compose build` after spinning up a fresh droplet on DO with docker-machine

**Comment by antoineco** [comment]
`docker-compose build` will only build the main "composition".

`docker-compose -f docker-compose.yml -f extensions/logspout/logspout-compose.yml build` is the command you want to execute.

**Comment by timelf123** [comment]
Sorry to waste your time, I posted this in the wrong repo
