### ISSUE TITLE
Service Logstash Failed to Build

### ISSUE THREAD

**Issue by guid1984** [deviantony/docker-elk#149]
I have just cloned the repo and ran docker-compose and ran into attached issue.
P.S. Did not make any changes yet.
![screen shot 2017-07-14 at 10 00 15 am](https://user-images.githubusercontent.com/8578605/28198398-85f82512-687b-11e7-80f7-39eae4396bbc.png)

**Comment by antoineco** [comment]
Looks like the Elastic Docker registry was feeling a bit dizzy when you executed the command, did you try multiple times? I'm quite sure by now the issue resolved itself.
