### ISSUE TITLE
How to process log file on host system

### ISSUE THREAD

**Issue by sslash** [deviantony/docker-elk#15]
Say I have a web app that is logging to a file that I have mounted with docker volumes, and I want logstash to process this file. Is there a way to configure the logstash container to get access to this file? I am a bit newbie when it comes to Docker and ELK, but I cant seem to find any good docs on this particular case. Thanks!

**Comment by deviantony** [comment]
There is multiple ways of doing what you want:
* you can use a forwarder (such as logstash-forwarder or log-courier) in your webapp container to read and send the logs to the logstash container
* you can mount your log folder on the Docker host and specify it as a volume of the logstash host to read it directly using a file input (this solution is not really scalable)

**Comment by deviantony** [comment]
@sslash Did you managed to solve your problem?

**Comment by deviantony** [comment]
@sslash I'll close this issue. Do not hesitate to reopen it if needed.
