### ISSUE TITLE
Kibana and Logstash not able to connect to ElasticSearch

### ISSUE THREAD

**Issue by guid1984** [deviantony/docker-elk#152]
every thing was working good. I accidentally clicked on "Connect To Host Network"  in elastic container in kitematic. 
![screen shot 2017-07-17 at 9 29 40 pm](https://user-images.githubusercontent.com/8578605/28277298-2c7828de-6b37-11e7-9745-d7a126150735.png)
I reverted the changes and the bridge is dockerelk_elk, but still Kibana and logstash are not able to find elastic searh at http://elasticsearch:9200.

**Comment by antoineco** [comment]
To recreate the stack with the correct network:

```console
$ docker-compose down -v
```

```console
$ docker-compose up
```

Closing since it's not directly related to this project.
