### ISSUE TITLE
how to restart elastic？

### ISSUE THREAD

**Issue by figoluis** [deviantony/docker-elk#157]
how to restart elastic？I can not kill pid 1?please tell me ? how to install ik plugins?

**Comment by antoineco** [comment]
You *can* kill the PID 1, but a better way to do this is to execute:

```console
$ docker-compose restart elasticsearch
```

The answer to your question regarding plugins installation is in the [README](https://github.com/deviantony/docker-elk#how-can-i-add-plugins).
