### ISSUE TITLE
X-Pack Security not disabled

### ISSUE THREAD

**Issue by michael-go** [deviantony/docker-elk#164]
Trying out https://github.com/deviantony/docker-elk/commit/41dc16c734321affa4300c8128431aa7570f73aa (Release 5.5.1)

It seems that although `elasticsearch`'s & `kibana`'s config `.yaml` fles set `xpack.security.enabled: false
`, Security is still enabled and thus `logstash` & `kibana` fail to connect to ES with 401 & 403 errors. 

One way I managed to overcome it was to set auth params everywhere:
`./logstash/pipeline/logstash.conf`:
```
output {
        elasticsearch {
               hosts => "elasticsearch:9200"
               user => elastic
               password => changeme
        }
 }
```

`./kibana/config/kibana.yml`:
```yaml
elasticsearch.username: kibana
elasticsearch.password: changeme
```

Another solution that works, is to remove X-Pack by adding:
`RUN elasticsearch-plugin remove x-pack` to `/elasticsearch/Dockerfile`
`RUN  #kibana-plugin remove x-pack` to `/kibana/Dockerfile`

b.t.w. thanks for maintaining this useful project!

**Comment by antoineco** [comment]
Did you build the `x-pack` branch at any point? If yes, you must rebuild the images when switching to the `master` branch.

Can't reproduce.

**Comment by michael-go** [comment]
Hi, no I didn't even checkout the `x-pack branch`, and I did rebuild it several times to make sure.

maybe it's something to do with docker/compose versions I have?..
`Docker version 17.05.0-ce, build 89658be`
`docker-compose version 1.9.0, build 2585387`

**Comment by antoineco** [comment]
I think your config YAML files are not readable from inside your containers, or simply not mounted.

Take a look at the note in the [Storage section of the README](https://github.com/deviantony/docker-elk#storage), and look for any related error in your startup logs.

**Comment by michael-go** [comment]
Oh ooops, you are totally right 🙈 
I by mistake had two `volumes` clauses inside my `elasticsearch` section in `docker-compose.yaml`, and this it didn't mount the `elasticsearch.yaml` configuration.

sorry for that!

**Comment by antoineco** [comment]
No problem, glad you found the source of your issue 👏

**Comment by antoineco** [comment]
For posterity: starting from 6.0.0 (pushed today) X-Pack is no longer included on the `master` branch.
