### ISSUE TITLE
Environment JVM heap size in docker-compose ignored

### ISSUE THREAD

**Issue by vitohuang** [deviantony/docker-elk#169]
https://github.com/deviantony/docker-elk/blob/f7f08449f2ce6b5f4f78e707af5b61c8ffcc7e91/docker-compose.yml#L13

The above environment get ignore because the elastic search jvm setting take preceding, see the following

```
vito@vito-MacBook ~/dev/docker-elk $ docker exec -i -t dockerelk_elasticsearch_1 /bin/bash
[elasticsearch@57f7a2d39e39 ~]$ pwd
/usr/share/elasticsearch
[elasticsearch@57f7a2d39e39 ~]$ ls
LICENSE.txt  NOTICE.txt  README.textile  bin  config  data  lib  logs  modules  plugins
[elasticsearch@57f7a2d39e39 ~]$ cat config/jvm.options
## JVM configuration

################################################################
## IMPORTANT: JVM heap size
################################################################
##
## You should always set the min and max JVM heap
## size to the same value. For example, to set
## the heap to 4 GB, set:
##
## -Xms4g
## -Xmx4g
##
## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
## for more information
##
################################################################

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms2g
-Xmx2g

################################################################
## Expert settings
################################################################
##
## All settings below this section are considered
## expert settings. Don't tamper with them unless
## you understand what you are doing
##
################################################################

## GC configuration
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
```
As you can see the 2G will override in the environment.

Maybe we can make some change to the Dockerfile that will do a search and replace, then the memory limit will be taken from environment.

**Comment by antoineco** [comment]
@vitohuang what does `ps auxww` return?

**Comment by vitohuang** [comment]
@antoineco Thanks for looking at it.

Here is the result 

```
[elasticsearch@57f7a2d39e39 ~]$ ps auxww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
elastic+     1  2.2 23.7 2860760 423552 ?      Ssl  20:42   4:20 /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.cgroups.hierarchy.override=/ -Xmx256m -Xms256m -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch
elastic+    45  0.0  0.4  67936  7860 ?        Sl   20:42   0:00 /usr/share/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller
elastic+   162  1.0  0.1  11776  2924 pts/0    Ss   23:54   0:00 /bin/bash
elastic+   178  0.0  0.1  47448  3240 pts/0    R+   23:54   0:00 ps auxww
[elasticsearch@57f7a2d39e39 ~]$
```
Not sure which one have the highest priority, but looking from `top` ES definitely use more than 256Mb

**Comment by antoineco** [comment]
The order of the options is actually correct, with the OpenJDK JVM the rightmost options are supposed to take precedence. The reason why it doesn't work in your setup will require some more investigation. Thanks for reporting!

**Comment by antoineco** [comment]
@vitohuang I enabled JMX as described in the README and opened jconsole. Here is what I see:

![ls_jmx](https://user-images.githubusercontent.com/3299086/30747795-94ec1af0-9fae-11e7-8e86-1cb6caae56e8.png)

The Heap is indeed caped to 256m.

If I change the value to `512m` in the compose file:

![ls_jmx](https://user-images.githubusercontent.com/3299086/30747906-e853f550-9fae-11e7-8920-ed0ccddb63ac.png)

The Heap is now caped to 512m.

Can you try to reproduce?

**Comment by vitohuang** [comment]
@antoineco Thanks for looking in to that.

I tried different machine and its working now. 

Not sure why it doesn't work on some.

**Comment by cdalexndr** [comment]
@vitohuang what machine were you using and what machine solved this issue?

**Comment by luhaixun** [comment]
I have the same issue and figure out the root cause. In fact, it's not related to the machine type.

The root cause is that once you create the container, the environment is persisted. You could check the environment inside the containers by `env` bash command to confirm this.

Therefore, the right approach is:

1. Stop the container via `docker-compose stop`
2. Remove the container via `docker-compose rm`, which will only remove the containers and will not remove the volumes so that your data is safe.
3. Start the container again via "docker-compose up -d"

Thanks,
Tim

**Comment by antoineco** [comment]
@luhaixun after changing the environment variables you have to run `docker-compose up` again. Compose will detect the changes, and recreate the containers automatically for you.

**Comment by luhaixun** [comment]
> @luhaixun after changing the environment variables you have to run `docker-compose up` again. Compose will detect the changes, and recreate the containers automatically for you.

In theory, it is. Somehow it doesn't work so I provide the above steps. My docker version is 19.03.5

Thanks,
Tim
