### ISSUE TITLE
Difficulty mounting configuration files on Windows

### ISSUE THREAD

**Issue by ramalo3** [deviantony/docker-elk#176]
Hi ^^

I am new to Docker, so I may be asking really dumb. I've been looking at all the issues that have been closed and I havent found one that solves my problem (this one https://github.com/deviantony/docker-elk/issues/150 seems to refer to the same error). Hope you have patience and I hope you can help me to solve the problem as soon as you can ^^

Once I execute the "docker-compose up" command, it downloads correctly kibana, es and logstash, but once it tries to create the elasticsearch container, the next error occurs:

-------------------------------------------------

```
PS C:\Users\Rafa\Desktop\docker-elk-master> docker-compose up
Removing dockerelkmaster_elasticsearch_1
Recreating 12e3c61ca9a4_dockerelkmaster_elasticsearch_1 ...
Recreating 12e3c61ca9a4_dockerelkmaster_elasticsearch_1 ... error

ERROR: for 12e3c61ca9a4_dockerelkmaster_elasticsearch_1  Cannot start service elasticsearch: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/c/Users/Rafa/Desktop
/docker-elk-master/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/fe48ed5c8292dad869b5a94d9094b72f9fc4ea670a4aa336d91810e185a3304f\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/fe48ed5c8292dad869b5a94d9094b72f9fc4ea670a4aa336d91
810e185a3304f/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for elasticsearch  Cannot start service elasticsearch: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/c/Users/Rafa/Desktop/docker-elk-master/elasticsearc
h/config/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/fe48ed5c8292dad869b5a94d9094b72f9fc4ea670a4aa336d91810e185a3304f\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/fe48ed5c8292dad869b5a94d9094b72f9fc4ea670a4aa336d91810e185a3304f/usr/share/elastic
search/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

------------------------------------------------------

Following the conversation I told you before, I checked I had shared my C: device. I can also tell you Im trying to use Docker in Windows 10 (I think the girl in the conversation does the same).

I really hope you can help me ^^ Sorry for disturbing you and thanks for every help you can give me ^^

**Comment by cristian04** [comment]
+1 Same issue here

**Comment by antoineco** [comment]
Nothing wrong in asking questions @ramalo :)

I never played with Docker for Windows, but the OP in #150 mentioned:
>  i mount my c: drive to /c/
Could it be that you have to define the mount path (`/c/`) manually?

**Comment by ramalo** [comment]
Hi!

I finally did something that made that error to not happen again. I disabled Hyper-V in Windows and installed Docker Toolbox in order to use the Docker Terminal. In that terminal I had no problem when I used docker-compose up.

Hope it helps you in any way @cristian04 

Thanks for the help ^^

**Comment by antoineco** [comment]
Docker Toolbox is the old version relying on VirtualBox right?

**Comment by ramalo** [comment]
I think so. I thought "Docker for Windows" would be a better decision than the Docker Toolbox, but since I got Docker Toolbox and used the Docker Terminal I found no problems (at least in doing correctly a "docker-compose up" command) ^^

**Comment by antoineco** [comment]
Alright thanks for clarifying. I have a Windows 10 machine at hand, I'll install Docker for Windows and try to reproduce.

**Comment by ramalo** [comment]
It might be a problem of my computer: I've never tried to use Docker before, so I am new in these programmes. Anyways, If you can run it without any problems using Docker for Windows I would be glad If you could say If you did something in order to achieve it ^^

**Comment by x2764tech** [comment]
It's worth checking the configuration of [Shared Drives](https://docs.docker.com/docker-for-windows/#shared-drives) within the Docker For Windows settings. It's tripped me up on a number of occasions.

**Comment by gerardnico** [comment]
Shared drive is the clue. See also #150 

Here is a step by step on what I have done to resolve this problem:

https://gerardnico.com/wiki/docker/installation#shared_drive

**Comment by vaxilicaihouxian** [comment]
@gerardnico You save my life.
