### ISSUE TITLE
cannot connect to logstash on port 5044

### ISSUE THREAD

**Issue by lakerzhou-lenovo** [deviantony/docker-elk#178]
I am testing the master ES version 5.6.2. My remote filebeat cannot access logstash via port 5044. I recommend enable 5044 port forwarding by default by adding the following line in logstash section at docker-compose.yml.
   "5044:5044"

**Comment by antoineco** [comment]
Not sure if that would be relevant, we don't have anything listening on TCP port 5044 by default.

https://github.com/deviantony/docker-elk/blob/6cd82cf47abf4c08396f34df9a789d52d0be4c07/logstash/pipeline/logstash.conf#L1-L13

**Comment by MarStarck** [comment]
maybe occupied by other program: try netstat -anp | grep 5044

**Comment by antoineco** [comment]
@lakerzhou-lenovo I would recommend following @MarStarck advice and track which program is listening on that port. If that's Logstash it would mean you configured a custom `input`, which makes that port only relevant within your setup.

**Comment by henriquebortoletti** [comment]
Hi, if you are using logstash with docker, try to make your port available for the other applications which are not in your container.  
You can use the flag -p 5044 when you are installing the docker. 
For example:

docker run -d --name logstash \
-p 5044:5044
--restart=always \
-e "XPACK.MONITORING.ELASTICSEARCH.URL=http://ELASTIC_IP:9200" \
docker.elastic.co/logstash/logstash:7.0.0
