### ISSUE TITLE
Kibana no longer starts

### ISSUE THREAD

**Issue by andrewthad** [deviantony/docker-elk#18]
Change elasticsearch from 0.0.0.0 to non_loopback made kibana stop launching correctly:

https://github.com/deviantony/docker-elk/commit/b3b3c131c18f6b0494ce911672b3d50897b6d73f#diff-04c6e90faac2675aa89e2176d2eec7d8L144

The above commit may need to be undone.

**Comment by deviantony** [comment]
Weird, still works for me ! Maybe this issue is related to your configuration/system?

Anyway, I'll revert the option to 0.0.0.0 !
