### ISSUE TITLE
Multiple node cluster

### ISSUE THREAD

**Issue by kallasramon** [deviantony/docker-elk#180]
This is great project, thanks for that :+1: 

However could you provide some simple tips for multiple node cluster?
Currently the single-node cluster is working fine, however would like to increase at least to two-nodes cluster.

Appreciate it,
Thanks!

**Comment by antoineco** [comment]
Would this work for you?
https://github.com/deviantony/docker-elk#how-can-i-scale-out-the-elasticsearch-cluster

**Comment by kallasramon** [comment]
I have forked your project and adjusted it to multiple node cluster.

https://github.com/kallasramon/docker-elk-cluster

**Comment by antoineco** [comment]
Cool, thanks for sharing your approach!
