### ISSUE TITLE
Data missing in elasticsearch?

### ISSUE THREAD

**Issue by MarStarck** [deviantony/docker-elk#185]
I find there are some log data get lost in elasticsearch and I cannot search for it.
What are possible causes and how to avoid it?

--
I guess adding  filebeat and kafka may help it. Can docker support these tools?

**Comment by antoineco** [comment]
Lost or never received?

**Comment by MarStarck** [comment]
How can I determine it's Logstash problem or Elasticsearch problem or their communication problem?

**Comment by MarStarck** [comment]
Possible causes:
1. some log inputs are not json. I dealt it with Logstash.
2. max_open_file limit. this param should be configured in logtash.conf:
```
input{
    max_open_files => 6144 # 4095 by default
}
```
