### ISSUE TITLE
[ERROR][c.f.s.a.BackendRegistry] Not yet initialized (you may need to run sgadmin)

### ISSUE THREAD

**Issue by zj8487** [deviantony/docker-elk#186]
Hi, Very sorry to trouble you.

I clone this repository and checkout to searchguard branch, and docker-compose up

Then i noticed the following errors, Did i miss some thing on the searchguard branch?

```
[ERROR][c.f.s.a.BackendRegistry  ] Not yet initialized (you may need to run sgadmin)
```

**Comment by antoineco** [comment]
Yes, the answer is in the README :)
Search for "sgadmin".

**Comment by antoineco** [comment]
I'm gonna go ahead and close this, but feel free to comment if you're facing other issues.
