### ISSUE TITLE
Pipeline folder

### ISSUE THREAD

**Issue by ivanrome** [deviantony/docker-elk#188]
Hello,

**Question**: 
* Why logstash config is saved in folder named `pipeline`? Should the folder be named `config` instead? 

https://github.com/deviantony/docker-elk/blob/0a7ec5eca45e6f90a25034159434942bc09cec4c/logstash/config/logstash.yml#L6

**Comment by deviantony** [comment]
As you can see in the `config` folder, you can find Logstash configuration file. The content of the `pipeline` folder is related to the event processing pipeline of logstash (input, filters, outputs), have a look here for more info: https://www.elastic.co/guide/en/logstash/current/pipeline.html

These are also separated this way in the official logstash image: https://github.com/elastic/logstash-docker/tree/master/build/logstash

**Comment by ivanrome** [comment]
Thanks for the information :+1:
