### ISSUE TITLE
Dynamic Build Version via ENV + ARG

### ISSUE THREAD

**Issue by gotjoshua** [deviantony/docker-elk#189]
Greetings,
I just made a fork ( [dcomposed/elk](https://github.com/dcomposed/elk) ) that uses an .env file to set the desired version:[commit/838ff63](https://github.com/dcomposed/elk/commit/838ff631195ee9f6d2f029b6169f1f2e4d8789ab)

Works quite well - i'm running 6.0.0-rc1.

Are you interested to integrate this strategy into your repo?

**Comment by antoineco** [comment]
ah, interesting, didn't even know one could parameterise the FROM instruction :)
I don't see any `env_file` option in your Compose file, does it mean you source your env file manually before running `docker-compose`?

**Comment by gotjoshua** [comment]
the .env file is automatically loaded:

> [Compose supports declaring default environment variables in an environment file named .env placed in the folder where the docker-compose command is executed (current working directory).](https://docs.docker.com/compose/env-file/)

One needs to be careful with that current working directory rule. I've run the docker-compose up from a subdirectory and been surprised to get a warning that my ENV var was not found...

Perhaps that is a reason to declare the .env via the env_file option.
In that case, I would include the .env file in the repo (rather than an example that needs to be copied and customized - as i did so far).

**Comment by gotjoshua** [comment]
but yeah - its pretty cool to be able to parameterize the FROM statement...

**Comment by antoineco** [comment]
Indeed the stack must start without any required modification. Users expect to be able to clone the repo and start the stack immediately.

If Compose supports the `.env` convention I'm fine using that without explicitly declaring redundant `env_file` options inside the Compose file. You'll need @deviantony's opinion before sending a PR though.

**Comment by deviantony** [comment]
What's the goal here? Add parameters in the FROM statements of each Dockerfile and an `.env` file defining the ELK version?

If these are the only changes I like, it will also help users to change the version of the stack quite easily (that should also be added in the README, maybe in the configuration section).

**Comment by gotjoshua** [comment]
Yes @deviantony thats the overall goal.
There are some other changes in my fork, but that is the focus of this issue and the nature of the changes in the commit that i reference above: https://github.com/dcomposed/elk/commit/838ff631195ee9f6d2f029b6169f1f2e4d8789ab

@antoineco and I were now discussing the best way to ensure that users can clone and deploy via docker-compose up -d without any modifications.

I am testing some different options for this requirement now... Any ideas?

**Comment by gotjoshua** [comment]
My tendency here is to use [variable substitution syntax](https://docs.docker.com/compose/compose-file/#variable-substitution) in the docker-compose file:
eg:
```
build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION:-5.6.3}
```
This will pass the $ELK_VERSION variable into the Dockerfile if it exists and is not empty, otherwise it will default to 5.6.3. The stack will then be ready to clone and up without modification.

**Comment by antoineco** [comment]
Assuming the user must be in the repo directory to start the stack, would there be any reason why the default wouldn't already come from the env file? With the syntax you suggested you still have to repeat the default version, just in the Compose file instead of Dockerfile.

**Comment by gotjoshua** [comment]
Right, the main reason is because I also want to encourage (but not require) the use of the IP_BIND variable to bind to a specific interface instead of 0.0.0.0 and this is a server specific configuration, therefore the wish to keep .env in the .gitignore file (as it will contain user specific info).

Adding a .env file is a conscious act to override the defaults.

**Comment by deviantony** [comment]
Could we use the values from the `.env` file directly to set the version in the FROM statement of the Dockerfile? Without having to modify the Compose file?

**Comment by gotjoshua** [comment]
as far as i know you would need to source the .env file, or explicitly pass
in the ARGS

but please correct me if i'm wrong - it would be great if it could be
simplified!

~
.:.joshua

“Our lives are not our own.
   We are bound to others, past and present,
     and by each crime and every kindness,
       we birth our future.”
           ― David Mitchell
<https://www.goodreads.com/author/show/6538289.David_Mitchell>, Cloud Atlas
<https://www.goodreads.com/work/quotes/1871423>

"Avoid the pursuit of happiness. Seek to define your mission and pursue
that."
   ― John Perry Barlow
<https://www.goodreads.com/author/show/273206.John_Perry_Barlow>

"Life is a series of gestures, into which we embed meaning..."
   ― *Joshua Gottdenker*

**Comment by antoineco** [comment]
I think the build ARG is necessary in the Dockerfile. If we put it there I think it can be excluded from the Compose file. Can you try that and confirm @gotjoshua?

**Comment by gotjoshua** [comment]
I can and will try, but I am not so hopeful.

Relevant links:
 - https://docs.docker.com/compose/compose-file/#args
 - https://docs.docker.com/engine/reference/builder/#arg
 - https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

I can't find any docs that indicate that ```docker-compose build``` nor ```docker build``` will source a .env file automatically.

**Comment by gotjoshua** [comment]
So...

```bash
$ cat .env
ELK_VERSION=5.6.1
$ source .env
$ echo $ELK_VERSION
5.6.1
  (the var is available in the shell ENV)
```

I set a default in the ARG statement in Dockerfile that i want to be overriden by .env:
```bash
$ cat logstash/Dockerfile
ARG ELK_VERSION=${ELK_VERSION:-5.6.2}
FROM docker.elastic.co/logstash/logstash:$ELK_VERSION

# make ELK_VERSION available in later commands:
ARG ELK_VERSION
ENV ELK_VERSION=$ELK_VERSION
RUN echo "env var for ELK_VERSION = $ELK_VERSION"
```

The build uses the .env for the image tag, but the build itself uses the default from the ARG statement in the Dockerfile:
```bash
$ docker-compose build logstash 
(Output condensed and commented):                                                  
Building logstash
Step 1/5 : ARG ELK_VERSION=${ELK_VERSION:-5.6.2}
Step 2/5 : FROM docker.elastic.co/logstash/logstash:$ELK_VERSION
Status: Downloaded newer image for docker.elastic.co/logstash/logstash:5.6.2
   (using the default value from ARG rather than .env file)
Step 3/5 : ARG ELK_VERSION && Step 4/5 : ENV ELK_VERSION $ELK_VERSION
Step 5/5 : RUN echo "env var for ELK_VERSION = $ELK_VERSION"
env var for ELK_VERSION = 5.6.2
Successfully tagged logstash:5.6.1 
   (because docker-compose loads the .env but does not pass in the args)
```

**Comment by antoineco** [comment]
So to sum it up, in order to make it consistent you have to set the arg:

- in the `.env` file
- in the `Dockerfile`
- in the Compose file

That's quite a lot of places for a version bump 😞

**Comment by gotjoshua** [comment]
My conclusion is that the ARGs need to be passed in explicitly either:
 - via docker compose args in the build object (with defaults optional here or in the Dockerfile OR both):
```
build:
      context: logstash/
      args:
        ELK_VERSION: ${ELK_VERSION:-5.6.2}
```
 - or via [docker build --build-arg ELK_VERSION=5.6.1](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg)

Reminder: if the ARGs are needed later[ they need to be redeclared below the FROM](https://github.com/moby/moby/pull/31352#issuecomment-315108094) (and defined as ENV vars if needed):

**Comment by gotjoshua** [comment]
Yeah - its alot of places agreed...

I feel like we would need to decide what has priority:
1) Clone and Up with no config
2) The Dockerfiles are independent of docker-compose (have their own defaults and can be built with docker build)
3) Most simple upgrade path (for both repo developers + early adopters)

**Comment by deviantony** [comment]
Agree with @antoineco, too many places to update the version.

Regarding the priority, it's definitely **1**: Clone and Up with no config

**Comment by gotjoshua** [comment]
After playing with it for most of the day, I am fine with a setup that includes an example .env in the repo (and also includes it in the .gitignore so custom changes will not be committed + pushed).
So I removed the defaults from docker compose and all Dockerfiles and all are now dependent on the .env: https://github.com/dcomposed/elk/commit/911678413e03d7791085fa81167edf44249f80a3

- [x] clone and up with no config
- [x] one place to bump version (in the .env)

**Comment by antoineco** [comment]
`image: kibana:${ELK_VERSION}` conflicts with `build:` unfortunately, with this syntax you're pulling the corresponding image from Docker Hub.

Overall my opinion is that somebody would certainly do what you did in order to bump 3 versions in one go, I really like that idea. However it seems to me that we'd introduce some complexity that may confuse newcomers. I always saw this repo as an accessible entry to ELK, and that's what I immediately liked about @deviantony's work.

People who are not familiar with Docker (and I can tell we see many of them around here) will wonder which version is being picked up (the env var, the .env file, the compose args?) while they currently see it crystal clear in the Dockerfiles.

If we could assume this repo only supports Compose (and we don't care about supporting manual `docker build`) that's what I would do:

1. Create an `elk.env` file containing 3 lines:
    ```
    ES_VERSION=5.6.3
    LS_VERSION=5.6.3
    KB_VERSION=5.6.3
    ```

2. At the beginning of the Compose file, add:
    ```yaml
    env_file: elk.env
    ```

3. For each `service:` add:
    ```yaml
    build:
      args:
        tag: $ES_VERSION
    …
    build:
      args:
        tag: $LS_VERSION
    …
    build:
      args:
        tag: $KB_VERSION
    ```

4. In each Dockerfile, set the tag to:
    ```docker
    ARG tag
    FROM docker.elastic.co/elasticsearch/elasticsearch:$tag
    ```

Feels easy enough for me to use as long as it's documented in the README.

**Comment by antoineco** [comment]
Working proposal: https://github.com/deviantony/docker-elk/compare/master...antoineco:version-param

**Comment by gotjoshua** [comment]
> image: kibana:${ELK_VERSION} conflicts with build: unfortunately, with this syntax you're pulling the corresponding image from Docker Hub.

The above is not true.

>[If you specify image as well as build, then Compose names the built image with the name:tag specified in image](https://docs.docker.com/compose/compose-file/#build)

**Comment by gotjoshua** [comment]
@antoineco , Thanks for the detailed investigation and engagement in the issue!

Yeah, I find it a bit restrictive that vars declared via env_file: are only available in the service they are declared, and NOT below in the docker-compose file. Only vars declared in the .env file are available to use in the docker-compose file - and ONLY the .env file that is in the current working directory will be sourced (Calling docker-compose up from a subdirectory will find the docker-compose file in the parent directory, but not the .env)

I like your idea to call the arg that we pass in "tag". And your working proposal is conceptually basically the same as my [most recent suggestion](https://github.com/deviantony/docker-elk/compare/master...dcomposed:master). (With the addition of some pipeline and certificate defaults)

Except, I don't understand the idea to offer separate version numbers for the different services. Is there a realistic use case for that? (I thought the ELK stack versions and BEAT versions always needed to be the same)

**Comment by antoineco** [comment]
Oh I didn't know that `image:` subtlety.

The 3 separate versions are just an example, I don't think they're that relevant either, I just wanted to push an example which focuses purely on versioning for clarity.

**Comment by antoineco** [comment]
Actually with the simplicity of the `.env` file I do believe this would be a good idea to push this, especially for Searchguard updates: https://github.com/deviantony/docker-elk/compare/searchguard...antoineco:version-param-searchguard

**Comment by deviantony** [comment]
I'm OK with @antoineco last proposal, it will definitely make it easier to bump the ELK version, as well as choose another version to run (tho, this should also be added in the README).

**Comment by antoineco** [comment]
Nice ! @gotjosua I'll leave you the honor to send the PR since it was originally your work :) I don't mind pushing changes to the README afterwards.

**Comment by antoineco** [comment]
Ping @gotjoshua. I'm gonna go ahead and merge https://github.com/deviantony/docker-elk/compare/searchguard...antoineco:version-param-searchguard. I think it's fair to commit this with your GitHub id, would it be fine if I do so?

**Comment by gotjoshua** [comment]
Thats Perfect, My branch has some other customizations, that I didn't take
time to isolate and MR/PR yet, so from my side that sounds perfectly fair.
Thanks for the detailed collaboration on this one! ; -)

~
.:.joshua

“Our lives are not our own.
   We are bound to others, past and present,
     and by each crime and every kindness,
       we birth our future.”
           ― David Mitchell
<https://www.goodreads.com/author/show/6538289.David_Mitchell>, Cloud Atlas
<https://www.goodreads.com/work/quotes/1871423>

"Avoid the pursuit of happiness. Seek to define your mission and pursue
that."
   ― John Perry Barlow
<https://www.goodreads.com/author/show/273206.John_Perry_Barlow>

"Life is a series of gestures, into which we embed meaning..."
   ― *Joshua Gottdenker*
