### ISSUE TITLE
Persisting elasticsearch data

### ISSUE THREAD

**Issue by andrewthad** [deviantony/docker-elk#19]
At the bottom of the readme, there is a section entitled "How can I store Elasticsearch data?". However, even without following those directions, I can already bring up the docker images, get data into ES, bring the images down, bring them back up again, and everything is persisted.

I'm new to docker, so I still don't totally get the persistence thing, but I thought that it was possibly a mistake in the readme.

**Comment by deviantony** [comment]
Indeed.

Thing is, the way provided by the section in the README allows you to persist your data after having deleted the containers.

Not really an issue, but I'll add some precisions in the README.

**Comment by andrewthad** [comment]
Ah, now I understand. Thanks for clearing that up!
