### ISSUE TITLE
Why does it use bridge network?

### ISSUE THREAD

**Issue by insikk** [deviantony/docker-elk#190]
In docer-compose.yml file, it uses bridge network. And, I don't see why it uses bridge that make unnecessarily complicate things. 
For ES, Kibana, Logstash, every port is mapped to the host. So If we knows host address, then we can access via the mapped port. 
Also among ELK containers, it can communicate with docker-assigned hostnames such as `elasticsearch`. 

Do we really need bridge? What am I missing here?

The reason I want to remove network is that my production server experience occasional `docker-compose down` not working because of zombie network endpoints on the bridge network.

**Comment by antoineco** [comment]
That's true on Linux, however on MacOS and Windows there's a little bit of magic around port mapping to lets you reach your services at `localhost`, although they're actually running inside a VM.

2 questions for you:

- can one use the port mapping syntax (`-p`) when `network==host`? This is necessary to keep it simple on macOS and Windows as explained above.
- can containers leverage the internal Docker DNS when `network==host`? All ELK components use it extensively.

**Comment by antoineco** [comment]
@insikk closing this for inativity, feel free to reopen if you have more info.
