### ISSUE TITLE
[searchguard] elasticsearch.yml is both mounted and copied

### ISSUE THREAD

**Issue by chersicm** [deviantony/docker-elk#191]
Why do you both COPY the config directory (that contains elasticsearch.yml) and bind-mount elasticsearch.yml? Isn't COPYing enough?

Dockerfile:

COPY config/ config/

docker-compose.yml:

volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

**Comment by antoineco** [comment]
Fair point, we should either COPY only the Searchguard files or mount everything.

**Comment by antoineco** [comment]
I'll fix this together with the 6.0.0 release.
