### ISSUE TITLE
The elasticsearch container was to grow memory size,But that not to take effect

### ISSUE THREAD

**Issue by lklkxcxc** [deviantony/docker-elk#192]
set paramers：
 environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"

enter elasticsearch container：
ps -ef result：
elastic+     1     0 23 08:02 ?        00:22:30 /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -Xms2g -Xmx2g

**Comment by antoineco** [comment]
The `-Xms2g -Xmx2g` flags are always set, they ensure the JVM starts with sane defaults.

The value of the `ES_JAVA_OPTS` environment variable is appended at the **end** of the startup command. Try `docker-compose exec elasticsearch ps -efww` instead to see the full command.

**Comment by antoineco** [comment]
You can also poll the Elasticsearch API to get a confirmation that your Heap size is correct. For example with the default of `-Xmx256m -Xms256m`:

```console
$ curl 'localhost:9200/_nodes/stats/jvm?pretty'

{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "docker-cluster",
  "nodes" : {
    "VskaaBsLTLK4iSbgqYE3WQ" : {
      ...
      "jvm" : {
        "timestamp" : 1509358903686,
        "uptime_in_millis" : 77122,
        "mem" : {
          ...
          "heap_max_in_bytes" : 259522560,    <--------  ~259 MB
          ...
      }
    }
```

**Comment by lklkxcxc** [comment]
thanks！
