### ISSUE TITLE
Fate of 'vagrant' branch

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#199]
This one's for you Anthony :)

The `vagrant` branch is stale and outdated. Since this project is mainly Docker oriented, I was wondering if you wanted to keep it around and/or remove its reference in the README?

**Comment by deviantony** [comment]
Hey @antoineco 

Sorry for the delay, I believe that we can keep the branch but remove any reference in the README. 

Thanks Antoine ! :+1:
