### ISSUE TITLE
how logstash forwarder works?

### ISSUE THREAD

**Issue by MatthewLiHW** [deviantony/docker-elk#20]
hello, I have installed this in less than 30 minutes, and it's an amazing work. one question raised here, where is the logstash forwarder located in your repo? bu using the logstash forwarder , I can collect many agent's log, then.

**Comment by deviantony** [comment]
Logstash forwarder is not integrated in this solution. You'll have to install it on the machines where your logs are located and then you'll be able to cable it with the soltuion by adding a lumberjack input in the logstash configuration.

Feel free to ask any questions if you need more explanations.

**Comment by deviantony** [comment]
@MatthewLiHW I'll close the issue now. Feel free to re-open it if you are having troubles with the logstash-forwarder setup.
