### ISSUE TITLE
Non-backward compatible Docker registry path

### ISSUE THREAD

**Issue by nikos** [deviantony/docker-elk#200]
When using the HEAD version of docker-elk with `ELK_VERSION=5.5.3` (set in `.env`) building the docker images is aborted, due to the fact that the registry URL seems to have changed with 6.0, so I had to fine-tune the Dockerfiles for elasticsearch, kibana and logstash in the following way:

```
-FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
+FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
```

**Comment by antoineco** [comment]
Yes that's the expected behaviour, the 6 series is the only one which contains pure OSS components (without X-Pack).

If you need an older version what you did is the right approach. Make sure you disable X-Pack explicitly in your ES/Kibana config if you don't use it (see last commit).

**Comment by antoineco** [comment]
@nikos I will close this in a few days only you have any other question/suggestion.
