### ISSUE TITLE
Install and configure x-pack

### ISSUE THREAD

**Issue by Nightbr** [deviantony/docker-elk#203]
Hey, this is not a real issue but I spent time to install and configure x-pack plugin. If you are interested I can make a PR to add this into the documentation.

Here is my doc:

## Configure X-Pack

[Official documentation](https://www.elastic.co/fr/downloads/x-pack)

Into `elasticsearch/Dockerfile`, install xpack plugin:

    RUN elasticsearch-plugin install x-pack

Into `kibana/Dockerfile`, install xpack plugin:

    RUN kibana-plugin install x-pack

Rebuild your stack:

    docker-compose up -d --build

Generate passwords:

    docker exec -it elk_elasticsearch_1 bin/x-pack/setup-passwords auto

    Initiating the setup of reserved user elastic,kibana,logstash_system passwords.
    The passwords will be randomly generated and printed to the console.
    Please confirm that you would like to continue [y/N]y

    Changed password for user kibana
    PASSWORD kibana = #j*LO*V$W+!oPFO^~tgw

    Changed password for user logstash_system
    PASSWORD logstash_system = HNn8Vi3g9i_#A9c=sX%~

    Changed password for user elastic
    PASSWORD elastic = lOHjUOb6TOGTJODRNdMg

Add credentials to `kibana/config/kibana.yml`:

    elasticsearch.username: "kibana"
    elasticsearch.password:  "<pwd>"

Restart Stack:

    docker-compose restart

Login with `elastic` user at http://localhost:5601

Create a new User for logstash pipeline

    logstash_gelf
    nvR9fKYKb2\yiQze5

Create a role and assign the index and all permissions

![logstash_writer_role](https://user-images.githubusercontent.com/4228646/33435908-bcd26afe-d5e3-11e7-8c6f-2c7b4457a503.png)

Configure your pipeline

    output {
    	elasticsearch {
    		hosts => "elasticsearch:9200"
            index => "app-%{+YYYY.MM.dd}"
            user => logstash_gelf
            password => "nvR9fKYKb2\yiQze5"
    	}
    }

Restart Stack to reload the configuration:

        docker-compose restart

-------------------------

Let me know ;)

**Comment by antoineco** [comment]
Hi @Nightbr, we do [maintain a branch with X-Pack](https://github.com/deviantony/docker-elk/tree/x-pack) already (see README).

**Comment by antoineco** [comment]
Thanks for the proposal anyway. I'm gonna go ahead and close this, but feel free to reopen the issue if you have suggestions about improving the X-Pack flavour!

**Comment by liamptk** [comment]
@antoineco I've been playing with your x-pack branch for a couple of days now but I'm having issues with trying to change the passwords.

I've tried updating the configs with new passwords, and that works great until a password is entered incorrectly and the stack falls over with an authentication error. Is there a different method for updating the passwords? Nothing is really explained in the README.

Many thanks,

**Comment by antoineco** [comment]
@liamptk I was not aware of this lockout, but the process for chamging built-in user passwords is described here:

[X-Pack for the Elastic Stack [6.0] » Securing Elasticsearch and Kibana » Getting Started with Security](https://www.elastic.co/guide/en/x-pack/6.0/security-getting-started.html)
