### ISSUE TITLE
Cannot build docker images

### ISSUE THREAD

**Issue by jemacom** [deviantony/docker-elk#210]
I cloned the repo then when I tried to start it I face this issue.
```
$ docker-compose build
Building elasticsearch
Step 1/6 : ARG ELK_VERSION
ERROR: Service 'elasticsearch' failed to build: Please provide a source image with `from` prior to commit
```
Apparently it's a known one [ARG before FROM](https://github.com/moby/moby/issues/32457) in docker. But this issue was closed and the problem solved in the docker project and am still facing it.

Here's an overview of my environment:
```
$ docker version                                                                                                                        
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   092cba3
 Built:        Thu Oct 12 22:34:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

````  
Normally this version of docker handles ARG before FROM.

I tried to copy `.env` file into elasticsearch, logstash and kibana directories and I rebuild again with NO success. 

Does anyone faced this issue before ? 

Any help is appreciated. Thanks in advance

**Comment by antoineco** [comment]
This issue is fixed on `master`, please use the latest commit.

**Comment by jemacom** [comment]
Am using `searchguard` branch in order to have searchguard out of the box. I couldn't those on `master` branch. Any suggestions about this ?

**Comment by antoineco** [comment]
Ah, good point, I was waiting for Searchguard 6.0 to update that branch, but I can push a fix independently.

**Comment by jemacom** [comment]
I can hardcode the docker images versions and docker stop complaining about the ARG issue. But it seems that there's another problem in the elasticsearch container. 

```
elasticsearch_1  | [2017-12-12T12:28:46,394][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
elasticsearch_1  | [2017-12-12T12:28:47,803][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.ml.enabled] did you mean [xpack.graph.enabled]?
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.ml.enabled] did you mean [xpack.graph.enabled]?
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:244) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:328) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	... 6 more
dockerelk_elasticsearch_1 exited with code 1
```

**Comment by jemacom** [comment]
If there's any work around please share it.

**Comment by antoineco** [comment]
@jemacom I cherry-picked commits from the `master` branch, could give it another try?

**Comment by jemacom** [comment]
I works smoothly now. Thanks :+1:

**Comment by antoineco** [comment]
@lakano we just reverted that change back, which means the minimum supported Docker version is 17.03.

That version is available from the Docker package repositories in most Linux distros nowadays. [Instructions for Fedora](https://docs.docker.com/install/linux/docker-ce/fedora/).

Would it be an option for you to update?

**Comment by lakano** [comment]
I also have projects on this system for K8S that is not compatible with all Docker version, I'll check that.
Thank you for the quick answer!

**Comment by antoineco** [comment]
Good point. That said 17.03 was validated against Kubernetes, but be careful if you use 18.xx.

**Comment by lakano** [comment]
Yep, just checked, I need the 17.03.x but with the instructions for Fedora link, there is a possibility to choose the version, but the versions proposed start from 18.x :-/

**Comment by lakano** [comment]
Ok, I've manually installed the .rpm package from Fedora 25 here:
https://download.docker.com/linux/fedora/25/x86_64/stable/Packages/docker-ce-17.03.2.ce-1.fc25.x86_64.rpm
and here:
 https://download.docker.com/linux/fedora/25/x86_64/stable/Packages/docker-ce-selinux-17.03.2.ce-1.fc25.noarch.rpm
Now, this should works with K8S projects and docker-elk but... I still have the same error :/
```
% docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by antoineco** [comment]
Are you sure you don't have the old version still installed and used by compose?

**Comment by lakano** [comment]
Good idea, but this seems to be one of the last version:
```
% docker-compose version
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.2.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h-fips  27 Mar 2018
```

**Comment by antoineco** [comment]
Actually you're right, just realized this landed [in Docker 17.05](https://github.com/moby/moby/commit/4d9e32a08e8e2613601cbc5d36bd8c7ecf32a772), not 17.03. Apologies for that 🙏

**Comment by lakano** [comment]
Just upgraded to 1.22 to be sure, same error:
```
% docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

% docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:23:59 2017
 OS/Arch:      linux/amd64
 Experimental: false

% docker-compose up
Building elasticsearch
Step 1/2 : ARG ELK_VERSION
ERROR: Service 'elasticsearch' failed to build: Please provide a source image with `from` prior to commit

```

**Comment by lakano** [comment]
Argh, ok, so I'm stuck because k8s could not works with docker version > 17.03.x :(

**Comment by antoineco** [comment]
Yup, that's expected, the Compose version does not matter. I meant the Docker version **used** by Compose.
>  used by compose

**Comment by antoineco** [comment]
I've seen people successfully running prod loads on Docker 18.03. Not sure how critical your cluster is, but it's worth giving it a try, or using 2 Docker daemons if necessary.

**Comment by lakano** [comment]
Yes I understood your position. In the Changelog of k8s version 1.10 they still said the supported version of docker is until 17.03.x (no mention found in releases 1.11 and 1.12).
I'll try to manually change your files to support the Docker 17.03.x version.
Thanks for your time and your help.

**Comment by antoineco** [comment]
@lakano the easiest thing you can do is checkout commit 1ac84fbe, or just revert commits up to this commit it.

**Comment by Deszce** [comment]
I use master branch，but i face the same issue

**Comment by antoineco** [comment]
@deszce please use a compatible Docker version. Cf. README

**Comment by yqbjtu** [comment]
I encounter this issue today(I used master branch 201811-22).

Building elasticsearch
Step 1/2 : ARG ELK_VERSION
ERROR: Service 'elasticsearch' failed to build: Please provide a source image with `from` prior to commit

**Comment by antoineco** [comment]
@yqbjtu please use a compatible Docker version. Cf. README

**Comment by MS52390** [comment]
Running into this issue with Docker v18.09 and Docker-compose v1.23.2. Cloned from master.

"Error: Service 'elasticsearch' failed to build: invalid reference format."

**Comment by jailbreakerSN** [comment]
hello @antoineco , same issue here.
Running into this issue with Docker v18.09.3 and Docker-compose v1.21.2. Cloned from master.
```bash
Building elasticsearch
Step 1/2 : ARG ELK_VERSION
ERROR: Service 'elasticsearch' failed to build: Please provide a source image with `from` prior to commit
```
Any help please!

**Comment by antoineco** [comment]
@jailbreakerSN did you by any chance delete the `.env` file from the repo, or modify the Compose file?

**Comment by jailbreakerSN** [comment]
@antoineco no, I don't think so. It was may be due to another problem, because I couldn't start any container with my docker service, even if it was running.
So I finally remove it and re-install docker and docker compose. All is going fine now!
Thanks !
