### ISSUE TITLE
Kibana Increase Memory Usage Limit

### ISSUE THREAD

**Issue by aniss05** [deviantony/docker-elk#213]
Hi,

I was wondering if it is possible to increase the memory usage max limit of Kibana Docker, I have searched over the net and found out that the best solution is to use:

NODE_OPTIONS="--max-old-space-size=4096"

But I am stuck in performing this change as I am not really familiar with NodeJS and I need someone's help to apply it.

Thanks in advance for your help guys.

**Comment by antoineco** [comment]
Node doesn't have the same restrictions as a Java app, it will have access to all the memory available on the machine if it has to. What are you trying to achieve exactly?

**Comment by aniss05** [comment]
The problem I have is that I have a lot of data which I insert into one index in elasticsearch(around 900 million documents) and also increased the Elasticsearch JVM options but when I want to create visualisations with Kibana on this data, it simply crashes. So I thought that by increasing the Kibana Memory usage limit, this issue will be fixed. Is my guess correct or is it related to some other configuration?

**Comment by antoineco** [comment]
I also don't know unfortunately. Have you tried setting this environment variable in the "kibana" service inside your compose file?

**Comment by aniss05** [comment]
Do you mean something like this:

environment:
  - max-old-space-size: 4096m

??

**Comment by antoineco** [comment]
Almost :)

```yaml
environment:
  NODE_OPTIONS: '--max-old-space-size=4096'
```

**Comment by aniss05** [comment]
Thanks a lot @antoineco , I will try it and see what happens.

**Comment by antoineco** [comment]
@aniss05 is your issue resolved?
