### ISSUE TITLE
JDBC Driver Library Error

### ISSUE THREAD

**Issue by Johnb21** [deviantony/docker-elk#215]
I am not sure if this is PEBKAC, Docker related or this project. However, when I am trying to use an input plugin in logstash, I keep getting the error message:

`The following config files contains non-ascii characters but are not UTF-8 encoded [\"/usr/share/logstash/pipeline/postgresql-42.1.4.jar\"]"`

the line in the logstash.conf file looks like this:

` jdbc_driver_library => "postgresql-42.1.4.jar"`

Has anyone gotten this to work with a jdbc input for logstash? Any assistance as to what is going wrong would be appreciated.

**Comment by antoineco** [comment]
`logstash/pipeline` can only contain config files and nothing else. You have a binary inside of it, hence the error.

Closing because it's a non-issue, but we can keep discussing.

**Comment by Johnb21** [comment]
Thanks. That was the exact issue @antoineco . I wasn't sure where the binary was supposed to go but I figured it out. I am new to both docker and elk

**Comment by dmarcos89** [comment]
Hey, I just found this issue which might help. I am quite new to docker and elk as well.
Where exactly should I place the .jar file?
Thanks in advance for any help!

```
input {
	tcp {
		port => 5000
	}
	jdbc {
        jdbc_driver_library => "/bin/mysql-connector-java-5.1.46-bin.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://192.168.99.100:3306/welovetravel"
        jdbc_user => "mysql"
        jdbc_password => "4Csds32AD"
        schedule => "* * * * *"
        statement => "SELECT * from bookings"
    }
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}


```

**Comment by antoineco** [comment]
@dmarcos89 you must either

* copy this file inside the Logstash Dockerfile
      ```dockerfile
      COPY /path/to/jar /bin/
      ```

* or add it as a bind mount inside the Compose file
      ```yaml
      volumes:
      - ...
      - ./logstash/bin/file.jar:/bin/file.jar:ro
      ```

**Comment by dmarcos89** [comment]
Thanks @antoineco!! Fixed!
👍 😄

**Comment by jmmadsen** [comment]
Having a related issue, `Error: unable to load /bin/postgresql-42.2.18.jar from :jdbc_driver_library, file not readable (please check user and group permissions for the path)`. These are my relevant files:

docker-compose.yml:
```
volumes:
  - type: bind
          source: ./logstash/postgresql-42.2.18.jar
          target: /bin/postgresql-42.2.18.jar:ro
```
logstash.conf:
```
jdbc_driver_library => "/bin/postgresql-42.2.18.jar"
```

**Comment by antoineco** [comment]
@jmmadsen could you please try to give read permissions on this file to all users?

```console
$ chmod -v o+r /bin/postgresql-42.2.18.jar
mode of '/bin/postgresql-42.2.18.jar' changed from 0640 (rw-r-----) to 0644 (rw-r--r--)
```

**Comment by jmmadsen** [comment]
@antoineco Thanks for the quick reply. Unfortunately, I am still getting the same issue. I will keep poking around to see if perhaps my configuration files are wrong.

**Comment by jmmadsen** [comment]
By copying it directly in the Dockerfile, I was able to get around this issue that I had using volumes.
