### ISSUE TITLE
Dynamic mapping -> no access from outside

### ISSUE THREAD

**Issue by rutgerg** [deviantony/docker-elk#218]
I followed your tip at https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster#port-mapping. Works great for scaling. My question is how do I reach my ES cluster from the outside?

http://ES:9200 doesn't work anymore.  http://ES:assigned_port does but will changes with every compose.

**Comment by antoineco** [comment]
If you want to reach your cluster from the outside you must either configure your client to know all ES servers, or have your own service discovery (eg with Consul, Zookeeper, SRV records, ...).

**Comment by antoineco** [comment]
@rutgerg I'm gonna close this now but feel free to comment below if you want to discuss further.

**Comment by rutgerg** [comment]
Txs for the heads up. I'm looking into Kubernetes and ingress at the moment.
