### ISSUE TITLE
docker-machine & volumes

### ISSUE THREAD

**Issue by zstarer** [deviantony/docker-elk#22]
not an issue with your work (it's great, thank you for this), but if anyone is using docker-machine to provision this, hopefully you'll find this first and save yourself the 15-20 min of WTF I just went through trying to debug why this wasn't working.

hadn't used docker-machine with docker-compose till now, but it would appear that:

if you try to use this with compose, you need to first move over the entire project directory to the directory returned by `docker-machine ssh <name> pwd`

here's the S/O to the issue:
http://stackoverflow.com/questions/30040708/how-to-mount-local-volumes-in-docker-machine

feel free to close this out. I just had to write that explanation out cuz there were weird symptoms (like..`localhost:9200` instead of `elasticsearch:9200` level weird. things worked 90% of the way.)

**Comment by deviantony** [comment]
Hey cool ! :+1: 

I'll leave this issue open, it could help other people.

**Comment by gvt** [comment]
+1 I have been banging my head off this for too long! Thanks for posting

**Comment by MBuffenoir** [comment]
If you don't change your config that often, `docker-machine scp` can be handy to send your config files on the remote machine

**Comment by btoueg** [comment]
Works nice locally, but with docker-machine nothing works (`docker 1.11.0`, `docker-compose 1.7.0`, `docker-machine  0.7.0`).

I've `scp` the folders to the remote machine:

```bash
root@metabase:~# tree .
.
|-- kibana
|   |-- config
|   |   `-- kibana.yml
|   |-- Dockerfile
|   `-- entrypoint.sh
`-- logstash
    `-- config
        `-- logstash.conf
```

I've also manually copied the files to their final location and commented out the `volumes` in the `docker-compose.yml`... I still get:

```bash
kibana_1         | FATAL CLI ERROR Error: ENOENT: no such file or directory, open '/opt/kibana/config/kibana.yml'
logstash_1       | {:timestamp=>"2016-04-30T08:29:11.160000+0000", :message=>"translation missing: en.logstash.runner.configuration.file-not-found", :level=>:error}
```

**Comment by btoueg** [comment]
I've finally find a way of making if work after destroying/recreating the containers. I'll edit later when I'll find the exact pattern to make it work.

**Comment by pydolan** [comment]
This was a pretty frustrating to deal with.  Thankfully I finally decided to google for the error message. (Yes, why didn't I do that earlier!)

Volumes are specific to the host (i.e., wherever docker is running on), so that's why the directory reported from `docker-machine ssh <machine> pwd` worked for some above.

My fix is to remove the `volumes:` declaration from docker-compose.yml, and modify the kibana/Dockerfile to copy the config file over:

```
FROM kibana:latest

RUN apt-get update && apt-get install -y netcat

COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh

RUN kibana plugin --install elastic/sense

#### New code for copying config file: ####
RUN mkdir -p /opt/kibana/config
COPY config/kibana.yml /opt/kibana/config/
#### End of new code ####

CMD ["/tmp/entrypoint.sh"]

```

**Comment by antoineco** [comment]
Closing because it's an old issue and does not apply to this project as such. Thanks for the tip!
