### ISSUE TITLE
Logstash - Plugin does not exist

### ISSUE THREAD

**Issue by go4cas** [deviantony/docker-elk#222]
I'm very new to the ELK stack and Ruby - so, please excuse if this is a noob question!

I am trying to install a [Zendesk Logstash plugin](https://github.com/ppf2/logstash-input-zendesk) in the Logstash container, when running docker-compose. I have run `gem build logstash-input-zendesk.gemspec` to create the `logstash-input-zendesk-2.0.0.gem` file.

My `Dockerfile` for Logstash:
```
FROM docker.elastic.co/logstash/logstash-oss:6.1.0
RUN logstash-plugin install logstash-input-zendesk
```
I have tried `logstash-input-zendesk-2.0.0` as well.

After updating the `Dockerfile`, I have run `docker-compose build`.

The build fails with this message:
```shell
Building elasticsearch
Step 1/1 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
 ---> 8819afa25e62
Successfully built 8819afa25e62
Successfully tagged dockerelk_elasticsearch:latest
Building logstash
Step 1/3 : FROM docker.elastic.co/logstash/logstash-oss:6.1.0
 ---> d252e3e90148
Step 2/3 : COPY logstash-input-zendesk-2.0.0.gem /etc/logstash
 ---> Using cache
 ---> 8a65bcdd6f9d
Step 3/3 : RUN logstash-plugin install logstash-input-zendesk
 ---> Running in e7ddc1da4b42
Validating logstash-input-zendesk
Plugin logstash-input-zendesk does not exist
ERROR: Installation aborted, verification failed for logstash-input-zendesk
ERROR: Service 'logstash' failed to build: The command '/bin/sh -c logstash-plugin install logstash-input-zendesk' returned a non-zero code: 1
```

What am I missing?

**Comment by antoineco** [comment]
You probably need two extra things here:
* a `COPY logstash-input-zendesk-2.0.0.gem .` statement to push the Gem file to the container file system
* pass the full file name to the `logstash-plugin install` command, eg `logstash-input-zendesk-2.0.0.gem`

**Comment by casalot** [comment]
Thanks, @antoineco! The issue was the file name.

For completeness sake, here's my updated `Dockerfile`:
```docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.0
COPY logstash-input-zendesk-2.0.0.gem /usr/share/logstash
RUN logstash-plugin install /usr/share/logstash/logstash-input-zendesk-2.0.0.gem
```

**Comment by go4cas** [comment]
Thanks, @antoineco! The issue was the file name.

For completeness sake, here's my updated `Dockerfile`:
```docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.0
COPY logstash-input-zendesk-2.0.0.gem /usr/share/logstash
RUN logstash-plugin install /usr/share/logstash/logstash-input-zendesk-2.0.0.gem
```
