### ISSUE TITLE
Logstash configs - conf.d files

### ISSUE THREAD

**Issue by RANGERBEE** [deviantony/docker-elk#223]
I am having trouble mapping my config files. Could you shed some light?

I have a conf.d folder with many .conf files that are for input and output parsing with numbered naming conventions.  IE: 1.conf, 2.conf, 3.conf    So that they are processed in order.

I have moved all my templates.json  and full conf.d folder under the /opt/docker-elk/logstash/config directory and after editing the compose file for ports , all I get are mapped ports with starting the stack. 
My filebeats agents are refused connections to the logstash instance ports...

I need my beats agents to send to the numerous expected ports running input services on the logstash instance.

Any help?   thank you!!!!

**Comment by antoineco** [comment]
@RANGERBEE did you copy your conf files under [`logstash/pipeline`](https://github.com/deviantony/docker-elk/tree/master/logstash/pipeline)?
That's the [configured location](https://github.com/deviantony/docker-elk/blob/5f1824f/logstash/config/logstash.yml#L6) for pipeline configuration files.

**Comment by RANGERBEE** [comment]
Yes, tried that. But Found that 5.x configs no longer are in a useful format.
See: https://github.com/elastic/logstash/issues/8420
I had to edit and comment the .yml file so the pipeline.conf would be seen, furthermore I had to put all my configs for plugins/ filters/ parsing/output into one file - the logstash.conf pipeline config file. (Which is the new way of doing business for 6.x)   Thanks Elastic.........  Hours of tshooting.

Anyhow thanks for the good builds, images, docs here  - good work! 

--Bee

**Comment by antoineco** [comment]
Nice catch, elastic/logstash-docker#64 is also related.

Regarding the single-file issue, it seems like you **can** spread your pipeline config across multiple files in 6.x using a wildcard. [Check that example](https://github.com/elastic/logstash/blob/40827a5/config/pipelines.yml#L13-L15).

**Comment by RANGERBEE** [comment]
Indeed. Verified use of the pipelines.yml file under logstash/config to designate pipeline settings.  
I pointed to my old conf.d folder with a wildcard glob *.conf and it started the pipeline without error.
All my parser- grok errors from 5.x are another story..  ;/
