### ISSUE TITLE
Logstash cannot connect to Elasticsearch

### ISSUE THREAD

**Issue by Bobspadger** [deviantony/docker-elk#224]
Docker for mac 17.12.0
OSX 10.13.3
8GB Ram provided and 4 CPU

```
logstash_1       | [2018-01-09T20:31:12,985][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash_system:xxxxxx@localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash_system:xxxxxx@localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
```

Kibana Loads and is accessible, but I'm unablbe to make an index for `logstash-*`

**Comment by Bobspadger** [comment]
Running `curl 'http://localhost:9200/.kibana/doc/_search?pretty'`

```
curl 'http://localhost:9200/.kibana/doc/_search?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "missing authentication token for REST request [/.kibana/doc/_search?pretty]",
        "header" : {
          "WWW-Authenticate" : "Basic realm=\"security\" charset=\"UTF-8\""
        }
      }
    ],
    "type" : "security_exception",
    "reason" : "missing authentication token for REST request [/.kibana/doc/_search?pretty]",
    "header" : {
      "WWW-Authenticate" : "Basic realm=\"security\" charset=\"UTF-8\""
    }
  },
  "status" : 401
}
```

**Comment by antoineco** [comment]
Sounds like you used to the `x-pack` branch and switched back to `master` without running `docker-compose build`, am I wrong?

**Comment by Bobspadger** [comment]
I just cloned the master branch to my knowledge ?

**Comment by antoineco** [comment]
Impossible, you wouldn't have to provide credentials on `master`.

**Comment by Bobspadger** [comment]
I've just done the following:

1. Remove all docker-elk containers
2. removed the cloned directory `rm -rf docker-elk`
3. Cloned the repo again `git clone git@github.com:deviantony/docker-elk.git`
4. `docker-compose up -d`
5. Same problem

**Comment by Bobspadger** [comment]
I'm clearly doing something wrong, but not sure what it is :)

**Comment by antoineco** [comment]
Try the build command I mentioned in my first reply ;)

**Comment by Bobspadger** [comment]
ah - let me get coffee and read properly

**Comment by Bobspadger** [comment]
and we have a winner!

Let me go update your readme :)

**Comment by antoineco** [comment]
It's already mentioned, if you add/remove plugins you have to rebuild your images. This is also the case when you swap base images (X-Pack to OSS in your case).

**Comment by Bobspadger** [comment]
I can see its added as under the plugins, but I have not made any changes to plugins, I was just trying to get the stack to come up

**Comment by antoineco** [comment]
That's true, but you had some images in your cache which were built at some point, and Compose was not clever enough to figure it out.

I'll close this and comment on your PR (thanks for that by the way).

**Comment by Bobspadger** [comment]
no problem - you've done more by making the repo !
I thought it might help the next person come along to use it who is not so up on docker (like me!)
