### ISSUE TITLE
Service 'elasticsearch' failed to build i/o timeout

### ISSUE THREAD

**Issue by rplees** [deviantony/docker-elk#227]
Hi,
`docker-elk rplees$ docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Building elasticsearch
Step 1/1 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
6.1.0: Pulling from elasticsearch/elasticsearch-oss
85432449fd0f: Pulling fs layer
1d148c943c04: Pulling fs layer
beb38eb8783a: Pulling fs layer
b8cfa3f2cdd3: Waiting
6b406786c96f: Waiting
e3be3cb91fad: Waiting
ERROR: Service 'elasticsearch' failed to build: error pulling image configuration: Get https://d2iks1dkcwqcbx.cloudfront.net/docker/registry/v2/blobs/sha256/88/8819afa25e6234681199c5d9430eb006e7d92f9289a9f3e0e4f35af92580bcac/data?Expires=1515667583&Signature=kBRPYzhh9LO0zcm~QzOcsNQAGfj5kT3SB8cXS9qqpFl6UVrTlQ5Q-KeXboywgIWmcmr56c8g1TEhUkAiigDx53GkAEjePITT9HbKkVIWoyBwT6uaESgC7WzFO9dS7xUbqwBFW-xU3E4uR8lu~ynpzUB8uFBAEv5~XltGrZZN9zAqREHA~BLogZGX0i4r0Vym1UigBnyUG3Mck-BBaANFyBJyhVxqbe9g4RoSXfL5JY2X-3~LlgxGFVP-L4XrEFKdaQBpZYCq-Z9e0B02lO2uLYx8u~m4Idbnk83vIAS06-O358Mny6BV1zL-ySJRX-HDF~RHZpDcyR9UAkdUPAO2lw__&Key-Pair-Id=APKAIVAVKHB6SNHJAJQQ: dial tcp: lookup d2iks1dkcwqcbx.cloudfront.net on 192.168.65.1:53: read udp 192.168.65.2:41217->192.168.65.1:53: i/o timeout`

- docker version
`Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true`

but I rebuild in other server is still work, and request in my pc in brower https://d2iks1dkcwqcbx.cloudfront.net/docker/registry/v2/blobs/sha256/88/8819afa25e6234681199c5d9430eb006e7d92f9289a9f3e0e4f35af92580bcac/data? can downloaded.

docker config:
`{
  "debug" : true,
  "experimental" : true,
  "registry-mirrors" : [
    "http://232779c7.m.daocloud.io"
  ]
}`

**Comment by antoineco** [comment]
Looks like you have a firewall or proxy blocking internal connections on the target machine.

**Comment by rplees** [comment]
@antoineco Ha, It is very possible, wall is too high and strong

**Comment by antoineco** [comment]
@rplees did you investigate? Any conclusion?
Feel free to close this issue if your network issues are fixed.

**Comment by StrangeTown** [comment]
It works after I set Docker/preferences/**proxies** to my shadowSockets http proxy.

**Comment by jobinsdevelopments** [comment]
docker pull logstash/logstash:7.2.0 command is working fine. But when i try to pull the image  by executing the  docker-compose.yml it is failing to pull hte imagea show the error message like below

**ERROR: Service 'logstash' failed to build: Get https://docker.elastic.co/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**

This is the situation for both filebeat and logstash but elasticsearch and kibana are working fine.
Does anyone have any idea?

**Comment by dendihandian** [comment]
same here.

here is my build error:

```
Service 'elasticsearch' failed to build: Get https://docker.elastic.co/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by antoineco** [comment]
@dendihandian you have a firewall or proxy blocking outbound connections from Docker's network interface.
