### ISSUE TITLE
Rejecting mapping update

### ISSUE THREAD

**Issue by uLan08** [deviantony/docker-elk#230]
I am trying to run this locally and running into an error saying

```
logstash_1       | [2018-01-19T09:02:52,303][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2018.01.19", :_type=>"response", :_routing=>nil}, #<LogStash::Event:0x965867>], :response=>{"index"=>{"_index"=>"logstash-2018.01.19", "_type"=>"response", "_id"=>"tKuoDWEBMQ6prbcqC-x2", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [logstash-2018.01.19] as the final mapping would have more than 1 type: [response, doc]"}}}}
```
My logstash.conf
```
input {
	tcp {
		port => 5000
		codec => json
	}
	udp {
		port => 5000
		codec => json
	}
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => ["elasticsearch:9200"]
	}
}
```
I created this index through the kibana ui, if that matters.
My knowledge on the ELK stack is still not that good so I would appreciate some help.

**Comment by antoineco** [comment]
Hi @uLan08,

The best place to ask questions about Elastic products is the Elastic community. I Googled the error message and stumbled upon this:

https://discuss.elastic.co/t/rejecting-mapping-update-for-new-index/109576

The short answer seems to be "logstash v5 and v6 indexes are not inter-compatible".

**Comment by uLan08** [comment]
Any reason as to why would I have a logstash v5 index?

**Comment by antoineco** [comment]
It doesn't necessarily mean you have a v5 index, it could be any index that doesn't match the logstash index template.

You said
> I created this index through the kibana ui

The logstash output plugin creates this index for you with the right template.

**Comment by uLan08** [comment]
I managed to fix the error. I had to specify the document type in logstash config to match the one being said on the error.  

```
output {
	elasticsearch {
		hosts => ["elasticsearch:9200"]
                document_type => "response"
	}
}
```

Thanks for your time.
