### ISSUE TITLE
Kibana authentication using nginx and basic auth 

### ISSUE THREAD

**Issue by vik-y** [deviantony/docker-elk#232]
Kibana can be accessed without any authentication (And so can be other services too). 

But to limit access to kibana I have added an nginx container with basic auth which reverse proxies to kibana. I have it running on my local setup. Will it be a helpful feature? If yes, then I can raise a PR. If no, then what is a better way to limit access to kibana dashboard?

**Comment by antoineco** [comment]
Why don't you use the Searchguard branch for that?

**Comment by vik-y** [comment]
Ok that sounds good. I was not aware of that. Thankyou.

**Comment by antoineco** [comment]
You're welcome :+1:
