### ISSUE TITLE
/bin/sh: ./build.sh: Text file busy trying to build extensions/logspout

### ISSUE THREAD

**Issue by gforghetti** [deviantony/docker-elk#233]
Running docker 17.06.2-ee-6 on a Ubuntu 16.04 vagrant.  Getting error /bin/sh: ./build.sh: Text file busy" trying to build the logspout docker image.  See below.  Saw some other similar problems and the resolution was to run "sync" after the chmod +x and before the ./build.sh

```console
$ docker image build .
Sending build context to Docker daemon  7.168kB
Step 1/2 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1/1 : COPY ./build.sh /src/build.sh
Step 1/1 : COPY ./modules.go /src/modules.go
Step 1/1 : RUN cd /src && chmod +x ./build.sh && ./build.sh "$(cat VERSION)-custom"
 ---> Running in e520c605ec9b
/bin/sh: ./build.sh: Text file busy
The command '/bin/sh -c cd /src && chmod +x ./build.sh && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
```

**Comment by antoineco** [comment]
Oh yes, I remember than one 🤕 
Your Docker storage backend is `aufs` I suppose? (`$ docker info`)

**Comment by gforghetti** [comment]
Correct - AUFS.

**Comment by antoineco** [comment]
It is said that Linux 4.4.6 fixes the issue, what kernel version are you using?

`sync` sounds like a reasonable workaround indeed.

**Comment by gforghetti** [comment]
I'm running 4.4.0-31-generic.

**Comment by gforghetti** [comment]
I updated the kernel to 4.14.0-041400 and the problem is resolved.

**Comment by antoineco** [comment]
Awesome!
