### ISSUE TITLE
How to connect from another docker-compose suite?

### ISSUE THREAD

**Issue by michaelgrosner** [deviantony/docker-elk#234]
Hi,

I am running my application in a docker-compose group, and docker-elk, on the same host machine. My application (a node.js app using elasticsearch.js) cannot connect to the elasticsearch instance. All of my connections are `ECONNREFUSED 127.0.0.1:9200`.

Is there anything special that I need to do to be able to connect from my instance?

**Comment by deviantony** [comment]
Hey @michaelgrosner, you have multiple solutions here:

* if you're using another docker-compose file to start your nodeJS app, you can probably access the elasticsearch instance by using the IP address of the node where the docker-elk stack is started (on port 9200)

* if you're using another docker-compose file to start your nodeJS app, another alternative is to define the `elk` network as external in there and use `elasticsearch` to connect to it (your nodeJS app must be declared in this network as well):

```
networks:
  elk:
    external:
      name: elk
```

* add your nodejs app as a part of the docker-elk compose file and use `elasticsearch` to connect to it
