### ISSUE TITLE
Cluster to an external host/container

### ISSUE THREAD

**Issue by RANGERBEE** [deviantony/docker-elk#238]
Hey Tony,

  Could you tell me what is the best way to setup config to cluster to an external host / container?

I was thinking the elasticsearch.yml.
Set zen discovery for unicast.
Set master servers to 2
Set the data and master node settings on each.
Set the seed list
network.host 0.0.0.0 - (so it uses the mapped / exposed IP)

Ref here: [https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html](url)

Please let me know if I am on the right track.

(I think the use of the compose file is still confusing my logic)

Thanks!!

**Comment by RANGERBEE** [comment]
Ive tried all settings with no joy.

**Comment by antoineco** [comment]
What do you mean exactly with "external host"?

Here is a guide on scaling Elasticsearch using Docker Compose: https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster

Of course it applies only to Compose since ES nodes discover each other using the internal Docker DNS server.

**Comment by RANGERBEE** [comment]
Yes I have the scaling of the service exercised just fine with compose..

What I want to do is connect the cluster to a totally seperate machine running a totally different container. I tried setting the configs to point to the exposed IP addresses ( as referenced in the link) with no Joy.

Any advice?

Thx.

**Comment by antoineco** [comment]
From an external machine you should be able to configure your clients to use a list of `ip:port`, where _port_ is dynamically allocated by Docker (check `docker container ls`).

Eg. `my.compose.server:32120,my.compose.server:32121`

Due to the dynamic nature of the port bindings, this should be reserved to prototyping use-cases.

**Comment by RANGERBEE** [comment]
Thanks!
