### ISSUE TITLE
elasticsearch/config/sg should be mounted?

### ISSUE THREAD

**Issue by dgptamayo** [deviantony/docker-elk#239]
Shouldn't the searchguard config dir (`elasticsearch/config/sg`) mounted from host? Spent hours updating the permissions and running `init_sg.sh` only to realize that it's not taking effect since it's not mounted

**Comment by antoineco** [comment]
It should be possible to mount that directory instead of baking it inside the image indeed.

**Comment by RANGERBEE** [comment]
So, mount via compose file under elasticsearch service as most effective solution?

**Comment by antoineco** [comment]
Yes that sounds reasonable. If you believe it makes things easier let's go for it.
