### ISSUE TITLE
Service 'kibana' failed to build

### ISSUE THREAD

**Issue by shredding** [deviantony/docker-elk#24]
Thanks for the package!

```
Service 'kibana' failed to build: The command '/bin/sh -c kibana plugin --install elastic/sense' returned a non-zero code: 137
```

Do you have an idea about that?

**Comment by deviantony** [comment]
Maybe an issue with your internet connection or sense was unavailable at the time from the elastic servers.

I've just tried to rebuild the images without problem:

```bash
Step 5 : RUN kibana plugin --install elastic/sense
 ---> Running in 6ca2cdf98c49
Installing sense
Attempting to extract from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
Downloading 318236 bytes....................
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
 ---> 51d27d7e3080
Removing intermediate container 6ca2cdf98c49

```

**Comment by shredding** [comment]
Okay, the problem was that I already had an elasticsearch container running somewhere else on the same port :)

Thanks for your help.

**Comment by joeydouglas** [comment]
I was getting the same error and it ended up being a lack of RAM (using the default 1024 megs from Vagrant - ubuntu/trusty64). Make sure you have at least 2GB, preferably a bit more.
