### ISSUE TITLE
problems after reboot

### ISSUE THREAD

**Issue by Pinblack** [deviantony/docker-elk#253]
When i reboot the ubuntu system i can´t acess elasticsearch and kibana via the webinterface.
What should i do that they are also running after reboot ?

**Comment by antoineco** [comment]
Hey @Pinblack 👋  Take a look at the `restart` setting: https://docs.docker.com/compose/compose-file/#restart

**Comment by Pinblack** [comment]
Hi. Thank you but that has not solved my problem.
The problem is that my  $ /vagrant folder is empty after reboot.
After installation it is mounted on a fodler on local PC. But after reboot it is empty. 
What can i do ?

**Comment by deviantony** [comment]
I think this issue is related to your environment (Vagrant setup) and not this project, I suggest you have a look at the Vagrant documentation.
