### ISSUE TITLE
Using Docke ELK to Collect Logs To Display Garbled

### ISSUE THREAD

**Issue by cddisk2000** [deviantony/docker-elk#256]
Original Log Location: 
[ 3月 22 11:37:20.568] [ message] [vmtoolsd] Plugin 'timeSync' initialized.
[ 3月 22 11:37:20.568] [ message] [vmsvc] Cannot load message catalog for domain 'vmbackup', language 'zh', catalog dir '/usr/share/open-vm-tools'.

ELK Log Presentation Garbled Like This:
u\u0000\u0002\xF8\xB3\xCA\xF1u\xC8*\xCEM\x88\xAFX\x98X\b\xAB%\x89B\xFEuOjq\x9B\u0017˶'\u001F%\xE62/\xCBz\x99\xDB\a'h\xE8\xBE\u0019\xB2ZZg\xAB\xAB\x8E\xB7\

I Try Go To Container ( dockerelk_logstash ) Modify This Location  => vi /usr/share/logstash/pipeline/logstash.conf

=====================
input {
        tcp {
                port => 5000
        }
        codec => plain {
                charset => ["UTF-8"]
               }
}

## Add your filters / logstash plugins configuration here

output {
        elasticsearch {
                hosts => "elasticsearch:9200"
        }
}
==========================

But Have Error  => "pipeline/logstash.conf" E212: Can't open file for writing

Can You Help Me .... How To solve

**Comment by antoineco** [comment]
You can not change the file inside the container because it is mounted in read-only mode (see compose file). Change it directly on the host instead.
