### ISSUE TITLE
Kibana Unable to connect to ElasticSearch

### ISSUE THREAD

**Issue by dhanugupta** [deviantony/docker-elk#26]
Kibana keep on getting Bad Gateway error connecting to Elasticsearch.
I checked elasticsearch instance, its working properly

{"statusCode":502,"error":"Bad Gateway","message":"connect ECONNREFUSED"}

any idea about this issue?

**Comment by deviantony** [comment]
Did you change anything in the Kibana configuration?

Also, are you using docker/docker-compose to start the stack? Or any other tool like docker-machine?

**Comment by dhanugupta** [comment]
Yes kibana.yml change elastic search url : http://localhost:9200 
Using docker-compose to start the stack...Both elastic search + log stash are working and able to post the data to elastic search.

**Comment by deviantony** [comment]
Do not change the elasticsearch URL in the configuration, it is already set to 'elasticsearch' which is the name of the docker container. docker-compose will use the container name 'elasticsearch' (the link attribute in the YML file) to establish the communication between kibana and elasticsearch.

**Comment by dhanugupta** [comment]
looks like it worked now..i did left the configuration as it is, since it was linked to elastic search container..when it didn't worked, was playing with it...thanks its now working correct...
qq: i have logstash-YYYY.MM.DD elastic search record, but cabin not able to show?

**Comment by hokiegeek2** [comment]
Thanks guys! This thread solved my kibana-elasticsearch connectivity issue
