### ISSUE TITLE
question

### ISSUE THREAD

**Issue by otpisani** [deviantony/docker-elk#261]
I have couple of question

- Can I find online elk stack emulator online config testing
- How much memory ELK stack will drain for small network monitoring suricata logs
- Do I need to add json plugin in logstash like you put in docker file example
- Can I add another conf file AND/OR different name in logstash/pipeline

I have remote suricata on which plan to install filebeats and send logs to logstash

This is my conf

ON  Filebeat side

  prospectors:

    - input_type: log
      paths:
        - /var/log/suricata/eve.json       
        document_type: SuricataIDPS 
output:
  logstash:
    hosts:
      - logstash.hostname:["xxx.xxx.xxx.xxx:5044"]

ON logstash side

	
input {
    beats {
        port => 5044
        codec => json
    }
}
}
filter {
  if [type] == "SuricataIDPS" {
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    ruby {
      code => "if event['event_type'] == 'fileinfo'; event['fileinfo']['type']=event['fileinfo']['magic'].to_s.split(',')[0]; end;"
    }
  }

  if [src_ip]  {
    geoip {
      source => "src_ip"
      target => "geoip"
      #database => "/etc/logstash/GeoLite2-City.mmdb"
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float" ]
    }
    if ![geoip.ip] {
      if [dest_ip]  {
        geoip {
          source => "dest_ip"
          target => "geoip"
          #database => "/etc/logstash/GeoLite2-City.mmdb"
        }
        mutate {
          convert => [ "[geoip][coordinates]", "float" ]
        }
	 }
 }
 }
 } 
output {
elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}

**Comment by antoineco** [comment]
Hi @optisani, this question has little to do with Docker, therefore I believe you'll have more success asking it at https://discuss.elastic.co/.

Closing.
