### ISSUE TITLE
logstash refuse connection

### ISSUE THREAD

**Issue by otpisani** [deviantony/docker-elk#269]
I have initial setup without any modification, why can't I connect on logstash, like 'telnet localhost 5044', but can connect on elasticsearch remotly or local....

`[otpisani@alfa2 docker-elk]$ telnet localhost 5044
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused`

Second Q. what is command and right path to check logstash conf file inside container, locally is 
`logtsash test config -c path to conf `

**Comment by antoineco** [comment]
@otpisani because there is nothing listing on port 5044.
Please read the README and fill in the issue template before opening issues.
