### ISSUE TITLE
In logstash.conf i likely to use nginx access.log file.Now how to check the output.

### ISSUE THREAD

**Issue by veeruborra** [deviantony/docker-elk#27]
```
//--gork filter

NGINX_ACCESS %{IPORHOST:remote_addr} - %{USERNAME:remote_user} \[%{HTTPDATE:time_local}\] %{QS:request} %{INT:status} %{INT:body_bytes_sent} %{QS:http_referer} %{QS:http_user_agent}
```

```
//--------------logstash.conf
input {

  file {
    type => "nginx"
    start_position => "beginning"
    path => [ "/var/log/nginx/access.log" ]
  }
}
filter {
  if [type] == "nginx" {
    grok {
	patterns_dir => "/etc/logstash/patterns"
	match => { "message" => "%{NGINX_ACCESS}" }
	remove_tag => ["_grokparsefailure"]
	add_tag => ["nginx_access"]
    }
 
    geoip {
      source => "remote_addr"
    }
  }
}


output {
	elasticsearch {
		
		hosts => "elasticsearch:9200"
	}
         
}
```

**Comment by deviantony** [comment]
I'm not sure I understand the problem, could you explain it in details please ?

**Comment by veeruborra** [comment]
The nginx access.log files are not saving in the elastic search.i want to know whether the access.log files are importing in to logstash.conf and whether it passing through the grok filter

**Comment by veeruborra** [comment]
///docker-compose.yml
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /var/log/nginx:/var/log/nginx
    - ./logstash/patterns/nginx:/etc/logstash/patterns/nginx
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch

///ends--------------


///logstash.conf ---------------starts--------

input {
	
 file {
    type => "nginx"
    start_position => "beginning"
    path => [ "/var/log/nginx/access.log" ]
  }
}
filter {
  if [type] == "nginx" {
    grok {
	patterns_dir => "/etc/logstash/patterns"
	match => { "message" => "%{NGINX_ACCESS}" }
	remove_tag => ["_grokparsefailure"]
	add_tag => ["nginx_access"]
    }
 
    geoip {
      source => "remote_addr"
    }
  }
}
## Add your filters here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
              
	}
}
//-----------------------ends-----------------------------------


//logstash/patterns/nginx------------starts----------

NGINX_ACCESS %{IPORHOST:remote_addr} - %{USERNAME:remote_user} \[%{HTTPDATE:time_local}\] %{QS:request} %{INT:status} %{INT:body_bytes_sent} %{QS:http_referer} %{QS:http_user_agent}


///---------------ends---------------------

**Comment by veeruborra** [comment]
The above is the configuration iam using..whether the process is correct or not ?.
can u tell me how to check nginx access.log

**Comment by deviantony** [comment]
Have you tried to explore the elasticsearch container using the `docker exec` command?

**Comment by veeruborra** [comment]
My problem is cleared.
The command line (logstash -f /etc/logstash/conf.d/logstash.conf) in docker-compose.yml is not responding..
we must go to logstash container and we must execute the command (logstash -f /etc/logstash/conf.d/logstash.conf ) or (logstash agent -f  /etc/logstash/conf.d/logstash.conf -w 10 &)
