### ISSUE TITLE
Limits on ELK X-Pack Branch?

### ISSUE THREAD

**Issue by ramalo3** [deviantony/docker-elk#270]
Good afternoon to whoever is reading this:

I've tried to include the X-Pack plugin manually in the master branch of the repository, but I got loads of problems. Above all, the reason why I decide not to follow that way is that with the trial license of X-Pack, you cant use any security pluggin of X-Pack, that is what I was looking for, sadly.

My only and simple question is: Which are the limits on the version of X-Pack that is included in the ELK X-Pack branch? Does it have the same limitations than the trial version? I am asking that because, although I looked for it, I found none asking or answering this, and in the Readme it is said that you have to enter an username and its password to log into Kibana (what makes me think that the security pluggin is activated in this version of X-Pack). Hope you can answer my question.

I'm sorry If my English isnt the best, but I hope it's enough to understand my problem ^^

Thanks for the help.

**Comment by antoineco** [comment]
@ramalo3 have you tried switching the current FROM image [`elasticsearch-basic`](https://github.com/deviantony/docker-elk/blob/x-pack/elasticsearch/Dockerfile#L2) to [`elasticsearch-platinum`](https://github.com/elastic/elasticsearch-docker/blob/dc321b6d38718a86d2d72d8ecf0d198f86caa6d3/Makefile#L16). Although I believe the only difference with the `basic` image is that `xpack.security.audit.enabled=true` is set by default, which you could very well add manually to your elasticsearch.yml without touching the image.

**Comment by ramalo3** [comment]
So, sorry If Im misunderstanding what you are saying, but you say I could use other versions of X-Pack by changing the image of Elasticsearch I choose to download in the Dockerfile? If thats not the idea, then I dont really get how that could solve my problem. Maybe I didnt explain myself correctly...

My problem is that I want to use the X-Pack security pluggin, but when I use the basic license of X-Pack, its not included. So thats why I was asking which is the version included in the branch that includes X-Pack.

Hope you can help me to solve this ^^
Thanks for your attention

**Comment by ramalo3** [comment]
Well, I'm not sure If that solves my problem, because I havent understood it correctly ^^"

I saw this page: https://www.elastic.co/subscriptions, where it says that you need at last a Gold license in X-Pack in order to use the security pluggin. My question was if in the version of X-Pack I can use the security pluggin or not...

When I tried to get X-Pack in the master branch, I could create some users and choose the passwords to each one of them, but although I did everything I saw in Internet, I couldnt stop receiving an error in ES saying that he couldnt authenticate the [kibana] user, so thats why I thought that the problem is that my trial license doesnt give me everything I need to use the security feature of X-Pack.

I may have forgotten something in the things I did to active X-Pack but I have done everything I read in posts from other people in a lots of pages and nothing works. Thats why I am asking if the branch that is in this repository let me use the security feature of X-Pack, or if it lets me use it with some limitations... Or If you know any way to get that feature.

Im sorry If Im not explaining myself, really.

**Comment by antoineco** [comment]
You need the license to continue using X-Pack paid features **after the trial license expires**. You also get all the features

Take a look at the X-Pack branch, 
 1. it really does contain *all* features
 2. it is configured with sane defaults
Make sure you rebuild your images when switching branches.
