### ISSUE TITLE
index pattern 

### ISSUE THREAD

**Issue by hakimFUT** [deviantony/docker-elk#272]
### Problem description

Hello , after implementing this project , all run okay , but when i add index into /logstash/pipeline/logstash.conf , it doen't appear in kibana , is it a permission probleme ?

#### Docker setup

```
<!-- Replace this comment with the full output of the `docker version` command. -->
```

```
<!-- Replace this comment with the full output of the `docker-compose version` command. -->
```

#### Docker logs

```
ogstash_1 | [2018-05-17T10:46:38,076][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//x.x.x.x:9200"]}
logstash_1 | [2018-05-17T10:46:38,980][INFO ][logstash.inputs.beats ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5000"}
logstash_1 | [2018-05-17T10:46:39,108][INFO ][logstash.pipeline ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x5c600635 run>"}
logstash_1 | [2018-05-17T10:46:39,277][INFO ][org.logstash.beats.Server] Starting server on port: 5000
logstash_1 | [2018-05-17T10:46:39,378][INFO ][logstash.agent ] Pipelines running {:count=>1, :pipelines=>["main"]}

logs for kibana :

kibana_1 | {"type":"response","@timestamp":"2018-05-17T10:46:57Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/","method":"get","headers":{"host":"x.x.x.x:5601","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate","connection":"keep-alive","upgrade-insecure-requests":"1"},"remoteAddress":"y.y.y.y","userAgent":"y.y.y.y"},"res":{"statusCode":200,"responseTime":724,"contentLength":9},"message":"GET / 200 724ms - 9.0B"}

filebeat logs :

2018-05-17T13:05:52.743+0200 INFO [monitoring] log/log.go:124 Non-zero metrics in the last 30s {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":150,"time":152},"total":{"ticks":480,"time":484,"value":480},"user":{"ticks":330,"time":332}},"info":{"ephemeral_id":"24ce3d02-fbf9-4163-b416-b518c0c7d05b","uptime":{"ms":1230287}},"memstats":{"gc_next":4194304,"memory_alloc":1451800,"memory_total":11129216}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"registrar":{"states":{"current":3}},"system":{"load":{"1":1.95,"15":30.98,"5":6.9,"norm":{"1":0.2438,"15":3.8725,"5":0.8625}}}}}}
```

**Comment by antoineco** [comment]
Indexes are automatically created by Logstash as soon as it receives data. All you have to do is feed log entries to Logstash, and your indexes will appear (cf. README file).

**Comment by hakimFUT** [comment]
okay , because in first i am using filebeat to put data into logstash , may be the probleme is there ?

**Comment by antoineco** [comment]
Probably yes, did you enable the Filebeat input inside your Logstash conf?

**Comment by hakimFUT** [comment]
that's my logstash.conf : 

input {
        beats {
                port => 5000
        }
}

## Add your filters / logstash plugins configuration here

output {
        elasticsearch {
                hosts => "x.x.x.x:9200"
                index => "logTest"
                user => logstash
                password => logstash
        }
}


x.x.x.x remplace my server add IP

**Comment by hakimFUT** [comment]
and there is my filebeat.yml : 

output:
  logstash:
    enabled: true
    hosts:
      - x.x.x.x:5000
    timeout: 15

filebeat:
  prospectors:
    -
      paths:
        - "/home/hakim/*.log"
      document_type: logHakim

**Comment by antoineco** [comment]
Any Filebeat logs?

**Comment by hakimFUT** [comment]
i didn't get what you do you mean by your question ? 

but the problème i think evenif there is no data into logstash it can creat index pattern , no ?

**Comment by hakimFUT** [comment]
there is log : 

logstash_1       | [2018-05-17T10:46:38,076][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//x.x.x.x:9200"]}
logstash_1       | [2018-05-17T10:46:38,980][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5000"}
logstash_1       | [2018-05-17T10:46:39,108][INFO ][logstash.pipeline        ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x5c600635 run>"}
logstash_1       | [2018-05-17T10:46:39,277][INFO ][org.logstash.beats.Server] Starting server on port: 5000
logstash_1       | [2018-05-17T10:46:39,378][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}


logs for kibana : 

kibana_1         | {"type":"response","@timestamp":"2018-05-17T10:46:57Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/","method":"get","headers":{"host":"x.x.x.x:5601","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate","connection":"keep-alive","upgrade-insecure-requests":"1"},"remoteAddress":"y.y.y.y","userAgent":"y.y.y.y"},"res":{"statusCode":200,"responseTime":724,"contentLength":9},"message":"GET / 200 724ms - 9.0B"}




filebeat logs : 


2018-05-17T13:05:52.743+0200	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":150,"time":152},"total":{"ticks":480,"time":484,"value":480},"user":{"ticks":330,"time":332}},"info":{"ephemeral_id":"24ce3d02-fbf9-4163-b416-b518c0c7d05b","uptime":{"ms":1230287}},"memstats":{"gc_next":4194304,"memory_alloc":1451800,"memory_total":11129216}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"registrar":{"states":{"current":3}},"system":{"load":{"1":1.95,"15":30.98,"5":6.9,"norm":{"1":0.2438,"15":3.8725,"5":0.8625}}}}}}

**Comment by antoineco** [comment]
When you opened your issue there were instructions about what information is useful for us to help you solving your issue. Please edit your issue report and add these.

Also please include the logs of your Filebeat agent.

You will be able to create the index pattern as soon as data flows in.

**Comment by hakimFUT** [comment]
i do it :)

**Comment by hakimFUT** [comment]
i resolved my issue ; it's was like my server doesn't take the existing log file ,so when i tried to creat a new log file test , it's worked , thank you antoineco ;)
