### ISSUE TITLE
Logstash could not write udp connection refused

### ISSUE THREAD

**Issue by sodaliAyran** [deviantony/docker-elk#282]
### Problem description
When I try to run 

docker-compose -f docker-compose.yml -f extensions/logspout/logspout-compose.yml up
I get the error (Or is it an error?)
2018/06/08 07:49:43 logstash: could not write:write udp 172.21.0.5:55829->172.21.0.3:5000: write: connection refused

Sorry if this already solved but I'm on this problem for days but couldn't find anything to solve it. I hope it has some silly answer I couldn't see. Thanks in advance.

#### Stack configuration
Is the same.

#### Docker setup

```
Docker version 18.03.1-ce, build 9ee9f40

```

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

#### Docker logs

```
logspout_1       | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout_1       | #   logstash	logstash:5000				map[]
logspout_1       | 2018/06/08 07:45:07 logstash: could not write:write udp 172.21.0.5:56225->172.21.0.3:5000: write: connection refused
logspout_1       | # logspout v3.2.5-custom by gliderlabs
logspout_1       | # adapters: logstash raw udp tcp
logspout_1       | # options : persist:/mnt/routes
logspout_1       | # jobs    : pump routes http[]:80
logspout_1       | # routes  :

```

**Comment by antoineco** [comment]
Thanks for reporting this @sodaliAyran. It looks indeed like logspout is using UDP instead of TCP now. I'll look into what needs to be reconfigured.

**Comment by jcochard** [comment]
> Use by setting a docker environment variable ROUTE_URIS=logstash://host:port to the Logstash server. The default protocol is UDP, but it is possible to change to TCP by adding +tcp after the logstash protocol when starting your container.  

For example:
`ROUTE_URIS=logstash+tcp://logstash.home.local:5000`

**Comment by antoineco** [comment]
@sodaliAyran you did not follow all the the instructions on https://github.com/deviantony/docker-elk/tree/master/extensions/logspout.

It is mentioned a UDP `input` is required inside the Logstash pipeline.

Closing.

**Comment by sharonsahadevan** [comment]
I used logspout:v2 image to fix the problem. But it was working fine with v3 image till yesterday.I have included a snippet from my docker compose file.

logspout:
    image: gliderlabs/logspout:v2
    command: 'udp://logstash:5044'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - odfe-node2
      - logstash
      - kibana
    networks:
      - odfe-net

This is my logstash.conf

input {
        tcp {
                port => 5000
        }
        udp{
            port => 5044
            codec => json
            type => dockerlog

       }
}

output {
        elasticsearch {
                hosts => "odfe-node2:9200"
        }
}

This is my repo, tested and working fine for me.
https://github.com/sharonsahadevan/opendistro-elk-logspout/

**Comment by pedro2555** [comment]
> @sodaliAyran you did not follow all the the instructions at https://github.com/deviantony/docker-elk/tree/master/extensions/logspout.
> 
> It is mentioned a UDP `input` is required inside the Logstash pipeline.
> 
> Closing.

2 years on and still facing this issue. Yet you decided the reason without reasoning back then.
