### ISSUE TITLE
Can't download nodejs/npm with Kibana

### ISSUE THREAD

**Issue by seanziee** [deviantony/docker-elk#289]
I'm trying to add some custom plugins to my kibana, all of which require me to npm install. How can I install node after pulling in the oss:6.2.4 version?

Code:
```
FROM docker.elastic.co/kibana/kibana-oss:6.2.4
```
I've tried:

`FROM node:9`
`RUN yum -y update && yum -y install nodejs npm`
`RUN apt-get -y update && apt-get -y install npm nodejs`
 to no avail.

After building, I get this error `docker-test1_kibana_1 exited with code 0`. When I remove the nodejs installations, I don't get the error anymore.

Is this a bug? I can't seem to make these work together.

**Comment by antoineco** [comment]
You can't use `FROM node:9`, this image does not contain Kibana.

Elastic images are [based on CentOS](https://github.com/elastic/kibana-docker/blob/master/templates/Dockerfile.j2#L19), not Debian, so you have to use the package manager from CentOS.

**Comment by seanziee** [comment]
Hmm interesting.. What would the command look like. Sorry for my ignorance
:)

**Comment by antoineco** [comment]
@seanziee this is documented in the link above.

In case of difficulties I kindly redirect you to https://wiki.centos.org/Documentation because general Linux questions are way outside of the scope of this repo.
