### ISSUE TITLE
docker-elk_logstash_1 exited with code 1

### ISSUE THREAD

**Issue by atheeth96** [deviantony/docker-elk#291]
I'm trying to pass syslogs to elasticsearch through logstash.I'm using the dckerized version of ELK stack.The default image runs with no error.However when i use logstash-input-file to give path of /var/log/*log and syslog i get the error mentioned.I did mount the /var/log dir to logstash container in docker-compose.yml.Please note that behind a firewall so do let me know if i have to make any proxy changes. The logatash container doesnt provide any error.I have tried all the previously mentioned solutions also.
Primarily i used this site for reference
https://logz.io/blog/elk-stack-on-docker/

root@debian:/home/arup123/docker-elk# docker-compose down
Removing docker-elk_logstash_1      ... done
Removing docker-elk_kibana_1        ... done
Removing docker-elk_elasticsearch_1 ... done
Removing network docker-elk_elk
root@debian:/home/arup123/docker-elk# docker-compose up --build
Creating network "docker-elk_elk" with driver "bridge"
Building elasticsearch
Step 1/1 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
 ---> 345a3630eed8
Successfully built 345a3630eed8
Successfully tagged docker-elk_elasticsearch:latest
Building logstash
Step 1/7 : FROM docker.elastic.co/logstash/logstash-oss:6.3.0
 ---> 77bdbc2dc566
Step 2/7 : ENV HTTP_PROXY http://194.138.0.25:9400
 ---> Using cache
 ---> 216e4e0a4550
Step 3/7 : ENV HTTPS_PROXY http://194.138.0.25:9400
 ---> Using cache
 ---> 85145b489156
Step 4/7 : RUN export http_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 76d517e946df
Step 5/7 : RUN export https_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 15badd9d5a39
Step 6/7 : RUN export ftp_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 63cd43f41889
Step 7/7 : RUN export no_proxy="localhost,127.0.0.1"
 ---> Using cache
 ---> caa5a13cab97
Successfully built caa5a13cab97
Successfully tagged docker-elk_logstash:latest
Building kibana
Step 1/1 : FROM docker.elastic.co/kibana/kibana-oss:6.3.0
 ---> 135bf752e257
Successfully built 135bf752e257
Successfully tagged docker-elk_kibana:latest
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_kibana_1        ... done
Creating docker-elk_logstash_1      ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_kibana_1, docker-elk_logstash_1
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
logstash_1       | OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:16Z","tags":["status","plugin:kibana@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:16Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["status","plugin:timelion@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["status","plugin:console@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["status","plugin:metrics@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0:5601"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.18.0.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:17Z","tags":["status","plugin:elasticsearch@6.3.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
elasticsearch_1  | [2018-07-10T08:33:19,607][INFO ][o.e.n.Node               ] [] initializing ...
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:19Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:19Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:33:20,101][INFO ][o.e.e.NodeEnvironment    ] [4k93D1D] using [1] data paths, mounts [[/ (overlay)]], net usable_space [8.1gb], net total_space [18.2gb], types [overlay]
elasticsearch_1  | [2018-07-10T08:33:20,104][INFO ][o.e.e.NodeEnvironment    ] [4k93D1D] heap size [1015.6mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2018-07-10T08:33:20,110][INFO ][o.e.n.Node               ] [4k93D1D] node name derived from node ID [4k93D1D_Q-uHM2Lt9oUxKg]; set [node.name] to override
elasticsearch_1  | [2018-07-10T08:33:20,113][INFO ][o.e.n.Node               ] [4k93D1D] version[6.3.0], pid[1], build[oss/tar/424e937/2018-06-11T23:38:03.357887Z], OS[Linux/4.9.0-6-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/10.0.1/10.0.1+10]
elasticsearch_1  | [2018-07-10T08:33:20,125][INFO ][o.e.n.Node               ] [4k93D1D] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.q9ZeaQof, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:22Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:22Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:33:25,405][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2018-07-10T08:33:25,412][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [analysis-common]
elasticsearch_1  | [2018-07-10T08:33:25,412][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [ingest-common]
elasticsearch_1  | [2018-07-10T08:33:25,413][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [lang-expression]
elasticsearch_1  | [2018-07-10T08:33:25,413][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [lang-mustache]
elasticsearch_1  | [2018-07-10T08:33:25,413][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [lang-painless]
elasticsearch_1  | [2018-07-10T08:33:25,414][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [mapper-extras]
elasticsearch_1  | [2018-07-10T08:33:25,414][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [parent-join]
elasticsearch_1  | [2018-07-10T08:33:25,414][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [percolator]
elasticsearch_1  | [2018-07-10T08:33:25,414][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [rank-eval]
elasticsearch_1  | [2018-07-10T08:33:25,415][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [reindex]
elasticsearch_1  | [2018-07-10T08:33:25,419][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [repository-url]
elasticsearch_1  | [2018-07-10T08:33:25,420][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [transport-netty4]
elasticsearch_1  | [2018-07-10T08:33:25,421][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded module [tribe]
elasticsearch_1  | [2018-07-10T08:33:25,422][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded plugin [ingest-geoip]
elasticsearch_1  | [2018-07-10T08:33:25,422][INFO ][o.e.p.PluginsService     ] [4k93D1D] loaded plugin [ingest-user-agent]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:33:39,194][INFO ][o.e.d.DiscoveryModule    ] [4k93D1D] using discovery type [single-node]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:33:41,744][INFO ][o.e.n.Node               ] [4k93D1D] initialized
elasticsearch_1  | [2018-07-10T08:33:41,762][INFO ][o.e.n.Node               ] [4k93D1D] starting ...
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:33:42,573][INFO ][o.e.t.TransportService   ] [4k93D1D] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2018-07-10T08:33:42,813][INFO ][o.e.h.n.Netty4HttpServerTransport] [4k93D1D] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2018-07-10T08:33:42,814][INFO ][o.e.n.Node               ] [4k93D1D] started
elasticsearch_1  | [2018-07-10T08:33:43,006][INFO ][o.e.g.GatewayService     ] [4k93D1D] recovered [0] indices into cluster_state
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:33:46Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
docker-elk_logstash_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker-elk_kibana_1        ... done
Stopping docker-elk_elasticsearch_1 ... done
root@debian:/home/arup123/docker-elk# /usr/share/logstash/bin/logstash-plugin install logstash-output-mongodb
Validating logstash-output-mongodb
Installing logstash-output-mongodb
Installation successful
root@debian:/home/arup123/docker-elk# gedit docker-compose.yml

(gedit:23956): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(gedit:23956): GLib-GIO-CRITICAL **: g_dbus_proxy_get_name_owner: assertion 'G_IS_DBUS_PROXY (proxy)' failed

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed

** (gedit:23956): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-spell-language not supported

** (gedit:23956): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-encoding not supported

** (gedit:23956): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-position not supported

(gedit:23956): dconf-WARNING **: failed to commit changes to dconf: The connection is closed
root@debian:/home/arup123/docker-elk# docker-compose down
Removing docker-elk_logstash_1      ... done
Removing docker-elk_kibana_1        ... done
Removing docker-elk_elasticsearch_1 ... done
Removing network docker-elk_elk
root@debian:/home/arup123/docker-elk# docker-compose up --buildCreating network "docker-elk_elk" with driver "bridge"
Building elasticsearch
Step 1/1 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
 ---> 345a3630eed8
Successfully built 345a3630eed8
Successfully tagged docker-elk_elasticsearch:latest
Building logstash
Step 1/7 : FROM docker.elastic.co/logstash/logstash-oss:6.3.0
 ---> 77bdbc2dc566
Step 2/7 : ENV HTTP_PROXY http://194.138.0.25:9400
 ---> Using cache
 ---> 216e4e0a4550
Step 3/7 : ENV HTTPS_PROXY http://194.138.0.25:9400
 ---> Using cache
 ---> 85145b489156
Step 4/7 : RUN export http_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 76d517e946df
Step 5/7 : RUN export https_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 15badd9d5a39
Step 6/7 : RUN export ftp_proxy=http://194.138.0.25:9400
 ---> Using cache
 ---> 63cd43f41889
Step 7/7 : RUN export no_proxy="localhost,127.0.0.1"
 ---> Using cache
 ---> caa5a13cab97
Successfully built caa5a13cab97
Successfully tagged docker-elk_logstash:latest
Building kibana
Step 1/1 : FROM docker.elastic.co/kibana/kibana-oss:6.3.0
 ---> 135bf752e257
Successfully built 135bf752e257
Successfully tagged docker-elk_kibana:latest
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_kibana_1        ... done
Creating docker-elk_logstash_1      ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_kibana_1, docker-elk_logstash_1
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
logstash_1       | OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
elasticsearch_1  | [2018-07-10T08:40:24,728][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-07-10T08:40:25,390][INFO ][o.e.e.NodeEnvironment    ] [ghCf0VW] using [1] data paths, mounts [[/ (overlay)]], net usable_space [8.1gb], net total_space [18.2gb], types [overlay]
elasticsearch_1  | [2018-07-10T08:40:25,392][INFO ][o.e.e.NodeEnvironment    ] [ghCf0VW] heap size [247.6mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2018-07-10T08:40:25,406][INFO ][o.e.n.Node               ] [ghCf0VW] node name derived from node ID [ghCf0VWrTF672_q5Kwx2_w]; set [node.name] to override
elasticsearch_1  | [2018-07-10T08:40:25,418][INFO ][o.e.n.Node               ] [ghCf0VW] version[6.3.0], pid[1], build[oss/tar/424e937/2018-06-11T23:38:03.357887Z], OS[Linux/4.9.0-6-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/10.0.1/10.0.1+10]
elasticsearch_1  | [2018-07-10T08:40:25,418][INFO ][o.e.n.Node               ] [ghCf0VW] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.z0Rf2x2Y, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Des.cgroups.hierarchy.override=/, -Xmx256m, -Xms256m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:26Z","tags":["status","plugin:kibana@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:26Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["status","plugin:timelion@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["status","plugin:console@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["status","plugin:metrics@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["listening","info"],"pid":1,"message":"Server running at http://0:5601"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["error","elasticsearch","admin"],"pid":1,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.18.0.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:27Z","tags":["status","plugin:elasticsearch@6.3.0","error"],"pid":1,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:29Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:40:30,747][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2018-07-10T08:40:30,757][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [analysis-common]
elasticsearch_1  | [2018-07-10T08:40:30,758][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [ingest-common]
elasticsearch_1  | [2018-07-10T08:40:30,759][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [lang-expression]
elasticsearch_1  | [2018-07-10T08:40:30,759][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [lang-mustache]
elasticsearch_1  | [2018-07-10T08:40:30,759][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [lang-painless]
elasticsearch_1  | [2018-07-10T08:40:30,761][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [mapper-extras]
elasticsearch_1  | [2018-07-10T08:40:30,761][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [parent-join]
elasticsearch_1  | [2018-07-10T08:40:30,762][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [percolator]
elasticsearch_1  | [2018-07-10T08:40:30,762][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [rank-eval]
elasticsearch_1  | [2018-07-10T08:40:30,762][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [reindex]
elasticsearch_1  | [2018-07-10T08:40:30,763][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [repository-url]
elasticsearch_1  | [2018-07-10T08:40:30,763][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [transport-netty4]
elasticsearch_1  | [2018-07-10T08:40:30,763][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded module [tribe]
elasticsearch_1  | [2018-07-10T08:40:30,765][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded plugin [ingest-geoip]
elasticsearch_1  | [2018-07-10T08:40:30,768][INFO ][o.e.p.PluginsService     ] [ghCf0VW] loaded plugin [ingest-user-agent]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:32Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:34Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:37Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:39Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:42Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:44Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:44Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:40:47,191][INFO ][o.e.d.DiscoveryModule    ] [ghCf0VW] using discovery type [single-node]
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:47Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:49Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:49Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch_1  | [2018-07-10T08:40:50,835][INFO ][o.e.n.Node               ] [ghCf0VW] initialized
elasticsearch_1  | [2018-07-10T08:40:50,840][INFO ][o.e.n.Node               ] [ghCf0VW] starting ...
elasticsearch_1  | [2018-07-10T08:40:51,643][INFO ][o.e.t.TransportService   ] [ghCf0VW] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2018-07-10T08:40:51,956][INFO ][o.e.h.n.Netty4HttpServerTransport] [ghCf0VW] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2018-07-10T08:40:51,957][INFO ][o.e.n.Node               ] [ghCf0VW] started
elasticsearch_1  | [2018-07-10T08:40:52,166][INFO ][o.e.g.GatewayService     ] [ghCf0VW] recovered [0] indices into cluster_state
kibana_1         | {"type":"log","@timestamp":"2018-07-10T08:40:53Z","tags":["status","plugin:elasticsearch@6.3.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
docker-elk_logstash_1 exited with code 1

#### Docker setup

```
<!-- Replace this comment with the full output of the `docker version` command. -->
```

```
<!-- Replace this comment with the full output of the `docker-compose version` command. -->
```

#### Docker logs

```
<!-- Replace this comment with the full output of the `docker-compose logs` command. -->
```

**Comment by antoineco** [comment]
@atheeth96 please fill-in the issue template and re-open this issue. It's really important for us to have clear information in order to be able to help you.
Thanks for your understanding.
