### ISSUE TITLE
Rather fail early if the arch is not supported 

### ISSUE THREAD

**Issue by fossxplorer** [deviantony/docker-elk#292]
### Problem description
Docker-compose up fails at a late stage on aarch64 due to the platform not being supported. Rather fail early BEFORE pulling/extracting the images when 'docker-compose up' is run on an unsupported arch :)

#### Stack configuration

Here is what happens on an aarch64 system:

_root@rock64:/var/data/zfstest/zfsssd/projects/git/docker-elk# docker-compose up
Creating network "dockerelk_elk" with driver "bridge"
Building elasticsearch
Step 1/1 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
6.3.0: Pulling from elasticsearch/elasticsearch-oss
7dc0dca2b151: Pull complete
a50481268b4a: Pull complete
ee5228de771f: Pull complete
da55b983e8eb: Pull complete
143eb5dd5e49: Pull complete
29d8a2d8ea47: Pull complete
be99c5384de1: Pull complete
Digest: sha256:0e0d73cb8bdce88c25adb9426aecabf89db4235d44ea29402f5f28b813f23d2e
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
 ---> 345a3630eed8
Successfully built 345a3630eed8
Successfully tagged dockerelk_elasticsearch:latest
WARNING: Image for service elasticsearch was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building logstash
Step 1/1 : FROM docker.elastic.co/logstash/logstash-oss:6.3.0
6.3.0: Pulling from logstash/logstash-oss
7dc0dca2b151: Already exists
49bfedd6a110: Pull complete
a64a68a73a51: Pull complete
1cd2ef8fceec: Pull complete
9c36f545c69b: Pull complete
56834e932068: Pull complete
5cddbd76eb86: Pull complete
c3bb761ee199: Pull complete
1d22756d288c: Pull complete
73e34c1b50e9: Pull complete
054f809e4ee2: Pull complete
Digest: sha256:3bb06bac6367163d0e62476a92b93a24391b7d6a0bb9ac775031902eb67bee1c
Status: Downloaded newer image for docker.elastic.co/logstash/logstash-oss:6.3.0
 ---> 77bdbc2dc566
Successfully built 77bdbc2dc566
Successfully tagged dockerelk_logstash:latest
WARNING: Image for service logstash was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building kibana
Step 1/1 : FROM docker.elastic.co/kibana/kibana-oss:6.3.0
6.3.0: Pulling from kibana/kibana-oss
7dc0dca2b151: Already exists
b9645d7e6c1f: Pull complete
b302e33a173a: Pull complete
dc79440b74ce: Pull complete
630d27689874: Pull complete
feca8dd48a11: Pull complete
294e4e758537: Pull complete
7200ec2d04f1: Pull complete
0728d5722948: Pull complete
Digest: sha256:61c80292ce97b05f460efe26409f176c20d8f493b9ec4bdd9da0a8fa78ff8f0a
Status: Downloaded newer image for docker.elastic.co/kibana/kibana-oss:6.3.0
 ---> 135bf752e257
Successfully built 135bf752e257
Successfully tagged dockerelk_kibana:latest
WARNING: Image for service kibana was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating dockerelk_elasticsearch_1
Creating dockerelk_logstash_1
Creating dockerelk_kibana_1
Attaching to dockerelk_elasticsearch_1, dockerelk_logstash_1, dockerelk_kibana_1
elasticsearch_1  | standard_init_linux.go:190: exec user process caused "exec format error"
logstash_1       | standard_init_linux.go:190: exec user process caused "exec format error"
kibana_1         | standard_init_linux.go:190: exec user process caused "exec format error"
dockerelk_elasticsearch_1 exited with code 1
dockerelk_logstash_1 exited with code 1
dockerelk_kibana_1 exited with code 1_

Not sure if you consider if you consider this an improvement, but IMO it should be given a thought at least :)

**Comment by antoineco** [comment]
Thanks for the report. What do you suggest to fix this?
