### ISSUE TITLE
about old release

### ISSUE THREAD

**Issue by LakyTT** [deviantony/docker-elk#293]
Hi，thanks for your inspiring work. And I want to know how I get the old release，such as 5.4.1?

best regards!

**Comment by antoineco** [comment]
Admittedly we haven't been too good at drafting proper releases.

What you can do is checkout the commit corresponding to the version you're interested in.

For example, I see [in the commit list](https://github.com/deviantony/docker-elk/commits/master) that the commit hash for 5.4.1 is `a059efcc`. So you can checkout this revision with 

```console
git checkout a059efcc
```

and run `docker-compose up` after that. Don't forget to `docker-compose build` everytime you checkout a new branch or revision.
