### ISSUE TITLE
added elasticsearch-head plugin  [solved]

### ISSUE THREAD

**Issue by hakimFUT** [deviantony/docker-elk#295]
hello every one , 

i want to added elasticsearch-head plugin , can you tell me the steps to do please ? 

thank you

**Comment by antoineco** [comment]
Check the cerebro example in the wiki: https://github.com/deviantony/docker-elk/wiki/External-applications

Just swap the image with what's documented in the elasticsearch-head repo: https://github.com/mobz/elasticsearch-head/blob/master/README.textile

**Comment by hakimFUT** [comment]
i have ES 6.2.3 so i installed ES-head plugin as a standalone server and it works , but now the problem is when i connect to plugin http://address:9100 i can't connect to my elasticsearch ,i got "cluster health: not connected" message , even if all works and good configured (i added http.cors.enabled: true
http.cors.allow-origin: "*" lines into elasticsearch.yml ) 
i am asking if the problem comes from searchguard ?

**Comment by antoineco** [comment]
Ah, you have SearchGuard enabled. In that case I would look for special instructions regarding authentication. Maybe you have to configure `elasticsearch-head` accordingly, but that question would be more suitable for the `elasticsearch-head` devs.

Btw, `elasticsearch-head` doesn't seem to be compatible with ES 6, are you sure it is supposed to work? Why not using Cerebro?

**Comment by hakimFUT** [comment]
does Cerebro do the same as Es-head ?

**Comment by antoineco** [comment]
Quite sure it does **more**. It's newer and well-maintained (from the author of "kopf"), although the docs are not perfect yet.

https://github.com/lmenezes/cerebro

**Comment by hakimFUT** [comment]
oh thank you a lot , it works !

**Comment by ajarouih** [comment]
Are you using binary or docker build ?

If you are using the binary build: 

./bin/plugin install elasticsearch-head && ./bin/elasticsearch

If your using the docker build you can create another service container:

  elasticsearch-head:
    container_name: sb-elasticsearch-head
    depends_on:
      - elasticsearch
    image: mobz/elasticsearch-head:5
    ports:
      - "9109:9100"
