### ISSUE TITLE
Logstash out of memory

### ISSUE THREAD

**Issue by Sneijky** [deviantony/docker-elk#296]
Hello,

I'm using 5GB of ram in my container, with 2 conf files in /pipeline for two extractions and logstash with the following options:

    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"

And logstash is crashing at start : 
[2018-07-19T20:44:59,456][ERROR][org.logstash.Logstash    ] java.lang.OutOfMemoryError: Java heap space

Any suggestion to fix this?
Thanks in advance.

**Comment by antoineco** [comment]
1G is already quite a lot.

Obvious question: did you try to increase the heap memory even more?

Could you run `docker-compose exec logstash ps auxww` right after logstash starts and post the output?

**Comment by Sneijky** [comment]
I ran the command two times after build successful and after Pipeline started succesfully:

`USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
logstash      1 46.9  4.9 3414180 250260 ?      Ssl  10:55   0:05 /bin/java -Xms1g -Xmx1g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.compile.invokedynamic=true -Djruby.jit.threshold=0 -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/urandom -Xmx1g -Xms1g -cp /usr/share/logstash/logstash-core/lib/jars/animal-sniffer-annotations-1.14.jar:/usr/share/logstash/logstash-core/lib/jars/commons-compiler-3.0.8.jar:/usr/share/logstash/logstash-core/lib/jars/error_prone_annotations-2.0.18.jar:/usr/share/logstash/logstash-core/lib/jars/google-java-format-1.5.jar:/usr/share/logstash/logstash-core/lib/jars/guava-22.0.jar:/usr/share/logstash/logstash-core/lib/jars/j2objc-annotations-1.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-annotations-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-core-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-databind-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-dataformat-cbor-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/janino-3.0.8.jar:/usr/share/logstash/logstash-core/lib/jars/javac-shaded-9-dev-r4023-3.jar:/usr/share/logstash/logstash-core/lib/jars/jruby-complete-9.1.13.0.jar:/usr/share/logstash/logstash-core/lib/jars/jsr305-1.3.9.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-api-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-core-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-slf4j-impl-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/logstash-core.jar:/usr/share/logstash/logstash-core/lib/jars/slf4j-api-1.7.25.jar org.logstash.Logstash`

`USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
logstash      1 80.2  9.9 3628688 504052 ?      Ssl  10:55   1:09 /bin/java -Xms1g -Xmx1g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.compile.invokedynamic=true -Djruby.jit.threshold=0 -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/urandom -Xmx1g -Xms1g -cp /usr/share/logstash/logstash-core/lib/jars/animal-sniffer-annotations-1.14.jar:/usr/share/logstash/logstash-core/lib/jars/commons-compiler-3.0.8.jar:/usr/share/logstash/logstash-core/lib/jars/error_prone_annotations-2.0.18.jar:/usr/share/logstash/logstash-core/lib/jars/google-java-format-1.5.jar:/usr/share/logstash/logstash-core/lib/jars/guava-22.0.jar:/usr/share/logstash/logstash-core/lib/jars/j2objc-annotations-1.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-annotations-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-core-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-databind-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/jackson-dataformat-cbor-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/janino-3.0.8.jar:/usr/share/logstash/logstash-core/lib/jars/javac-shaded-9-dev-r4023-3.jar:/usr/share/logstash/logstash-core/lib/jars/jruby-complete-9.1.13.0.jar:/usr/share/logstash/logstash-core/lib/jars/jsr305-1.3.9.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-api-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-core-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/log4j-slf4j-impl-2.9.1.jar:/usr/share/logstash/logstash-core/lib/jars/logstash-core.jar:/usr/share/logstash/logstash-core/lib/jars/slf4j-api-1.7.25.jar org.logstash.Logstash
logstash     56  0.0  0.0  50888  3780 pts/0    Rs+  10:57   0:00 ps auxww`

Btw to the docker-composer I also added a java application, but I don't think it's the root of the problem because every other component is working fine only logstash is crashing.

**Comment by Sneijky** [comment]
total        used        free      shared  buff/cache   available
Mem:           4930        1537        1346           1        2046        3069
Swap:          2047           1        2046

Pretty of memory available.

**Comment by antoineco** [comment]
And `docker-compose exec <your-component> free -m` **after** Logstash crashes?

**Comment by Sneijky** [comment]
total        used        free      shared  buff/cache   available
Mem:           4930         722        2306           1        1901        3964
Swap:          2047           3        2044

Also tried to change logstash to:

    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"

Crashed again

**Comment by antoineco** [comment]
`2g` is worse than `1g`, you're already exhausting your system's memory with 1GB.

This issue does not make any sense to me, I'm afraid I can't help you with it.
Make sure you did not set resource limits (using Docker) on the Logstash container. If not, you're good for an in-depth inspection of your Docker host.

**Comment by Sneijky** [comment]
I made some changes to my conf files, looks like a miss configuration on the extraction file was causing logstash to crash. Nevertheless the error message was odd. Thanks for your help.
