### ISSUE TITLE
Set up filebeats

### ISSUE THREAD

**Issue by Phu-Bar** [deviantony/docker-elk#300]
Hi,

I'm just struggling to get filebeat to push logs to logstash.

Can you include on how to set up filebeat in the read me please.

Thanks,

**Comment by antoineco** [comment]
I'm kindly redirecting you to https://discuss.elastic.co as stated in the issue template, and also to [Filebeat Reference [6.3] » Getting Started With Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html).
