### ISSUE TITLE
Docker Compose - ElasticSearch / Logstash Communication issue

### ISSUE THREAD

**Issue by tvollscw** [deviantony/docker-elk#304]
Trying to use `docker-compose up` in order to create the docker containers. 
I have used the master branch before, and it works beautifully, but trying the searchguard branch out, I have an error where logstash will repeatedly output:

```
logstash_1       | [2018-08-10T20:00:31,869][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:xxxxxx@elasticsearch:9200/, :path=>"/"}
logstash_1       | [2018-08-10T20:00:31,873][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://logstash:xxxxxx@elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://logstash:xxxxxx@elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch"}
```

Any known reason on why this might be happening?
No other docker containers are running.

**Comment by antoineco** [comment]
Did you run sg_admin as suggested in the README?

**Comment by tvollscw** [comment]
Yes, but that doesn't seem to work either; it just gives me this error:

> 
> root@ubuntu:~/docker-elk# docker-compose exec -T elasticsearch bin/init_sg.sh
> OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bin/init_sg.sh\": stat bin/init_sg.sh: no such file or directory": unknown

It doesn't even get to a point where all of the containers can successfully run.. Only dockerelk_logstash_1 will be running when doing a  `docker ps`, and if I try to start up dockerelk_elasticsearch_1, it will just stop itself right away..

**Comment by antoineco** [comment]
Seems like you forgot to run `docker-compose build` after switching branches.

**Comment by tvollscw** [comment]
**_D'oh!_** Didn't see that note in there. That is absolutely correct. That was my issue. Thanks for your quick response!
