### ISSUE TITLE
Kibana Dockerfile - failing @installing sense

### ISSUE THREAD

**Issue by trajakovic** [deviantony/docker-elk#31]
At image **build** time, line `RUN kibana plugin --install elastic/sense` is waiting endlessly for running elasticsearch instance...

Reading documentation, this is probably "new" thing: https://www.elastic.co/guide/en/sense/current/installing.html#installing

```
{"name":"Kibana","hostname":"fcdb0b513411","pid":6,"level":50,"err":"Request error, retrying -- connect ECONNREFUSED","msg":"","time":"2015-12-18T09:13:11.860Z","v":0}
{"name":"Kibana","hostname":"fcdb0b513411","pid":6,"level":40,"msg":"Unable to revive connection: http://localhost:9200/","time":"2015-12-18T09:13:11.863Z","v":0}
```

**Comment by deviantony** [comment]
Did you update the kibana configuration?

From the following logs, it seems that you've updated the `elasticsearch_url` option:

```json
{"name":"Kibana","hostname":"fcdb0b513411","pid":6,"level":40,"msg":"Unable to revive connection: http://localhost:9200/","time":"2015-12-18T09:13:11.863Z","v":0}
```

You've got to keep the value of this option to *http://elasticsearch:9200*, elasticsearch is the name of the container and the kibana container will be able to communicate with it by using this specific hostname (thanks to docker-compose).

I've just rebuilt the stack without any problem.

**Comment by deviantony** [comment]
@trajakovic any update on this issue?

**Comment by deviantony** [comment]
Closing this issue, do not hesitate to reopen if you're still having problems.
