### ISSUE TITLE
Logspout / Filebeat

### ISSUE THREAD

**Issue by gallofeliz** [deviantony/docker-elk#313]
### Answer description

Logspout looks great, but send all docker containers logs (surely configurable to only ones), need that applications uses Docker, and seems that if it is off, then on, it doesn't send logs off the period "off".

I have tried Filebeat and it can send logs for a non-docker application, and read the log file from the start. Do you think that it has its place in extensions directory ?

Regards,

**Comment by antoineco** [comment]
Logspout also sends logs from the creation of the containers, even when it starts "late". However every addition is welcome.

To my knowledge, Filebeat operates in the area of the application and not of the ELK stack. I.e. you configure it to send logs from specific files for specific apps. How would you move it *inside*  the ELK stack and make it generic enough to ship logs for any app?

**Comment by gallofeliz** [comment]
I have successfully created an extension (with a fork) that make that. You need into its docker-compose to put the good mounts, and you need to change the filebeat.yaml if you want to parse logs as json, etc.

About Logspout, I didn't think like included in log stack. My vision was a machine with ELK stack and machines with applications + logspout that send logs to ELK. Same with Filebeat, but filebeat seems more flexible (you can monitor logs files).

It should be better to put Filebeat out of the this ELK stack :)

Regards,

**Comment by antoineco** [comment]
Indeed, that doesn't sound appropriate for an extension. However it might be helpful to others to document your procedure inside a GitHub wiki page.

What do you think?

**Comment by gallofeliz** [comment]
I can be a good idea. I need to play more with my stack (I need so time for that), and see to document Filebeat if I feel that makes sense.

Regards,
