### ISSUE TITLE
Kibana is not accesible outside the container

### ISSUE THREAD

**Issue by tikoflano** [deviantony/docker-elk#316]
### Problem description

Kibana is not accesible outside the container. I know this has been asked a lot of times, but still got no solution working. 

### Extra information

The command `nmap -sT -O -p5601 127.0.0.1` shows: 

```
PORT     STATE  SERVICE
5601/tcp open   unknown
```
Why is the service unknown?

#### Stack configuration

Using ELK_VERSION=6.2.2 with SearchGuard

#### Docker setup

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

#### Docker logs

Not relevant here.

**Comment by antoineco** [comment]
Did you initialize Search Guard? Kibana won't start before that.

**Comment by tikoflano** [comment]
@antoineco, Search Guard is running, I executed `docker-compose exec -T elasticsearch bin/init_sg.sh`.

My configuration is the one provided in this repo, unmodifed. 

The response from `curl -XGET localhost:5601 -vvv` when executed in the host is:

 ```
About to connect() to localhost port 5601 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5601 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5601
> Accept: */*
>
* Recv failure: Conexión reinicializada por la máquina remota
* Closing connection 0
curl: (56) Recv failure: Conexión reinicializada por la máquina remota

```

Inside the kibana container the output is this:

```
* About to connect() to localhost port 5601 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5601 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:5601
> Accept: */*
>
< HTTP/1.1 302 Found
< location: /login?nextUrl=%2F
< kbn-name: kibana
< kbn-version: 6.2.2
< cache-control: no-cache
< content-length: 0
< Date: Wed, 12 Sep 2018 12:54:02 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact

```

Maybe is worth noting that I get the same error when trying to connect to Elastic Search at port 9200.

**Comment by tikoflano** [comment]
When I curl form within teh container, the logs show this:

`{"type":"response","@timestamp":"2018-09-12T12:54:02Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":7,"contentLength":9},"message":"GET / 302 7ms - 9.0B"}`

Is it okay if this is showing `"host":"localhost:5601"`? Isn´t it supposed to show `"host":"0.0.0.0:5601"`?

**Comment by tikoflano** [comment]
Ok. It seems to be a firewall issue in my host. I disabled CSF & LFD and now it is working.

I'm sory for wasting your time.

**Comment by antoineco** [comment]
No worries, there is no bad question, glad it works!
