### ISSUE TITLE
OSS Docker images don't exist for 5.x

### ISSUE THREAD

**Issue by mchelen** [deviantony/docker-elk#318]
The `-oss` suffix used in https://github.com/deviantony/docker-elk/blob/master/elasticsearch/Dockerfile#L4 will fail for any `ELK_VERSION` less than 6 (such as 5.6.11) because there is no OSS version of those images published at https://www.docker.elastic.co

**Comment by antoineco** [comment]
It's true, but how do you suggest to fix this?

**Comment by mchelen** [comment]
@antoineco How about something like: https://github.com/deviantony/docker-elk/compare/master...mchelen:patch-1
I can update the places where the env vars are usef if this looks like a good approach.

**Comment by antoineco** [comment]
That could work, but I have a feeling using the x-pack branch would be much simpler, because all images included x-pack before v6.
