### ISSUE TITLE
logstash protocol error

### ISSUE THREAD

**Issue by rohitshrivastava04** [deviantony/docker-elk#32]
I am using Windows 7 with boot2docker. while using docker-compose up I am facing this error

    Creating dockerelkmaster_logstash_1 [31mERROR←[0m: Cannot start container c25a5accedb6b554f40c7c7177ff933b703e26e454d8f1348b92fcc58278516f: stat /c/Users/****/My Documents/docker-elk-master/docker-elk-master/logstash/config: protocol error

However elastcisearch is created successfully.

Could you please suggest me whats wrong here?

**Comment by deviantony** [comment]
Well I did not found any hints about your issue on the web, but the fact that it says that it cannot start a container may point a problem with your setup (boot2docker / docker-compose).

Sorry, can't really help you on this one !

**Comment by deviantony** [comment]
@rohitshrivastava04 any update on this issue?

**Comment by rohitshrivastava04** [comment]
Nope, i dropped it and used some other image. Thanks!
