### ISSUE TITLE
Troubles while run search guard branch

### ISSUE THREAD

**Issue by metju312** [deviantony/docker-elk#320]
A few minutes ago I clone `search guard branch` and I does everythink what `README` said.

After `docker-compose up -d` all services are working but `elasticsearch_1` log one error every few secounds:

> elasticsearch_1  | [2018-09-14T08:59:49,614][ERROR][c.f.s.a.BackendRegistry  ] Not yet initialized (you may need to run sgadmin)

After that I run `docker-compose exec -T elasticsearch bin/init_sg.sh`, output:

> Search Guard Admin v6
Will connect to localhost:9300 ... done
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/usr/share/elasticsearch/plugins/search-guard-6/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Elasticsearch Version: 6.3.2
Search Guard Version: 6.3.2-23.0
Connected as CN=kirk,OU=client,O=client,L=Test,C=DE
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
ERR: Timed out while waiting for a green or yellow cluster state.
o. Try running sgadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
o. Make also sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in elasticsearch.yml
o. If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)
o. Add --accept-red-cluster to allow sgadmin to operate on a red cluster.

I guess that sgadmin can't connect to elasticsearch cluster but I does everythink what README said.

Any sugestions how to fix this?
Thanks for answers.

**Comment by antoineco** [comment]
The connection looks fine to me

> `Will connect to localhost:9300 ... done`
...
`Connected as CN=kirk,OU=client,O=client,L=Test,C=DE`
`Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...`

Here is what a successful execution of `init_sg.sh` looks like: https://travis-ci.org/deviantony/docker-elk/builds/415931495#L646-L675

Unfortunately you did not fill-in the issue template, so we have no possibility to reproduce your issue. Please reopen when you can provide the required information. Thank you for your understanding.

**Comment by metju312** [comment]
I already resolve this. Your product, works complitely fine. I had error with index win Kibana which make `elasticsearch cluster` RED status - never YELLOW.

If you want connect your `sgadmin` with `elasticsearch cluster` without waiting for YELLOW status use line: **`--accept-red-cluster`** in `init_sg.sh` script: 

> #!/bin/sh
plugins/search-guard-6/tools/sgadmin.sh \
	-cd config/sg/ \
	-ts config/sg/truststore.jks \
	-ks config/sg/kirk-keystore.jks \
	-nhnv \
	-icl \
	--accept-red-cluster

Then everything works fine and Kibana will show you why you have RED status - in my case kibana index problem.

@antoineco Thanks for your answer and for help.

PS. @antoineco in my opinion you can add `--accept-red-cluster` to `init_sg.sh` file.
