### ISSUE TITLE
Any tips on how to git clone the branch with search guard support?

### ISSUE THREAD

**Issue by ovizii** [deviantony/docker-elk#329]
I was looking at this tutorial https://logz.io/blog/elk-stack-on-docker/ on how to install the elk stack but I'd like to try the branch with search guard support. Any tips on what needs changing from the default command of git clone https://github.com/deviantony/docker-elk.git ?

**Comment by antoineco** [comment]
`git checkout searchguard`

**Comment by ovizii** [comment]
Thanks
