### ISSUE TITLE
Adding logstash references/different use cases

### ISSUE THREAD

**Issue by navdeep-G** [deviantony/docker-elk#33]
Hey,

I was thinking it would be worth while to add a reference folder for logstash in docker-elk, which can display how one can connect to different data sources. This can act as different use cases for docker-elk and logstash.

For example, imagine if someone was using docker-elk and they wanted to connect to a database. It would be really nice if there was a folder to the effect of "logstash-references" in which they can open up and get direction on how to connect to a database using logstash, which would essentially make their workflow very efficient, imho.

I am still thinking this through, but thats the initial thought I had. 

Any other thoughts on this?

**Comment by deviantony** [comment]
The question had already been raised when @rgroten opened the PR #13.

My initial thoughts on this project were the following:

* Easy to use, basically clone and run
* Mininum changes to official images in order to work

I feel that adding a folder containing logstash-references could bloat the project. Maybe a wiki or external reference...

The project is open, let's debate about this, what do you guys think about it?

**Comment by rgroten** [comment]
@navdeep-G Are you thinking these references are in the form of sample config file(s)?  Or more instructional?  I think samples would fit in the project ok, instructions would be better for a wiki like @deviantony said.

**Comment by navdeep-G** [comment]
@rgroten I was thinking sample config file(s) for now.

**Comment by luke-vidler** [comment]
+1 for examples

**Comment by nilsnh** [comment]
I really like the simplicity of this docker compose setup and how readable the readme.md is, which was the reason I chose to use this docker image.

I'm working on doing a basic ssl setup with self-signed certificates in a fork: https://github.com/nilsnh/docker-elk-ssl Would happily contribute a short guide back to this project either in the readme or in a wiki page.

**Comment by vladoatanasov** [comment]
Hi, I have added support for rabbitMQ here https://github.com/vladoatanasov/docker-elk

Maybe we can set up a list of the forks that extend functionality?

**Comment by antoineco** [comment]
If people feel that they need examples I suggest we create wiki pages for more advanced setups like this one, instead of creating more branches and making this project complex to maintain.

**Comment by antoineco** [comment]
I started populating the wiki with some information: https://github.com/deviantony/docker-elk/wiki/External-applications

@navdeep-G (and everybody else who still follows that issue) if you have a scenario in mind that could be a candidate for a wiki page feel free to talk about it here.

**Comment by dschaper** [comment]
Do you think something like this https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-sample-dashboards.html would be a candidate? I'm using the x-elk branch and being able to load the sample dashboards would be helpful. I'm starting from scratch with ELK and am pretty green with things, can do some docker and compose but not nearly as proficient as I'd like to be. (And would like to contribute back someday to this repo.)

**Comment by antoineco** [comment]
It seems like Elastic also distributes images for their Beats products: https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html 💪 

I successfully imported the dashboards like this:
```
docker run --rm --network dockerelk_elk docker.elastic.co/beats/metricbeat:5.4.0 \
  ./scripts/import_dashboards \
  -es http://elasticsearch:9200 \
  -user elastic \
  -pass changeme
````

Could you try it and confirm it works for you as well? If yes I can certainly add it to the wiki.

**Comment by dschaper** [comment]
Yeah, that seems to work just perfectly! Thanks!

**Comment by isspek** [comment]
I have Twitter template in json format, and is stored in my host. I couldn't figure out how I can map it to logistash container. Using following entries, I got this error: `[2019-05-09T14:15:38,783][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, input, filter, output at line 33, column 1`

entry in docker-compose.yml:
```
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
```

entry in logstash.conf: 
```
output {
        elasticsearch {
                hosts => "localhost:9200"
                index => "twitter_index"
                template => "/usr/share/logstash/pipeline/twitter_template/twitter_template.json" 
                template_name => "twitter"
                template_overview => true
        }
}
      
```
Is anyone can give an example of using twitter template?

**Comment by Narendranath2** [comment]
It was really nice, it was up and running in a couple of seconds
But I'm facing issues in adding filebeat to it. can you please tell me how to add filebeat in this ?

**Comment by antoineco** [comment]
@Narendranath2 let's take this conversation to Gitter (first badge at the top of the README) since it's vastly unrelated to the topic of this issue.
Thanks

**Comment by antoineco** [comment]
This discussion has been inactive for quite a while, and the latest comments have been mostly unrelated to the original topic. I'm not sure whether docker-elk should be the place for documenting all possible ways to use Logstash, but if there is something we can help with, we will.
