### ISSUE TITLE
Update to 6.5.1

### ISSUE THREAD

**Issue by mw-jko** [deviantony/docker-elk#335]
* [Elasticsearch 6.5.1 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/release-notes-6.5.1.html)
* [Logstash 6.5.1 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-6-5-1.html) - Note: no changes, but there are some in 6.5.0
* [Kibana 6.5.1 Release Notes](https://www.elastic.co/guide/en/kibana/current/release-notes-6.5.1.html)

Looks like Searchguard is already up-to-date: https://github.com/floragunncom/search-guard/releases/tag/v6.5.1-23.2

**Comment by antoineco** [comment]
Done, thanks for the changelog 🙌

**Comment by mw-jko** [comment]
When will we get an update for the `searchguard`-Branch as well? Or did you change the handling and you can just merge `master` into `searchguard`?

**Comment by antoineco** [comment]
@mw-jko good that you remind me. I just cherry-picked the changes onto the `searchguard` branch.

**Comment by mw-jko** [comment]
@antoineco thank you for the quick port :)
