### ISSUE TITLE
Update to 6.5.2

### ISSUE THREAD

**Issue by mrnonz** [deviantony/docker-elk#338]
* [Elasticsearch 6.5.2 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/release-notes-6.5.2.html)
* [Logstash 6.5.2 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-6-5-2.html)
* [Kibana 6.5.2 Release Notes](https://www.elastic.co/guide/en/kibana/current/release-notes-6.5.2.html)

**Comment by antoineco** [comment]
@mw-jko done, sorry for the delay.
