### ISSUE TITLE
Docker Log Drivers and ELK Stack

### ISSUE THREAD

**Issue by ryanjbaxter** [deviantony/docker-elk#34]
Docker supports various types of [log drivers](https://docs.docker.com/engine/reference/logging/overview/) as a way of gathering logs from your Docker containers.  One common scenario for docker-elk might be to extend the docker-compose file to add an app to and have the log drivers build into Docker pipe the logs to the ELK stack.  For example you can easily configure logstash with a syslog endpoint and then use the Docker syslog driver to pipe logs to logstash.

The problem appears to be that Docker tries to make a connection to the syslog endpoint before starting the containers for the ELK stack so the whole `docker-compose up` command fails.  I am wondering if there is any way around this or other alternatives to solving this problem.

**Comment by deviantony** [comment]
Sorry, not so much time actually to work on this project, I'll try to think about an evolution for this.

**Comment by MBuffenoir** [comment]
If I understood correctly, this can be achieved with an environment variable in the compose file. Set up the varibale with something like : 

`export $IP_LOGSTASH=$(docker-machine ip <elk machine name>)`

**Comment by HackerWilson** [comment]
I have written the [docker-elk-deployment](https://github.com/HackerWilson/docker-elk-deployment) project to supports the Elastic Stack 5.2.0+ on swarm mode cluster, and use gelf logging driver to gathering logs from docker containers, anyone who meet the requirement can go to have a try.

**Comment by antoineco** [comment]
@ryanjbaxter as you said the target (syslog in your case) must be up before the other containers can even start. It's a pretty bad design but for prototyping with Compose it should be enough to make your `syslog` service a dependency of all its consumers with `depends_on:`.
