### ISSUE TITLE
Deploying on docker swarm fails to form a cluster when scaling beyond one elasticsearch instance

### ISSUE THREAD

**Issue by aldencolerain** [deviantony/docker-elk#342]
Deploying on docker swarm fails to form a cluster when scaling beyond one elasticsearch instance. Using docker swarm dnsrr may not be necessary.

See: #229 and https://github.com/elastic/elasticsearch-docker/issues/91#issuecomment-319698631
 
I *think* mine is running with these changes:
network.host: 0.0.0.0
network.publish_host: _eth0_

**Comment by antoineco** [comment]
Even if you configure `zen` to use the DNS name `tasks.elasticsearch` instead of `elasticsearch`?

**Comment by antoineco** [comment]
@aldencolerain is this issue still valid?

**Comment by kakoni** [comment]
For anyone running into similar problems in 2020, please check that you are not using healthcheck in your docker-compose file. DNS resolution + healthcheck really don't play that well together (Node has to be healthy before dns resolution inside docker swarm works)
