### ISSUE TITLE
 pipelines

### ISSUE THREAD

**Issue by CCH0124** [deviantony/docker-elk#343]
### Problem description

Use pipelines to achieve multi-pipeline transmission. Otherwise, using multiple beats or file to read data will cause the data of beat and file to be mixed at the same time. It is not good to make a classification.

#### Docker setup

```
/logstash/config$ vi logstash.yml
# path.config: /usr/share/logstash/pipeline # annotation
```
Establish a separate pipeline
```
/logstash/config$ vi pipelines.yml
- pipeline.id: csv
  queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/readCSV.conf" 

```

**Comment by antoineco** [comment]
I'm not sure if I understood the problem. The official documentation page for multi-pipeline is here:
https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

Did you check it out already? Is there any problem specific to docker-elk?

**Comment by CCH0124** [comment]
Maybe I want to collect service logs and packets separately for analysis, but the default pipeline causes two data to be output to the same index, which leads to poor analysis. In addition to using labels to distinguish, can you use the multiple-pipelines method.
I don't know if this question is correct, thank you!

**Comment by antoineco** [comment]
Sure, it's possible.

1. First of all you have to *remove the default pipeline description* inside the `logstash/pipeline` directory. Deleting the file ensures the default pipeline is disabled.

2. Create a pipeline config file under `logstash/config/pipelines.yml`. See the documentation below for examples.

3. Make sure you're mounting `pipelines.yml` as well as all pipeline config files at the right locations in your docker-compose.yml file.

Interesting references:
* https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html 
* https://www.elastic.co/guide/en/logstash/current/dir-layout.html#docker-layout

**Comment by antoineco** [comment]
@CCH0124 did I answer the question? Are you still facing issues related to the original problem?

**Comment by CCH0124** [comment]
Thank you for your information.
I already know everything.
