### ISSUE TITLE
kibana and logstash cannot connect to Elasticsearch on Mac 

### ISSUE THREAD

**Issue by Tonkong** [deviantony/docker-elk#346]
kibana_1         | {"type":"log","@timestamp":"2018-12-23T11:57:21Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}

logstash_1       | [2018-12-23T11:57:20,501][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch"}

**Comment by seanfcarroll** [comment]
I am having the same problem ... what is the solution? @Tonkong

**Comment by arcadas** [comment]
In my case, I created a new logstash/pipeline config file, but I missed the username and password:
```js
output {
  elasticsearch {
      hosts => "elasticsearch:9200"
      user => "elastic"
      password => "changeme"
      ...
  }
}
```
