### ISSUE TITLE
Consider add HealtCheck on Elasticsearch

### ISSUE THREAD

**Issue by leto1210** [deviantony/docker-elk#359]
Add HealthCheck for introducing a wait dependancy for Kibana

services:
  elasticsearch:
........
healthcheck:
      test: ["CMD-SHELL", "docker-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 6

 kibana:
............
depends_on:
      elasticsearch :
        condition: service_healthy

**Comment by leto1210** [comment]
Docker healtcheck example for Elasticsearch

#!/bin/bash
set -eo pipefail

host="$(hostname --ip-address || echo '127.0.0.1')"

if health="$(curl -fsSL "http://$host:9200/_cat/health?h=status")"; then
	health="$(echo "$health" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" # trim whitespace (otherwise we'll have "green ")
	if [ "$health" = 'green' ]; then
		exit 0
	fi
	echo >&2 "unexpected health status: $health"
fi

exit 1

**Comment by antoineco** [comment]
Is that necessary? Kibana will wait and retry connection until Elasticsearch comes up.

**Comment by leto1210** [comment]
Hello,

You right, the finality is to ensure that beat services don't crash when they connect to the stack. Until Kibana is down, metricbeat or filebeat container will crashed.

**Comment by antoineco** [comment]
Thanks for the clarification. Metricbeat only requires Elasticsearch to function, not Kibana. Kibana is just an optional frontend, it doesn't persist any data.

What you want to do, I think, is create a dependency (`depends_on`) for Metricbeat on the `elasticsearch` service. The health script you suggested is a valid way to do this indeed

**Comment by antoineco** [comment]
@leto1210 did the suggested approach work for you?

**Comment by leto1210** [comment]
Hello,

Works fine.

Thanks
