### ISSUE TITLE
Question regards license upgrade.

### ISSUE THREAD

**Issue by rong0312** [deviantony/docker-elk#361]
Hey,
First of all, I would like to thank you guys for an amazing project.
I have deployed this solution via docker swarm in our development environment and it seems very promising! 
This leads me to the next step which is a license upgrade in order to use some alerts. 
Before I do so, Iv been thinking what will happen if my Kibana container will shut down and will be relaunched in another host? what will happen with my upgraded settings? 
In case someone here got any experience regards this issue/cluster DR I will be glad to hear some insights.

Thank you!

**Comment by antoineco** [comment]
Hi @rong0312, as this question is purely about Docker products I kindly redirect you to https://forums.docker.com/ as stated in the issue template.

The short answer is: settings are persisted and it doesn't matter where Kibana starts. Just make sure your DNS is configured properly, if you use a customized DNS name.
