### ISSUE TITLE
Need help for a Kibana Curator-Plugin "Cleaner"

### ISSUE THREAD

**Issue by CodeFreezr** [deviantony/docker-elk#364]
Hello together,

we have tried you`re ELK-Stack compilation compose with build-in SearchGuard. Very, very convenient! Thanks for that work. Formerly we use a single container solution without any security.

As a simple Index-"Curator" Solution we use "Cleaner" (see https://github.com/TrumanDu/cleaner). Now we have the problem, that this plugin did not work with this docker stack (ELK v. 6.4.1). Installation of the plugin works, but if we want click on the cleaner-button, nothing happend. After looking inside the Chrome-Debugger we see only an "unauthorzied" Respond in every request. Checking again the old installation without SearchGuard (also 6.4.1) everything works fine.

Perhaps it's only a simple configuration issue. But we can't figure out where what to configure.

**Comment by CodeFreezr** [comment]
Here are the crossposting in the "cleaner" github: https://github.com/TrumanDu/cleaner/issues/1

**Comment by CodeFreezr** [comment]
Here are the Get-Request which creates the "403" Response: 
https://[kibana-url]/api/cleaner/list

**Comment by antoineco** [comment]
This project doesn't seem to support authentication, or be actively maintained. Not much we can do about it here unfortunately :(

**Comment by antoineco** [comment]
Closing as per this answer: https://github.com/floragunncom/search-guard/issues/643#issuecomment-471368566
