### ISSUE TITLE
Shield / auth for Kibana?

### ISSUE THREAD

**Issue by ror6ax** [deviantony/docker-elk#37]
Hi! Thanks for this terrific work, I've tried nearly all docker elk images and find yours the best-crafted!

I'm wondering if auth for Kibana is already implemented or can be done?

Thanks

**Comment by deviantony** [comment]
Yeah shield support is available in a separate branch: https://github.com/deviantony/docker-elk/tree/shield-support

**Comment by ror6ax** [comment]
You are the man! Cool! Thanks a lot!
