### ISSUE TITLE
Support for Search Guard and X-Pack

### ISSUE THREAD

**Issue by santuari** [deviantony/docker-elk#379]
### Problem description
I would like to be able to run Search Guard together with X-Pack.

I created [this branch](https://github.com/WuerthPhoenix/docker-elk/tree/searchguard-xpack) which runs both Search Guard and X-Pack, but I cannot create a pull request to a no-existing branch. 

If that's ok for you, you could create a new branch starting from `searchguard` one so that I will be able to create the pull request. I will also update the documentation on the master to explain what this branch contains.

#### Stack configuration

ELK + Search Guard + X-Pack with monitoring enabled

**Comment by antoineco** [comment]
@santuari we won't be adding a new branch to the project, however X-Pack can be enabled together with Search Guard by simply switching [this value](https://github.com/deviantony/docker-elk/blob/searchguard/.env#L2-4) and applying your own configuration changes to the Elastic components.

We will probably enable X-Pack by default in the close future.

**Comment by santuari** [comment]
@antoineco I know, it is exactly what I did, but special configurations are needed.
I will submit the pull request to the `searchguard` branch so that you can see if it works for you to enable X-Pack by default.

Best regards.
