### ISSUE TITLE
logstash: could not write:write udp .... write: connection refused

### ISSUE THREAD

**Issue by jailbreakerSN** [deviantony/docker-elk#389]
### Problem description

Have a issue about collecting and sending container's logs to Logstash using Logspout extensions.
I have tried UDP and TCP protocol but always have the same issue, Logspout is not able to write udp on Logstash port (5000 for me).

#### Docker setup

```
<!-- $ docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false -->
```

```
<!-- $ docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017-->

```

#### Docker logs

```
<!-- $ docker logs 17412416bfac
# logspout v3.2.6-custom by gliderlabs
# adapters: udp tcp logstash raw
# options : persist:/mnt/routes
!! lookup logstash on 127.0.0.11:53: no such host
# logspout v3.2.6-custom by gliderlabs
# adapters: udp tcp logstash raw
# options : persist:/mnt/routes
!! lookup logstash on 127.0.0.11:53: no such host
# logspout v3.2.6-custom by gliderlabs
# adapters: logstash raw udp tcp
# options : persist:/mnt/routes
# jobs    : http[]:80 pump routes
# routes  :
#   ADAPTER     ADDRESS         CONTAINERS      SOURCES OPTIONS
#   logstash+udplogstash:5000                           map[]
2019/04/26 23:36:19 logstash: could not write:write udp 172.25.0.5:43952->172.25.0.2:5000: write: connection refused
# logspout v3.2.6-custom by gliderlabs
# adapters: logstash raw udp tcp
# options : persist:/mnt/routes
# jobs    : http[]:80 pump routes
# routes  :
#   ADAPTER     ADDRESS         CONTAINERS      SOURCES OPTIONS
#   logstash+udplogstash:5000                           map[]
2019/04/26 23:36:21 logstash: could not write:write udp 172.25.0.5:51246->172.25.0.2:5000: write: connection refused
# logspout v3.2.6-custom by gliderlabs
# adapters: logstash raw udp tcp
# options : persist:/mnt/routes
# jobs    : http[]:80 pump routes
# routes  :
#   ADAPTER     ADDRESS         CONTAINERS      SOURCES OPTIONS
#   logstash+udplogstash:5000                           map[]
2019/04/26 23:36:24 logstash: could not write:write udp 172.25.0.5:39461->172.25.0.2:5000: write: connection refused
# logspout v3.2.6-custom by gliderlabs
# adapters: logstash raw udp tcp
# options : persist:/mnt/routes
# jobs    : http[]:80 pump routes
# routes  :
 -->

```

**Comment by antoineco** [comment]
@jailbreakerSN did you enable the UDP input in your Logstash pipeline as mentioned here?
https://github.com/deviantony/docker-elk/blob/master/extensions/logspout/README.md

**Comment by jailbreakerSN** [comment]
@antoineco or course, I did it but always got the same result. I followed instructions step by step.
Can time synchronisation between the host machine and docker containers be the problem's source?? I mean if the local machine's date and time is not well configured, may it cause a issue??

**Comment by antoineco** [comment]
I don't think so, it really seems to be a problem with the connector according to the error logs you posted:
`write udp 172.25.0.5:39461->172.25.0.2:5000: write: connection refused`

Let me try to reproduce locally.

**Comment by jailbreakerSN** [comment]
the matter is that I can now visualize logs from containers incoming in the kibana discover page, but at a different timestamp which refers to my local machine date and time. For instance, as my local machine date is 2019-04-27 hh:mm:ss, when I refresh the discover page, I can see logs date changing.
And as i m not the server administrator, i don't have the ability to change date and time.

**Comment by antoineco** [comment]
That's one thing you may want to fix but it's not related to the Logspout issue.

**Comment by jailbreakerSN** [comment]
Ok I will try it. But as I said you, logspout data are coming now through my Kibana Discover page when fixe the time range to last 7 days.
For the issue, may be it's related to start delay between Logspout and Logstash container, as Logstash need a certain time to be ready and listen on UDP port!

**Comment by antoineco** [comment]
Ah yes, there is a small delay where you will see those errors because Logspout starts faster than Logstash. You can safely ignore those errors, as long as Logspout does not crash.

**Comment by jailbreakerSN** [comment]
Thank a lot @antoineco ! I can close this issue so!
