### ISSUE TITLE
Csv filter plugin

### ISSUE THREAD

**Issue by Fitz22** [deviantony/docker-elk#391]
Hello, I do not understand how to add the plugin "Csv filter plugin" in logstash.

I add the line "RUN logstash-plugin install logstash-filter-csv"
in the Dockerfile of Logstash but nothing conclusive. 

Someone to help me. 

Thank you.

**Comment by antoineco** [comment]
@Fitz22 there is nothing to install, [Csv filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-csv.html) is a built-in Logstash plugin.

You can confirm this by listing the installed plugins using the following command:
```
docker-compose exec logstash bin/logstash-plugin list
```

**Comment by Fitz22** [comment]
Thank you for your reply. My problem does not come from there. Best regards
