### ISSUE TITLE
how to persist elasticsearch-setup-passwords? after each docker-compose restart it's back to default 'changeme'

### ISSUE THREAD

**Issue by alonsnir** [deviantony/docker-elk#397]
### Problem description
Is there a way to keep passwords generated by elasticsearch-setup-passwords between
docker-compose restarts?
Also: 
Readme says 'replace the elastic username with kibana and logstash_system inside the Kibana and Logstash pipeline configuration files respectively', but i only find log stash/pipeline/configuration not kibana. 

#### Stack configuration

no changes has made

#### Docker setup

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

```
docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

#### Docker logs

```

```

**Comment by antoineco** [comment]
Very good point, I ignored the bootstrap password was overwriting the generated password upon every restart. Thanks for pointing that out.

For the time being I'd simply recommend deleting [this line](https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml#L17) from the Compose file. I'll try to think about a better solution, or document this better if I can't find any.

> I only find log stash/pipeline/configuration not kibana.

The location of the Kibana config file is documented in the README (`kibana/config/kibana.yml`).

**Comment by antoineco** [comment]
@alonsnir I just created a new stack, initialized all passwords with `'bin/elasticsearch-setup-passwords auto --batch`, replaced the values in all 3 conf files and restarted the stack with `docker-compose restart`.

Logstash is up:
```console
$ docker-compose logs logstash
...
logstash_1       | [2019-05-27T17:08:12,859][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elastic:xxxxxx@elasticsearch:9200/]}}
logstash_1       | [2019-05-27T17:08:12,896][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://elastic:xxxxxx@elasticsearch:9200/"}
```

Kibana is up:
```console
$ docker-compose logs kibana
...
kibana_1         | {"type":"log","@timestamp":"2019-05-27T17:07:32Z","tags":["license","info","xpack"],"pid":1,"message":"Imported license information from Elasticsearch for the [monitoring] cluster: mode: trial | status: active | expiry date: 2019-06-26T17:00:47+00:00"}
```

Are you *deleting* the ES container when you restart your stack? If yes, do you persist your data?

The keystore containing the bootstrap password is located at `/usr/share/elasticsearch/config/elasticsearch.keystore`, but this file doesn't need to be backed up as long as your ES data is persisted.

**Comment by alonsnir** [comment]
@antoineco you have just resolved my issue. I was not paying attention to all the places where passwords need to be replaced. It's all works as expected and restarts do not override generated passwords. Thank you
