### ISSUE TITLE
How add new node in docker-compose.yml?

### ISSUE THREAD

**Issue by nipua** [deviantony/docker-elk#399]
Hi, you can show how add node in docker-compose.yml

**Comment by antoineco** [comment]
Please use the `replicas` parameter as described here: https://docs.docker.com/compose/compose-file/#replicas

**Comment by nipua** [comment]
> Please use the `replicas` parameter as described here: https://docs.docker.com/compose/compose-file/#replicas

Maybe you have example how add two o more nodes for this repo?

**Comment by antoineco** [comment]
Sure, it is described in the README already, right here: https://github.com/deviantony/docker-elk/blob/master/README.md

**Comment by nipua** [comment]
Thanks man!

**Comment by antoineco** [comment]
Please note that the number of replicas can only be configured on the command line in Compose mode: https://docs.docker.com/compose/reference/scale/

The `replicas` option I mentioned above works only in Swarm mode.
