### ISSUE TITLE
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];

### ISSUE THREAD

**Issue by zhongxian93** [deviantony/docker-elk#400]
### Problem description
Failed to bind to storage after trying to add in /path/to/storage

### Extra information

version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /f/datadrive/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
      - "12200:12200/udp"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge

#### Stack configuration

added      ` - /f/datadrive/elasticsearch:/usr/share/elasticsearch/data`

i had ensure that both folders `datadrive` & `elasticsearch` has full acccess

could someone advise what i have done wrong?

**Comment by antoineco** [comment]
Docker Toolbox is probably not mapping your local F: drive inside the Docker VM. It might be something you can configure inside VirtualBox, but have you considered updating to Docker for Windows? https://github.com/deviantony/docker-elk/blob/master/README.md#windows

**Comment by zhongxian93** [comment]
> Docker Toolbox is probably not mapping your local F: drive inside the Docker VM. It might be something you can configure inside VirtualBox, but have you considered updating to Docker for Windows? https://github.com/deviantony/docker-elk/blob/master/README.md#windows

i have attempted to add Shared folder before this 
![image](https://user-images.githubusercontent.com/31924391/59657613-d8076100-91d3-11e9-9c43-151fd35969bb.png)

and if i am not wrong i need window 10 pro to install docker for windows

**Comment by zhongxian93** [comment]
> Docker Toolbox is probably not mapping your local F: drive inside the Docker VM. It might be something you can configure inside VirtualBox, but have you considered updating to Docker for Windows? https://github.com/deviantony/docker-elk/blob/master/README.md#windows
> 
> ![volumes](https://camo.githubusercontent.com/4f8a242db710fe672d8cf19706ec8460252dad81/68747470733a2f2f646f63732e646f636b65722e636f6d2f646f636b65722d666f722d77696e646f77732f696d616765732f73657474696e67732d7368617265642d6472697665732e706e67)

i have already added the F drive 
![image](https://user-images.githubusercontent.com/31924391/59657706-16048500-91d4-11e9-8347-fc43f4994080.png)

And if i am not wrong i need window 10 pro to install docker for windows

is there any other possible solution?

**Comment by antoineco** [comment]
If you open a terminal inside the machine, what does `mount -l` return?

**Comment by zhongxian93** [comment]
hi tried ssh into my default vm and run `mount -l`

this is what i got:
```

tmpfs on / type tmpfs (rw,relatime,size=911836k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
/dev/sda1 on /mnt/sda1 type ext4 (rw,relatime,data=ordered) [boot2docker-data]
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
/C_DRIVE on /C_DRIVE type vboxsf (rw,nodev,relatime)
/c/Users on /c/Users type vboxsf (rw,nodev,relatime)
/dev/sda1 on /mnt/sda1/var/lib/docker type ext4 (rw,relatime,data=ordered) [boot2docker-data]

```

**Comment by antoineco** [comment]
I see `C_DRIVE` but no `F_DRIVE`. Maybe you need to restart the VM for changes to take effect? (I am not familiar with VirtualBox).

**Comment by zhongxian93** [comment]
tried restarting and F_DRIVE appeared, however it still didn't work, thus i went to attempt change to 
` - /c/Users/datadrive/elasticsearch:/usr/share/elasticsearch/data`  and it `worked`
thanks.

**Comment by antoineco** [comment]
Did you change your path in the compose file to `/F_DRIVE/datadrive/...` instead of `/f/datadrive/...`?

**Comment by zhongxian93** [comment]
no i didnt, after i restart the VM i proceed to run docker-compose up without changing anything so the path is still `- /f/datadrive/elasticsearch:/usr/share/elasticsearch/data` at that point in time

**Comment by antoineco** [comment]
That's the reason why it doesn't work. The mount path must match. If `mount -l` shows that the disk is mounted at `/F_DRIVE`, you have to use that name instead of `/f`.

You could also rename your shared folder from "F_DRIVE" to "f" in VirtualBox", this way it will be mounted at `/f`.

**Comment by antoineco** [comment]
Closing, please reopen if the issue persists!

**Comment by Mohammadtrabelsi** [comment]
It may be a good [solution](https://stackoverflow.com/posts/56960062/timeline) :
You need to make sure that the directory on the host machine is owned by 1000:1000. Run the following command.
`sudo chown 1000:1000 <directory you wish to mount>
`
