### ISSUE TITLE
How to Use docker-elk 6.7.0?

### ISSUE THREAD

**Issue by zhongxian93** [deviantony/docker-elk#403]
Hi all, i have managed to pull and use the docker-elk 7.0.1 but i wanted to try 6.7.0 
### Problem description
i do not know how to pull/use docker-elk 6.7.0, but i managed to find a link for that [https://hub.docker.com/r/sebp/elk/](https://hub.docker.com/r/sebp/elk/) but i do not know how to use it in conjunction with the docker-elk git.
Any help will be appreciated, Thanks

**Comment by deviantony** [comment]
Have a look at https://github.com/deviantony/docker-elk#using-a-newer-stack-version
