### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by gxlqssjf** [deviantony/docker-elk#407]
Envirment:
![image](https://user-images.githubusercontent.com/1277598/60233191-e63f3680-98d1-11e9-8ff0-8c4adb45ae31.png)
Error:
![image](https://user-images.githubusercontent.com/1277598/60233156-d0317600-98d1-11e9-869e-0d9bf9ba69d9.png)

Modify the config file to my computer IP address

**Comment by antoineco** [comment]
Could you please provide all the requested information? We need to see your configuration and logs to be able to help you.

**Comment by indapublic** [comment]
Had same issue, but it works after couple of minutes. Probably, Kibana need some time for initial start.

**Comment by gxlqssjf** [comment]
![image](https://user-images.githubusercontent.com/1277598/60495491-7bcc3300-9ce3-11e9-93c2-23c0e185d995.png)
![image](https://user-images.githubusercontent.com/1277598/60495508-825aaa80-9ce3-11e9-88a0-856c2049c3a0.png)
![image](https://user-images.githubusercontent.com/1277598/60495523-88e92200-9ce3-11e9-9fe3-39c31aa7ecb1.png)
![image](https://user-images.githubusercontent.com/1277598/60495538-90a8c680-9ce3-11e9-8548-72752b5b43e9.png)
![image](https://user-images.githubusercontent.com/1277598/60495549-97373e00-9ce3-11e9-8810-3b03020ce1bd.png)

the question is exiists

**Comment by gxlqssjf** [comment]
> Had same issue, but it works after couple of minutes. Probably, Kibana need some time for initial start
The error is already exists

**Comment by antoineco** [comment]
@gxlqssjf please post your logs. The issue template is available [here](https://github.com/deviantony/docker-elk/blob/master/.github/ISSUE_TEMPLATE.md). We are not able to help you if you don't share the information we need.

**Comment by sdellenb** [comment]
I had the same error today and the kibana logs gave the hint on how to solve it.

```
{"type":"log","@timestamp":"2019-07-02T07:33:03Z","tags":["warning","migrations"],"pid":1,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_4 and restarting Kibana."}
```

I `docker exec`d into the kibana instance and deleted the mentioned index with
`curl -X DELETE http://elasticsearch:9200/.kibana_4` (your values may vary - I'm on my own branch).
After a restart, everything was fine.

**Comment by gxlqssjf** [comment]
wait for the answer

**Comment by antoineco** [comment]
https://github.com/deviantony/docker-elk/issues/407#issuecomment-507602449

**Comment by gxlqssjf** [comment]
Kibana logs:
{"type":"log","@timestamp":"2019-07-03T03:38:16Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-07-03T03:38:16Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
elasticsearch logs:
{"type": "server", "timestamp": "2019-07-03T06:18:54,404+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-ilm]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,405+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-logstash]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,405+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-ml]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,405+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-monitoring]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,405+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-rollup]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,405+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-security]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,406+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-sql]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,406+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "loaded module [x-pack-watcher]"  }
{"type": "server", "timestamp": "2019-07-03T06:18:54,406+0000", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "no plugins loaded"  }
{"type": "server", "timestamp": "2019-07-03T06:19:04,846+0000", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]"  }
{"type": "server", "timestamp": "2019-07-03T06:19:08,370+0000", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "[controller/164] [Main.cc@110] controller (64 bit): Version 7.2.0 (Build 65aefcbfce449b) Copyright (c) 2019 Elasticsearch BV"  }
{"type": "server", "timestamp": "2019-07-03T06:19:11,003+0000", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security"  }
{"type": "server", "timestamp": "2019-07-03T06:19:12,852+0000", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "using discovery type [single-node] and seed hosts providers [settings]"  }
{"type": "server", "timestamp": "2019-07-03T06:19:15,130+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "initialized"  }
{"type": "server", "timestamp": "2019-07-03T06:19:15,130+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "starting ..."  }
{"type": "server", "timestamp": "2019-07-03T06:19:16,023+0000", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}"  }
{"type": "server", "timestamp": "2019-07-03T06:19:16,055+0000", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "cluster UUID [u4Jre-BfRfqY8K0ZOdAvjQ]"  }
{"type": "server", "timestamp": "2019-07-03T06:19:16,464+0000", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "elected-as-master ([1] nodes joined)[{2fcff1a94fc0}{agzyoHN1TSWOmoyckNplfg}{p8Z2_79vRoeXwn9Ya5GRBA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=8341348352, xpack.installed=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 3, version: 46, reason: master node changed {previous [], current [{2fcff1a94fc0}{agzyoHN1TSWOmoyckNplfg}{p8Z2_79vRoeXwn9Ya5GRBA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=8341348352, xpack.installed=true, ml.max_open_jobs=20}]}"  }
{"type": "server", "timestamp": "2019-07-03T06:19:18,232+0000", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0",  "message": "master node changed {previous [], current [{2fcff1a94fc0}{agzyoHN1TSWOmoyckNplfg}{p8Z2_79vRoeXwn9Ya5GRBA}{172.18.0.2}{172.18.0.2:9300}{ml.machine_memory=8341348352, xpack.installed=true, ml.max_open_jobs=20}]}, term: 3, version: 46, reason: Publication{term=3, version=46}"  } {"type": "server", "timestamp": "2019-07-03T06:19:18,442+0000", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}"  }
{"type": "server", "timestamp": "2019-07-03T06:19:18,444+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "started"  }
{"type": "server", "timestamp": "2019-07-03T06:19:19,021+0000", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "license [ec45f176-9f0a-44ad-bc50-62fef7119dae] mode [trial] - valid"  }
{"type": "server", "timestamp": "2019-07-03T06:19:19,028+0000", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "recovered [7] indices into cluster_state"  }
{"type": "server", "timestamp": "2019-07-03T06:19:29,326+0000", "level": "INFO", "component": "o.e.x.w.WatcherService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "reloading watcher, reason [new local watcher shard allocation ids], cancelled [0] queued tasks"  }
{"type": "server", "timestamp": "2019-07-03T06:19:36,306+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "2fcff1a94fc0", "cluster.uuid": "u4Jre-BfRfqY8K0ZOdAvjQ", "node.id": "agzyoHN1TSWOmoyckNplfg",  "message": "Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.monitoring-es-7-2019.07.02][0]] ...])."  }
elasticsearch in browser:
![image](https://user-images.githubusercontent.com/1277598/60568055-49cbd700-9d9e-11e9-93ea-79bdb2cd5932.png)





> [#407 (comment)](https://github.com/deviantony/docker-elk/issues/407#issuecomment-507602449)

**Comment by antoineco** [comment]
`Cluster health status changed from [RED] to [GREEN]`

Perfect 👌 Elasticsearch is working and Kibana is now ready. Refresh the page at http://127.0.0.1:5601 and the login screen will appear.

**Comment by gxlqssjf** [comment]
> `Cluster health status changed from [RED] to [GREEN]`
> 
> Perfect 👌 Elasticsearch is working and Kibana is now ready. Refresh the page at http://127.0.0.1:5601 and the login screen will appear.

![image](https://user-images.githubusercontent.com/1277598/60571030-569ff900-9da5-11e9-9e6e-8c8a92b528bd.png)

**Comment by antoineco** [comment]
Be patient, the first time you start Kibana it can take several minutes before it comes up depending how fast your machine is.
Don't stop the container. Just wait.

**Comment by gxlqssjf** [comment]
> Be patient, the first time you start Kibana it can take several minutes before it comes up depending how fast your machine is.
> Don't stop the container. Just wait.

I wait for the whole  day,also like :
![image](https://user-images.githubusercontent.com/1277598/60579973-c9fe3680-9db6-11e9-8654-ff464b05c30a.png)

**Comment by gxlqssjf** [comment]
> Be patient, the first time you start Kibana it can take several minutes before it comes up depending how fast your machine is.
> Don't stop the container. Just wait.

I set use 2g memory for elk,but it do not work as normal

**Comment by gxlqssjf** [comment]
> Be patient, the first time you start Kibana it can take several minutes before it comes up depending how fast your machine is.
> Don't stop the container. Just wait.

![image](https://user-images.githubusercontent.com/1277598/60580274-60325c80-9db7-11e9-9071-df66641044a5.png)

**Comment by antoineco** [comment]
@gxlqssjf please follow the instructions from the README. You set a user called `"elk"`, but this user **does not exist**. The built-in user is `"elastic"` and the password is `"changeme"`.

I suggest you reset **all your changes** and read the README carefully.

**Comment by gxlqssjf** [comment]
> @gxlqssjf please follow the instructions from the [README](https://github.com/deviantony/docker-elk#initial-setup). You set a user called `"elk"`, but this user **does not exist**. The built-in user is `"elastic"` and the password is `"changeme"`.
> 
> I suggest you reset **all your changes** and read the [README](https://github.com/deviantony/docker-elk#initial-setup) _carefully_.

OK,I try again,thanks!but also error.
the kibana logs:
{"type":"log","@timestamp":"2019-07-04T02:18:21Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://127.0.0.1:9200/"}
{"type":"log","@timestamp":"2019-07-04T02:18:21Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2019-07-04T02:18:21Z","tags":["warning","task_manager"],"pid":1,"message":"PollError No Living connections"}
{"type":"log","@timestamp":"2019-07-04T02:18:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://127.0.0.1:9200/"}
{"type":"log","@timestamp":"2019-07-04T02:18:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2019-07-04T02:18:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://127.0.0.1:9200/"}
{"type":"log","@timestamp":"2019-07-04T02:18:24Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2019-07-04T02:18:24Z","tags":["warning","task_manager"],"pid":1,"message":"PollError No Living connections"}

the kibana config:
![image](https://user-images.githubusercontent.com/1277598/60635455-78e95380-9e45-11e9-9f81-54aee106d19b.png)

the logstash confgi:
![image](https://user-images.githubusercontent.com/1277598/60635478-8d2d5080-9e45-11e9-865b-1d99d4c695a0.png)
![image](https://user-images.githubusercontent.com/1277598/60635487-961e2200-9e45-11e9-86da-c3bfa5651c3e.png)

the elasticsearch config:
![image](https://user-images.githubusercontent.com/1277598/60635503-a504d480-9e45-11e9-8aad-056c62399542.png)

the elasticsearch in browser:
![image](https://user-images.githubusercontent.com/1277598/60635534-bb129500-9e45-11e9-9037-41d5ff1450a1.png)

the docker-compose.yml like :
![image](https://user-images.githubusercontent.com/1277598/60635552-ccf43800-9e45-11e9-807f-09db12bc5511.png)
![image](https://user-images.githubusercontent.com/1277598/60635563-d2ea1900-9e45-11e9-9a86-eb5752ec31f5.png)

the docker 👍:
![image](https://user-images.githubusercontent.com/1277598/60635588-e1d0cb80-9e45-11e9-90aa-9c1e8d1113b8.png)

the error like 👍 👍 
![image](https://user-images.githubusercontent.com/1277598/60635630-ff059a00-9e45-11e9-97e9-c2e976740d69.png)
![image](https://user-images.githubusercontent.com/1277598/60635637-062ca800-9e46-11e9-8d54-a91873222620.png)

what is the problem?

**Comment by gxlqssjf** [comment]
> @gxlqssjf please follow the instructions from the [README](https://github.com/deviantony/docker-elk#initial-setup). You set a user called `"elk"`, but this user **does not exist**. The built-in user is `"elastic"` and the password is `"changeme"`.
> 
> I suggest you reset **all your changes** and read the [README](https://github.com/deviantony/docker-elk#initial-setup) _carefully_.

I want to know how to change the user name??thanks

**Comment by n0d3tr** [comment]
this work for me:

docker run -d --name kibana **--link elasticsearch:elasticsearch** -p 5601:5601 kibana:7.9.3
