### ISSUE TITLE
Password needs to be in quotes in the "logstash.conf" file

### ISSUE THREAD

**Issue by SlavikCA** [deviantony/docker-elk#408]
### Problem description
I'm setting the system on Docker on Windows Server 2016

Currently logstash.conf has this line:
```
		password => changeme
```

When I replaced password and started the service, I was getting this errors:
```
[ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>
"LogStash::ConfigurationError", :message=>"Expected one of #, { at line 14, column 2 (byte 221) after output {\r\n\telasticsearch {\r\n\t\thosts => \"elastics
earch:9200\"\r\n\t\tuser => elastic\r\n\t\tpassword =>
...
```
and after few minutes:
```
[INFO ][logstash.runner          ] Logstash shut down.
```

I fixed issue by putting password in double quotes.

#### Docker setup

```
PS C:\Users\Administrator\code\docker-elk> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
PS C:\Users\Administrator\code\docker-elk> docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by antoineco** [comment]
That's because your password contains special escape characters. This behavior is common to all configuration formats out here, in one form of another, so I was assuming we don't have to go into that level of detail (otherwise well pretty much have to copy and paste the Elastic documentation into this repo).

How should we fix this, with links to the documentation so users know when they have to use quotes and when they don't need them?

**Comment by SlavikCA** [comment]
I would suggest to fix like this:
```
password => "changeme"
```

**Comment by antoineco** [comment]
Ok sounds reasonable: https://www.elastic.co/guide/en/logstash/7.2/configuration-file-structure.html#string
