### ISSUE TITLE
License expired message

### ISSUE THREAD

**Issue by lucj** [deviantony/docker-elk#41]
Hi, I've installed branch shield-support of docker-elk (I just created the my own image to deploy to machine: https://github.com/lucj/docker-elk/tree/shield-support) and I now have the "Status: Red" message with:

     [security_exception] current license is non-compliant for [shield], with: {"license.expired.feature":"shield"}

How to you handle the license update when using shield ?

**Comment by deviantony** [comment]
As stated in the documentation, a 30 day trial license is shipped with the Shield installation, see: https://www.elastic.co/guide/en/shield/current/license-management.html

I guess that you could just recreate the Elasticsearch container in order to re-create a new installation and a new license.

**Comment by lucj** [comment]
Thanks, I missed this part :)
Trying to re-create the ES container did not work but I'm trying to add a nginx based solution to secure the thing. https-portal (Docker / Let's Encrypt / Nginx) is great for this purpose.

**Comment by xermus** [comment]
Can you please turn this off by default or give information here how this can be disabled. The trial period is over and the logs are full of the expiration errors.

**Comment by antoineco** [comment]
@xermus literally the first note in the README.
