### ISSUE TITLE
Extension APM-Server not working?

### ISSUE THREAD

**Issue by DevZ1** [deviantony/docker-elk#411]
Hi,

like documented in extensions I started all in the elk root folder with this command:

docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up -d

Now it states that it starts apm-server and it does, and is active if i do docker ps, but somehow in the kibana APM interface, if i check apm server status, it's says its not running. Also the weird thing is that this creates a apm-server folder with a config folder and a apm-server.yml folder. That's right a folder, and not a apm-server.yml file. The folder is also empty btw.

So what am i doing wrong here? Can anybody help please, cause we want to log our .net app errors to the APM-Server.

Thanks!

Best, Hay.

**Comment by antoineco** [comment]
It's most likely a permission issue since we enabled authentication with v7.0.0 and didn't update that extension. I'll take a look tomorrow.

**Comment by DevZ1** [comment]
That would be really awesome. Thank you, awaiting your feedback and solutions for this.
In the meantime i added this to docker-compose.yml but no go.

  apm-server:
    build:
      context: extensions/apm-server/
      args:
       ELK_VERSION: $ELK_VERSION
    volumes:
       - ./apm-server/config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro
    ports:
       - "8200:8200"
    environment:
      - output.elasticsearch.hosts=['http://elasticsearch:9200']
      - apm-server.host="0.0.0.0:8200"
      - setup.kibana.host="kibana:5601"
      - setup.template.enabled=true
      - logging.to_files=false
    networks:
       - elk
    depends_on:
       - elasticsearch
       - kibana

Also created and copied apm-server to elk root folder and changed config to this, but also nogo :-(

apm-server:
  host: localhost:8200

output:
  elasticsearch:
    hosts: http://elasticsearch:9200
    username: elastic
    password: changeme

**Comment by antoineco** [comment]
Done! Feel free to re-open if you're still having issues.

**Comment by DevZ1** [comment]
I still get APM Server has still not connected to Elasticsearch :-(

**Comment by antoineco** [comment]
@DevZ1 did you revert the previous changes you did to the compose file and apm-server config? If you generated passwords for built-in users, did you replace the default password "changeme" by your own password?

**Comment by antoineco** [comment]
Oh, and please fill in the issue template (the one that appears when you open a new issue), it's impossible to help you without knowing anything about your environment.

**Comment by DevZ1** [comment]
Yes I did. I used it on a fresh install on a different server.
This also happened again:

Also the weird thing is that this creates a apm-server folder with a config folder and a apm-server.yml folder. That's right a folder, and not a apm-server.yml file. The folder is also empty btw.

I took fresh copy and executed : docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up -d

**Comment by antoineco** [comment]
I still don't know anything about your setup, please fill in the issue template.

**Comment by DevZ1** [comment]
Here you go sir. I included your issue template. If you have any other question please let me know.
Thank you!
[IssueTemplate.txt](https://github.com/deviantony/docker-elk/files/3352396/IssueTemplate.txt)

**Comment by DevZ1** [comment]
If you want, I could even give you acces to my laptop via Teamviewer and you can do anything you want trough my screen and open terminal. Please let me know.

**Comment by antoineco** [comment]
Alright so apparently you're running on Linux, and Docker is running on the local host so it's hard for me to explain why you see a directory instead of a file, unless you moved the file around the first time your started the APM server.

Also I can't see your APM server logs, `docker-compose logs` only shows the main components unless you pass `-f extensions/apm-server/apm-server-compose.yml` as an argument.

My guess is that you have to stop and delete the APM container, then recreate it. Try this:
```console
$ docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml down -v apm-server
```
```console
docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up -d
```

**Comment by mbandizzle** [comment]
I'm having the same issue when trying to start up a fresh install when using the `up` command in the readme (`docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up`).

I get messages like this over and over as the APM Server tries to connect to Elasticsearch but fails:

```
apm-server_1     | 2019-07-04T00:05:22.261Z     ERROR   pipeline/output.go:100  Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
apm-server_1     | 2019-07-04T00:05:22.262Z     INFO    pipeline/output.go:93   Attempting to reconnect to backoff(elasticsearch(http://elasticsearch:9200)) with 7 reconnect attempt(s)
```
What's strange is that if I `docker exec` into the apm-server container and curl the Elasticsearch server, I'm successful if I pass in the username and password, which makes me think the credentials you added to `apm-server.yml` aren't being used for some reason:

```
bash-4.2$ curl http://elasticsearch:9200/
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

bash-4.2$ curl -u elastic:changeme http://elasticsearch:9200/
{
  "name" : "6b5f05318c68",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "x0A-8XN_TmqTAi3Q-9G_ng",
  "version" : {
    "number" : "7.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "508c38a",
    "build_date" : "2019-06-20T15:54:18.811730Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by mbandizzle** [comment]
Another thing to note, I'm also on Ubuntu (16.04) and had the same issue that was described in the first comment here.

Starting fresh there is no `apm-server` directory in the root `docker-elk` directory.  However after running `docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up` from the root directory, a new `apm-server` directory appears in the root.  Inside is a `config/` and inside of that is a `apm-server.yml/`.  It's not the actual .yml, but it's a directory named `apm-server.yml`.

It seems like the relative pathing inside the `apm-server-compose.yml` file isn't quite working and the result is the compose is looking for a config yml that doesn't actually have anything readable.  It's looking at `docker-elk/apm-server/config/apm-server.yml` which isn't real when it should be looking at `docker-elk/extensions/apm-server/config/apm-server.yml` where you have the username and password defined.  I hope this makes sense.  Thanks for your help!

**Comment by antoineco** [comment]
> It seems like the relative pathing inside the apm-server-compose.yml file isn't quite working

You're right, `./extensions/` is missing from that path. Nice catch. I wonder how I could possibly have missed the errors in my logs.

**Comment by DevZ1** [comment]
Hi, 

i changed path, but now APM check says : APM Server has still not connected to Elasticsearch
My config is:

version: '2'

services:
  apm-server:
    build:
      context: extensions/apm-server/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./extensions/apm-server/config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch


And 

apm-server:
  host: localhost:8200

output:
  elasticsearch:
    hosts: ['http://elasticsearch:9200']
    username: elastic
    password: xxxxxxx(my new password)

Any idea what i'm missing here?

Thank you!

**Comment by YosBD** [comment]
Same here. *using the latest version*.

I just cloned the latest master branch.

running `docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up`.

Getting the following on the apm container logs:
`Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}`

**Comment by antoineco** [comment]
The path has changed from
`/usr/share/apm-server/config/apm-server.yml`
to
`/usr/share/apm-server/apm-server.yml` (no more `config` directory)

according to https://www.elastic.co/guide/en/apm/server/current/running-on-docker.html.
