### ISSUE TITLE
Logstash Internal Log

### ISSUE THREAD

**Issue by ts-kazuob** [deviantony/docker-elk#413]
I would like to ask how to store the logstash internal log in a file.
Tried to set path.logs in logstash.yml but it does not create any file.
E.g. Is it possible to put the logstash internal logs under the /logstash_logs directory?

- ELK Version 7.0.1
- [Related Issue](https://github.com/deviantony/docker-elk/issues/145)

**Comment by ts-kazuob** [comment]
I added file below and it seems log can be seen in the logstash container.
logstash/config/log4j2.properties
https://github.com/elastic/logstash/blob/master/config/log4j2.properties

**Comment by antoineco** [comment]
Thanks for sharing your solution! Using a `RollingFile` appender is indeed the way to go.
