### ISSUE TITLE
vm memory too low

### ISSUE THREAD

**Issue by daithi-coombes** [deviantony/docker-elk#415]
### Problem description

Continuous stack traces filling up docker logs (new install). Seem this issue is container isn't scaling to elasticsearch's requirements. Seems the virtual memory is too low, think this should be sorted on docker side, ie here ;)

### Extra information

```
...
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
...
elasticsearch_1  | "Caused by: org.elasticsearch.cluster.block.ClusterBlockException: index [.monitoring-es-7-2019.07.12] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];",                                                                                                                
elasticsearch_1  | "at org.elasticsearch.cluster.block.ClusterBlocks.indicesBlockedException(ClusterBlocks.java:222) ~[elasticsearch-7.2.0.jar:7.2.0]"
...
elasticsearch_1  | {"type": "server", "timestamp": "2019-07-12T10:52:11,819+0000", "level": "WARN", "component": "o.e.x.m.e.l.LocalExporter", "cluster
.name": "docker-cluster", "node.name": "ae00db7abf5e", "cluster.uuid": "PtK27-9eS7Ka4_RSoZC96g", "node.id": "ZJ_GY_19Sk-sfIGyxHOj0g",  "message": "une
xpected error while indexing monitoring document" ,                                                                                                   
elasticsearch_1  | "stacktrace": ["org.elasticsearch.xpack.monitoring.exporter.ExportException: ClusterBlockException[index [.monitoring-es-7-2019.07.
12] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]",
```

#### Stack configuration

Only change was for `paid features` to be set to `basic` from `trial`, issue persisted before. Have followed instructions from here: https://stackoverflow.com/a/50609418/288644 to remove watermark warning

```
PUT _cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "100gb",
    "cluster.routing.allocation.disk.watermark.high": "50gb",
    "cluster.routing.allocation.disk.watermark.flood_stage": "10gb",
    "cluster.info.update.interval": "1m"
  }
}
```

#### Docker setup

```
docker-compose up
```

#### Docker logs

@see extra information above

**Comment by daithi-coombes** [comment]
my solution was to log into container and execute following:
```
[root@88b50b279fa5 elasticsearch]# sysctl -w vm.max_map_count=262144
sysctl: setting key "vm.max_map_count": Read-only file system
[root@88b50b279fa5 elasticsearch]#
```

Even with `Read-only file system` warning it still worked. Thinking this should be in a Dockerfile?

**Comment by antoineco** [comment]
You're absolutely right and the ES documentation makes it very clear that this setting must be increased for productive setups. However this project focuses on newcomers and PoCs, so we chose to bypass those checks by using the `single-node` mode in the ES config, mainly because hacking those kernel settings is not possible for users who do not have direct admin access to the underlying host OS.

We should definitely add a note about the consequences of using `single-node`.

**Comment by antoineco** [comment]
Ref #108
