### ISSUE TITLE
E: Unable to locate package nc

### ISSUE THREAD

**Issue by olisteadman** [deviantony/docker-elk#416]
### Problem description

`README.md` suggests the use of `nc` in [ln157](https://github.com/deviantony/docker-elk/blame/master/README.md#L157)
... but `sudo apt install nc -y` gives error `E: Unable to locate package nc`

### Extra information

Presumably by nc you mean `netcat`

#### Stack configuration

N/A

#### Docker setup

N/A

#### Docker logs

N/A

**Comment by antoineco** [comment]
`nc` and `netcat` are the same program, but the command may vary depending on the OS or OS distribution you use. Because you didn't specify what your environment was I'm gonna assume you're using Ubuntu and drop that extract from the OS documentation here:

> Package **netcat**
>    …
>    bionic (18.04LTS) (net): TCP/IP swiss army knife -- transitional package [universe]
>    1.10-41.1: all
>    also provided by: **netcat-openbsd**, **netcat-traditional**
>
> -- _https://packages.ubuntu.com/search?keywords=netcat_

Any of the highlighted package names should have you covered:

```console
$ docker run ubuntu:bionic sh -c 'apt update && apt install -y netcat && which nc'

Fetched 16.8 MB in 2s (6983 kB/s)
Reading package lists...
Building dependency tree...

…

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  netcat-traditional
The following NEW packages will be installed:
  netcat netcat-traditional
0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
Need to get 65.1 kB of archives.
After this operation, 157 kB of additional disk space will be used.

…

Setting up netcat (1.10-41.1) ...
/bin/nc
```
