### ISSUE TITLE
Logs are gone after I rebooted my laptop

### ISSUE THREAD

**Issue by c0debreaker** [deviantony/docker-elk#425]
First of all, docker-elk is awesome! I have all elasticsearch, logstash and kibana running on my mac osx. Yesterday, I had to reboot my laptop. I didn't delete the ELK containers. The command `docker ps -a` still shows the container. When I started it with `docker-compose up`, I noticed kibana and logstash was failing to connect to ElasticSearch. It was saying authorization failure. I had to run the command below again to generate a new password.
```
docker-compose exec -T elasticsearch bin/elasticsearch-setup-passwords auto --batch
```
After running the above, I updated logstash and kibana configuration files and ran
```
docker-compose restart kibana logstash
```
Kibana and Logstash was finally able to connect. However, it can't find the previous logs from yesterday. I tried last 24 hours and last 7 days but no luck.

In your doc it says that if container was deleted, that's the only time that data will be gone. However, I didn't delete the ELK containers. What might have happened? Is there something I'm missing?

**Comment by antoineco** [comment]
My assumption was also that changes would be persisted as long as the container still exists. Can you reproduce if you stop the stack and start it again?
```
docker-compose down
docker-compose up
```

**Comment by c0debreaker** [comment]
The issue doesn't happen when doing `docker-compose up` or `down`. I will try to reboot my laptop tonight. I can't do it right now as I'm working on many stuff. I will update this ticket.

Thank you.

**Comment by antoineco** [comment]
Actually `docker-compose down` _deletes_ the containers, so it's better to avoid using it if you need your containers to be persisted. I edited my previous comment.

Output of `down`:
```
$ docker-compose down
Stopping docker-elk_logstash_1      ... done
Stopping docker-elk_kibana_1        ... done
Stopping docker-elk_elasticsearch_1 ... done
Removing docker-elk_logstash_1      ... done
Removing docker-elk_kibana_1        ... done
Removing docker-elk_elasticsearch_1 ... done
Removing network docker-elk_elk
```

It could be that `docker-compose up` _recreates_ the containers in a similar manner on your machine, but I can not reproduce on mine.

What I would recommend:
* On your side, use `start/stop` instead of `up/down` if you want to avoid recreating containers and lose data in the process.
* On our side, we should ensure the Elasticsearch data directory is set to an empty volume by default, so that users that did not explicitly persist their data do not lose everything.

**Comment by deviantony** [comment]
> On our side, we should ensure the Elasticsearch data directory is set to an empty volume by default, so that users that did not explicitly persist their data do not lose everything.

Well, by default all the Elasticsearch data should be persisted inside the container. And if its required to persist the data outside of the container, users should simply follow the instructions at https://github.com/deviantony/docker-elk#how-to-persist-elasticsearch-data

Is that incorrect?

**Comment by antoineco** [comment]
What I meant is that Docker lets you create named volumes that do not require the user to care where the data is persisted. But in insight I think you're right, it's better to avoid side effects, and fair to expect users follow the docs and explicitly decide how to persist their data, since we have it documented. @c0debreaker anything stopping you from using the method documented in the README?

**Comment by deviantony** [comment]
Actually you are right, what prevents us from defaulting to the use of named volumes in the Compose stack and removing that entire how to persist documentation section? We then provide a default stack with data persisted (even resilient to `docker-compose down`, not to `docker-compose -v` though).

**Comment by antoineco** [comment]
The only thing I could think of is that data may be persisted forever after a `docker-compose down` without the user knowing or wanting it. Also if a user wants to start fresh, they will have to clear the volume manually, or ensure they use `down -v`. Compose files use YAML, so a good compromise could be to have a commented section.

**Comment by deviantony** [comment]
> The only thing I could think of is that data may be persisted forever after a docker-compose down without the user knowing or wanting it

True, as always it's just a matter of documentation. 

I think that in most of the cases, people will want to persist their data. It is probably more convenient for most of the userbase to provide a data persisted default.

What do you think of the following?

* Use a named volume for Elasticsearch data
* Remove the https://github.com/deviantony/docker-elk#how-to-persist-elasticsearch-data section
* Add a new documentation section about "Cleanup" or "Reset", maybe in https://github.com/deviantony/docker-elk#usage ?
* Indicate that Elasticsearch data is persisted by default

**Comment by deviantony** [comment]
All good let me come up with a PR quickly.

**Comment by c0debreaker** [comment]
Cool stuff! I honestly haven't tried it yet. I've got so many stuff on my laptop. 

Anyways, I stopped kibana and elasticsearch with `ctrl+c` since I didn't use -d with docker-compose. Right after pressing ctrl+c, this is what I got
```
.......
.......
"7b63d0fe3f2e", "cluster.uuid": "fwIuqZFdR-iUnHr1FHwgEg", "node.id": "Rk2vZnc8STqTpkLUTlu7vw",  "message": "[gc][31919] overhead, spent [970ms] collecting in the last [3.1s]"  }
elasticsearch_1  | {"type": "server", "timestamp": "2019-09-08T15:57:13,500+0000", "level": "ERROR", "component": "o.e.x.m.c.n.NodeStatsCollector", "cluster.name": "docker-cluster", "node.name": "7b63d0fe3f2e", "cluster.uuid": "fwIuqZFdR-iUnHr1FHwgEg", "node.id": "Rk2vZnc8STqTpkLUTlu7vw",  "message": "collector [node_stats] timed out when collecting data"  }
elasticsearch_1  | {"type": "server", "timestamp": "2019-09-08T15:57:30,269+0000", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "docker-cluster", "node.name": "7b63d0fe3f2e", "cluster.uuid": "fwIuqZFdR-iUnHr1FHwgEg", "node.id": "Rk2vZnc8STqTpkLUTlu7vw",  "message": "[gc][31937] overhead, spent [343ms] collecting in the last [1s]"  }
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker-elk_kibana_1        ... done
Stopping docker-elk_elasticsearch_1 ... done
```

Then I ran `docker ps -a`
```
5b7b002aaf81        docker-elk_kibana                                        "/usr/local/bin/dumb…"   7 days ago          Exited (137) 34 hours ago                                                       docker-elk_kibana_1
7b63d0fe3f2e        docker-elk_elasticsearch                                 "/usr/local/bin/dock…"   7 days ago          Exited (137) 34 hours ago                                                       docker-elk_elasticsearch_1
```

I just did a docker-compose down. You are correct. It deleted the containers. I guess what really happened previously was that I ran docker-compose down then my machine crashed the same day, then I started accusing docker-elk that it didn't persist the data. :)

I saw the conversation above. I think it's really a good idea to keep data persistent by default.

**Comment by c0debreaker** [comment]
Glad the pr was merged! I'll be pulling it. Thank you for the quick turn around. :)

**Comment by antoineco** [comment]
I maybe naively assume users know Compose is a developer tool, but it doesn't cost anything to add a few warning signs if you think it's appropriate.

The list of reasons why this stack is not production ready is not limited to storage considerations so we may want to list a few of them: Compose is single node so no high-availability or data replication, no TLS encryption, `changeme` password by default, we skip bootstrap checks for simplification, ...

**Comment by deviantony** [comment]
@antoineco I've seen this notice on another stack project which I think is quite comparable to this one: https://github.com/stefanprodan/swarmprom#monitoring-production-systems (even if it's not defined in the introduction of the project)

And yeah, sounds good to me.

**Comment by c0debreaker** [comment]
👍coolio!

**Comment by unstephenk** [comment]
I tried adding the following line to my `docker-compose.yml` and now I am getting a security node error.

```
- type: volume
        source: $PWD/elasticsearch/data
        target: /usr/share/elasticsearch/data
```

ERROR:
```
{"type": "server", "timestamp": "2020-02-27T17:36:20,019Z", "level": "ERROR", "component": "o.e.x.s.a.e.NativeUsersStore", "cluster.name": "docker-cluster", "node.name": "0844a39c5441", "message": "security index is unavailable. short circuiting retrieval of user [userXX]", "cluster.uuid": "TT6ipho7TR-RaXZ4xWs3sA", "node.id": "JLO2KhoDQLyrmDUX96W-qg"  }
```

**Comment by antoineco** [comment]
@unstephenk I don't think Compose accepts variables in volume definitions (`$PWD` will most likely be interpreted literally).

Please also read the note about user permissions carefully in the README.
