### ISSUE TITLE
Sense returns always "Client request error: connect ECONNREFUSED"

### ISSUE THREAD

**Issue by thedarkside** [deviantony/docker-elk#43]
Trying out the examples in the help section returns me always the error

>Error connecting to 'http://localhost:9200/elasticsearch/index/type/1':
>Client request error: connect ECONNREFUSED

**Comment by deviantony** [comment]
Hello,

Sorry for the late update, I've noticed something with the use of Sense, you can't specify your server as `http://localhost:9200` in the server address bar, it won't work. For Sense to work, you must specify the IP address of your network interface (e.g for me it was 192.168.x.x).

**Comment by deviantony** [comment]
@thedarkside Did you had the opportunity to try my workaround?

**Comment by deviantony** [comment]
I'll consider this issue closed. Feel free to re-open if you need more info.

**Comment by olglay** [comment]
yes it works
