### ISSUE TITLE
FATAL  ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]

### ISSUE THREAD

**Issue by newgeekorder** [deviantony/docker-elk#431]
### Problem description
Cloned the latest (master)  repo for env 7.3.1  and docker-compose up 
Kibana fails to start 

FATAL  ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]

### Extra information

Elastic 7.3 added hosts as a new config and the environment configuration looks correct. 
I cannot yet determine why this instance of kibana appears to be looking for an older config 

#### Stack configuration

no configuratoion changes 

#### Docker setup

Docker version 19.03.1, build 74b1e89

docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

#### Docker logs

Creating network "docker-elk_elk" with driver "bridge"
Creating docker-elk_elasticsearch_1 ... done
Creating docker-elk_logstash_1      ... done
Creating docker-elk_kibana_1        ... done
Attaching to docker-elk_elasticsearch_1, docker-elk_kibana_1, docker-elk_logstash_1
elasticsearch_1  | Created elasticsearch keystore in /usr/share/elasticsearch/config
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1  | [2019-09-14T11:52:24,799][INFO ][o.e.e.NodeEnvironment    ] [piDty0Y] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/nvme0n1p2)]], net usable_space [237.9gb], net total_space [453.2gb], types [ext4]
elasticsearch_1  | [2019-09-14T11:52:24,811][INFO ][o.e.e.NodeEnvironment    ] [piDty0Y] heap size [247.5mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2019-09-14T11:52:25,022][INFO ][o.e.n.Node               ] [piDty0Y] node name derived from node ID [piDty0YfQIS81y9ffJ_5sw]; set [node.name] to override
elasticsearch_1  | [2019-09-14T11:52:25,022][INFO ][o.e.n.Node               ] [piDty0Y] version[6.5.2], pid[1], build[default/tar/9434bed/2018-11-29T23:58:20.891072Z], OS[Linux/4.4.0-159-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
elasticsearch_1  | [2019-09-14T11:52:25,023][INFO ][o.e.n.Node               ] [piDty0Y] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.pFY4FpDK, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xmx256m, -Xms256m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
elasticsearch_1  | [2019-09-14T11:52:29,219][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2019-09-14T11:52:29,219][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [analysis-common]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [ingest-common]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [lang-expression]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [lang-mustache]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [lang-painless]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [mapper-extras]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [parent-join]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [percolator]
elasticsearch_1  | [2019-09-14T11:52:29,220][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [rank-eval]
elasticsearch_1  | [2019-09-14T11:52:29,227][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [reindex]
elasticsearch_1  | [2019-09-14T11:52:29,227][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [repository-url]
elasticsearch_1  | [2019-09-14T11:52:29,227][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [transport-netty4]
elasticsearch_1  | [2019-09-14T11:52:29,227][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [tribe]
elasticsearch_1  | [2019-09-14T11:52:29,228][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-ccr]
elasticsearch_1  | [2019-09-14T11:52:29,235][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-core]
elasticsearch_1  | [2019-09-14T11:52:29,235][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-deprecation]
elasticsearch_1  | [2019-09-14T11:52:29,235][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-graph]
elasticsearch_1  | [2019-09-14T11:52:29,235][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-logstash]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-ml]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-monitoring]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-rollup]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-security]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-sql]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-upgrade]
elasticsearch_1  | [2019-09-14T11:52:29,236][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded module [x-pack-watcher]
elasticsearch_1  | [2019-09-14T11:52:29,237][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded plugin [ingest-geoip]
elasticsearch_1  | [2019-09-14T11:52:29,237][INFO ][o.e.p.PluginsService     ] [piDty0Y] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2019-09-14T11:52:38,842][INFO ][o.e.x.s.a.s.FileRolesStore] [piDty0Y] parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]
kibana_1         | {"type":"error","@timestamp":"2019-09-14T11:52:39Z","tags":["fatal","root"],"pid":1,"level":"fatal","error":{"message":"child \"elasticsearch\" fails because [\"hosts\" is not allowed]","name":"ValidationError","stack":"ValidationError: child \"elasticsearch\" fails because [\"hosts\" is not allowed]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:138:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:108:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:81:10)\n    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:10)\n    at <anonymous>"},"message":"child \"elasticsearch\" fails because [\"hosts\" is not allowed]"}
kibana_1         | 
kibana_1         |  FATAL  ValidationError: child "elasticsearch" fails because ["hosts" is not allowed]
kibana_1         | 
elasticsearch_1  | [2019-09-14T11:52:39,974][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [piDty0Y] [controller/249] [Main.cc@109] controller (64 bit): Version 6.5.2 (Build 767566e25172d6) Copyright (c) 2018 Elasticsearch BV
docker-elk_kibana_1 exited with code 1
elasticsearch_1  | [2019-09-14T11:52:41,395][INFO ][o.e.d.DiscoveryModule    ] [piDty0Y] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2019-09-14T11:52:42,970][INFO ][o.e.n.Node               ] [piDty0Y] initialized
elasticsearch_1  | [2019-09-14T11:52:42,971][INFO ][o.e.n.Node               ] [piDty0Y] starting ...
elasticsearch_1  | [2019-09-14T11:52:43,160][INFO ][o.e.t.TransportService   ] [piDty0Y] publish_address {172.27.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2019-09-14T11:52:43,297][WARN ][o.e.b.BootstrapChecks    ] [piDty0Y] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2019-09-14T11:52:43,414][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [piDty0Y] publish_address {172.27.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2019-09-14T11:52:43,414][INFO ][o.e.n.Node               ] [piDty0Y] started
elasticsearch_1  | [2019-09-14T11:52:45,026][INFO ][o.e.l.LicenseService     ] [piDty0Y] license [daec5c52-8a6e-4ed2-bf0f-057b0ed66862] mode [trial] - valid
elasticsearch_1  | [2019-09-14T11:52:45,111][INFO ][o.e.g.GatewayService     ] [piDty0Y] recovered [7] indices into cluster_state
elasticsearch_1  | [2019-09-14T11:52:46,393][INFO ][o.e.c.r.a.AllocationService] [piDty0Y] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.watcher-history-9-2019.09.13][0], [.monitoring-es-6-2019.09.13][0]] ...]).
logstash_1       | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1       | [2019-09-14T11:52:55,262][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.hosts" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:137:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:278:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:237:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:73:in `<main>'"]}
logstash_1       | [2019-09-14T11:52:55,294][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

**Comment by antoineco** [comment]
Thanks for taking the time for sharing those details! It seems like Compose picked up images from an older v6.5.2 stack, according to the logs.

Could you try rebuilding the images with `docker-compose build`?

**Comment by antoineco** [comment]
Friendly ping @newgeekorder
