### ISSUE TITLE
ERROR: Version mismatch between ./docker-compose.yml and apm-server-compose.yml

### ISSUE THREAD

**Issue by mcquadenc** [deviantony/docker-elk#432]
### Problem description
Docker raises the following execution when executing the command `docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up`:

```ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.2 but extension file ./extensions/apm-server/apm-server-compose.yml uses version 2.0```

### Extra information

The versions apm-server-compose.yml and docker-compose.yml are:
`apm-server-compose.yml`:
```version: '2'```

`docker-compose.yml`:
```version: '3.2'```

#### Docker setup

```
Docker version 17.05.0-ce, build 89658be
```

```
docker-compose -f docker-compose.yml -f extensions/apm-server/apm-server-compose.yml up
```

**Comment by antoineco** [comment]
Nice catch, thanks for reporting!
