### ISSUE TITLE
Error running latest with docker-compose.

### ISSUE THREAD

**Issue by Akayeshmantha** [deviantony/docker-elk#433]
### Problem description
Hi all

I am working on spinning up safeguard integrated elk stack.

When I clone the latest and run the below command 

`docker-compose -f docker-compose.yml --project-name ninfra up --build -d` 

I get the below error 

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://repo1.maven.org/maven2/com/floragunn/search-guard-7/7.3.1-36.1.0/search-guard-7-7.3.1-36.1.0.zip

And as it says zip file is not anymore there.

Any idea on how to fix this issue.

**Comment by antoineco** [comment]
I just ran a build on Travis CI and the installation was successful: https://travis-ci.org/deviantony/docker-elk/builds/582730093

Could it be that you experienced a temporary issue?

**Comment by antoineco** [comment]
Maven has an artifact called `7.3.1-36.1.0-api`, not sure if the suffix was added or if it's a different artifact from the regular ES plugin.

We could also start downloading directly from releases.floragunn.com instead of Maven.

**Comment by Akayeshmantha** [comment]
Hi @antoineco any update on the issue.

**Comment by antoineco** [comment]
The `searchguard` branch is now functional again. Thanks for your patience, and sorry for the delay 🙌
