### ISSUE TITLE
ERROR: Service 'elasticsearch' failed to build

### ISSUE THREAD

**Issue by aidiss** [deviantony/docker-elk#436]
### Problem description

Canno docker-compose up: results in `ERROR: Service 'elasticsearch' failed to build: Please provide a source image with `from` prior to commit`

### Extra information

Did no changes to files after cloning repo.

#### Stack configuration

No changes

#### Docker setup

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false
```

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

#### Docker logs

```
Attaching to
```

**Comment by antoineco** [comment]
That version of Docker is about 3 years old and unsupported. Please update to a newer version.

The requirements are written right at the beginning of the README: https://github.com/deviantony/docker-elk/blob/master/README.md#requirements

**Comment by aidiss** [comment]
I tried upgrading docker with `yum upgrade` but it did not work.

Then I tried instructions given in https://stackoverflow.com/questions/26472586/upgrade-docker-on-centos-7 and now it works just fine, thank you!

**Comment by antoineco** [comment]
The EPEL version should be fairly recent yes. Alternatively, you could follow the instructions from the Docker docs, and use Docker's official YUM repo: https://docs.docker.com/install/linux/docker-ce/centos/
