### ISSUE TITLE
Logstash not working 

### ISSUE THREAD

**Issue by Alakazam03** [deviantony/docker-elk#437]
Hi, thanks for the package. I am trying to push data from docker container to elastic search using logstash. I have made a volume (apchelogs) and wants to push catalina logs to elastic search. Below is my conf file. But its not happenning. Do i need to attach file somewhere with logstash or anything else? 
```
input {
	file {
		path => "/apachelogs/localhost_access_log.*.txt"
	}
}

## Add your filters / logstash plugins configuration here
filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
	  geoip {
		source => "clientip"
	  }
    }

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
	}
	stdout { codec => rubydebug }
}

```

**Comment by antoineco** [comment]
Thanks for reporting this, but by skipping the information requested in the issue template you’re making it challenging to provide guidance.

- no logs: we don’t know if an error happened
- no config: we don’t know whether `/apachelogs` is mounted from the host, another container, or not mounted at all

I will close this issue for now and encourage you to ping us again once the issue template has been filled. Thank you for your understanding.
