### ISSUE TITLE
Logs not coming into elastic search

### ISSUE THREAD

**Issue by Alakazam03** [deviantony/docker-elk#438]
### Problem description
I have cloned the repo and have added my image to docker-compose.yml. Its been working fine.
![image](https://user-images.githubusercontent.com/23367724/66718802-b9257e00-ee05-11e9-8e69-02e83585e4a9.png)

I want to send logs from docker-app container to ELK. I have made a volume as can be seen above. I am able to get Catalina logs out to my host machine. I made changes to logstash.conf and build and ran the container. I am getting the logs onto the host machine but not been able to send my logs to elastic search.
![image](https://user-images.githubusercontent.com/23367724/66718826-fe49b000-ee05-11e9-9711-ea9c8efa836c.png)

sorry for the newbie question.

![image](https://user-images.githubusercontent.com/23367724/66718865-48cb2c80-ee06-11e9-81ee-67009b865afe.png)

**Comment by antoineco** [comment]
Thanks for filling the requested info! Now the problem is clear to me.

Your Apache logs directory is mounted in your app’s container, but it must also be mounted in the Logstash container (read-only is sufficient). Containers run with an isolated filesystem, so the `/apachelogs` directory does not exist from Logstash’s perspective.

**Comment by Alakazam03** [comment]
I updated my files to this. Still no luck. Thanks for telling about the fault.
![image](https://user-images.githubusercontent.com/23367724/66720070-956a3400-ee15-11e9-9781-119b7d9de4a9.png)

![image](https://user-images.githubusercontent.com/23367724/66720121-5c7e8f00-ee16-11e9-8ec5-16c38ee313a7.png)

**Comment by antoineco** [comment]
The mount looks good to me.

What does this command return?
```
docker-compose exec logstash ls -l logs
```

**Comment by Alakazam03** [comment]
`alakazam@vaibhavs-MacBook-Air docker-elk $ docker-compose exec logstash ls -l logs
total 132
-rw-r----- 1 logstash logstash 49720 Oct 13 18:54 catalina.2019-10-13.log
-rw-r----- 1 logstash logstash  8286 Oct 14 03:48 catalina.2019-10-14.log
-rw-r----- 1 logstash logstash 59210 Oct 14 03:48 catalina.out
-rw-r----- 1 logstash logstash     0 Oct 13 18:21 host-manager.2019-10-13.log
-rw-r----- 1 logstash logstash     0 Oct 14 03:47 host-manager.2019-10-14.log
-rw-r----- 1 logstash logstash  2754 Oct 13 18:54 localhost.2019-10-13.log
-rw-r----- 1 logstash logstash   458 Oct 14 03:48 localhost.2019-10-14.log
-rw-r----- 1 logstash logstash     0 Oct 13 18:21 localhost_access_log.2019-10-13.txt
-rw-r----- 1 logstash logstash     0 Oct 14 03:47 localhost_access_log.2019-10-14.txt
-rw-r----- 1 logstash logstash     0 Oct 13 18:21 manager.2019-10-13.log
-rw-r----- 1 logstash logstash     0 Oct 14 03:47 manager.2019-10-14.log
`

**Comment by Alakazam03** [comment]
Thanks for the immediate help. I figured i forgot to put username and password. Its working great now. I will close the issue
