### ISSUE TITLE
Problem about bin/init_sg.sh to deploy search-guard

### ISSUE THREAD

**Issue by DenizParlak** [deviantony/docker-elk#439]
Hi,

Even I tried 'docker-compose build', it's still same.

docker-compose exec -T elasticsearch bin/init_sg.sh

root@elk3:~/docker-elk# docker-compose exec -T elasticsearch bin/init_sg.sh
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"bin/init_sg.sh\": stat bin/init_sg.sh: no such file or directory": unknown

**Comment by antoineco** [comment]
Could you please share the output of `git branch`?

**Comment by antoineco** [comment]
You're on the wrong branch, please
1. switch branch
2. build images
3. retry

**Comment by antoineco** [comment]
OK, making progress :) Looks like @floragunncom changed the directory structure of the releases mirror. Meanwhile Search Guard artifacts are back on Maven, so I'll revert the previous commit, which should fix the issue.

**Comment by antoineco** [comment]
@DenizParlak the fix is on the branch now. Could you please pull changes and give it another try?

**Comment by antoineco** [comment]
Considering the issue as solved, feel free to reopen if not.
