### ISSUE TITLE
Problem when "installing" the second time around

### ISSUE THREAD

**Issue by TooDizzy** [deviantony/docker-elk#44]
Hi,

I seem to have a problem with the compose build. It all worked fine for me the first time around, but after I started over (removed the git repo and deleted all old images) the `docker-compose up` fails.

The error message: 
> Service ‘kibana’ needs to be built, but –no-build was passed

Maybe it's a local thing?

I'm running docker 1.8.3 on CoreOS.

**Comment by deviantony** [comment]
Did you try to rebuild the images before running the stack?

```bash
$ docker-compose build
```

**Comment by TooDizzy** [comment]
I tried to manually build the failing Kibana image, but that didn't help much.
After running the `docker-compose build` command everything seems to be working just fine again.

Thanks!
