### ISSUE TITLE
Upgrade to compose file format version 2

### ISSUE THREAD

**Issue by deviantony** [deviantony/docker-elk#45]
There is a new version of the compose file format, the current will be deprecated in the future.

The new file fomat version requires the following:

* Docker engine 1.10.x+
* Compose 1.6.x+

See: https://docs.docker.com/compose/compose-file/#versioning

The format will not be updated at the moment, as I'm not sure about the tooling versions of the user base.

**Comment by MBuffenoir** [comment]
Hey, maybe this can help: I have a v2 version here: https://github.com/skippbox/docker-on-cluster-howtos/blob/master/swarm/apps/elk/docker-compose.yml compatible with swarm (i.e no links)

**Comment by deviantony** [comment]
Sweet, thanks ! I'll have a look at it when the time will come to upgrade to the new version of the compose format.

**Comment by mamoit** [comment]
:+1:

**Comment by deviantony** [comment]
Thanks for the PR @mamoit ! :+1: 

Has I said before, I'm not sure when I should update the compose file to the new format.

**Comment by mamoit** [comment]
No need to accept it just for the sake of the upgrade (no need to accept at all for that matter).
I converted the docker-compose file just to explore elk, so I decided to share what I did.

**Comment by HackerWilson** [comment]
Hey, guys. i wrote the v2 version there: https://github.com/HackerWilson/docker-elk-deployment

with redis broker and logstash shipper support.

i am not sure that if i change the readme to english, then can it be your version2?

**Comment by deviantony** [comment]
@HackerWilson I'd rather not change the structure of the project by keeping the actual number of components (so no redis/logstash shipper).

Anybody know what upgrading to the new format could bring to this project (beside solving a future deprecation)?

**Comment by mamoit** [comment]
Does the old format support network overlays in a swarm cluster?
I think the main bonuses would be facing towards swarm support and integration.
But again, I'm still exploring, so I can't say I'm sure about anything right now.

**Comment by HackerWilson** [comment]
@deviantony I am new to elk, and I was wondering that how many logs can elk deal with when deployed without redis/logstash shipper support?

**Comment by deviantony** [comment]
@mamoit Never played with swarm, I got to check it though.

@HackerWilson Well I did use a production setup with a multi node Elasticsearch cluster and 1 logstash indexer node, it was able to deal with 30M events/day.

**Comment by HackerWilson** [comment]
@deviantony hmn, good.

**Comment by MBuffenoir** [comment]
Hi,

@deviantony  I've a got a v2 version with the addition of a authenticating reverse proxy (+ ssl support), it can be necessary in an  internet facing set up, as kibana is really unsecure.

It's there: https://github.com/MBuffenoir/elk

Hope it can help

**Comment by deviantony** [comment]
As stated in #54, I'll switch to v2 format when x-pack will be released. The master branch will then point to an ELK 5 x-pack setup in Docker Compose V2 format.

**Comment by deviantony** [comment]
All the branches are now using the compose v2 format !
