### ISSUE TITLE
elasticsearch data persistence in swarm mode

### ISSUE THREAD

**Issue by eoli3n** [deviantony/docker-elk#451]
Hi,
No volume is set in ``docker-stack.yml``.

Should we use a shared volume ?
As -> [https://sysadmins.co.za/docker-swarm-persistent-storage-with-nfs/](https://sysadmins.co.za/docker-swarm-persistent-storage-with-nfs/)

Or as Kibana is aware of every elasticsearch nodes, it can aggregate datas ?

If it does, why ``docker-stack.yml`` does not declare defaultly local storages ?
As -> [https://github.com/jakubhajek/elasticsearch-docker-swarm/blob/master/stack-elastic.yml](https://github.com/jakubhajek/elasticsearch-docker-swarm/blob/master/stack-elastic.yml)

Is this possible to add relative documentation in your wiki ?
[https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster](https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster)

**Comment by eoli3n** [comment]
For information : [https://stackoverflow.com/questions/47756029/how-does-docker-swarm-implement-volume-sharing](https://stackoverflow.com/questions/47756029/how-does-docker-swarm-implement-volume-sharing)

**Comment by antoineco** [comment]
The short answer is that it's quite difficult to deploy stateful applications on Swarm without making assumptions about the underlying infrastructure. In the example you shared, each Elasticsearch instance is pinned to a specific Swarm node, which facilitates the usage of local storage. Each Elasticsearch node is also defined explicitly inside the stack definition (master-1, master-2,...). In our repo, we don't know anything about the user's cluster, or how many Elasticsearch instances the user wants to deploy.

Keep in mind that the main purpose of this repository is to provide an Elastic stack that is easy to run on a developer's machine. The Swarm file serves the same purpose.

**Comment by eoli3n** [comment]
Ok, thanks. Maybe just adding a little word on that in the wiki section could be useful.

**Comment by eoli3n** [comment]
I used [https://github.com/gluster/gluster-ansible](https://github.com/gluster/gluster-ansible)
Which made really simple glusterfs setup.
