### ISSUE TITLE
Discovery not working in swarm when fresh install of 19.03.5

### ISSUE THREAD

**Issue by eoli3n** [deviantony/docker-elk#455]
### Problem description

Configuring elasticsearch in swarm mode as wiki says results in discovery issue when installing docker 19.03.5 on Debian Buster from scratch.

Installing 19.03.3 and run stack works
Then upgrade to 19.03.5, works too.

(did it 10 times)

### Extra information

```
# Install docker
apt update && apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
```

#### 19.03.5 
```
apt update && apt-get install docker-ce docker-ce-cli containerd.io -y
```

#### 19.03.3
```
apt update && apt-get install docker-ce=5:19.03.3~3-0~debian-buster docker-ce-cli=5:19.03.3~3-0~debian-buster containerd.io -y
```
```
# Swarm init
docker swarm init

# Sysctl config
sysctl vm.max_map_count=262144

# Project clone and run stack
git clone https://github.com/eoli3n/docker-elk
cd docker-elk
docker stack deploy -c docker-stack.yml elk
docker service logs elk_elasticsearch -f
```

#### Stack configuration

Here diff i applied to configure docker-elk
[https://github.com/deviantony/docker-elk/compare/master...eoli3n:master](https://github.com/deviantony/docker-elk/compare/master...eoli3n:master)

##### 19.03.5 fresh
[docker service logs elk_elasticsearch](http://ix.io/23E5)

##### 19.03.3 fresh
[docker service logs elk_elasticsearch](http://ix.io/23Ee)
[curl -D- 'http://127.0.0.1:30000/_cluster/health?pretty' -u elastic:changeme](http://ix.io/23Ef)

**Comment by antoineco** [comment]
For some reason you have that weird behavior where nodes discover themselves on the 10.0.0.0/24 network where the DNS resolves to 10.0.1.0/24, but I'm honestly not able to explain it. I doubt it's related to docker-elk specifically.

> {**10.0.0.8:9300**}{dilm}{ml.machine_memory=4092379136, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [**10.0.1.8:9300, 10.0.1.9:9300, 10.0.1.10:9300**

**Comment by antoineco** [comment]
I'd be curious to know what network interfaces and IPs are assigned to your containers.

`network.host` is set to `0.0.0.0` by default (ES config file) which could be problematic if you have multiple interfaces, because the value of `network.publish_host` would become unpredictable.

> 0.0.0.0 is an acceptable IP address and will bind to all network interfaces.

> Currently an Elasticsearch node may be bound to multiple addresses, but only publishes one. If not specified, **this defaults to the “best” address from network.host**, sorted by IPv4/IPv6 stack preference, then by reachability.
> -- https://www.elastic.co/guide/en/elasticsearch/reference/7.4/modules-network.html#advanced-network-settings

You could try replacing `0.0.0.0` with the name of the desired container's network interface surrounded by underscores (e.g. `_en0_`) or the special value `_site_`. Both are highly depend on your setup.

**Comment by eoli3n** [comment]
### Working 10.03.3 fresh
```
            "VirtualIPs": [
                {
                    "NetworkID": "oo3pv7lkhhp1yo5mlm6upenvo",
                    "Addr": "10.255.0.7/16"
                },
                {
                    "NetworkID": "vve4g261t45kbgyk0g2dyo7xp",
                    "Addr": "10.0.0.7/24"
                }
```
### Working 10.03.4 fresh
```
            "VirtualIPs": [
                {
                    "NetworkID": "dp9u9by3ctpjrpk7zmbqvruu1",
                    "Addr": "10.255.0.5/16"
                },
                {
                    "NetworkID": "ebgjsrm2h1zcn0rylyo368l8w",
                    "Addr": "10.0.0.5/24"
                }
```
### Failing 10.03.5 fresh
```
            "VirtualIPs": [
                {
                    "NetworkID": "u7nnn0c7jx3z56x47yu22pzxp",
                    "Addr": "10.0.0.5/24"
                },
                {
                    "NetworkID": "m9t8nwsuewqj91uw73h3rt7xc",
                    "Addr": "10.0.1.5/24"
                }
```
### Working 10.03.5 upgraded from 10.03.3
```
            "VirtualIPs": [
                {
                    "NetworkID": "oo3pv7lkhhp1yo5mlm6upenvo",
                    "Addr": "10.255.0.5/16"
                },
                {
                    "NetworkID": "13gy8ur7tpa4jn0216dc0mdlo",
                    "Addr": "10.0.0.5/24"
                }
```

This is network related.
Nothing suspicious in [10.03.5 changelog](https://github.com/docker/docker-ce/releases)

**Comment by antoineco** [comment]
Aha, nice catch!

In the working scenarios, the two networks are `10.255.0.0/16` (bridge) and `10.0.0.0/24` (overlay). Elasticsearch seems to automatically pick up the first IP by lexical comparison, which is the 10.0.0.X address.

In the non-working scenario, the networks are 10.0.0.0/24` (bridge) and `10.0.1.0/24` (overlay), and the selected address is also 10.0.0.X, except that address in not in the overlay.

**Comment by eoli3n** [comment]
Yes :)
I tried ``_site_`` (quoted or not), didn't do the trick.
I'm trying with interface name fix, but it would be better to find a less specific way.

**Comment by antoineco** [comment]
Maybe it's possible to prevent containers from joining the bridge, and only be added to the overlay.

**Comment by antoineco** [comment]
I think we can close this as a "Docker related behavior"?

**Comment by eoli3n** [comment]
Yes, thanks again for helping. If i find how to fix this, i will comment.

**Comment by eoli3n** [comment]
``10.0.0.0/24`` is the  [ ingress overlay network](https://docs.docker.com/network/overlay/) which manage [mesh routing](https://docs.docker.com/engine/swarm/ingress/)
The new ``10.0.4.0/24`` is the default overlay for swarm containers, before it was ``10.255.0.0/16``.
Using ``network.host: "_eth0_"`` makes discover work again.
Problem is that, as i force ES to listen only on eth0, it doesn't listen on query from ingress network.

```
root@tspeda-swarm-manager1:~# docker exec elk_elasticsearch.1.r4mrkbgbmaytjvc8w433iy205 busybox ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:0A:00:01:03  
          inet addr:10.0.1.3  Bcast:10.0.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:4038 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3902 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3486065 (3.3 MiB)  TX bytes:3880957 (3.7 MiB)

eth1      Link encap:Ethernet  HWaddr 02:42:0A:00:00:04  
          inet addr:10.0.0.4  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:316 (316.0 B)  TX bytes:192 (192.0 B)
.......
root@tspeda-swarm-manager1:~# curl -D- 'http://127.0.0.1:30000/_cluster/health?pretty' -u elastic:changeme
curl: (7) Failed to connect to 127.0.0.1 port 30000: Connexion refusée
```
I think that when i use ``127.0.0.1`` query it uses ``10.0.0.0/24`` to route the query.

**Comment by eoli3n** [comment]
I specified a list as described [here](https://stackoverflow.com/a/52362882/11061370)
I was expected ES to keep the order. But it choose again the wrong network for discovering.
```
network.host: [ _eth0_ , _eth1_, _lo_ ]
```
I open a elasticsearch issue.

**Comment by eoli3n** [comment]
Here's the workaround
Just after initializing the swarm
```
docker network rm ingress
docker network create --driver overlay --ingress --subnet=10.255.0.0/16 ingress
```

**Comment by antoineco** [comment]
Thanks for sharing!

**Comment by eoli3n** [comment]
Just realized differences between ``network.host`` and ``network.publish_host``
I will try tommorow to set ``network.publish_host: _eth0_`` on a fresh 10.03.5 without recreating ingress overlay network

**Comment by eoli3n** [comment]
Changing to ``network.publish_host: _eth0_`` is a better working fix than recreate ingress network.

**Comment by ayay129** [comment]
牛逼，I just follow your conversation, then solved this problem, thanks for sharing!

**Comment by hustlibraco** [comment]
> 牛逼，I just follow your conversation, then solved this problem, thanks for sharing!

牛逼. Well done.

**Comment by antoineco** [comment]
I just ran into this myself today, months after this was reported.

After setting `network.publish_host: _eth0_` to force publishing on the `elk` overlay (not the `ingress` overlay), the issue seems to be gone for me.

I'm assuming the order of network interfaces to be stable, but I'm not sure whether this is documented. The order does _not_ seem to match the output of `docker service inspect elk_elasticsearch --format '{{ .Endpoint.VirtualIPs }}'`:

**service inspect** (10.0.0.0/24 comes first)
```json
 [
  {
    "NetworkID": "51fzebsryvrwxl0p1a2g37n08",
    "Addr": "10.0.0.7/24"
  },
  {
    "NetworkID": "kjnn48rny0wy3z5zdfvn4a19n",
    "Addr": "10.0.1.7/24"
  }
]
```

**ifconfig** (10.0.1.0/24 comes first)
```
eth0      Link encap:Ethernet  HWaddr 02:42:0A:00:01:08  
          inet addr:10.0.1.8  Bcast:10.0.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth1      Link encap:Ethernet  HWaddr 02:42:0A:00:00:08  
          inet addr:10.0.0.8  Bcast:10.0.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:11 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:834 (834.0 B)  TX bytes:1146 (1.1 KiB)

eth2      Link encap:Ethernet  HWaddr 02:42:AC:12:00:03  
          inet addr:172.18.0.3  Bcast:172.18.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:698 (698.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
