### ISSUE TITLE
How to receive syslog from logstash

### ISSUE THREAD

**Issue by Howard0529** [deviantony/docker-elk#458]
**Problem description**
How can I receive syslog from logstash?I have mapping port 5000 from linux vm to logstash  in 
/docker-elk-master/docker-compose.yml

>logstash:
>  build:
>      context: logstash/
>    args:
>        ELK_VERSION: $ELK_VERSION
>    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
      - "514:514"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - 

elasticsearch

And I issue the logstash.conf in "docker-elk-master/logstash/pipeline"
>input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}

>filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

>output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => ["logstash"]
    user => elastic
    password => changeme
 }

>  stdout { codec => rubydebug }
}

But I can not find the syslog in Kibana, is there any setting missing?  Thanks for the help.

**Comment by antoineco** [comment]
Could you please share your logs as requested in the issue template?

**Comment by Howard0529** [comment]
Hi 
I have change the logstash.conf in "docker-elk-master/logstash/pipeline", but I still receive syslog,
Is there anything else to check?Thanks for the help.

>input {
    syslog {
        port => 514
    }
}

>filter {           
   grok { 
                  match => [
                  "message", "%{SYSLOG5424PRI}date=20%{DATE} time=%{TIME:time} devname=%{HOSTNAME:devName} devid=%{HOSTNAME:devId} logid=%{NUMBER:logId} type=%{WORD:logType} subtype=%{WORD:logSubType} level=%{WORD:level} vd=%{DATA:virtualDomain} srcip=%{IP:srcIP} srcport=%{NUMBER:srcPort} srcintf=%{DATA:srcInterface} dstip=%{IP:dstIP} dstport=%{NUMBER:dstPort} dstintf=%{DATA:dstInterface} poluuid=%{DATA:poluuid} sessionid=%{NUMBER:sessionid} proto=%{INT:protocol}
action=%{WORD:action} policyid=%{INT:policyId} policytype=%{WORD:policytype} dstcountry=%{QS:dstcountry} srccountry=%{QS:dstcountry} trandisp=%{WORD:trandisp} transip=%{IP:transip} transport=%{NUMBER:transport} service=%{QS:service} appcat=%{QS:appcat} applist=%{QS:applist} duration=%{NUMBER:duration} sentbyte=%{NUMBER:entbyte} rcvdbyte=%{NUMBER:rcvdbyte} sentpkt=%{NUMBER:sentpkt} rcvdpkt=%{NUMBER:rcvdpkt} wanin=%{NUMBER:wanin} wanout=%{NUMBER:wanout} lanin=%{NUMBER:lanin} lanout=%{NUMBER:lanout}"
                           ]
                }
        } 

>output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "xxx"
		password => "xxx"
	}
}

"Docker ps" Command response as below, the port mapping is normal.
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                                                                                          NAMES
8b6abdedb837        docker-elk-master_logstash        "/usr/local/bin/dock…"   33 minutes ago      Up 33 minutes       0.0.0.0:514->514/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:9600->9600/tcp, 0.0.0.0:5000->5000/udp, 5044/tcp   docker-elk-master_logstash_1
0e1ccc8760bc        docker-elk-master_kibana          "/usr/local/bin/dumb…"   33 minutes ago      Up 33 minutes       0.0.0.0:5601->5601/tcp                                                                                                         docker-elk-master_kibana_1
381dbb65762e        docker-elk-master_elasticsearch   "/usr/local/bin/dock…"   33 minutes ago      Up 33 minutes       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp                                                                                 docker-elk-master_elasticsearch_1
0f72c59384a6        portainer/portainer               "/portainer"             6 days ago          Up 6 days           0.0.0.0:9000->9000/tcp             

"netstat -a" Command response is open syslog and tcpdump check the server have receive syslog, but the kibana can not find log.

**Comment by antoineco** [comment]
Did you configure your `rsyslog` service to _send_ logs to Logstash?

Logstash doesn't fetch logs for you, you must send it something.

**Comment by an-t-oine** [comment]
i think i have the same issue.
In your docker-compose.yml file, i see that you expose port 514 which is under 1024. So you probably have a permission issue. You can confirm that by display logs:
`$ docker container logs -f docker-elk_logstash_1`
`Errno::EACCES: Permission denied - bind(2) for "0.0.0.0" port 514`

As i can't modify my syslog port from client, i don't know how to fix this issue.
Any help is welcome.
regards.

**Comment by antoineco** [comment]
@an-t-oine for this you have to run with `user: root` or set the extra `CAP_NET_BIND_SERVICE` capability on the `java` executable ([more details on StackOverflow](https://stackoverflow.com/a/414258/4716370).

@Howard0529 I will close this issue unless you are able to provide all the information that was requested in the issue template (logs especially) and answer my question regarding the configuration of your syslog service.

**Comment by an-t-oine** [comment]
thanks for the reply,
but i don't know where to put the "user: root" setting.


Le lun. 30 déc. 2019 à 09:17, Antoine Cotten <notifications@github.com> a
écrit :

**Comment by antoineco** [comment]
@an-t-oine [check this out](https://stackoverflow.com/a/48730146/4716370).

**Comment by an-t-oine** [comment]
thanks for the tips. It works.

**Comment by antoineco** [comment]
User didn't share log. Closing
