### ISSUE TITLE
Adding instructions in Read Me how the tcp command for logstash work and display the same in the Kibana UI for log trace

### ISSUE THREAD

**Issue by RajezMariner** [deviantony/docker-elk#464]
Hi, 

Could you please add the instructions to setup the index pattern creation in Kibana. I tried executing the project but I am not able to find the instructions how TCP command for port actually send the data to elastic search and displays it as part of the Kibana UI.

My use case is read the file from s3 bucket and would like to index the same in Kibana UI. Before that I would like to do with sample examples.

Kindly help me with that.

Thanks,
Rajesh

**Comment by antoineco** [comment]
Hi @RajezMariner, the README mention these two steps are required:

1. [Inject some data over TCP](https://github.com/deviantony/docker-elk#injecting-data)

The suggested approach is simply to use the `nc` command (short for "netcat") to send data to Logstash (port 5000). This tool should come pre-installed on most Unix operating systems (MacOS, Linux distributions, BSD).

You can replace the example file `/path/to/logfile.log` with any real log file. Those are usually stored inside the `/var/log` directory, for example `/var/log/syslog`.

If all you want to do is test whether Logstash can process incoming data and forward it to Elasticsearch, you can also send a random string to Logstash (TCP port 5000):
```console
$ echo 'test' | nc localhost 5000
```

2. [Create an index pattern](https://github.com/deviantony/docker-elk#default-kibana-index-pattern-creation)

If the data you sent above was successfully received by Elasticsearch, Kibana should prompt you to create an [_Index pattern_](https://www.elastic.co/guide/en/kibana/current/connect-to-elasticsearch.html) after you click "Explore" (first icon in the left menu bar). Logstash indices have the format `logstash-2020-01-22` by default, so you can enter `logstash-*` as you index pattern to match anything that starts with "logstash-".

---

After following those instructions, is there anything that still feels unclear or does not work in your environment?

**Comment by RajezMariner** [comment]
Hey @antoineco Thanks for the solution. 

I am currently going with new approach, reading logs from AWS cloudwatch logs. Cloud watch logs are read fine. But I am not sure if the output is reaching elastic search or incorrect configuration in Kibana as well?

When I tried stdout in logstash, I could see the logs. But in Kibana I am not able to see the same. I would like to know how to verify the index is configured correctly between Kibana and Elastic search?

**Comment by antoineco** [comment]
@RajezMariner first of all I'd check whether any indice was created in Elasticsearch. You can do this from Kibana's dev console at http://localhost:5601/app/kibana#/dev_tools/console (replace localhost with your own host name).

Please send the following request and post the results:
```
GET /_cat/indices
```

**Comment by RajezMariner** [comment]
@antoineco Thanks. It helps.
