### ISSUE TITLE
can't restore initial setup status.

### ISSUE THREAD

**Issue by harryhan24** [deviantony/docker-elk#466]
### Problem description
i cant restore initial state which password is "changeme"

#### Docker setup
Pure Setting on latest mac os version
Docker Desktop Version 2.2.0.3
#### Docker Logs
```
 {"type":"log","@timestamp":"2020-02-14T22:27:45Z","tags":["warning","plugins","licensing"],"pid":7,"message":"License information could not be obtained from Elasticsearch for the [data] cluster. [security_exception] failed to authenticate user [elastic], with { header={ WWW-Authenticate=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } :: {\"path\":\"/_xpack\",\"statusCode\":401,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [elastic]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [elastic]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\",\"wwwAuthenticateDirective\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}"}
```

#### Details
the repo provide very simple and easy way run elastic search from scratch. so i tested some feature but after i excute " docker-compose exec -T elasticsearch bin/elasticsearch-setup-passwords auto --batch" command, i never restore initial state which password is "changeme". i am planning to education presentation with the stack, i need to go back initial state.

#### What i do
```
docker rm $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker-compose up --build
docker system prune --all,
rm -rf ./docker-elk
+ inspecting docker-compose.yml
+ read Documents.
+ delete all temporary, buffer files
+ delete kubernetes, k3s
```

everything is not work at this moment. after i reinstall docker and clean buffer files even
`/Library/Containers/com.docker.docker/Data/vms/0/data` which docker image location in my mac
then i cloned this repo then excuted docker-compose up --build. even so still password is not "changeme"  but auto-generated password with `docker-compose exec`

 i cant find location elastic-search reference disk space.. when i check docker-compose.yml file's volume point out just in docker-elk directory and docker is just inside container.

**Comment by antoineco** [comment]
@harryhan24 "changeme" is the *default* password. As soon as you execute `elasticsearch-setup-passwords`, that password is replaced by another random password. This is clearly explained in the README.

**Comment by harryhan24** [comment]
yes right i know but is there anyway go back excute `elasticsearch-setup-passwords` even if i download fresh image and rebuild?

**Comment by antoineco** [comment]
The images do _not_ contain any password, so downloading/building images is not necessary. If you want to reset your data completely, you only need to run `docker compose down -v`.

The initial password is set inside the compose file (`ELASTIC_PASSWORD: changeme`). After running `elasticsearch-setup-passwords`, you can not come back to the bootstrap password unless you reset your data with `docker compose down -v`.

You can find more details about Elasticsearch's security at https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html#bootstrap-elastic-passwords

**Comment by harryhan24** [comment]
if you say so, it must be my fault. thx for answering.
