### ISSUE TITLE
Add historical version branches of ELK

### ISSUE THREAD

**Issue by m2kar** [deviantony/docker-elk#467]
### Problem description
In some cases, developers especially new starter need to use a historical version of ELK for testing and learning. As can be found in issues, there are some historical issues and pull requests about versions upgrade. 

Could you please open some branches or set some tags for historical versions. Especially for 6.x and 5.x. 

#### some history issue about version upgrade
1. https://github.com/deviantony/docker-elk/pull/382
2. https://github.com/deviantony/docker-elk/pull/362
3. https://github.com/deviantony/docker-elk/pull/339
4. https://github.com/deviantony/docker-elk/pull/290
5. https://github.com/deviantony/docker-elk/pull/286

**Comment by antoineco** [comment]
Maintaining one branch per _major_ version shouldn't be an issue, since those do not get updated that often. E.g. `release-5.x`, `release-6.x` and later `release-7.x` once 8.x makes it to `master`.

For a more granular version selection, users can use the `.env` file after switching to the desired release branch.

Would that work @m2kar?

**Comment by antoineco** [comment]
@deviantony I'll take that thumb up as an endorsement and send 2 PRs your way so we can discuss over there 🙂

**Comment by deviantony** [comment]
Will review these 2 PRs this week-end !

**Comment by deviantony** [comment]
So I was looking at these 2 relateds PRs... The 5-x version is not working and while I was troubleshooting the configuration I stumbled upon the Elastic EOL policy.

While I agreed to have major release branch versions in this project, I wonder if we need to support all the major ones? I don't see the point of maintaining/creating a branch for a software stack that is declared EOL.

https://www.elastic.co/support/eol

Thoughts @antoineco @m2kar ?

**Comment by antoineco** [comment]
I agree that EOL versions are quite a gray area. What I can understand, however, is that there are still more than one ES5 instances in the wild, and that developers/operators may appreciate using this stack as a quick go-to.

To keep everyone happy, I can suggest we add a warning at the top of the 5.x README mentioning the branch will only exist until the release of 8.x. What do you think?

@m2kar do you personally use 5.x?

**Comment by deviantony** [comment]
My thoughts are: we should not bother with 5.x. 

After all, this project is supposed to help you get started with the Elastic stack, I don't believe there are that many users out there using EOL versions of the stack. 

And in that case, if they want to use 5.x or any other EOL version, they'll have to support by configuring the repo themselves.

@m2kar I'm quite interested about that feedback around 5.x too.

> developers especially new starter need to use a historical version of ELK for testing and learning.

Can you share more details with us?

**Comment by m2kar** [comment]
> My thoughts are: we should not bother with 5.x.
> 
> After all, this project is supposed to help you get started with the Elastic stack, I don't believe there are that many users out there using EOL versions of the stack.
> 
> And in that case, if they want to use 5.x or any other EOL version, they'll have to support by configuring the repo themselves.
> 
> @m2kar I'm quite interested about that feedback around 5.x too.
> 
> > developers especially new starter need to use a historical version of ELK for testing and learning.
> 
> Can you share more details with us?

I prefer to use the version 5.x because learning materials translated to Chinese are quite a little.
Many learning materials use the 5.x or even 2.x ElasticSearch. But as we all know, API from 5.x to 7.x changed a lot. So as a beginner, many people want to use version 5.x for learning. This is the demand of many Chinese people.

Thank you a lot for working on this great project, it really helps me a lot.

**Comment by deviantony** [comment]
I'm ok to go for one round of old release branch creation and as such I'll review #468 and try to make it work. But IMO we should add a notice to each of these branches where the version that is used is currently defined as EOL by Elastic.

You should not try to learn how to use a tool using a deprecated/unsupported version of the tool in my opinion but I can understand the issue with the learning materials.

**Comment by m2kar** [comment]
Thanks for your comprehension. Different Language is a big gap in learning new things. I usually learn a new tool with Chinese materials, even it used the old version tool. After I learned it, I will choose the currently newest version or stable version for development.

**Comment by deviantony** [comment]
Release 6.x and 5.x are now supported via branches. This is documented in the README, have a look at it @m2kar

**Comment by m2kar** [comment]
> Release 6.x and 5.x are now supported via branches. This is documented in the README, have a look at it @m2kar

OK, thanks for your contributions. I will try it.
