### ISSUE TITLE
ERROR: could not find plugin bridge in v1 plugin registry: plugin not found

### ISSUE THREAD

**Issue by mikenlanggio** [deviantony/docker-elk#472]
I use Docker Windows.
When I run "docker-compose up"
It throw message:

> ERROR: could not find plugin bridge in v1 plugin registry: plugin not found.

Full message:

> Creating network "docker-elk-master_elk" with driver "bridge"
> ERROR: could not find plugin bridge in v1 plugin registry: plugin not found

What's wrong?

**Comment by antoineco** [comment]
@mikenlanggio this happens because your Docker daemon is configured to use the "Windows Container Mode". The ELK stack runs on _Linux_ containers (Docker's default mode). Please check your settings.

**Comment by antoineco** [comment]
@mikenlanggio did this solve your problem?
