### ISSUE TITLE
docker-elk_logstash_1 exited with code 0

### ISSUE THREAD

**Issue by inandi** [deviantony/docker-elk#475]
logstash is getting shut down when I try to get logs from file 

```
logstash_1       | [2020-03-22T19:37:14,865][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elastic:xxxxxx@elasticsearch:9200/]}}
logstash_1       | [2020-03-22T19:37:14,927][WARN ][logstash.outputs.elasticsearch][.monitoring-logstash] Restored connection to ES instance {:url=>"http://elastic:xxxxxx@elasticsearch:9200/"}
logstash_1       | [2020-03-22T19:37:14,946][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] ES Output version determined {:es_version=>7}
logstash_1       | [2020-03-22T19:37:14,947][WARN ][logstash.outputs.elasticsearch][.monitoring-logstash] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
logstash_1       | [2020-03-22T19:37:15,040][INFO ][logstash.outputs.elasticsearch][.monitoring-logstash] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://elasticsearch:9200"]}
logstash_1       | [2020-03-22T19:37:15,257][INFO ][logstash.javapipeline    ][.monitoring-logstash] Starting pipeline {:pipeline_id=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2, "pipeline.sources"=>["monitoring pipeline"], :thread=>"#<Thread:0x40222fdb run>"}
logstash_1       | [2020-03-22T19:37:16,654][INFO ][logstash.javapipeline    ][.monitoring-logstash] Pipeline started {"pipeline.id"=>".monitoring-logstash"}
logstash_1       | [2020-03-22T19:37:17,384][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
logstash_1       | [2020-03-22T19:37:17,944][INFO ][logstash.javapipeline    ] Pipeline terminated {"pipeline.id"=>".monitoring-logstash"}
logstash_1       | [2020-03-22T19:37:18,090][INFO ][logstash.runner          ] Logstash shut down.
docker-elk_logstash_1 exited with code 0

```

**Comment by antoineco** [comment]
@inandi The issue template is clear about the information we need to be able to help you. Please include all that information so we can at least know your configuration and reproduce the issue.
Thank you.

**Comment by inandi** [comment]
@antoineco thank u man for the early reply :) 

I have just cloned the repo and facing the issue. I have cleared all the other images to avoid any conflict.
![Screenshot (12)](https://user-images.githubusercontent.com/33930347/77260658-6e126f80-6caf-11ea-9138-3034f0c3d1ea.png)

please let me know how to debug this issue?

**Comment by inandi** [comment]
my main  intention is to write log from file to elastic.

logsatsh.conf:

```
input {
	file {
		path => "review_data.json"
		start_position => "beginning"
		sincedb_path => "/dev/null"
		codec => "json"        
	}
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
		index => "review_location_test"
	}
}

**Comment by chenyongze** [comment]
elasticsearch_1  | java.lang.IllegalStateException: cannot downgrade a node from version [7.6.1] to version [7.6.0]
elasticsearch_1  | 	at org.elasticsearch.env.NodeMetaData.upgradeToCurrentVersion(NodeMetaData.java:94)
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.loadNodeMetaData(NodeEnvironment.java:432)
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:329)
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:277)
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:257)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
elasticsearch_1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
elasticsearch_1  | For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
docker-elk_elasticsearch_1 exited with code 1

**Comment by antoineco** [comment]
@chenyongze please open a new issue.

**Comment by antoineco** [comment]
@inandi the file path indicated in your config must be relative to the `logstash` directory:
```
path => "pipeline/review_data.json"
```
Also you should reserve the `pipeline` directory for actual pipeline configurations.

**Comment by inandi** [comment]
@antoineco thanks for the reply. I followed your suggestion and moved my JSON file outside. And I checked the log, it was asking for an absolute path. so updated my conf and logstash is not shutting down now.

```file 
{
	path => "/e/work_station/docker-elk/logstash/review_data.json"
	start_position => "beginning"
	sincedb_path => "/dev/null"
	codec => "json" 
}
```

but still, it is not writing my logs. but that is a different issue I guess so I am closing this one.
