### ISSUE TITLE
ELK version issue

### ISSUE THREAD

**Issue by arcadas** [deviantony/docker-elk#476]
Hi!

I changed the ELK stack version to 7.3.2 in the  .env file, but the stack version will be 7.5.1.
Should I have to do any other things to can start an ELK stack with 7.3.2 version?

.env:
```sh
ELK_VERSION=7.3.2
```
http://localhost:9200/
```json
{
"name": "94a73f475815",
"cluster_name": "docker-cluster",
"cluster_uuid": "x7m_i2T9Qiab8F9YI6cg5w",
"version": {
"number": "7.5.1",
"build_flavor": "default",
"build_type": "docker",
"build_hash": "3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96",
"build_date": "2019-12-16T22:57:37.835892Z",
"build_snapshot": false,
"lucene_version": "8.3.0",
"minimum_wire_compatibility_version": "6.8.0",
"minimum_index_compatibility_version": "6.0.0-beta1"
},
"tagline": "You Know, for Search"
}
```
Docker version:
```sh
docker -v
Docker version 18.03.1-ce, build 9ee9f40
docker-compose -v
docker-compose version 1.21.0, build 5920eb08
```
OS: Windows 10 (Version 1709)

**Comment by antoineco** [comment]
Hi @arcadas, you may have overlooked the following warning:
> ⚠️ You must rebuild the stack images with docker-compose build whenever you switch branch or update the version of an already existing stack.

**Comment by arcadas** [comment]
Thank you very much! It works.
