### ISSUE TITLE
ERR: Kibana: Configure an index pattern

### ISSUE THREAD

**Issue by mcd-php** [deviantony/docker-elk#49]
Simply not working at all.

Am I supposed to take any extra steps, and if so, where is the documentation ?

```shell
#!/bin/sh
## sudo apt-get install git netcat
git clone https://github.com/deviantony/docker-elk.git
cd docker-elk
docker-compose up -d
dmesg | nc localhost 5000
```
Then in browser go to `http://localhost:5601/` and see the show-stopper.

**Comment by deviantony** [comment]
Simply just work. I've just tried it.

Now, this screen is normal, you need to configure an index pattern but if you've followed your step in this order and then, at the end, accessed `http://localhost:5601` then you would just have to click on the create button.

And the documentation for that part is here: https://www.elastic.co/guide/en/kibana/current/setup.html#connect

This project does not aim to teach you how to use the elastic stack, it aims to quickly setup one.

**Comment by sci-burns** [comment]
This threw me at first too - Kibana comes up, but I didn't have a create button.

You only get the create button once you have log data - the readme on project does mention writing log data, but I glossed over that.

Really like the project, thanks for sharing.

**Comment by deviantony** [comment]
I should probably add a note about that in the README.
