### ISSUE TITLE
Using Pull Dog for automatic test environments

### ISSUE THREAD

**Issue by ffMathy** [deviantony/docker-elk#490]
I recently launched a service that I believe could be helpful in this repository. It's free to use (from a demo-cluster pool of free servers), and I need feedback. I think it could really be a win-win for us both.

https://github.com/apps/pull-dog

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a `docker-compose.yml` file that you choose.

I think it could be helpful in general, to test things out in production before they are merged.

What do you think?

**Comment by antoineco** [comment]
The idea is interesting, but are you suggesting we use it for our acceptance tests as a replacement for Travis CI?

**Comment by ffMathy** [comment]
Thank you for your interest! :bow:

No, not at all. The CI environment's job checks that the code is correct and that it doesn't break anything with tests etc.

My tool is helpful for that too, but its primary purpose in this scenario would most likely be to see if someone's feature actually works, or if it is satisfying enough, without having to pull the code locally and test it on the same machine.

**Comment by antoineco** [comment]
Assuming that this person's project leverages Elasticsearch you mean? In that case, how would you envision that integration? Out of the box our stack requires a few Dockerfiles and other local files to start.

**Comment by ffMathy** [comment]
The file here already describes it all, I assume?
https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml

All you would need to do to enable it (after installing the app), is put a `pull-dog.json` file in your `master` branch, in the root project:

```json
{
  "dockerComposeYmlFilePaths": ["docker-compose.yml"]
}
```

And that's it!

But you are right - right now, it doesn't support fetching dependent files of the Docker Compose files (it wouldn't automatically download the environment files etc), but that is coming very soon.

It also doesn't support arguments like `$ELK_VERSION`, but that is also coming very soon.

I'll get back to you as soon as both of those things are ready - perhaps in a week or so.

And once again, thanks for your feedback so far! You're really helping to make this product more usable for others and helping me. I am also almost certain it could be useful to you.

By the way, here's a blog post of me using it in action, if you are curious:
https://medium.com/@mathiaslykkegaardlorenzen/pull-dog-docker-test-environments-for-pull-requests-21af71784bcc

**Comment by antoineco** [comment]
If not to us, it could be for projects who depend on us for their test pipelines indeed.

**Comment by deviantony** [comment]
@ffMathy interesting, dropped you an email.

**Comment by ffMathy** [comment]
And I replied now :+1:

**Comment by deviantony** [comment]
@ffMathy I don't believe it make sense for us to use pull-dog in the context of this repository. This repo revolves around providing a proper way to start the Elastic stack, as such it is OK to have an automated validation test for PR (our current travis build).

To be more precise, we don't need to actually login into Kibana to inspect if a change was correctly applied or to try and inject data into Elasticsearch as all these configurations are usually made on the user side (after cloning the repository).

I'll close this issue, I still think pull-dog is great though :)
