### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by stefnats** [deviantony/docker-elk#493]
Hi,

is it possible to enable letsencrypt for the elk stack / elastic stack. If so, how to?

**Comment by deviantony** [comment]
Hi @stefnats 

There is a discussion already opened in https://github.com/deviantony/docker-elk/issues/402 for documenting a TLS setup.

As it was written by Antoine in https://github.com/deviantony/docker-elk/issues/402#issuecomment-503315433, this is not something that will be easy to add but you can try to follow the official Elastic documentation about this: https://www.elastic.co/guide/en/elasticsearch/reference/7.1/configuring-tls.html

Closing this issue, feel free to continue the discussion in #402

**Comment by antoineco** [comment]
I'm the one to blame for letting that issue rot, I should have tackled that guide long ago. But like @deviantony said, Elastic's docs are really good, you should be able to enable TLS by following their guides, even when running the stack in Docker containers.

**Comment by stefnats** [comment]
Sorry, i didn't find that issue. Thanks for your help!
