### ISSUE TITLE
Mark docker-elk as a template repo?

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#496]
GitHub introduced template repositories last year to let users generate new repos from existing "templates". It's quite similar to forking, with a few minor differences:

> * A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
> * Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
> * A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

It might be a good fit fot `docker-elk`, since I believe the majority of users want to use the project as a starting point and then iterate from there without necessarily contributing their changes upstream. What are your thoughts @deviantony?

Refs:

* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

**Comment by deviantony** [comment]
Yeah, I wasn't aware of this. Even though I believe it's oriented towards boilerplate code (I think the main use case seems to be project template) I do agree with the following point:

>  I believe the majority of users want to use the project as a starting point and then iterate from there without necessarily contributing their changes upstream.

I'll update the repo.

**Comment by deviantony** [comment]
Done !

Good idea @antoineco

**Comment by antoineco** [comment]
Thanks! Not sure if anyone's gonna find that useful, but I immediately though about this repo while starting a toy project from a template the other day.

**Comment by deviantony** [comment]
Yeah agree but there is no actual impact of simply toggling the template mode so all good :)
