### ISSUE TITLE
Initialize passwords for built-in users Kibana down

### ISSUE THREAD

**Issue by Koploseus** [deviantony/docker-elk#497]
### Problem description

When i initialize passwords for built-in users, the kibana UI never start (always get Kibana server is not ready yet)
If i use the default password, everything is good (except if change all the passwords via the UI interface)
#### Docker setup

I just followed the readme

Docker version
``` docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by antoineco** [comment]
Did you replace the passwords in your config files and restart the stack?

**Comment by Koploseus** [comment]
@antoineco yes, like on the readme stuff !

**Comment by antoineco** [comment]
In this case I have really no idea. The issue description doesn't include any of the requested info so it will be difficult to reproduce and help you.

**Comment by Koploseus** [comment]
Well because i didn't change anything (a part the password stuff ofc)

I only clone the repo, launch the stuff , launch the command to generate password, replace it, restart kibana and logstash, and kaboom

**Comment by antoineco** [comment]
How does Kibana fail? "Server is not ready" indicates a problem in Elasticsearch, not Kibana, otherwise you'd see "permission denied". Logs would be useful, that's why we request them.

**Comment by Koploseus** [comment]
elasticsearch_1  | {"type": "server", "timestamp": "2020-05-18T09:01:44,407Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "f10401a58ad7", "message": "Authentication of [logstash_system] was terminated by realm [reserved] - failed to authenticate user [logstash_system]", "cluster.uuid": "QbHbJTJoTMOlQA0r9t1bfw", "node.id": "WEviQnWxR_OuPKT_jlr6gQ"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-05-18T09:01:44,539Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "f10401a58ad7", "message": "Authentication of [kibana] was terminated by realm [reserved] - failed to authenticate user [kibana]", "cluster.uuid": "QbHbJTJoTMOlQA0r9t1bfw", "node.id": "WEviQnWxR_OuPKT_jlr6gQ"  }

**Comment by antoineco** [comment]
If the default password still works it means the passwords were reverted to their defaults. This happens when you clear the elasticsearch data volume.

Either this, or your volume already contained an initialized keystore and the password initialization refused to override the existing passwords.

Either way, I'd recommend running `docker-compose down -v` and going through the procedure again. We have automated tests for this, so I'm 100% confident it works, providing that you start clean.

**Comment by Koploseus** [comment]
Yeah thats weird, because i already used **docker-compose down -v** , after that i restart all docker, then the command for password changes, then i change the files, then i restart kibana/logstash.. and then.. no kibana ^^

**Comment by Koploseus** [comment]
I have restart all the stuff etc, this is my log : 

kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:00Z","tags":["warning","plugins","security","config"],"pid":6,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:00Z","tags":["warning","plugins","security","config"],"pid":6,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","apm_oss"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","translations"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","data"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","share"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","home"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","spaces"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","cloud"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","apm"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","graph"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","plugins","bfetch"],"pid":6,"message":"Setting up plugin"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["info","savedobjects-service"],"pid":6,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
kibana_1         | Could not create APM Agent configuration: Authentication Exception
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to [security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } :: {\"path\":\"/_xpack\",\"statusCode\":401,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\",\"wwwAuthenticateDirective\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"} error"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:01Z","tags":["error","savedobjects-service"],"pid":6,"message":"Unable to retrieve version information from Elasticsearch nodes."}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:17:31Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to [security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } :: {\"path\":\"/_xpack\",\"statusCode\":401,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\",\"wwwAuthenticateDirective\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"} error"}
kibana_1         | {"type":"log","@timestamp":"2020-05-18T12:18:01Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to [security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } :: {\"path\":\"/_xpack\",\"statusCode\":401,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"failed to authenticate user [kibana]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"security\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\",\"wwwAuthenticateDirective\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"} error"}

**Comment by antoineco** [comment]
@Koploseus found the cause?

**Comment by Koploseus** [comment]
Nope, but i have recreate a docker-compose and it work ^^ , but still thanks for the help! i still don't know why it wasn't working
