### ISSUE TITLE
ELK Stack V5 + X-Pack

### ISSUE THREAD

**Issue by user82461** [deviantony/docker-elk#50]
Could you you make a branch for the V5 stack with X-Pack?

https://www.elastic.co/v5

Your releases make testing new features easy and are highly appreciated 👍

**Comment by deviantony** [comment]
Hi @user82461, sure I'll have a look at this today ;)

**Comment by deviantony** [comment]
Installation docs: https://www.elastic.co/downloads/x-pack

**Comment by deviantony** [comment]
According to the installation procedure, the following commands needs to be run *AFTER* the Elasticsearch instance has been started:

```shell
$ bin/x-pack/users useradd elastic -r admin
$ bin/x-pack/users useradd kibana -r kibana4_server
```

Unfortunately, I did not found a way to do that within a `docker-compose` setup. There may be a hacky way to do this by using a script as an entrypoint, something like:

```bash
#!/usr/bin/env bash

echo "Starting Elasticsearch"
gosu elasticsearch elasticsearch &

echo "Waiting for Elasticsearch to boot..."
while true; do
    nc -q 1 localhost 9200 2>/dev/null && break
done

echo "Elasticsearch ready. Creating x-pack users..."

/usr/share/elasticsearch/bin/x-pack/users useradd elastic -r admin -p 'adminpass'
/usr/share/elasticsearch/bin/x-pack/users useradd kibana -r kibana4_server -p 'kibanapass'
```

By using a solution like this one, Docker would not control the Elasticsearch process anymore, which is why it's hacky. Thus, I did not found a solution so the container won't exit after execution of the script.

Any idea?

**Comment by user82461** [comment]
Adding `fg %1` to the end might work. That command should bring the elasticsearch process back to the foreground (went to background with the &). Similar thing might be possible with screen or tmux. 

If that doesn't work, a `while true; sleep 60` loop would work to keep the container from exiting, but probably isn't the best solution.

**Comment by deviantony** [comment]
@user82461 : All right, here it is : https://github.com/deviantony/docker-elk/tree/x-pack

Use *elastic* / *pass-elastic* to login in Kibana.

*NOTE*: I went for the `while true; do sleep 1000; done` hack in order to keep the Elasticsearch container running after the creation of the users. I really don't like it, I'll keep this issue open and I'll close it when I'll have find a better solution.

I just tried to login / inject logs in Elasticsearch, nothing more.

Enjoy !

**Comment by deviantony** [comment]
@user82461 Did you had the opportunity to try it?

**Comment by user82461** [comment]
Not yet, but I will try it early this week. Thanks for making it so fast!
I'll see if I can find some alternative ways to keep the container running.

@user82461 <https://github.com/user82461> Did you had the opportunity to
try it?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/deviantony/docker-elk/issues/50#issuecomment-217620702>

**Comment by user82461** [comment]
@deviantony Just gave it a go. Seems like elasticsearch would not come up.

I ran `sudo chcon -R system_u:object_r:admin_home_t:s0 . ` in the docker-elk folder since i'm on CentOS7.

Kibana never launches and leaves off at `Stalling for Elasticsearch`. 

Logstash also cannot connect to elasticsearch:
`logstash_1       | {:timestamp=>"2016-05-13T21:57:26.805000+0000", :message=>"Connection refused", :class=>"Manticore::SocketException", :level=>:error}`

Is there any other debugging info I can provide?

**Comment by deviantony** [comment]
@user82461 maybe you could have a look at the elasticsearch container logs? Works well on my workstation. Do you use docker-machine?

**Comment by user82461** [comment]
I looked at the stdout log using `docker logs <instance>`, but it was the
same as the stdout from the `docker-compose up` command to run it. I'll try
to enable some more verbosity in the es config and run some tests via the
entrypoint script. I have docker running natively on CentOS 7.

**Comment by deviantony** [comment]
Ok, I just tried it, seems that there is a new x-pack version (5.0.0-alpha2) and now the Elasticsearch container is not working anymore.

I got the following logs when starting the stack:

```
elasticsearch_1  | [2016-05-15 03:54:51,382][INFO ][node                     ] [White Queen] version[5.0.0-alpha2], pid[8], build[e3126df/2016-04-26T12:08:58.960Z]
elasticsearch_1  | [2016-05-15 03:54:51,383][INFO ][node                     ] [White Queen] initializing ...
elasticsearch_1  | [2016-05-15 03:54:52,057][INFO ][plugins                  ] [White Queen] modules [lang-mustache, lang-painless, ingest-grok, reindex, lang-expression, lang-groovy], plugins [x-pack]
elasticsearch_1  | [2016-05-15 03:54:52,132][INFO ][env                      ] [White Queen] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/dm-6)]], net usable_space [59.4gb], net total_space [126.4gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2016-05-15 03:54:52,133][INFO ][env                      ] [White Queen] heap size [989.8mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2016-05-15 03:54:52,202][INFO ][watcher.trigger.schedule ] [White Queen] using [ticker] schedule trigger engine
elasticsearch_1  | [2016-05-15 03:54:56,214][INFO ][node                     ] [White Queen] initialized
elasticsearch_1  | [2016-05-15 03:54:56,214][INFO ][node                     ] [White Queen] starting ...
elasticsearch_1  | [2016-05-15 03:54:56,454][WARN ][shield.authc.file        ] [White Queen] no users found in users file [/etc/elasticsearch/x-pack/users]. use bin/x-pack/users to add users and role mappings
elasticsearch_1  | [2016-05-15 03:54:56,460][WARN ][shield.authc.file        ] [White Queen] no entries found in users_roles file [/etc/elasticsearch/x-pack/users_roles]. use bin/xpack/users to add users and role mappings
elasticsearch_1  | [2016-05-15 03:54:56,471][INFO ][marvel.agent             ] [White Queen] monitoring service started
elasticsearch_1  | [2016-05-15 03:54:56,774][INFO ][shield.transport         ] [White Queen] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | Exception in thread "main" java.lang.RuntimeException: bootstrap checks failed
elasticsearch_1  | initial heap size [268435456] not equal to maximum heap size [1073741824]; this can cause resize pauses and prevents mlockall from locking the entire heap
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:93)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:66)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:191)
elasticsearch_1  | 	at org.elasticsearch.node.Node.start(Node.java:323)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:269)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:53)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
elasticsearch_1  | Refer to the log for complete error details.
elasticsearch_1  | [2016-05-15 03:54:56,791][INFO ][node                     ] [White Queen] stopping ...
elasticsearch_1  | [2016-05-15 03:54:56,852][INFO ][node                     ] [White Queen] stopped
elasticsearch_1  | [2016-05-15 03:54:56,852][INFO ][node                     ] [White Queen] closing ...
elasticsearch_1  | [2016-05-15 03:54:56,884][INFO ][node                     ] [White Queen] closed
```

Also I suggest to start the stack using `docker-compose up` (no `-d` option) to see all the containers logs.

I'll investigate.

**Comment by deviantony** [comment]
Have a look at this issue: https://github.com/docker-library/elasticsearch/issues/98#issuecomment-218071315

**Comment by deviantony** [comment]
Ok, so they changed a few things in the alpha-2 version so I updated the solution:

* No need to create the users anymore, it comes with built-in users: https://www.elastic.co/guide/en/x-pack/v5.0.0-alpha2-docs/setting-up-authentication.html#built-in-users
* you need to increase `max_map_count` on your Docker host: `sudo sysctl -w vm.max_map_count=262144`
* to prevent the Elastichsearch warning `initial heap size [268435456] not equal to maximum heap size [1073741824]; this can cause resize pauses and prevents mlockall from locking the entire heap` a new environment variable has been set for the elasticsearch container

The good thing is that we don't need the `while true; do sleep 1000; done` hack. It's cleaner now.

Use the following credentials to connect in Kibana: `elastic` / `changeme`

*NOTE*: It is currently using the `elastic` super-user in Logstash to connect against Elasticsearch, and it uses the default credentials (password is `changeme`). You will want to change that obviously.

I've also updated the README to add a section about the `max_map_count` in the requirements.

I'll keep this issue open until the 5.0 version is released, as there may be others changes in the future.

Have a look at https://github.com/deviantony/docker-elk/commit/54cd6679120723548b7bda3ca82fa5dcc99a1a51 if you're interested in the changes.

**Comment by deviantony** [comment]
@user82461 test it quickly before Elasticsearch upgrades to alpha-3 ;)

**Comment by user82461** [comment]
Seems to work pretty well! Running some test data through it now. Haven't tried messing with much of the x-pack yet.

Thanks Anthony!

**Comment by CCoffie** [comment]
I just submitted a pull request to make it compatible with alpha3. Logstash is broken now and I couldn't figure that out so maybe @deviantony might be able to look into that.

**Comment by deviantony** [comment]
Ahah, seems that they always introduce a lot of change between versions. I'll have a look !

**Comment by deviantony** [comment]
All right, I've updated the branch with the required changes to support Alpha-3 !

Changes:

* There is a bug in the logstash image at the moment, it needs to be run with the following command: `/usr/share/logstash/bin/logstash --path.settings /etc/logstash/`, see https://github.com/docker-library/logstash/issues/49
* The content of the file `kibana/config/kibana.yml` is totally different, I've updated it with the latest default configuration
* A fix with the command lines flags passed to Elasticsearch

Most of which you've already seen @CCoffie thanks, your PR helped me to make the changes.

**Comment by deviantony** [comment]
Note, now that https://github.com/docker-library/logstash/issues/49 is fixed, I've updated the logstash `command`.

**Comment by deviantony** [comment]
@agonzalezm 

I recommend you to use the `x-pack` branch if you want to play with X-Pack: https://github.com/deviantony/docker-elk/tree/x-pack

I've just updated it so it support alpha-4.

**Comment by agonzalezm** [comment]
thanks i used that branch and worked but 

- if i try to use sense http://localhost:5601/app/sense I get not found:
{"statusCode":404,"error":"Not Found","message":"Unknown app sense"}

- logstash doesnt have a build Dockerfile to add plugins

**Comment by deviantony** [comment]
@agonzalezm If you follow the README in the `x-pack` branch you'll see that there is no more access to sense. As @CCoffie stated, chances are that they replace it with something new in X-Pack.

**Comment by deviantony** [comment]
I've also updated the `x-pack` branch, latest commit https://github.com/deviantony/docker-elk/commit/890c3959e6f78363e987309ab8c31581b73b8cd6 allows you to manage logstash plugins.

See the updated README.

**Comment by agonzalezm** [comment]
Thanks, but last commit logstash Dockerfile point to latest instead of logstash:5.

Yes, right Kibana Console works fine and replaces sense.

**Comment by deviantony** [comment]
Woops ! Fixed.

**Comment by deviantony** [comment]
No changes required between alpha-4 and alpha-5. Alpha-5 works well.

**Comment by deviantony** [comment]
No changes required between alpha-5 and RC-1. RC-1 works well.

**Comment by deviantony** [comment]
ELK 5 stable with X-Pack support in is available here: https://github.com/deviantony/docker-elk/tree/x-pack

Enjoy :)
