### ISSUE TITLE
could this es in the docker connect to another es(data node)?

### ISSUE THREAD

**Issue by jevislee** [deviantony/docker-elk#504]
could I add the below line in docker-elk/elasticsearch/config/elasticsearch.yml?
discovery.zen.ping.unicast.hosts: ["192.168.1.68"]

thanks

**Comment by antoineco** [comment]
There are a little bit more configuration options involved than just that one if you want to form a cluster: https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster

Nodes need to be able to talk to each other, for a start. Docker Compose may not be suitable in case you have some nodes running on different machines.

**Comment by jevislee** [comment]
then whether the docker-elk project should be used in production enviroment? or is it just for study or development enviroment?

**Comment by antoineco** [comment]
Compose is limited to one node, if that's OK with your setup you can run this stack in production.

If you need to run each component on different nodes with some redundancy, Compose is not the right choice for you.

Swarm and Kubernetes can scale containers across multiple nodes, but that's beyond the scope of this project.

**Comment by jevislee** [comment]
thanks a lot
