### ISSUE TITLE
Unable to launch kibana - Kibana server is not ready yet

### ISSUE THREAD

**Issue by securigeek** [deviantony/docker-elk#505]
Hello,

I I tried following the steps using the files in this git but I have an issue with starting the Kibana , I am getting "Kibana server is not ready yet" error . 

WHile in daemon mode I dont know where to search for logs but in plain docker-compose up mode I have the following logsat the end , please help 

````
https://pastebin.com/JQmWkuN8 - logs

Thanks,

**Comment by antoineco** [comment]
Elasticsearch is unreachable. Please reopen the issue with all the requested information so we have a chance to help you figure where the problem is coming from. Thank you for your understanding.

**Comment by securigeek** [comment]
I am sorry but I don't see the list of requested informetion. Could you please precise ?

**Comment by antoineco** [comment]
When you open a new GitHub issue, there is a template that prompts you to provide some information. You deleted it, but it's important to us, otherwise we have to keep asking the same questions again and again to everyone (Docker logs, ELK config, details about the environment, ...)
