### ISSUE TITLE
Show warning in bold texts in the README

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#509]
A user suggested we display warnings in bold text, because block quotes are rendered in gray color, which does not catch the eye enough.

--- 

Unbelievable i overlooked it... perhaps because it is gray (comment).

> ⚠ You must rebuild the stack images with docker-compose build whenever you switch branch or update the version of an already existing stack.

Perhaps better write your ⚠ in **bold** instead of a comment 😅 something like:

> **⚠ You must rebuild the stack images with `docker-compose build` whenever you switch branch or update the version of an already existing stack.**

_Originally posted by @FireEmerald in https://github.com/deviantony/docker-elk/issues/508#issuecomment-641804865_

**Comment by bubbajames-docker** [comment]
Simple update to README to replace block quotes with emphasis; Warnings bold, Information Source italics.

#524
