### ISSUE TITLE
Kibana container shutting down in less than a day

### ISSUE THREAD

**Issue by Rhjulskov** [deviantony/docker-elk#51]
When upping docker-compose on Azure, the Kibana container shuts down after ~1 day. Everything ells keeps running but that.

The containers logs is as follows:

```
{"type":"log","@timestamp":"2016-04-28T01:14:45+00:00","tags":["status","plugin:elasticsearch","error"],"pid":1,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2016-04-28T01:15:25+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2016-04-28T01:16:20+00:00","tags":["status","plugin:elasticsearch","error"],"pid":1,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2016-04-28T01:17:04+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2016-04-28T01:17:42+00:00","tags":["status","plugin:elasticsearch","error"],"pid":1,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2016-04-28T01:19:11+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2016-04-28T01:20:16+00:00","tags":["status","plugin:elasticsearch","error"],"pid":1,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
```

**Comment by deviantony** [comment]
Hi, did you made any changes in the configuration?

What version of docker / docker-compose are you using?

**Comment by Rhjulskov** [comment]
Docker version 1.10.3, build 20f81dd
docker-compose version: 1.5.1

With the original config. I've added a filter to Logstash config — that's all

**Comment by deviantony** [comment]
Weird, maybe the issue is related to your network?

I also found that post: https://discuss.elastic.co/t/kibana-flapping-between-red-and-green/36328/9

The issue here was the memory associated to the Node process. Seems that a way to solve this is to update the *NODE_OPTIONS* environment variable before starting the Kibana process.

```bash
NODE_OPTIONS="--max-old-space-size=250" bin/kibana
```

You could try to update the compose definition of the Kibana container like this:

```yml
kibana:
  build: kibana/
  environment:
    NODE_OPTIONS: "--max-old-space-size=250"
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```

Of course, you may need to adjust the memory value according to your needs (the available memory on your system I guess).

See these issues for more info:
https://github.com/spujadas/elk-docker/issues/17
https://github.com/elastic/kibana/issues/5170
https://github.com/elastic/kibana/pull/5451

Let me know if that solves your issue.

**Comment by deviantony** [comment]
@Rhjulskov any news?

**Comment by Rhjulskov** [comment]
Sorry for the late response. I just restarted the compose file with the new changes. I'll response to the issue in a day or two.

Thanks a lot for your time :)

**Comment by deviantony** [comment]
@Rhjulskov can I assume that everything is fine? :)

**Comment by Rhjulskov** [comment]
Yes it is. Thanks alot! :)

**Comment by stonefury** [comment]
I'm running a single node on a VM where I have the option to add a lot of RAM/CPU.  Our elk stack crashes as well after awhile.

I just pulled the latest image and am trying it now. Is this fixed in the latest image?

tnx

**Comment by deviantony** [comment]
@stonefury please have a look at this issue: https://github.com/deviantony/docker-elk/issues/51#issuecomment-215356944

**Comment by stonefury** [comment]
Ah, ok thank you @deviantony. Appreciate it! Cheers.
