### ISSUE TITLE
Update images to reflect latest release of the ELK stack, version 7.8.0

### ISSUE THREAD

**Issue by blorincz1** [deviantony/docker-elk#514]
### Problem description

Per project owner's request, opening this issue to have images updated to the latest release of the ELK stack, 7.8.0.

### Extra information

https://hub.docker.com/_/elasticsearch?tab=tags
https://hub.docker.com/_/kibana?tab=tags
https://hub.docker.com/_/logstash?tab=tags

**Comment by antoineco** [comment]
@blorincz1 good idea. I'll bump the version and verify that all our tests are still passing. Have you tried on your side already?

**Comment by blorincz1** [comment]
I haven't had a chance to yet, sorry.

**Comment by antoineco** [comment]
@blorincz1 7.8.0 is now the default version in this repo. Happy to hear about any feedback.
