### ISSUE TITLE
Couldn't find any Elasticsearch data

### ISSUE THREAD

**Issue by shirayner** [deviantony/docker-elk#516]
### Problem description
After cloned the project，I run `docker-compose up -d`， es, kibana and logstash start successfuly，but it seems that kibana cannot conect to elasticsearch. Just like following，

![image](https://user-images.githubusercontent.com/11574340/86260806-5b81cd80-bbf0-11ea-8564-4b60d0306b22.png)

## System
my operation system is windows 10

**Comment by shirayner** [comment]
because there should be at least one record existed in elasticsearch so that kinaba can find the data

**Comment by antoineco** [comment]
Indeed

> :information_source: You need to inject data into Logstash before being able to configure a Logstash index pattern via
the Kibana web UI.
>
> -- https://github.com/deviantony/docker-elk/blob/master/README.md#default-kibana-index-pattern-creation
