### ISSUE TITLE
Elasticsearch cluster cannot find the master node in the docker swarm using docker stack deploy 

### ISSUE THREAD

**Issue by TamilTintin** [deviantony/docker-elk#521]
Hi all I have tried this for ES cluster in docker swarm , https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster
but i cannot get Elastic cluster in docker swarm.

docker-compose.yml 
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch1-data:/usr/share/elasticsearch/data
    environment:
      - "node.name:elk_elasticsearch.{{.Task.Slot}}"
      - "discovery.seed_hosts:tasks.elasticsearch"
      - "cluster.initial_master_nodes:elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3"
      - "discovery.zen.ping.unicast.hosts=tasks.elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "node.max_local_storage_nodes:'3'"
      - "discovery.type: ''"
    networks:
      - elasticsearch_distributed
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
volumes:
  elasticsearch1-data:
networks:
  elasticsearch_distributed:
    driver: overlay

Inside the log in a container , i have found
{"type": "server", "timestamp": "2020-07-27T12:03:59,936Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "docker-cluster", "node.name": "57246b31c6ee", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{57246b31c6ee}{X5_mB1FiR7C5_Wjz89G3BQ}{Fvypf8HeR5y5qihELLcOBA}{10.0.0.217}{10.0.0.217:9300}{dilmrt}{ml.machine_memory=16656715776, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]; discovery will continue using [10.0.5.3:9300] from hosts providers and [{57246b31c6ee}{X5_mB1FiR7C5_Wjz89G3BQ}{Fvypf8HeR5y5qihELLcOBA}{10.0.0.217}{10.0.0.217:9300}{dilmrt}{ml.machine_memory=16656715776, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
Can anyone help me resolve this ? 

Thanks

**Comment by antoineco** [comment]
The format of your environment variables looks strange, with a mix of quotes, colons and equal signs.

Could you please try using this exact format without any other modification? (just for now, you can tweak later)

```yaml
  elasticsearch:
    environment:
      node.name: elk_elasticsearch.{{.Task.Slot}}
      discovery.type: ''
      discovery.seed_hosts: tasks.elasticsearch
      cluster.initial_master_nodes: elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3
```

**Comment by TamilTintin** [comment]
Now its fine !


version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch1-data:/usr/share/elasticsearch/data
    environment:
      - node.name:elk_elasticsearch.{{.Task.Slot}}
      - discovery.seed_hosts:tasks.elasticsearch
      - cluster.initial_master_nodes:elk_elasticsearch.1,elk_elasticsearch.2,elk_elasticsearch.3
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - node.max_local_storage_nodes:'3'
      - discovery.type:''

    networks:
      - elasticsearch_distributed
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
volumes:
  elasticsearch1-data:

networks:
  elasticsearch_distributed:
    driver: overlay
