### ISSUE TITLE
How to setup for syslog

### ISSUE THREAD

**Issue by manbobo2002** [deviantony/docker-elk#531]
As caption, how do we setup for network syslog?

**Comment by antoineco** [comment]
@manbobo2002 it should be as simple as adding the following `input` to your Logstash pipeline file ([logstash/pipeline/logstash.conf](https://github.com/deviantony/docker-elk/blob/master/logstash/pipeline/logstash.conf)):

```ruby
input {
	# you can remove or comment the default "tcp" input if you don't need it
	#
	# tcp {
	# 	port => 5000
	# }

	syslog {
		port => 10514
	}
}
```

Then, configure your rsyslog clients to forward all locally generated log messages to Logstash:

```sh
# replace 10.0.0.1 with the IP address or host name of your Elastic stack
*. *  @@10.0.0.1:10514
```

For more information about Logstash's `syslog` input, see [Logstash Reference » Input plugins » Syslog input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html).

**Comment by manbobo2002** [comment]
Hi, thanks, I already fixed it.

But my approach is port forward from port 514 into port 5555
