### ISSUE TITLE
Got error everytime I changed the elastic user's password

### ISSUE THREAD

**Issue by ysf08** [deviantony/docker-elk#538]
As mentioned in the read me doc the default user is elastic and the password is change me. but unfortunately every time I change the user's password I got following error:

```
Cannot connect to the Elasticsearch cluster
See the Kibana logs for details and try reloading the page.
```
I can't let that user to stay using same password due to security reason.
Any help regarding this?

**Comment by antoineco** [comment]
@ysf08 I assume you changed the password using the instructions from the README, is that right? https://github.com/deviantony/docker-elk#how-to-reset-a-password-programmatically
If you did so, did you also update the password inside `kibana.yaml`?

Just in case you are trying to update the password by setting the `ELASTIC_PASSWORD` variable: as described in https://github.com/deviantony/docker-elk#setting-up-user-authentication, you can not use the `ELASTIC_PASSWORD` variable to change the bootstrap password _after_ the initial startup, only _before_. This password is only used to initialize Elasticsearch during the **first start**, it is completely ignored in all subsequent restarts.

**Comment by ysf08** [comment]
Will try and let you know the result

**Comment by ysf08** [comment]
Hmmhm doesn't work, I will Install it manually on the host instead

**Comment by antoineco** [comment]
@ysf08 you need to restart Kibana as well in order to apply changes.

As mentioned in the README (https://github.com/deviantony/docker-elk#configuration)
> https://github.com/deviantony/docker-elk#configuration

```
docker-compose restart kibana
```

**Comment by ysf08** [comment]
Here is how I solved the issue:

1. Update docker compose change elastic_password:
ELASTIC_PASSWORD: "mypassword"
2. change elastic password on following files:
./logstash/config/logstash.yml
./kibana/config/kibana.yml
3. hit APIs
curl -XPOST -D- 'http://localhost:9200/_security/user/elastic/_password'  -H 'Content-Type: application/json' -u elastic:changeme  -d '{"password" : "mypassword"}'

**Comment by antoineco** [comment]
You did the right thing :+1:

Note: Like I mentioned already, ELASTIC_PASSWORD has no effect at all at this point. It's only read to initialize the password during the **first** start. After that, you can remove it from the Compose file, or ignore it.

That's the reason why you had to reset the password via the API, because the password had already been initialized to "changeme" once.
