### ISSUE TITLE
Please update to 7.9.2

### ISSUE THREAD

**Issue by ylz-at** [deviantony/docker-elk#539]

**Comment by ylz-at** [comment]
It works after I simply change the version in .env.

**Comment by antoineco** [comment]
@ylz-at done!

Changelog
* [Elasticsearch 7.9.2 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.9.2.html)
* [Kibana 7.9.2 Release Notes](https://www.elastic.co/guide/en/kibana/current/release-notes-7.9.2.html)
* [Logstash 7.9.2 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-7-9-2.html)

**Comment by ylz-at** [comment]
@antoineco Thanks!
