### ISSUE TITLE
The logstash configuration file is configured with filebeat, but the image of filebeat is not seen in the project, and how filebeat configures log collection rules?

### ISSUE THREAD

**Issue by hy-2019** [deviantony/docker-elk#547]
#### Docker setup

```
<!-- Replace this comment with the full output of the `docker version` command. -->
```

```
<!-- Replace this comment with the full output of the `docker-compose version` command. -->
```

#### Docker logs

```
<!-- Replace this comment with the full output of the `docker-compose logs` command. -->
```

**Comment by antoineco** [comment]
@hy-2019 I'm afraid we don't have a maintainer that understands Chinese, but if the following translation is correct:

> _The logstash configuration file is configured with filebeat, but the image of filebeat is not seen in the project, and how filebeat configures log collection rules?_

then the answer is:

Beats is a [collection of _agents_](https://www.elastic.co/cn/beats/) that run on the **system you want to monitor**. With the `beats` input enabled by default, you are allowed to run your own agents (Filebeat, Metricbeat, Packetbeat etc.) and configure them to communicate with the dockerized ELK stack **remotely** on port `5044`.

You can run the agents as a Docker container if you want ([Run Filebeat on Docker](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html)), but these are not part of the ELK stack, they **external agents**.

**Comment by antoineco** [comment]
Translating the issue title to keep things international.

**Comment by hy-2019** [comment]
Thank you very much
