### ISSUE TITLE
Can't start Elasticsearch container

### ISSUE THREAD

**Issue by q2dg** [deviantony/docker-elk#549]
### Problem description

I've just run docker-compose up without doing any change to cloned github repo and I get this error:

![Captura de pantalla de 2020-10-28 12-21-01](https://user-images.githubusercontent.com/7274874/97429858-486dd880-1918-11eb-95e6-742b0c330d3e.png)

It seems a permission error related to "/usr/share/elasticsearch/data/nodes" folder. I've seen some similar errors in Google with some solutions but I don't know the inners of your specific implementation.

Thanks

**Comment by antoineco** [comment]
@q2dg if you didn't change anything it means Elasticsearch is using the local Docker volume set in the Compose file, and therefore permissions shouldn't be an issue.

Would you mind filling the information from the issue template so I can reproduce? It was displayed when you created the issue but you deleted it.

**Comment by q2dg** [comment]
Sorry for the inconvenience.
I'm using podman-compose instead of docker-compose... Maybe this is the thing. If you don't mind, I'll close the issue in order to further investigate which is the source of the problem so I can confirm it's not related to docker-elk project itself.
Sorry again.

**Comment by antoineco** [comment]
@q2dg that would be the reason, yes. `podman-compose` doesn't use Docker's magic to infer the permissions of a volume based on the container image configuration: https://github.com/containers/podman-compose/issues/98.

I assume you have to set those permissions yourself using `chown`. The uid of the `elasticsearch` user is `1000`:  https://github.com/elastic/elasticsearch/blob/ef4ea4ae1030f2ca6dc55e7011bd3397512a32a5/distribution/docker/src/docker/Dockerfile#L234-L235

**Comment by q2dg** [comment]
Thanks a lot again! If you don't mind, if/when I find a workaround for this issue I'll post it here to help other people having the same issue (while podman-compose doesn't solve its own issues...)

**Comment by antoineco** [comment]
Sounds good! I just did a quick search and `podman` seems to create volumes in `${HOME}/.local/share/containers/storage/volumes/`. There is a long discussion about volumes support in https://github.com/containers/podman-compose/issues/13 but things still seem a bit shaky.

**Comment by q2dg** [comment]
Well, I just write to note for the record that this issue isn't resolved yet using Podman 3.2.0 and Podman-compose 0.1.7 (in a Fedora 34).
