### ISSUE TITLE
executing init_sg.sh with docker-compose

### ISSUE THREAD

**Issue by ismailazerty** [deviantony/docker-elk#562]
Hello,

    Is there a way to execute init_sg.sh automatically with docker-compose.yml ?

Thank you

**Comment by antoineco** [comment]
You could, but you'd have to override Elasticsearch's [startup script](https://github.com/elastic/elasticsearch/blob/68b5465/distribution/docker/src/docker/bin/docker-entrypoint.sh) (also called "Docker entrypoint") in order to include the execution of `init_sg.sh`. You would have to ensure your startup script doesn't fail because Search Guard was already initialized though.

**Comment by ismailazerty** [comment]
I think it's important  to add this feature, or document the fact that this script is for manuel execution. I spent a lot of time to understand that.

thx

**Comment by antoineco** [comment]
It is documented, right at the beginning of the **Initial Setup** section, which we expect people to read.

![Screenshot_20210111-143204](https://user-images.githubusercontent.com/3299086/104188728-fe29cd00-5419-11eb-9dd5-2ee0987456ba.png)

**Comment by antoineco** [comment]
Another challenge may arise by trying to execute the script automatically: Elasticsearch must be up and running before Search Guard can be initialized, so orchestrating that in the startup script itself is a bit hacky.

And, like I already mentioned, the initialization is suppose to be performed only once (updates are slightly different). Detecting that Search Guard is already initialized would require communicating with Elasticsearch, which means we need to inject credentials in the startup script, and this will break as soon as the user changes their password.

**Comment by ismailazerty** [comment]
> It is documented, right at the beginning of the **Initial Setup** section, which we expect people to read.
> 
> https://github.com/deviantony/docker-elk/tree/searchguard#initial-setup

my bad, I have red the readme of master branch
