### ISSUE TITLE
Error when deploying in ARM64 architecture

### ISSUE THREAD

**Issue by douglascarlini** [deviantony/docker-elk#576]
### Problem description

Error when deploying on Raspberry Pi 4 (ARM64)

### Extra information

`standard_init_linux.go:219: exec user process caused: exec format error`

#### Stack configuration

No changes.

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:47 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
```

```console
$ docker-compose version

docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

#### Container logs

```console
$ docker-compose logs

elasticsearch_1  | {"type": "server", "timestamp": "2021-02-19T12:47:58,514Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "31f8ba2bcf54", "message": "loaded module [x-pack-ml]" }
kibana_1         | standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by antoineco** [comment]
You're raising a very good point. The Docker image for Elasticsearch is multi-architecture, but Kibana is not: https://stackoverflow.com/a/65283294/4716370

You can find an alternative, non-official image here and use-it as a drop-in replacement: https://github.com/barasher/

The StackOverflow above mentions another image, but it doesn't seem to support anything newer than v7.6.

**Comment by antoineco** [comment]
It seems like official support for ARM64 is coming in Kibana 8.0: https://github.com/elastic/kibana/pull/84831

**Comment by douglascarlini** [comment]
Thanks for the workaround, @antoineco

Let's wait for the v8, I hope it doesn't take long.

I found this one for v7.6.2 https://github.com/gagara/docker-elk-arm64

**Comment by antoineco** [comment]
@douglascarlini Elastic added support for the `arm64` architecture to Kibana images since the v7.13.0 release yesterday (25th May). Check this out:

`docker manifest inspect --verbose docker.elastic.co/kibana/kibana:7.13.0`

```jsonc
[
  // ...
  {
    "Descriptor": {
      // ...
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    // ...
  },
  {
    "Descriptor": {
      // ...
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
  // ...
  }
]
```

**Comment by douglascarlini** [comment]
@antoineco Thanks for feedback!
