### ISSUE TITLE
How can i show logstash's log??

### ISSUE THREAD

**Issue by jabel123** [deviantony/docker-elk#588]
How can i show logstash's log??

**Comment by ankkie** [comment]
You can use the following:
docker logs -f SERVICE_NAME
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by ankkie** [comment]
If you want to see the logstash pipeline output then use the following in the output section:
 ```stdout { codec => rubydebug }```
https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html

**Comment by antoineco** [comment]
@jabel123, does @ankkie's suggestion answer question?
