### ISSUE TITLE
Error: No config files found

### ISSUE THREAD

**Issue by israelidanny** [deviantony/docker-elk#59]
I'm trying to run this docker compose as is, without changing anything, and it fails with the following error:

```
logstash_1      | {:timestamp=>"2016-08-01T07:57:36.721000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}
```

The config file exists, and contains the default configuration as per the cloned `master` branch of this repository.

Here is the full output of `docker-compose up`:

```
~/docker-elk$ docker-compose up
Creating dockerelk_elasticsearch_1
Creating dockerelk_logstash_1
Creating dockerelk_kibana_1
Attaching to dockerelk_elasticsearch_1, dockerelk_logstash_1, dockerelk_kibana_1
kibana_1        | Stalling for Elasticsearch
elasticsearch_1 | [2016-08-01 07:57:24,742][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elasticsearch_1 | [2016-08-01 07:57:25,054][INFO ][node                     ] [Morlun] version[2.3.4], pid[1], build[e455fd0/2016-06-30T11:24:31Z]
elasticsearch_1 | [2016-08-01 07:57:25,054][INFO ][node                     ] [Morlun] initializing ...
elasticsearch_1 | [2016-08-01 07:57:25,897][INFO ][plugins                  ] [Morlun] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1 | [2016-08-01 07:57:25,946][INFO ][env                      ] [Morlun] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [22.9gb], net total_space [28.4gb], spins? [possibly], types [ext4]
elasticsearch_1 | [2016-08-01 07:57:25,947][INFO ][env                      ] [Morlun] heap size [1007.3mb], compressed ordinary object pointers [true]
elasticsearch_1 | [2016-08-01 07:57:30,007][INFO ][node                     ] [Morlun] initialized
elasticsearch_1 | [2016-08-01 07:57:30,007][INFO ][node                     ] [Morlun] starting ...
elasticsearch_1 | [2016-08-01 07:57:30,283][INFO ][transport                ] [Morlun] publish_address {172.17.0.8:9300}, bound_addresses {[::]:9300}
elasticsearch_1 | [2016-08-01 07:57:30,294][INFO ][discovery                ] [Morlun] elasticsearch/wMoCsRxwSgGDYQJC5uYE3g
elasticsearch_1 | [2016-08-01 07:57:33,474][INFO ][cluster.service          ] [Morlun] new_master {Morlun}{wMoCsRxwSgGDYQJC5uYE3g}{172.17.0.8}{172.17.0.8:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1 | [2016-08-01 07:57:33,548][INFO ][http                     ] [Morlun] publish_address {172.17.0.8:9200}, bound_addresses {[::]:9200}
elasticsearch_1 | [2016-08-01 07:57:33,550][INFO ][node                     ] [Morlun] started
kibana_1        | Starting Kibana
elasticsearch_1 | [2016-08-01 07:57:33,891][INFO ][gateway                  ] [Morlun] recovered [0] indices into cluster_state
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["warning","config"],"pid":1,"key":"bundled_plugin_ids","val":["plugins/dashboard/index","plugins/discover/index","plugins/doc/index","plugins/kibana/index","plugins/markdown_vis/index","plugins/metric_vis/index","plugins/settings/index","plugins/table_vis/index","plugins/vis_types/index","plugins/visualize/index"],"message":"Settings for \"bundled_plugin_ids\" were not applied, check for spelling errors and ensure the plugin is loaded."}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:sense","info"],"pid":1,"name":"plugin:sense","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:kibana","info"],"pid":1,"name":"plugin:kibana","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:kbn_vislib_vis_types","info"],"pid":1,"name":"plugin:kbn_vislib_vis_types","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:markdown_vis","info"],"pid":1,"name":"plugin:markdown_vis","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:metric_vis","info"],"pid":1,"name":"plugin:metric_vis","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:spyModes","info"],"pid":1,"name":"plugin:spyModes","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:statusPage","info"],"pid":1,"name":"plugin:statusPage","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["status","plugin:table_vis","info"],"pid":1,"name":"plugin:table_vis","state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:35+00:00","tags":["listening","info"],"pid":1,"message":"Server running at http://0.0.0.0:5601"}
logstash_1      | {:timestamp=>"2016-08-01T07:57:36.721000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}
dockerelk_logstash_1 exited with code 1
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:40+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
elasticsearch_1 | [2016-08-01 07:57:41,141][INFO ][cluster.metadata         ] [Morlun] [.kibana] creating index, cause [api], templates [], shards [1]/[1], mappings [config]
elasticsearch_1 | [2016-08-01 07:57:41,345][INFO ][cluster.routing.allocation] [Morlun] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
kibana_1        | {"type":"log","@timestamp":"2016-08-01T07:57:43+00:00","tags":["status","plugin:elasticsearch","info"],"pid":1,"name":"plugin:elasticsearch","state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
```

**Comment by israelidanny** [comment]
I played around with permissions, and this seems to be a permissions issue. 

What kind of permissions are expected? `chmod 777` works, but I don't want to have such generous permissions.

**Comment by deviantony** [comment]
@israelidanny 

Can you give me more information about Docker version, your OS, compose version?

Also, what did you try to `chmod 777` ?

**Comment by israelidanny** [comment]
I did `chmod 777` on the logstash config folder, otherwise when mounted it was inaccessible to the daemon.

```
~/docker-elk$ docker --version
Docker version 1.11.2, build b9f10c9
```

```
~/docker-elk$ uname -a
Linux staging-jp 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
~/docker-elk$ docker-compose --version
docker-compose version 1.6.2, build 4d72027
```

**Comment by deviantony** [comment]
Strange, default permissions should be the one used after cloning the repo which are:

* 775 for `logstash/config` folder
* 664 for `logstash/config/logstash.conf` file

Can you confirm you have the same permissions after a fresh cloning of the repository?

**Comment by deviantony** [comment]
@israelidanny any update?

**Comment by kostich** [comment]
I'm experiencing the same issue (I would say). Logstash can't read the config file.

`ogstash_1       | {:timestamp=>"2016-08-05T10:57:25.524000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}`

Here are all the permissions:

`-rw-rw-r--. 1 username username 1082 Aug  5 11:31 LICENSE
-rw-rw-r--. 1 username username 6831 Aug  5 11:31 README.md
-rw-rw-r--. 1 username username  476 Aug  5 11:31 docker-compose.yml
drwxrwxr-x. 3 username username 4096 Aug  5 11:31 elasticsearch
drwxrwxr-x. 3 username username 4096 Aug  5 11:31 kibana
drwxrwxr-x. 3 username username 4096 Aug  5 11:31 logstash
-rw-rw-r--. 1 username username 6831 Aug  5 11:31 ./README.md
total 12
-rw-rw-r--. 1 username username  210 Aug  5 11:31 Dockerfile
drwxrwxr-x. 2 username username 4096 Aug  5 11:31 config
-rw-rw-r--. 1 username username  238 Aug  5 11:31 entrypoint.sh
-rw-rw-r--. 1 username username 210 Aug  5 11:31 ./kibana/Dockerfile
-rw-rw-r--. 1 username username 238 Aug  5 11:31 ./kibana/entrypoint.sh
total 4
-rw-rw-r--. 1 username username 2752 Aug  5 11:31 kibana.yml
-rw-rw-r--. 1 username username 2752 Aug  5 11:31 ./kibana/config/kibana.yml
total 4
drwxrwxr-x. 2 username username 4096 Aug  5 11:31 config
total 0
-rw-rw-r--. 1 username username 43 Aug  5 11:31 ./elasticsearch/config/.placeholder
total 8
-rw-rw-r--. 1 username username  121 Aug  5 11:31 Dockerfile
drwxrwxr-x. 2 username username 4096 Aug  5 11:31 config
-rw-rw-r--. 1 username username 121 Aug  5 11:31 ./logstash/Dockerfile
total 4
-rw-rw-r--. 1 username username 158 Aug  5 11:31 logstash.conf
-rw-rw-r--. 1 username username 158 Aug  5 11:31 ./logstash/config/logstash.conf
-rw-rw-r--. 1 username username 476 Aug  5 11:31 ./docker-compose.yml
-rw-rw-r--. 1 username username 1082 Aug  5 11:31 ./LICENSE
`

**Comment by kostich** [comment]
Ok, it seems that my problem is caused by SELinux. If I temporarily disable it via `sudo setenforce 0`, logstash can read the config file... SELinux context seems ok(?):

ystem_u:object_r:admin_home_t:s0 158  5. авг. у 11:31 logstash.conf

**Comment by kostich** [comment]
It seems that `volumes` lines needs to be changed in the yml file so that docker process has enough permissions for the config files in the mounted volumes. I was able to successfully start docker-elk on a SELinux-enabled system (Fedora 24) with the following docker-compose.yml:

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d:Z
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/:Z
  ports:
    - "5601:5601"
  links:
    - elasticsearch

**Comment by deviantony** [comment]
@kostich 

Related to SELinux, there is a specific command that needs to be run (it's specified in the README).

Did you do it?
```shell
.-root@centos ~
-$ chcon -R system_u:object_r:admin_home_t:s0 docker-elk/
```

**Comment by kostich** [comment]
@deviantony, I did follow the README.

[user@box docker-elk]$ ls -lZ
укупно 28
-rw-rw-r--. 1 user user system_u:object_r:admin_home_t:s0  480  5. авг. у 14:58 docker-compose.yml
drwxrwxr-x. 3 user user system_u:object_r:admin_home_t:s0 4096  5. авг. у 11:31 elasticsearch
drwxrwxr-x. 3 user user system_u:object_r:admin_home_t:s0 4096  5. авг. у 11:31 kibana
-rw-rw-r--. 1 user user system_u:object_r:admin_home_t:s0 1082  5. авг. у 11:31 LICENSE
drwxrwxr-x. 3 user user system_u:object_r:admin_home_t:s0 4096  5. авг. у 13:40 logstash
-rw-rw-r--. 1 user user system_u:object_r:admin_home_t:s0 6831  5. авг. у 11:31 README.md

**Comment by deviantony** [comment]
@israelidanny are you using SELinux too?

**Comment by israelidanny** [comment]
I don't have SELinux enabled. Checked that.

**Comment by deviantony** [comment]
@kostich What's the `Z` access mode used for?

I'm not sure how to process this issue, will need more info to determine what could be the underlying problem...

It seems that you have the same problem with two different OS/configs.

**Comment by kostich** [comment]
@deviantony, volume labels are explained much better than I could explain [here](https://docs.docker.com/engine/tutorials/dockervolumes/#/volume-labels).

If I was you, I would try to reproduce it first on a SELinux-enabled system. Best bet is to try on Fedora 24 and a freshly cloned docker-elk repo. That's where I'm having these problems.

**Comment by markl17** [comment]
hi what does thi mean and how do i repair it it is on win10
kibana_1         | {"type":"log","@timestamp":"2016-08-08T03:54:35+00:00","tags":["status","plugin:elasticsearch","error
"],"pid":8,"name":"plugin:elasticsearch","state":"red","message":"Status changed from red to red - Elasticsearch is stil
l initializing the kibana index.","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearc
h:9200."}
elasticsearch_1  | [2016-08-08 03:54:36,248][INFO ][cluster.routing.allocation] [Dr. John Grey] Cluster health status ch
anged from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
kibana_1         | {"type":"log","@timestamp":"2016-08-08T03:54:38+00:00","tags":["status","plugin:elasticsearch","info"
],"pid":8,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready
","prevState":"red","prevMsg":"Elasticsearch is still initializing the kibana index."}
logstash_1       | {:timestamp=>"2016-08-08T03:54:40.947000+0000", :message=>"Connection refused", :class=>"Manticore::S
ocketException", :level=>:error}
logstash_1       | {:timestamp=>"2016-08-08T03:54:41.810000+0000", :message=>"Pipeline main started"}
logstash_1       | {:timestamp=>"2016-08-08T03:54:41.962000+0000", :message=>"Pipeline main has been shutdown"}
logstash_1       | {:timestamp=>"2016-08-08T03:54:44.819000+0000", :message=>"stopping pipeline", :id=>"main"}
mydockerbuild4_logstash_1 exited with code 0

**Comment by deviantony** [comment]
@markl17 Kibana is not able to connect to Elasticsearch, for some reasons. Could you open another issue and copy the whole content of the logs in there?

**Comment by markl17** [comment]
i solved my own problem

**Comment by deviantony** [comment]
I'll open this issue for any help, I don't more idea on a solution for now.

The `Z` volume label seems to be a solution when SELinux is in the equation. For the OP problem, I've got no idea what's wrong.

**Comment by Dr-Jerm** [comment]
Just dropping in to say I'm having the same issue.

My permissions after cloning were:

750 for logstash/config folder
640 for logstash/config/logstash.conf file

After updating to your suggested permissions it worked.

**Comment by deviantony** [comment]
Thanks for your input @Dr-Jerm !

This is strange, a fresh clone on my laptop have the correct permissions:

```shell
% git clone https://github.com/deviantony/docker-elk.git                                                                                                                                                                              Clonage dans 'docker-elk'...
...

% ls -lahR docker-elk/logstash
docker-elk/logstash:
total 16K
drwxrwxr-x 3 tony tony 4,0K août  13 11:31 .
drwxrwxr-x 6 tony tony 4,0K août  13 11:31 ..
drwxrwxr-x 2 tony tony 4,0K août  13 11:31 config
-rw-rw-r-- 1 tony tony  121 août  13 11:31 Dockerfile

docker-elk/logstash/config:
total 12K
drwxrwxr-x 2 tony tony 4,0K août  13 11:31 .
drwxrwxr-x 3 tony tony 4,0K août  13 11:31 ..
-rw-rw-r-- 1 tony tony  158 août  13 11:31 logstash.conf
```

Could it be related to the OS configuration?

**Comment by luis-echegaray** [comment]
I am making the transition from separate AWS amis to docker elk but I am facing this problem as well.  (love the work though)

using docker 1.12 

`
kibana_1         | FATAL CLI ERROR Error: ENOENT: no such file or directory, open '/opt/kibana/config/kibana.yml'
`

`
logstash_1       | {:timestamp=>"2016-08-13T01:47:10.835000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}
`

funny enough it works locally on my macbook pro, but when I push it to my test docker swarm mode cluster, it gives me the above errors.

I will report back if I can find a fix.

**Comment by deviantony** [comment]
@luis-echegaray Did you checked the permissions after clone?

Also, I never tested it with Docker 1.12, neither against a Swarm cluster actually.

**Comment by deviantony** [comment]
@israelidanny 

Even if the volume labels solution seems related to SELinux, could you try with the following content in `docker-compose.yml`?

```yml
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d:Z
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/:Z
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```

**Comment by stephan7878** [comment]
Encountering the same issue on Windows 10, the :Z flag does not resolve the issue.
Workaround by using this Dockerfile:

`
FROM logstash:latest
RUN chown -R logstash:root /etc/logstash/conf.d; \ 
    chmod 0750 /etc/logstash/conf.d;

ONBUILD COPY config/logstash.conf /etc/logstash/conf.d/; \
        RUN chmod 0640 /etc/logstash/conf.d/*
`

**Comment by kevinfealey** [comment]
I'm having this same issue on Win 10 - the volumes are not mounted, so the config files are not available during boot. 

The solution proposed by @stephan7878 did not work for me, though it did help me get a better understanding of what was going wrong, so thanks @stephan7878!

After some digging, I discovered this known issue in Docker for Windows:
https://github.com/docker/docker/issues/23992

The crux of it is that certain special characters in a user's password break Docker's ability to mount a shared drive. Looks like they are evaluating solutions (https://github.com/docker/for-win/issues/94), but they don't have one yet. About to try running this in an Ubuntu VM for now, which seems like it should work.

**Comment by sourcekick** [comment]
I just experienced this in Ubuntu. Note that I am running umask 0077.

I can confirm that chmod o+r for Logstash configuration files on the docker host and chmod o+X on the directory that contains the configuration files (Logstash attempts to load and concatenate all files therein) on the docker host resolved my issue, but it can only be considered a workaround.

At the same time the same problem was true for Elasticsearch trying to read its configuration file. There chmod o+r on the configuration file on the docker host resolved the issue as a workaround.

**Comment by liuchenbuaa** [comment]
my linux version is centos7 and I solved the problem by enable SELinux.  the command is `setenforce 0`

**Comment by antoineco** [comment]
@israelidanny please comment here if you're still running into this issue with the current master. Otherwise this issue will be closed within the next few days.

**Comment by bilal68** [comment]
I am experiencing the this issue 



input {
    jdbc {
        jdbc_connection_string => "jdbc:mysql://localhost:3306/xgearobd"
        jdbc_user => "user"
        jdbc_password => ""
        schedule => "* * * * *"
        jdbc_validate_connection => true
        jdbc_driver_library => "C:/Users/User/Downloads/Compressed/mysql-connector-java-8.0.11/mysql-connector-java-8.0.11.jar"
        jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
        statement => "SELECT * from tbl_users"
    }
     
output {
    elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => rubydebug }
}


this is my config file.....

and when i run "bin/logstash -f logstash.config"
it gives me this
Sending Logstash's logs to C:/Users/User/Downloads/Compressed/logstash-6.3.0/logs which is now configured via log4j2.properties
[2018-06-20T17:06:34,336][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-06-20T17:06:34,905][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.3.0"}
[2018-06-20T17:06:34,999][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"C:/Users/User/Downloads/Compressed/logstash-6.3.0/logstash.config"}
[2018-06-20T17:06:35,012][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2018-06-20T17:06:35,588][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

kindly help me out

**Comment by antoineco** [comment]
`C:/Users/User/Downloads/Compressed/logstash-6.3.0/logstash.config` is most likely not available inside your Docker machine. Please open a new issue, this one is closed.

**Comment by bilal68** [comment]
i am not runing it on local

**Comment by StrongSad388** [comment]
The file should be owned and readable by the user ID that is running logstash.  That is usually user ID 1000.
So, use chown -R 1000 logstash-folder
