### ISSUE TITLE
How to exclude containers from kibana dashboard?

### ISSUE THREAD

**Issue by prime3045** [deviantony/docker-elk#590]
when we run the metricbeat in kibana the following containers are also shown:
docker-elk_logstash
docker-elk_kibana
docker-elk_elasticsearch

How can we exclude these from the Kibana Dashboard? (Especially in Prod servers)

**Comment by antoineco** [comment]
@prime3045 you can configure a _Processor_ for that: https://www.elastic.co/guide/en/beats/metricbeat/current/filtering-and-enhancing-data.html

**Comment by prime3045** [comment]
> @prime3045 you can configure a _Processor_ for that: https://www.elastic.co/guide/en/beats/metricbeat/current/filtering-and-enhancing-data.html
> 
> In your case, you should probably use the [drop_event](https://www.elastic.co/guide/en/beats/metricbeat/current/drop-event.html) processor.
> 
> Example (see [data sample](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-docker-container.html)):
> 
> ```yaml
> processors:
> - drop_event:
>   when:
>     contains:
>       container.image.name:
>       - docker-elk_logstash
>       - docker-elk_kibana
>       - docker-elk_elasticsearch
> ```

Many thanks, this is exactly what I was looking for, since I am new with this could you please let me know where shall I configure this processor?

**Comment by antoineco** [comment]
@prime3045 the Metricbeat configuration reference is available at [Metricbeat Reference [7.12] » Configure Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/configuring-howto-metricbeat.html).

> To configure Metricbeat, edit the configuration file. The default configuration file is called `metricbeat.yml`.

If you're using the docker-elk extension for Metricbeat, this file is here: https://github.com/deviantony/docker-elk/blob/main/extensions/metricbeat/config/metricbeat.yml

**Comment by prime3045** [comment]
> @prime3045 the Metricbeat configuration reference is available at [Metricbeat Reference [7.12] » Configure Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/configuring-howto-metricbeat.html).
> 
> > To configure Metricbeat, edit the configuration file. The default configuration file is called `metricbeat.yml`.
> 
> If you're using the docker-elk extension for Metricbeat, this file is here: https://github.com/deviantony/docker-elk/blob/main/extensions/metricbeat/config/metricbeat.yml

Thanks for the response.

For some reason I am getting this error:
Exiting: error loading config file: yaml: line 128: did not find expected key

the modified metricbeat.yml looks like this:

# ================================= Processors =================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
- drop_event:
  when:
    contains:
      container.image.name:
      - docker-elk_logstash
      - docker-elk_kibana
      - docker-elk_elasticsearch
# ================================== Logging ===================================

What am I doing wrong?

**Comment by antoineco** [comment]
You have mismatched indentations. E.g. you cannot mix indentation levels like you did:

```yaml
list_of_values:
  - one value    # 2 spaces
- another value  # no space
```

You must either use "no space" everywhere, or "2 spaces", but not both in the same list.

Correct indentation is critical in YAML documents.

**Comment by prime3045** [comment]
> You have mismatched indentations. E.g. you cannot mix indentation levels like you did:
> 
> ```yaml
> list_of_values:
>   - one value    # 2 spaces
> - another value  # no space
> ```
> 
> You must either use "no space" everywhere, or "2 spaces", but not both in the same list.
> 
> Correct indentation is critical in YAML documents.
> 
> Here are 2 possible syntaxes which are both valid:
> 
> ```yaml
> processors:
>   - add_cloud_metadata: ~
>   - drop_event:
>     when:
>       contains:
>         container.image.name:
>           - docker-elk_logstash
>           - docker-elk_kibana
>           - docker-elk_elasticsearch
> ```
> 
> ```yaml
> processors:
> - add_cloud_metadata: ~
> - drop_event:
>   when:
>     contains:
>       container.image.name:
>       - docker-elk_logstash
>       - docker-elk_kibana
>       - docker-elk_elasticsearch
> ```

thank you, now getting this:

Exiting: error initializing processors: each processor must have exactly one action, but found 2 actions (drop_event,when)

**Comment by antoineco** [comment]
My bad! I used the wrong indentation for `when:`. I just edited my message.

**Comment by antoineco** [comment]
@prime3045 I just tried in a separate Git branch. The syntax is valid, but I still get the events in Elasticsearch for some reason: https://github.com/antoineco/docker-elk/runs/2465889326?check_suite_focus=true#step:8:170

Something must be wrong in the way I used `contains:` so I'll have to do a little bit more research, but I think we are very close to the solution.

**Comment by antoineco** [comment]
OK, found it.

`contains` verified that **all** values match, but we want just **one**.

You have to use this instead:

```yaml
processors:
  - add_cloud_metadata: ~
  - drop_event:
    when:
      or:
        - equals:
            container.image.name: docker-elk_logstash
        - equals:
            container.image.name: docker-elk_kibana
        - equals:
            container.image.name: docker-elk_elasticsearch
```

**Comment by prime3045** [comment]
I changed all as per your comments still getting the containers
https://ibb.co/FnJ8wKS

**Comment by prime3045** [comment]
tried both:
https://ibb.co/g6jbvwH
https://ibb.co/pLvJdC2

**Comment by antoineco** [comment]
Could those be old entries, created before you applied the filter? The filter does not _remove_ old entries, it simply prevents _new_ events from being created. Things that were already created either need to be deleted from Elasticsearch, or you need to exclude them from your dashboards using a [Kibana filter expression](https://www.elastic.co/guide/en/beats/packetbeat/current/kibana-queries-filters.html#_create_filters).

Example:
```
NOT container.image.name: docker-elk_*
```

**Comment by prime3045** [comment]
> Could those be old entries, created before you applied the filter? The filter does not _remove_ old entries, it simply prevents _new_ events from being created. Things that were already created either need to be deleted from Elasticsearch, or you need to exclude them from your dashboards using a [Kibana filter expression](https://www.elastic.co/guide/en/beats/packetbeat/current/kibana-queries-filters.html#_create_filters).
> 
> Example:
> 
> ```
> NOT container.image.name: docker-elk_*
> ```

yes, they might be old entries. How can I "need to be deleted from Elasticsearch" or where to put "NOT container.image.name: docker-elk_*"

**Comment by prime3045** [comment]
@antoineco thanks a ton, after the restart, the container logs are not showing (Except for the "Number of Containers" section, it's counting the ignored ones as well)
https://ibb.co/r4wS9dw

**Comment by prime3045** [comment]
one last thing my metricbeat keeps stopping after sometime, can I use restart= unless-stopped in metricbeat.yml ?

**Comment by antoineco** [comment]
`restart: unless-stopped` is a [Docker Compose setting](https://docs.docker.com/compose/compose-file/compose-file-v3/#restart), not a Metricbeat setting, so it goes inside [extensions/metricbeat/metricbeat-compose.yml](https://github.com/deviantony/docker-elk/blob/main/extensions/metricbeat/metricbeat-compose.yml).

You can do that, but a better solution would be to figure out why the container is stopping by looking at its logs.

**Comment by prime3045** [comment]
@antoineco you rock!!
