### ISSUE TITLE
where does the log files stored for logstash and elasticsearch

### ISSUE THREAD

**Issue by daiyueweng** [deviantony/docker-elk#60]
Hi, I am wondering where are the log files for `logstash` and `elasticsearch` stored in the `docker`? I couldn't find them anywhere. There is no `elasticsearch/logs`.

cheers

**Comment by deviantony** [comment]
@daiyueweng what do you want the log files for? Do you know that you can access the logs using `docker-compose logs` ?

Or if you want you can also start the stack in the foreground using `docker-compose up` and the logs will be streamed.

**Comment by daiyueweng** [comment]
thanks, `docker-compose up` is very helpful.
