### ISSUE TITLE
Can't create an index with logstash

### ISSUE THREAD

**Issue by Gazzito** [deviantony/docker-elk#600]
I've seen that i need to mount a volume, and i did it. I don't know if it is well done but here it is the code.

docker-compose.yml:
--------------------------------------------------------------------------
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./csv
        target: /usr/share/logstash/csv
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:

pipeline config:
------------------------------------------------------------------------------------------
input {
	file {
		path =>"/csv/cidades.csv"
		start_position => "beginning"
		sincedb_path => "/dev/null"
	}
	
}

filter {

      csv {

         columns => ["cidade","codigo"]
      }

}

output {
	
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
		index => "cities"
	}
	stdout {}
	
}
-----------------------------------------------------------------

logstash logs 
![image](https://user-images.githubusercontent.com/87108769/124864425-c8bd0100-dfb0-11eb-8c3c-60c7f0358e69.png)

Please help me.

**Comment by antoineco** [comment]
@Gazzito I'm not seeing any error in the logs so I'm not sure I understand the problem, but if you mean that you're not receiving any data, you could look into this:

Your CSV file is mounted in `/usr/share/logstash/csv`, but the Logstash pipeline is configured to read from `/csv`.

**Comment by Gazzito** [comment]
So what does that means? Do i need to change the path in pipeline or in docker-compose.yml?

**Comment by Gazzito** [comment]
Would you help me by joining my virtual machine through teamviewer or anydesk? I'm kinda desperate. And its easier for you to help

**Comment by antoineco** [comment]
You can change the path of the CSV file in your pipeline's input to `/usr/share/logstash/csv/cidades.csv`, and things should start working.

Also, please double check that your file is located inside `docker-elk/csv/cidades.csv` (inside the Git repository), and that it can be read by the logstash user. Execute `chmod -v o+r docker-elk/csv/cidades.csv` in case you're not sure.

**Comment by Gazzito** [comment]
It didn't work... 
Thanks anyway for the help. I'm using tcp method to import data, i don't care.

**Comment by antoineco** [comment]
Unless you can share a clear error message I believe it's all I can suggest. Glad to hear you figured something out!
