### ISSUE TITLE
"message": "Not yet initialized (you may need to run sgadmin)

### ISSUE THREAD

**Issue by M-Matos** [deviantony/docker-elk#609]
Hi,  I am having this error on the elasticsearch container, please let me know what can i do to resolve this and start the cointainers. 
I Cloned this repository onto the Docker host and use the docker compose command
thanks 

{"type": "server", "timestamp": "2021-08-05T23:32:09,412Z", "level": "ERROR", "component": "c.f.s.a.BackendRegistry", "cluster.name": "docker-cluster", "node.name": "5af9849859b7", "message": "Not yet initialized (you may need to run sgadmin)", "cluster.uuid": "f64GOBrqTG-ifwH7cRcETg", "node.id": "niZ3SATiRSOL7Ni2KuJ6Fg"  }

**Comment by antoineco** [comment]
@M-Matos did you follow the instructions from the `searchguard` branch? (since you seem to be using Search Guard)

**Comment by M-Matos** [comment]
Hi Antoineco, Thanks for the fast responce. I believe I did, I am testing this in a new centos 7 vm. these are the steps I performed, please let me know if I am missing something or doing something wrong, this is the first time I am testing this. so please help me. 

1. I changed the selinux to permissive mode.  
2. then cloned the git to a folder created under /home/testuser/docker-elk
3. Run the docker-compose up -d command , docker created the images with no errors. 
4. then after elasticsearch is started run the docker-compose exec -T elasticsearch bin/init_sg.sh command.  I had to modify this command because for some reason docker compose is changing the name of the containers, instead of the elastic container be elasticsearch is docker-elk_elasticsearch_1 the same happends to the other containers. after changing the container name to the correct one the command executed with no errros, but still continue to see the error on the elasticsearch container "you may need to run sgadmin"
5. I am sure I must be missing something or doing something wrong,please let me know if you can help me. Thanks

**Comment by M-Matos** [comment]
Hi I found the problem,  if I execute the **"docker-compose exec -T elasticsearch bin/init_sg.sh"** for some reason the script did not run. but if I run the command with the full path of the script it worked "**docker-compose exec -T elasticsearch/ /usr/share/elasticsearch/bin/init_sg.sh"**.  that executed the scritpt. Thanks for all the great work you are doing here.

**Comment by antoineco** [comment]
@M-Matos thanks that's some useful feedback! Maybe there is something we need to fix there.
