### ISSUE TITLE
How to install x-pack without error

### ISSUE THREAD

**Issue by cutd** [deviantony/docker-elk#62]
I want use dockerelk install x-pack plugin,but when I installed find a error that I can't access to elasticsearch because I don't know account and password with elasticsearch so that report a authenticate exception.
What should I do to install x-pack.
All of these version is alpha-5.

**Comment by deviantony** [comment]
Please use the following branch if you want to play with X-Pack: https://github.com/deviantony/docker-elk/tree/x-pack and follow the instructions in the README.

Note, I just tested it it's compatible with alpha-5.

Also, if you have any trouble with it, an issue is currently open: #50
