### ISSUE TITLE
Adding TLS to this ELK container environment

### ISSUE THREAD

**Issue by ewitkop-panw** [deviantony/docker-elk#621]
Do we have any instructions on how to add TLS certificates to these containers. 

Can the file path to each cert be on the host?

Can we use the same priv/pub key pair on Kibana, elasticsearch, and filebeat?

**Comment by antoineco** [comment]
@ewitkop-panw there is a Git branch called `tls` that is linked in the README.
On this branch, you will find a version of this stack that has communications to Elasticsearch secured over TLS (Kibana -> ES, Logstash ->) with instructions on how to generate your own certificate.

Let me know if you need more assistance getting it to work.
You will need to rebuild all stack images (see README).

**Comment by ewitkop-panw** [comment]
It works great. Thanks!
