### ISSUE TITLE
cannot select indices on many kibana pages

### ISSUE THREAD

**Issue by ewitkop-panw** [deviantony/docker-elk#625]
I cannot select my indices on the alert page where you create alerts. I have all the fields I expect and @timestamp. I also created a new user named erik who is a super user, I cannot select an indices in the proper field. 

https://discuss.elastic.co/t/kibana-7-cant-load-index-pattern/180167/13

<img width="617" alt="error" src="https://user-images.githubusercontent.com/52043632/134418007-ba6618c9-2881-4949-ac53-72a486a635c5.png">

**Comment by antoineco** [comment]
Hi @ewitkop-panw, this issue isn't related to Docker, is it?

**Comment by ewitkop-panw** [comment]
It could be. It seems there is a bug in the versions of kibana/elastic.  Do you test on AWS? Perhaps pipeline provisioning doesn't work with these AWS values.

https://github.com/elastic/kibana/issues/102512

**Comment by antoineco** [comment]
The only thing we do here is connect the different components of the Elastic stack using containers. We don't provide support for Elastic's product or resolve bugs that occur inside those products.

If this is an identified bug in an Elastic product, I kindly ask you to continue the discussion in the issue trackers monitored by Elastic. Thank you for your understanding!

**Comment by ewitkop-panw** [comment]
Ok, thanks! Sorry about that.

On Fri, Sep 24, 2021 at 2:27 PM Antoine Cotten ***@***.***>
wrote:

> The only thing we do here is connect the different components of the
> Elastic stack using containers. We don't provide support for Elastic's
> product or resolve bugs that occur inside those products.
>
> If this is an identified bug in an Elastic product, I kindly ask you to
> continue the discussion in the issue trackers monitored by Elastic. Thank
> you for your understanding!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_deviantony_docker-2Delk_issues_625-23issuecomment-2D926837313&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=8fomxMtwNysMjJv0v9GCNSJ71gTlxnFMRn710LdxCmM&s=aeR9ah1oBjK12txMUtBQmGL2si6dAEUWNARHj2r5gy4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMNB64A4KKXRLFKSFORLA3LUDS7JBANCNFSM5ESGPP2A&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=8fomxMtwNysMjJv0v9GCNSJ71gTlxnFMRn710LdxCmM&s=5vUFa7pH3jdz-oQfRig4XfDtNN4TAdX8E4GZ3eSYNN8&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=8fomxMtwNysMjJv0v9GCNSJ71gTlxnFMRn710LdxCmM&s=xV5zM9VTgD8PXOq2FX8mpyH_y2F8ogssl9Kx8yCMhkA&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=bVyA4ImNgL43Q2UXlCGr3sMBg1TcSClSpBCjQ8q9PH8&m=8fomxMtwNysMjJv0v9GCNSJ71gTlxnFMRn710LdxCmM&s=kO2DOkVqdFONXrkpVuBuFgSwyNvoHqWN2l-LwRVPZPw&e=>.
>
>
-- 


Erik Witkop  |  DOD Systems Engineer | PCNSE CISSP GPEN

Palo Alto Networks  |  Boston, MA |  USA

Mobile: 603-490-3737  | www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.
