### ISSUE TITLE
ELK is not working with podman-compose, but containers running without any errors

### ISSUE THREAD

**Issue by ultymatom** [deviantony/docker-elk#626]
### Problem description

Hello !

Maybe this issue is really specific because it's more a podman related issue (in this case I understand that you cannot treat it but maybe someone who had this problem will see this issue and will be able to help me)

I'm using podman on windows, I have a podman remote client installed on my computer and a VM generated by minikube on the same host, whe I use podman-compose (a python script that read the docker-compose.yml to generate and execute the command needed to make work the multicontainer app)

the podman-compose script generate all these commands : 

`podman pod create --name=docker-elk-main --share net -p "5601:5601" -p "9600:9600" -p "5000:5000/tcp" -p "5044:5044" -p "5000:5000/udp" -p "9300:9300" -p "9200:9200"

podman volume inspect docker-elk-main_elasticsearch || podman volume create docker-elk-main_elasticsearch

podman run --name=docker-elk-main_elasticsearch_1 -d --pod=docker-elk-main --label io.podman.compose.config-hash=123 --label io.podman.compose.project=docker-elk-main --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=docker-elk-main --label com.docker.compose.project.working_dir=/tmp_shared_ctr/docker-elk-main --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=elasticsearch -e ES_JAVA_OPTS="-Xmx256m -Xms256m" -e ELASTIC_PASSWORD=changeme -e discovery.type=single-node -v ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro -v docker-elk-main_elasticsearch:/usr/share/elasticsearch/data --add-host elasticsearch:127.0.0.1 --add-host docker-elk-main_elasticsearch_1:127.0.0.1 --add-host logstash:127.0.0.1 --add-host docker-elk-main_logstash_1:127.0.0.1 --add-host kibana:127.0.0.1 --add-host docker-elk-main_kibana_1:127.0.0.1 docker-elk-main_elasticsearch

podman start docker-elk-main_elasticsearch_1

podman run --name=docker-elk-main_logstash_1 -d --pod=docker-elk-main --label io.podman.compose.config-hash=123 --label io.podman.compose.project=docker-elk-main --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=docker-elk-main --label com.docker.compose.project.working_dir=/tmp_shared_ctr/docker-elk-main --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=logstash -e LS_JAVA_OPTS="-Xmx256m -Xms256m" -v ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro -v ./logstash/pipeline:/usr/share/logstash/pipeline:ro --add-host elasticsearch:127.0.0.1 --add-host docker-elk-main_elasticsearch_1:127.0.0.1 --add-host logstash:127.0.0.1 --add-host docker-elk-main_logstash_1:127.0.0.1 --add-host kibana:127.0.0.1 --add-host docker-elk-main_kibana_1:127.0.0.1 docker-elk-main_logstash

podman start docker-elk-main_logstash_1

podman run --name=docker-elk-main_kibana_1 -d --pod=docker-elk-main --label io.podman.compose.config-hash=123 --label io.podman.compose.project=docker-elk-main --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=docker-elk-main --label com.docker.compose.project.working_dir=/tmp_shared_ctr/docker-elk-main --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=kibana -v ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro --add-host elasticsearch:127.0.0.1 --add-host docker-elk-main_elasticsearch_1:127.0.0.1 --add-host logstash:127.0.0.1 --add-host docker-elk-main_logstash_1:127.0.0.1 --add-host kibana:127.0.0.1 --add-host docker-elk-main_kibana_1:127.0.0.1 docker-elk-main_kibana

podman start docker-elk-main_kibana_1`

all commands executed succesfully, and when i list all my container, the three of them are running correctly, but qwhen I try to connect to kibana on my browser I've got the same error as if nothing was running. (for information I made it run with docker desktop on another computer and it works perfectly, also this is not the first time I'm using podman-compose, and previous time it worked succesfully but wih more basic app)

When I want to get the logs of each containers it's like they started and after some seconds they just paused

Again sorry if this is not something related to this app but this is a call for help, as I'm new with containers (I cannot switch to docker desktop, for some reason I have to use podman), but if you can't help me with that I would totally get it.

Thank you in advance for your time

#### Stack configuration

I downloaded the "main" version (on 22th of september", and I did not change anything

#### Docker setup

podman --version
podman version 2.2.1

podman-compose --version
podman-composer version  0.1.7dev

Please paste the full output of the `docker-compose version` command below.

#### Container logs

`podman logs docker-elk-main_elasticsearch_1
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore

podman logs docker-elk-main_logstash_1
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

 podman logs docker-elk-main_kibana_1
(I did not forget the output, the output is empty)`

EDIT:

Kibana logs after some time (don"t have precise duration but I would say between 5 and 10 minutes)
But I guess this is because it can"t contact elasticsearch.

{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["info","plugins-service"],"pid":1217,"message":"Plugin \"metricsEntities\" is disabled."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","config","deprecation"],"pid":1217,"message":"Setting [elasticsearch.username] to \"elastic\" is deprecated. You should use the \"kibana_system\" user instead."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","config","deprecation"],"pid":1217,"message":"plugins.scanDirs is deprecated and is no longer used"}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","config","deprecation"],"pid":1217,"message":"Config key [monitoring.cluster_alerts.email_notifications.email_address] will be required for email notifications to work in 8.0.\""}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","config","deprecation"],"pid":1217,"message":"Setting [monitoring.username] to \"elastic\" is deprecated. You should use the \"kibana_system\" user instead."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","config","deprecation"],"pid":1217,"message":"\"xpack.reporting.roles\" is deprecated. Granting reporting privilege through a \"reporting_user\" role will not be supported starting in 8.0. Please set \"xpack.reporting.roles.enabled\" to \"false\" and grant reporting privileges to users using Kibana application privileges **Management > Security > Roles**."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["info","http","server","NotReady"],"pid":1217,"message":"http server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["info","plugins-system"],"pid":1217,"message":"Setting up [106] plugins: [translations,taskManager,licensing,globalSearch,globalSearchProviders,banners,licenseApiGuard,code,usageCollection,xpackLegacy,telemetryCollectionManager,telemetryCollectionXpack,kibanaUsageCollection,securityOss,share,screenshotMode,telemetry,newsfeed,mapsEms,mapsLegacy,legacyExport,kibanaLegacy,embeddable,uiActionsEnhanced,expressions,charts,esUiShared,bfetch,data,savedObjects,visualizations,visTypeXy,visTypeVislib,visTypeTimelion,features,visTypeTagcloud,visTypeTable,visTypePie,visTypeMetric,visTypeMarkdown,tileMap,regionMap,presentationUtil,timelion,home,searchprofiler,painlessLab,grokdebugger,graph,visTypeVega,management,watcher,licenseManagement,indexPatternManagement,advancedSettings,discover,discoverEnhanced,dashboard,dashboardEnhanced,visualize,visTypeTimeseries,savedObjectsManagement,spaces,security,transform,savedObjectsTagging,lens,reporting,canvas,lists,ingestPipelines,fileUpload,maps,dataVisualizer,encryptedSavedObjects,dataEnhanced,timelines,dashboardMode,cloud,upgradeAssistant,snapshotRestore,fleet,indexManagement,rollup,remoteClusters,crossClusterReplication,indexLifecycleManagement,enterpriseSearch,eventLog,actions,alerting,triggersActionsUi,stackAlerts,ruleRegistry,osquery,ml,cases,securitySolution,observability,uptime,infra,monitoring,logstash,console,apmOss,apm]"}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["info","plugins","taskManager"],"pid":1217,"message":"TaskManager is identified by the Kibana UUID: c58e052d-3e2c-4dc7-8177-5187074b56a2"}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","security","config"],"pid":1217,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","security","config"],"pid":1217,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","reporting","config"],"pid":1217,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","reporting","config"],"pid":1217,"message":"Chromium sandbox provides an additional layer of protection, but is not supported for Linux CentOS 8.4.2105\n OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","encryptedSavedObjects"],"pid":1217,"message":"Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","actions","actions"],"pid":1217,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["warning","plugins","alerting","plugins","alerting"],"pid":1217,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2021-09-23T10:27:47+00:00","tags":["info","plugins","ruleRegistry"],"pid":1217,"message":"Write is disabled, not installing assets"}
{"type":"log","@timestamp":"2021-09-23T10:27:48+00:00","tags":["info","savedobjects-service"],"pid":1217,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2021-09-23T10:27:48+00:00","tags":["error","savedobjects-service"],"pid":1217,"message":"Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 127.0.0.1:9200"}

**Comment by antoineco** [comment]
Thanks for the detailed report 🙌  We don't officially test this stack with Podman but it would certainly be nice to know that it works with it.

I see Kibana is trying to contact Elasticsearch at `127.0.0.1:9200`, which should be reachable inside the pod.

Are you able to query the Elasticsearch API?

**Comment by ultymatom** [comment]
I can't contact the API, but I've just noticed something that can be the answer, I've checked the memory left I have, and it seems that everything is used, so I'm gonna try to change the parameter of my VM so that I'm sure it' not a memory related issue

![image](https://user-images.githubusercontent.com/90399827/134496691-ae6ef7d6-0708-4a31-8cd4-6096ece40a3a.png)

**Comment by ultymatom** [comment]
Ok I'lm just stupid, I doubled the memory of my VM, Now I can acces kibana HMI, I did not try everything functionality, but it seems to be working well !

Sorry for opening a useless issue
