### ISSUE TITLE
Kibana menu isn't loaded when accessing remotely

### ISSUE THREAD

**Issue by andreroggeri** [deviantony/docker-elk#633]
### Problem description
I've deployed the ELK on a AWS EC2 machine, but after logging in the menu doesn't load.

But if I access via SSH port forwarding  to my localhost the kibana loads normally

### Extra information
Screenshot accessing the host directly
![image](https://user-images.githubusercontent.com/6232673/139460879-8db4bd11-52b1-458c-9d4c-c7bcb2403a37.png)

Screenshot accessing "locally" using port forwarding
![image](https://user-images.githubusercontent.com/6232673/139460951-f3794786-b731-4573-a8f8-e62e8ab27b92.png)

#### Stack configuration
```console
$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 669e337..872cb08 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -24,7 +24,7 @@ services:
       # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
       discovery.type: single-node
     networks:
-      - elk
+      - jenkins_default

   logstash:
     build:
@@ -48,7 +48,7 @@ services:
     environment:
       LS_JAVA_OPTS: "-Xmx256m -Xms256m"
     networks:
-      - elk
+      - jenkins_default
     depends_on:
       - elasticsearch

@@ -63,15 +63,16 @@ services:
         target: /usr/share/kibana/config/kibana.yml
         read_only: true
     ports:
-      - "5601:5601"
+      - "9000:5601"
     networks:
-      - elk
+      - jenkins_default
     depends_on:
       - elasticsearch

 networks:
-  elk:
+  jenkins_default:
     driver: bridge
+    external: true

 volumes:
   elasticsearch:
```

#### Docker setup
```console
$ docker version
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Oct 12 18:51:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Mon Oct 12 18:51:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

#### Container logs
The relevant logs that I found is that some authentication is failing on ES  everytime I reload kibana home screen:

```console
$ docker-compose logs

elasticsearch_1  | {"type": "server", "timestamp": "2021-10-29T15:11:38,986Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "49f4275839ea", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "c7iF3jgPTqulEG-_bfMbBA", "node.id": "ax__9_WXQ0WkPmxnhoYUig"  }
elasticsearch_1  | {"type": "server", "timestamp": "2021-10-29T15:11:41,485Z", "level": "INFO", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "49f4275839ea", "message": "Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]", "cluster.uuid": "c7iF3jgPTqulEG-_bfMbBA", "node.id": "ax__9_WXQ0WkPmxnhoYUig"  }
```

**Comment by antoineco** [comment]
@andreroggeri My attempts to reproduce the issue haven't been successful so far.

What I did:

1. Ran a fresh VM (which in my case is available at `<VM_NAME>.mshome.net` or the IP address `172.19.160.1`)
1. Installed Docker (`20.10.8`, although the version doesn't matter here)
1. Performed the same port replacement as you did:

    ```diff
         ports:
    -      - "5601:5601"
    +      - "9000:5601"
    ```

1. Ran the stack with `docker-compose up`
1. Opened my web browser at both `http://<VM_NAME>.mshome.net:9000` (and `http://172.19.160.1:9000`, just to be sure)
1. Logged in

I am able to navigate to the dashboard after logging in, and to use all the views I usually use ("Management", "Discover", ...):

![image](https://user-images.githubusercontent.com/3299086/139538960-ad196a83-254d-416c-a054-2167a222a866.png)

I am noticing that Kibana is warning me about the [`server.publicBaseUrl`](https://www.elastic.co/guide/en/kibana/current/settings.html#server-publicBaseUrl) setting not being set (bottom right corner in the screenshot), but it doesn't seem to affect anything in my case.

What I would try if I were you:

- Set `server.publicBaseUrl` to `http://${VM_PUBLIC_IP}:9000` (replace with your own public IP address), restart Kibana and see if it helps.
- Clear the web browser's cache and cookies for this specific site, or try in "private mode", or simply use your web browser's keyboard shortcut for ["hard refresh"](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache) right after opening Kibana.

Let me know if any of these help.

If not, could it be that you ran Elasticsearch in the past using docker-elk, then tried to re-create the stack without clearing the volume used by Elasticsearch?

**Comment by antoineco** [comment]
@andreroggeri Did you get a chance to try any of my suggestions? Without further input I'm afraid I'm unable reproduce this issue and provide further assistance (but I'm still curious to know what happened!).

**Comment by andreroggeri** [comment]
Sorry for the delay...

Yes, I tried to set the property `server.publicBaseUrl` and private navigation with no avail

I spun a new instance on my private AWS account and it did work properly, so it must be something on the current instance or the network that is making it fail on the authentication.

Thank you very much for you help, I'll keep digging and report back here if I find something, but will close this issue for now

**Comment by antoineco** [comment]
Appreciate the feedback, and glad to hear it works in another account. Cheers!

**Comment by andreroggeri** [comment]
Just coming back for a feedback.

Its working now 🤷 


Probably after a reboot on the host and things started to work
