### ISSUE TITLE
Unable to start docker-elk

### ISSUE THREAD

**Issue by VolhvPorechja** [deviantony/docker-elk#64]
Disabling SELinux not issue for me. But 
```
.-root@centos ~
-$ chcon -R system_u:object_r:admin_home_t:s0 docker-elk/
```
doesn't help. It still can't get access

```
kibana_1         | FATAL CLI ERROR Error: EACCES: permission denied, open '/opt/kibana/config/kibana.yml'
kibana_1         |     at Error (native)
kibana_1         |     at Object.fs.openSync (fs.js:549:18)
kibana_1         |     at Object.fs.readFileSync (fs.js:397:15)
kibana_1         |     at module.exports (/opt/kibana/src/cli/serve/read_yaml_config.js:52:31)
kibana_1         |     at Command.callee$1$0$ (/opt/kibana/src/cli/serve/serve.js:67:22)
kibana_1         |     at tryCatch (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
kibana_1         |     at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
kibana_1         |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
kibana_1         |     at invoke (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:136:37)
kibana_1         |     at enqueueResult (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:185:17)
kibana_1         |     at new Promise (/opt/kibana/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:201:7)
kibana_1         |     at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/opt/kibana/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
kibana_1         |     at AsyncIterator.enqueue (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:184:12)
kibana_1         |     at AsyncIterator.prototype.(anonymous function) [as next] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
kibana_1         |     at Object.runtime.async (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:209:12)
kibana_1         |     at Command.callee$1$0 (/opt/kibana/src/cli/serve/serve.js:51:32)
logstash_1       | {:timestamp=>"2016-09-02T14:20:02.365000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}
dockerelk_logstash_1 exited with code 1
```

What means .-root@centos ~ ?? Is that means that chcon should be executed under root??
Under what user should be executed docker-compose run??

**Comment by deviantony** [comment]
Strange, can you verify the permissions of the folders/file?

Should be:

* 775 for `logstash/config` and `kibana/config` folders
* 664 for `logstash/config/logstash.conf` and `kibana/config/kibana.yml` file

About the user, this depends of your system. I can use it with my user on my system (no root).

For the `chcon`, I guess that it should be executed with the user used to start the docker-compose stack.

**Comment by deviantony** [comment]
Also looks like there are some simillarities with #59

**Comment by VolhvPorechja** [comment]
No any changes.

[ishikawa@localhost docker-elk]$ ls -lZ -R
.:
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 docker-compose.yml
drwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 elasticsearch
drwxrwxr-x. ishikawa ishikawa system_u:object_r:admin_home_t:s0 kibana
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 LICENSE
drwxrwxr-x. ishikawa ishikawa system_u:object_r:admin_home_t:s0 logstash
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 README.md

./elasticsearch:
drwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 config

./elasticsearch/config:

./kibana:
drwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 config
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 Dockerfile
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 entrypoint.sh

./kibana/config:
-rw-rw-r--. ishikawa ishikawa system_u:object_r:admin_home_t:s0 kibana.yml

./logstash:
drwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 config
-rwxrwxrwx. ishikawa ishikawa system_u:object_r:admin_home_t:s0 Dockerfile

./logstash/config:
-rw-rw-r--. ishikawa ishikawa system_u:object_r:admin_home_t:s0 logstash.conf

[ishikawa@localhost docker-elk]$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 

[ishikawa@localhost docker-elk]$ sudo docker-compose up
Starting dockerelk_elasticsearch_1
Starting dockerelk_logstash_1
Starting dockerelk_kibana_1
Attaching to dockerelk_elasticsearch_1, dockerelk_logstash_1, dockerelk_kibana_1
kibana_1         | Stalling for Elasticsearch
elasticsearch_1  | [2016-09-03 10:56:38,652][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
elasticsearch_1  | [2016-09-03 10:56:39,214][INFO ][node                     ] [Douglas Birely] version[2.4.0], pid[1], build[ce9f0c7/2016-08-29T09:14:17Z]
elasticsearch_1  | [2016-09-03 10:56:39,214][INFO ][node                     ] [Douglas Birely] initializing ...
elasticsearch_1  | [2016-09-03 10:56:40,735][INFO ][plugins                  ] [Douglas Birely] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | [2016-09-03 10:56:40,885][INFO ][env                      ] [Douglas Birely] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/centos-root)]], net usable_space [31.5gb], net total_space [37.3gb], spins? [possibly], types [xfs]
elasticsearch_1  | [2016-09-03 10:56:40,885][INFO ][env                      ] [Douglas Birely] heap size [1007.3mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2016-09-03 10:56:46,094][INFO ][node                     ] [Douglas Birely] initialized
elasticsearch_1  | [2016-09-03 10:56:46,094][INFO ][node                     ] [Douglas Birely] starting ...
elasticsearch_1  | [2016-09-03 10:56:46,516][INFO ][transport                ] [Douglas Birely] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2016-09-03 10:56:46,527][INFO ][discovery                ] [Douglas Birely] elasticsearch/7N8q5ZDpTgarmaT2oOogxQ
elasticsearch_1  | [2016-09-03 10:56:49,682][INFO ][cluster.service          ] [Douglas Birely] new_master {Douglas Birely}{7N8q5ZDpTgarmaT2oOogxQ}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1  | [2016-09-03 10:56:49,764][INFO ][http                     ] [Douglas Birely] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2016-09-03 10:56:49,764][INFO ][node                     ] [Douglas Birely] started
kibana_1         | Starting Kibana
elasticsearch_1  | [2016-09-03 10:56:49,943][INFO ][gateway                  ] [Douglas Birely] recovered [2] indices into cluster_state
elasticsearch_1  | [2016-09-03 10:56:51,323][INFO ][cluster.routing.allocation] [Douglas Birely] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[logstash-2016.09.02][2], [logstash-2016.09.02][2], [.kibana][0]] ...]).
logstash_1       | {:timestamp=>"2016-09-03T10:56:53.123000+0000", :message=>"No config files found: /etc/logstash/conf.d/logstash.conf\nCan you make sure this path is a logstash config file?", :level=>:error}
kibana_1         | FATAL CLI ERROR Error: EACCES: permission denied, open '/opt/kibana/config/kibana.yml'
kibana_1         |     at Error (native)
kibana_1         |     at Object.fs.openSync (fs.js:549:18)
kibana_1         |     at Object.fs.readFileSync (fs.js:397:15)
kibana_1         |     at module.exports (/opt/kibana/src/cli/serve/read_yaml_config.js:52:31)
kibana_1         |     at Command.callee$1$0$ (/opt/kibana/src/cli/serve/serve.js:67:22)
kibana_1         |     at tryCatch (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:67:40)
kibana_1         |     at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:315:22)
kibana_1         |     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
kibana_1         |     at invoke (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:136:37)
kibana_1         |     at enqueueResult (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:185:17)
kibana_1         |     at new Promise (/opt/kibana/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:201:7)
kibana_1         |     at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/opt/kibana/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
kibana_1         |     at AsyncIterator.enqueue (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:184:12)
kibana_1         |     at AsyncIterator.prototype.(anonymous function) [as next] (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:100:21)
kibana_1         |     at Object.runtime.async (/opt/kibana/node_modules/babel-runtime/regenerator/runtime.js:209:12)
kibana_1         |     at Command.callee$1$0 (/opt/kibana/src/cli/serve/serve.js:51:32)
dockerelk_logstash_1 exited with code 1
dockerelk_kibana_1 exited with code 1

**Comment by VolhvPorechja** [comment]
Looks like labeling volumes solves problem. https://docs.docker.com/engine/tutorials/dockervolumes/#/volume-labels
