### ISSUE TITLE
logstash: [ERROR][logstash.javapipeline    ][main][] A plugin had an unrecoverable error. Will restart this plugin.   Pipeline_id:main

### ISSUE THREAD

**Issue by maryamkh** [deviantony/docker-elk#641]

**Comment by antoineco** [comment]
The error message is correct. As indicated in the README, port 9600 is already assigned to Logstash's Monitoring API.

More info in the Elastic documentation at: https://www.elastic.co/guide/en/logstash/current/monitoring-logstash.html

**Comment by maryamkh** [comment]
Hi @antoineco 
Thank you so much for your answer. I've tried to follow the template as much as possible, I have not used docket and therefore I did not write anything about docker part in the template. Could you please let me know what other info you need  that I can provide you with?
Thanks

**Comment by antoineco** [comment]
I'm a bit confused, you're not using the software from this repo?

**Comment by maryamkh** [comment]
Oh! No Sorry! I was searching for a solution and I found similar issues reported here. And I also saw that this repo is connected to Elasticsearch forum. So I thought it is ES related repo. That is why I asked here! I am sorry! I will delete my issue.

**Comment by antoineco** [comment]
Closing because all comments were removed (and the original question wasn't related to docker-elk to start with).
