### ISSUE TITLE
Kibana fails to build

### ISSUE THREAD

**Issue by Dr-Jerm** [deviantony/docker-elk#65]
On running docker-compose up as root I get the following error:
```
Optimizing and caching browser bundles...
Killed
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c kibana plugin --install elastic/sense' returned a non-zero code: 137

```

**Comment by deviantony** [comment]
@Dr-Jerm hey, did you retry after that? This may be cause by the Elastic servers being temporarly unavailable.

**Comment by Dr-Jerm** [comment]
Hey, so pretty sure the issue was my Digital Ocean micro instance running out of memory standing everything up. Upping to a Gig of memory and some swap space resolved the issue.
