### ISSUE TITLE
How to configure TLS for filebeat

### ISSUE THREAD

**Issue by GRiverone** [deviantony/docker-elk#655]
### Problem description
Refer to the [TLS certificates](https://github.com/deviantony/docker-elk/blob/tls/tls/README.md),  I have successfully started the ELK cluster using the files of the tls branch. But I encountered a problem, which certificate should I use in the filebeat configuration to connect to the ES cluster normally. The filebeat log tells me `Get "https://x.x.x.x:9200": x509: certificate signed by unknown authority`

I saw this [article](https://www.elastic.co/guide/en/beats/filebeat/7.16/configuration-ssl.html#key) on the ES official website, but I don’t have the files `cert.pem` and `cert.key` in the example, How can I get them, thanks.

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:44:05 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker-compose version

Docker Compose version v2.2.2
```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by antoineco** [comment]
Good catch, Filebeat isn't configured properly for TLS.
The configuration should look like this:

https://github.com/deviantony/docker-elk/blob/9e280d8dc3a56174e1406bab7824d4e179256469/extensions/metricbeat/config/metricbeat.yml#L34-L39

I'll fix it!

**Comment by antoineco** [comment]
Fixed on the `tls` branch ([diff](https://github.com/deviantony/docker-elk/compare/b417ab9b5dbf37683e74a324c1c1d7560f5e71cd..62fdd7c6b92d231926a38d85ad7a47134f774dcf))
