### ISSUE TITLE
TLS: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by TmyWu** [deviantony/docker-elk#659]
I can't seem to get HTTPS to work.
I have tried to do it with and without generating new certs.
when I try to visit it with https I get SSL_ERROR_RX_RECORD_TOO_LONG
Help??

**Comment by antoineco** [comment]
> when I try to visit it with https

What is "it"?

If you're referring to Kibana, only the communications **from Kibana to Elasticsearch** are secured. Kibana itself doesn't expose a HTTPS endpoint.

To do that, we would have to include a sample TLS certificate for Kibana in this project, and users would have to manually add it to their web browsers in order for it to be considered as trusted. Without this extra step, the browser would throw a warning which would confuse a lot of people.

You can use a service such as Letsencrypt to generate a free and trusted TLS certificate, then use that certificate in Kibana as described at https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-basic-setup-https.html#encrypt-kibana-browser

**Comment by TmyWu** [comment]
Oh... yes you're right. 
Thank you for your help.

**Comment by antoineco** [comment]
For posterity, there is now [a new section inside `tls/README.md`](https://github.com/deviantony/docker-elk/tree/945d1a341f4549c6bba0fe6bf4aa623612178bae/tls#kibana-server-certificate-optional) which explains how to enable TLS in the Kibana server (between web browsers and Kibana), as well as a sample certificate and key which Kibana is pre-configured to use when TLS is enabled.
