### ISSUE TITLE
[Solved] Anomalies with date parsing/restitution/sync in Kibana search

### ISSUE THREAD

**Issue by githule** [deviantony/docker-elk#663]
### Problem description
- Cant find logs in any Kibana view with no explanation
 - New docs where added to the ES from logstash from the index statistics (so not a logstash/log source issue)
 - Inability to search in index with the time filter in Kibana.
- When I rebuilt the index pattern **without time field** I was then able to list documents.
 - Date parsing worked well at the logstash level as seen in the stored docs.

### Extra information

As a solution, I added the following lines to the volumes of the different containers in docker-compose
`      - /etc/localtime/:/etc/localtime:ro`

I spent a day to solve this issue. 

I think it's because the container may have lost it's own timesource.

although, I cant say precisely why this issue happened, the workaround worked so I sent this issue to community if it can help.

#### Docker setup

I am using a stack via portainer but this is quite the same a a docker compose configuration.

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by antoineco** [comment]
I've heard some problems could arise with containers because they don't share the timezone configuration of the host, but I've never encountered something like that. Thanks for sharing!

Out of curiosity, if you force Kibana's time range selector to use the UTC timezone instead of your browser's timezone (the default), does it change anything?

**Comment by antoineco** [comment]
Closing because the issue was solved.

I'm expecting this issue to pop in the search results in case someone is looking for something related.

**Comment by githule** [comment]
> I've heard some problems could arise with containers because they don't share the timezone configuration of the host, but I've never encountered something like that. Thanks for sharing!
> 
> Out of curiosity, if you force Kibana's time range selector to use the UTC timezone instead of your browser's timezone (the default), does it change anything?

Sorry I don't have much time to re-trigger the issue and check this as it is stabilized.
I will try to trigger this issue if I deploy some new backup/test platform. But as I said It worked at the begging and failed after few days/weeks so not sure to get the same conditions.
