### ISSUE TITLE
SearchGuard update

### ISSUE THREAD

**Issue by gijs007** [deviantony/docker-elk#665]
The SearchGuard ELK stack variant is outdated, the latest version of SearchGuard supports ELK 7.16.3: https://docs.search-guard.com/latest/search-guard-versions

Are there any plans to update this variant?

**Comment by antoineco** [comment]
I can do that 👍
I'll push an update in the next few days. Meanwhile it is possible to use a more recent version by simply changing the `.env` file.

**Comment by antoineco** [comment]
The `searchguard` branch is now updated to the default to the latest version.
