### ISSUE TITLE
why changed kibana's user???

### ISSUE THREAD

**Issue by LongTaiJun** [deviantony/docker-elk#669]
{"type":"log","@timestamp":"2022-02-14T06:06:23+00:00","tags":["warning","plugins","alerting"],"pid":7,"message":"APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command."}
{"type":"log","@timestamp":"2022-02-14T06:06:23+00:00","tags":["info","plugins","ruleRegistry"],"pid":7,"message":"Installing common resources shared between all indices"}
{"type":"log","@timestamp":"2022-02-14T06:06:24+00:00","tags":["info","plugins","reporting","config"],"pid":7,"message":"Chromium sandbox provides an additional layer of protection, and is supported for Linux Ubuntu 20.04 OS. Automatically enabling Chromium sandbox."}
{"type":"log","@timestamp":"2022-02-14T06:06:27+00:00","tags":["error","elasticsearch-service"],"pid":7,"message":"Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.22.0.2:9200"}
{"type":"log","@timestamp":"2022-02-14T06:06:45+00:00","tags":["warning","process"],"pid":7,"message":"Error [ProductNotSupportedSecurityError]: The client is unable to verify that the server is Elasticsearch due to security privileges on the server side. Some functionality may not be compatible if the server is running an unsupported product.\n    at /usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:576:19\n    at onBody (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:369:9)\n    at IncomingMessage.onEnd (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)\n    at IncomingMessage.emit (node:events:402:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
{"type":"log","@timestamp":"2022-02-14T06:06:45+00:00","tags":["error","elasticsearch-service"],"pid":7,"message":"Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]"}

kibana is not login!!!

changed file:
[root@test-124 docker-elk]# cat kibana/config/kibana.yml 
---
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic     #why change this user?
elasticsearch.password: 'changeme'

**Comment by antoineco** [comment]
It's a new restriction from Elastic v8. It is technically not possible anymore to use the `elastic` user to authenticate Kibana, and docker-elk has unfortunately **no control over this**.

From the README:

> **:warning: Starting with Elastic v8.0.0, it is no longer possible to run Kibana using the bootstraped privileged
`elastic` user. If you are starting the stack for the very first time, you MUST initialize a password for the [built-in
`kibana_system` user][builtin-users] to be able to start and access Kibana. Please read the section below attentively.**
> -- https://github.com/deviantony/docker-elk/blob/641290c2/README.md#initial-setup

**Comment by LongTaiJun** [comment]
[root@test-124 docker-elk]# $ docker-compose exec -T elasticsearch bin/elasticsearch-reset-password --batch --user elastic
-bash: $: command not found

Why can't it be enforced?

root@4032f43cd34c:/usr/share/elasticsearch# elasticsearch
elasticsearch                     elasticsearch-geoip               elasticsearch-setup-passwords
elasticsearch-certgen             elasticsearch-keystore            elasticsearch-shard
elasticsearch-certutil            elasticsearch-migrate             elasticsearch-sql-cli
elasticsearch-cli                 elasticsearch-node                elasticsearch-sql-cli-7.17.0.jar
elasticsearch-croneval            elasticsearch-plugin              elasticsearch-syskeygen
elasticsearch-env                 elasticsearch-saml-metadata       elasticsearch-users

**Comment by antoineco** [comment]
@LongTaiJun it looks like you are using Elastic **v7** images, but the `main` branch is now **v8**. For every new version, you MUST update your Docker images by rebuilding them with `docker-compose build`.

If you want to stay on v7, you don't need to switch to the `kibana_system` user, you can keep using the `elastic` user. In this case, please [switch to the `release-7.x` branch](https://github.com/deviantony/docker-elk/blob/641290c2/README.md#version-selection) and rebuild your Docker images with `docker-compose build`.

Everything I've mentioned here is in the README. I highly recommend reading at least the whole `Usage` section before using docker-elk, since it contains important information: https://github.com/deviantony/docker-elk/blob/641290c2/README.md#usage

**Comment by LongTaiJun** [comment]
ok，thanks，I found the problem.

**Comment by a-fly-fly-bird** [comment]
> Duplicate if #666.
> 
> It's a new restriction from Elastic v8. It is technically not possible anymore to use the `elastic` user to authenticate Kibana, and docker-elk has unfortunately **no control over this**.
> 
> From the README:
> 
> > **⚠️ Starting with Elastic v8.0.0, it is no longer possible to run Kibana using the bootstraped privileged
> > `elastic` user. If you are starting the stack for the very first time, you MUST initialize a password for the built-in
> > `kibana_system` user to be able to start and access Kibana. Please read the section below attentively.**
> > -- https://github.com/deviantony/docker-elk/blob/641290c2/README.md#initial-setup

or just change the default password of `elastic` and then you can login with it.

**Comment by antoineco** [comment]
@a-fly-fly-bird the issue was not about logging in as the `elastic` user. The issue was about **connecting Kibana to Elasticsearch** using the `elastic` user.
