### ISSUE TITLE
elk_setup failed with permission denied error

### ISSUE THREAD

**Issue by ericzhf** [deviantony/docker-elk#676]
### Problem description
Hi, I'm running this new 8.0.0 version for the first time (removed all old containers and images), but I'm getting permission denied error for elk_setup, all other containers are running just fine but without this initial setup kibana won't start. 

[root@ericsandbox elk]# docker-compose up -d
Creating network "elk_elk" with driver "bridge"
Creating volume "elk_setup" with default driver
Creating volume "elk_elasticsearch" with default driver
Creating elk_elasticsearch_1 ... done
**Creating elk_setup_1         ... error**
Creating elk_logstash_1      ...
Creating elk_kibana_1        ...

Creating elk_logstash_1      ... done
Creating elk_kibana_1        ... done

ERROR: for setup  Cannot start service setup: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown

#### Stack configuration

all files untouched, only changed license from "trial" to "basic"

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:44 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```console
$ docker-compose version

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by antoineco** [comment]
@ericzhf thanks for reporting :+1:

To me, it seems like the executable flag of the
 `setup/entrypoint.sh` file wasn't preserved while cloning the repository.

Could you please check with the command `ls -l setup/entrypoint.sh`? It should contain the `x` permission.

If not, you can fix the permission with `chmod +x setup/entrypoint.sh`, then rebuild the image with `docker-compose build setup`.

**Comment by ericzhf** [comment]
@antoineco yep, you were right, it doesn't have x permission:

_[root@ericsandbox elk]# ls -l setup/entrypoint.sh
-rw-r--r-- 1 root root 1930 Feb 21 02:19 setup/entrypoint.sh

and your solution solved the issue, thanks!

**Comment by antoineco** [comment]
Sweet!

May I ask how you obtained the code? Did you download an archive, or did you clone using `git`?
Git should always preserve the executable attribute.

**Comment by 120dev** [comment]
Thank you very much for this tip, I see I'm not the only one right now :))

**Comment by antoineco** [comment]
@120dev interesting. Could you please shed lights on how you downloaded the code? https://github.com/deviantony/docker-elk/issues/676#issuecomment-1049844333

**Comment by ericzhf** [comment]
@antoineco I downloaded the code rirectly (Code - Download ZIP) because I didn't intall git on my server, I guess that's why most people doesn't have this issuse if they use git clone.

**Comment by antoineco** [comment]
OK thanks for clarifying. It seems like Zip archives need to be extracted with extra options for file permissions to be preserved.

I'll add a `chmod +x` inside the Dockerfile to avoid that situation to users.
