### ISSUE TITLE
`logstash_writer` role does not have permission to `logstash` index

### ISSUE THREAD

**Issue by panos-indev** [deviantony/docker-elk#679]
### Problem description
When running the docker-compose with elastic stack version 7.17.0, the permissions defined in the role defined on /setup/roles/logstash_writer.json are not complete. This makes logstash throw an error when connecting to elasticsearch.

In order to fix the issue, the role must be provided with access to the "logstash" index as well.

#### Stack configuration
ELASTIC_VERSION=7.17.0

#### Docker setup

Docker version:
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:36 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Docker compose version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by antoineco** [comment]
@panos-indev thanks for investigating this. 

First of all, a word of advice: the `release-7.x` branch doesn't have the `setup` service and is using the `elastic` user to connect to Elasticsearch by default.
I do not recommend using the `main` branch to run the v7 release version of the Elastic stack as some configuration settings may differ.

With that being said, you're raising a good point. We probably _should_ use the `setup` service to initialize v7 too, as we want people to use unprivileged users as much as possible.

I'll work on enabling the `setup` service on the `release-7.x` branch and incorporate your recommendation 🙌

**Comment by antoineco** [comment]
Related: https://github.com/elastic/logstash/issues/10722
