### ISSUE TITLE
Fix the docker compose version

### ISSUE THREAD

**Issue by eabykov** [deviantony/docker-elk#684]
In `README.md` the screenshot shows an example from the version of Docker Composer V2, and below in the section `Host setup` you are talking about an older version `[Docker Compose](https://docs.docker.com/compose/install/) version 1.26.0 or newer`

Need to replace with
- old `[Docker Compose](https://docs.docker.com/compose/install/) version 1.26.0 or newer`
- new `[Docker Compose](https://docs.docker.com/compose/cli-command/#installing-compose-v2) version 2.3.2 or newer`

**Comment by eabykov** [comment]
@antoineco but in the [official Docker Compose repository](https://github.com/docker/compose) they write
> Docker Compose V2 is a major version bump release of Docker Compose

The fact is that the commands are even different in docker compose version 1 and version 2
- v1 - `docker-compose up -d`
- v2 - `docker compose up -d` etc.

In the gif picture you show how compose version 2 works, and below write about version 1, but they are different, my emphasis was on the fact that the documentation should be for one specific version, and not one thing in the picture, but another in the text, if I put version 1 and try to execute a command from the picture, I will not succeed
> The installation instructions for Compose V2 differ from V1. V2 is not a standalone binary anymore, and installation scripts will have to be adjusted. Some commands are different.

**Comment by eabykov** [comment]
@antoineco you even have tests on the v2 of Compose, and even the latest https://github.com/deviantony/docker-elk/commit/12dc0a4b74b2e983af36e4e2b04cead202427e85

**Comment by antoineco** [comment]
Yes but we support BOTH versions, v1 and v2. They are fully inter-compatible. On macOS and Windows, `docker-compose` is even an alias for Compose v2 by default, so the hyphen between `docker` and `compose` is only syntactic sugar. I could re-add it to the Gif if that would feel less confusing.

What we indicate in our README is the **minimum requirement** ("v1.26.0 **or newer**"). A majority of users still use v1 from what we see in issue reports, and that's perfectly OK.

Again, the fact that we use a recent version in our Gifs or tests doesn't mean that users are **forced** to use that version, it simply means that newer versions are _supported_, along with older one.

The change you suggested implies that docker-elk only runs with Compose v2, which isn't true.
