### ISSUE TITLE
logstash hangs up on redis input

### ISSUE THREAD

**Issue by darshanime** [deviantony/docker-elk#70]
logstash hangs on redis input without the `key` field in it's configuration which is optional as mentioned in the [docs](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html)

**Comment by deviantony** [comment]
Hi @darshanime 

Please provide us more info about your issue. It's probably related to your configuration.

Also details? What's happening?

Please provide docker version, compose version, docker compose logs... otherwise we cannot really help you.

**Comment by deviantony** [comment]
ping @darshanime 

Any update?

**Comment by deviantony** [comment]
I'll close it for now. Feel free to re-open it if you need to.
