### ISSUE TITLE
Does logstash support exec command?

### ISSUE THREAD

**Issue by XaviLC** [deviantony/docker-elk#71]
Hello, 

I was wondering whether the image of logstash of this docker does support _exec_ command by default in the logstash.conf or the plug in has to be preloaded in the Dockerconfig/

Thanks in advance!

**Comment by XaviLC** [comment]
I have installed the plugin  exec-output adding the line below to  _logstash/Dockerfile_
`RUN logstash-plugin install logstash-output-exec`

Then I have added my statement to _logstash/config/logstash.conf_
```
output {
        elasticsearch {
                hosts => "elasticsearch:9200"
        }


        if "All brokers rejected" in [message]
        {
                exec {
                        command => "/tmp/logstash/nodeFail.bash a 112 CCC &"
                }
                stdout { codec => "rubydebug" }
        }
}
```
I see how stdout is executed and I get output, but not the commnad exec

**Comment by deviantony** [comment]
@XaviLC never used that, but isn't this a filter? Shouldn't it be in a `filter` section instead of `output`?

**Comment by XaviLC** [comment]
@deviantony , yes it is kind of filter, but it is check every time that there is an input. Actually, the exec is a pluging that has to be downloaded. I did it, but it didn't work so I moved to another solution using the tcp plugin

**Comment by deviantony** [comment]
Do you have any log of logstash trying to execute the exec plugin? What if you remove the condition?

**Comment by XaviLC** [comment]
No I don't have log from logstash, I didn't have time to test more with exec pluging and I moved to the tcp plugin

**Comment by deviantony** [comment]
@XaviLC so can we close this issue then?

**Comment by deviantony** [comment]
ping @XaviLC

**Comment by antoineco** [comment]
Old issue, OP did not answer. Feel free to reopen!
