### ISSUE TITLE
logstash_internal user no longer exists

### ISSUE THREAD

**Issue by rbos** [deviantony/docker-elk#711]
### Problem description

I built a fresh docker-elk. When I generated fresh passwords to paste into .env, I got two successes and one failure:

`ERROR: Failed to reset password for the [logstash_internal] user`

I changed the passwords I could and rebuilt it. When I log into the Elastic web UI now, there's only one related user defined in the permissions panel: `logstash_system`

#### Stack configuration

No changes from default.

#### Docker setup
```
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:19:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:18:08 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

#### Container logs
The full output of `docker compose logs` is probably unnecessary, and too verbose, but the missing logstash_internal user is probably responsible for this:

```docker-elk-logstash-1       | [2022-05-16T17:31:52,043][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://logstash_internal:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'"}
docker-elk-logstash-1       | [2022-05-16T17:31:57,054][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://logstash_internal:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'"}
```

I can provide more if you like.

**Comment by rbos** [comment]
(I'm guessing this is some kind of upstream change in the docker containers that you may need to account for)

**Comment by antoineco** [comment]
@rbos thanks for the detailed issue report.

I can't tell why the `logstash_internal` user was removed. Did you by any chance wipe Elasticsearch's data without removing docker-elk's volumes?

You should be able to remediate the situation by removing the volume that holds the `/state/done` file, as follows:

```
docker-compose rm setup
docker volume rm docker-elk_setup
```

Then run the setup again:

```
docker-compose up setup
```

This will reapply the passwords from the `.env` file for the `kibana_system` and `logstash_internal` users (and create them if they don't already exist).

**Comment by antoineco** [comment]
The rationale for **not** recreating those users automatically after the initial setup is that users should be free to do whatever that want once the stack was initialized. If users want to delete/rename default users docker-elk shouldn't prevent them to do so.

That also means the setup process must be forced in case it is desired to recreate these users.

**Comment by rbos** [comment]
I had attempted to fully remove and start fresh by removing all the docker containers and volumes: `docker system prune --volumes`. When I did a `docker ps` and `find / | grep [elasticsearch etc]` I removed anything seemingly related. Then I did a git pull and `docker compose up`. So it is possible that something was left behind - I'd previously installed elasticsearch etc from RPMs and was messing around with that, as well as this.

Well, if nobody else complains, I guess this is probably just a "me" problem from screwing around.

I manually created a logstash_internal user with [these](https://www.elastic.co/guide/en/logstash/current/ls-security.html) role settings.

**Comment by antoineco** [comment]
The RPM installation shouldn't have any influence on docker-elk because the two do not store data in the same places.

Removing containers without removing volumes is very likely the cause of your issue, especially the `setup` volume as mentioned in my previous comment. `docker system prune --volumes` only removes volumes which aren't used by any container, but if you only grep'd the terms "elasticsearch", "kibana" and "logstash" you may have missed the "setup" container.

In general it is not recommended to fiddle manually with containers created by Compose. For a full removal, I recommend referring the the README which recommends using `docker-compose down -v`.

In case you want to reset the `logstash_internal` user and role to docker-elk's default, these instructions still apply: https://github.com/deviantony/docker-elk/issues/711#issuecomment-1127955116

**Comment by rbos** [comment]
Sorry, I meant I deleted the docker containers with "docker rm `docker ps -q -a`", and then when none were showing up, i then purged all unused volumes to be safe, before rebuilding it from scratch. So I don't see how anything would have still been hanging around. :/

It doesn't look like re-creating the setup container did anything to my (manually created) logstash_internal user. I have filebeat configured to ship Docker containers, but it complains about a missing permission.

`docker-elk-logstash-1       | [2022-05-16T18:24:27,015][INFO ][logstash.outputs.elasticsearch][main][35188d91ce573dcbd2610030987004e61de3344cb17744f7d85a59552d8d984c] Retrying failed action {:status=>403, :action=>["create", {:_id=>nil, :_index=>"logs-generic-default", :routing=>nil}, {"@timestamp"=>2022-05-16T17:25:59.876Z, "@version"=>"1", "event"=>{"original"=>"[2022-05-16T17:25:59,875][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>\"http://logstash_internal:xxxxxx@elasticsearch:9200/\", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>\"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'\"}"}, "stream"=>"stdout", "container"=>{"labels"=>{"org_label-schema_url"=>"https://www.elastic.co/products/logstash", "org_label-schema_vcs-url"=>"https://github.com/elastic/logstash", "org_opencontainers_image_vendor"=>"Elastic", "com_docker_compose_project"=>"docker-elk", "org_label-schema_name"=>"logstash", "com_docker_compose_version"=>"2.5.0", "com_docker_compose_container-number"=>"1", "org_label-schema_schema-version"=>"1.0", "org_label-schema_vendor"=>"Elastic", "org_opencontainers_image_version"=>"8.2.0", "org_opencontainers_image_created"=>"2022-04-20T10:38:42Z", "com_docker_compose_service"=>"logstash", "org_label-schema_build-date"=>"2022-04-20T10:38:42Z", "com_docker_compose_depends_on"=>"elasticsearch:service_started", "com_docker_compose_project_working_dir"=>"/opt/docker-elk", "com_docker_compose_image"=>"sha256:58d084c5e929c0daa10fbd1f3ac93a4f8803866e7d7f7168e0d858ce69e2bae5", "org_label-schema_version"=>"8.2.0", "org_opencontainers_image_licenses"=>"Elastic License", "com_docker_compose_oneoff"=>"False", "org_opencontainers_image_description"=>"Logstash is a free and open server-side data processing pipeline that ingests data from a multitude of sources, transforms it, and then sends it to your favorite 'stash.'", "com_docker_compose_config-hash"=>"cae7e456d2425c3711984a0ca877df1892ccbcc04b950a7e012eaf32fd8f0821", "org_opencontainers_image_title"=>"logstash", "org_label-schema_license"=>"Elastic License", "com_docker_compose_project_config_files"=>"/opt/docker-elk/docker-compose.yml"}, "id"=>"8b4d298e5055bac8dae607735d673988f2d4cee6cbfa659cdfbb3a8c90e48862", "name"=>"docker-elk-logstash-1", "image"=>{"name"=>"docker-elk_logstash"}}, "log"=>{"file"=>{"path"=>"/var/lib/docker/containers/8b4d298e5055bac8dae607735d673988f2d4cee6cbfa659cdfbb3a8c90e48862/8b4d298e5055bac8dae607735d673988f2d4cee6cbfa659cdfbb3a8c90e48862-json.log"}, "offset"=>212041}, "tags"=>["beats_input_codec_plain_applied"], "message"=>"[2022-05-16T17:25:59,875][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>\"http://logstash_internal:xxxxxx@elasticsearch:9200/\", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>\"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'\"}", "ecs"=>{"version"=>"8.0.0"}, "host"=>{"name"=>"lib-logs.dc.sfu.ca"}, "input"=>{"type"=>"container"}, "agent"=>{"version"=>"8.2.0", "id"=>"d7214912-6716-4e37-b112-07e573b4fea8", "ephemeral_id"=>"1f3505d1-03a3-484e-8e34-24cd7cfc2c13", "name"=>"lib-logs.dc.sfu.ca", "type"=>"filebeat"}, "data_stream"=>{"type"=>"logs", "dataset"=>"generic", "namespace"=>"default"}}], :error=>{"type"=>"security_exception", "reason"=>"action [indices:admin/auto_create] is unauthorized for user [logstash_internal] with roles [logstash_writer] on indices [logs-generic-default], this action is granted by the index privileges [auto_configure,create_index,manage,all]"}}`

Tempted to wipe it back down to the OS and try again.

**Comment by rbos** [comment]
I manually added permissions for logs-* for logstash_internal, which lets it accept those shipped logs, so I guess that'll do for now. This is mostly a pathfinder project so I might end up re-doing it from scratch later.

**Comment by antoineco** [comment]
For posterity, the error

> action [indices:admin/auto_create] is unauthorized for user [logstash_internal] with roles [logstash_writer] on indices [logs-generic-default], this action is granted by the index privileges [auto_configure,create_index,manage,all]

is covered here:

https://github.com/deviantony/docker-elk/blob/4319be7cd0e15fc3387e9bd1ac170e96420d20a6/setup/roles/logstash_writer.json#L10

But this assumes of course that users use the role that ships with docker-elk.

**Comment by Charlie-Root** [comment]
Having the same issue here. Output of the setup container:
`# sudo docker logs d7944ebc94be
-------- Thu Jul 28 19:57:23 UTC 2022 --------
[+] Waiting for availability of Elasticsearch. This can take several minutes.
   ⠿ Elasticsearch is running
[+] Role 'logstash_writer'
   ⠿ Creating/updating
[+] User 'kibana_system'
   ⠿ User exists, setting password
[+] User 'logstash_internal'
   ⠿ User does not exist, creating
`

i have deleted and recreated everything over 10 times now.

**Comment by antoineco** [comment]
@Charlie-Root it seems like the setup went as expected.

At this stage, the passwords of all users are the ones defined inside the `.env` file.

Right after seeing the setup complete, what happens when the execute this? `docker-compose exec elasticsearch bin/elasticsearch-reset-password --batch --user logstash_internal`

**Comment by Charlie-Root** [comment]
That command failed, the user doesnt exist so it seems.

**Comment by antoineco** [comment]
But the logs of the `setup` container confirm its creation:

```
[+] User 'logstash_internal'
  ⠿ User does not exist, creating
```

If the user disappears, _something_ is making it disappear, and that's definitely not docker-elk. The setup runs only once, and then the stack is completely unmanaged.
