### ISSUE TITLE
Error from metricbeat

### ISSUE THREAD

**Issue by edkry** [deviantony/docker-elk#712]
### Problem description

When I run the command:
```console
docker-compose -f docker-compose.yml -f extensions/metricbeat/metricbeat-compose.yml up
```

I get this error from metricbeat container:
```console
Exiting: 1 error: error initializing cgroup reader: error finding mountpoints: open /hostfs/proc/self/mountinfo: no such file or directory
```

### Extra information

Nothing has been changed, just did git clone and ran that command.

**Comment by antoineco** [comment]
Are you running Docker for Desktop in WSL mode by any chance?
I noticed that `/proc/self` wasn't available in this configuration, which I reported but never got an answer: https://github.com/docker/for-win/issues/10116

**Comment by edkry** [comment]
Yes, I am running Docker for Desktop in WSL. Thanks for letting me know!

Is there any workaround for that?

**Comment by antoineco** [comment]
Closing as specific to the runtime environment, which is outside docker-elk's control, but feel free to continue the discussion here anytime.
