### ISSUE TITLE
.env file line missing from docker-compose.yml file

### ISSUE THREAD

**Issue by Ic3Nine** [deviantony/docker-elk#724]
Hey all,

I just cloned the repo and ran docker-compose and it spat out this warning which caused the 

~/docker/elk$ docker-compose up -d
WARN[0000] The "ELASTIC_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "ELASTIC_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "ELASTIC_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "ELASTIC_VERSION" variable is not set. Defaulting to a blank string.

I'm still new to compose but I realized that each of the services in the compose.yml file is missing the **env_file** entry and it led to the variables not being resolved.  I added the below to each service and was able to spin up the containers without any errors.
**env_file:
- ./.env**
Not sure if this is known or I just missed something but figured I'd make a post.

**Comment by antoineco** [comment]
@Ic3Nine environment variables are set from the `.env` file at the root of the repo. Compose [supports this natively](https://docs.docker.com/compose/environment-variables/#the-env-file). Maybe you omitted this file?
