### ISSUE TITLE
Mac OS Monterey port 5000 already in use

### ISSUE THREAD

**Issue by binary-signal** [deviantony/docker-elk#739]
### Problem description

Running docker compose up command on latest version of Mac Os Monterey
is not able to bind on default port 5000.

docker-compose up console log
```console
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use
```

```console
❯ lsof -n -i :5000
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ControlCe      514 user   31u  IPv4 0x9701b8e195665313      0t0  TCP *:commplex-main (LISTEN)
ControlCe      514 user   32u  IPv6 0x9701b8dcca1b2db3      0t0  TCP *:commplex-main (LISTEN)
```

By running lsof -n -i :5000, I found out the process using the port was named ControlCenter, which is a native macOS application. If this is happening to you, even if you use brute force (and kill) the application, it will restart itself. In my laptop, lsof -i :5000 returns that Control Center is being used by process id 514. I could do killall -p 514, but macOS keeps restarting the process.

The process running on this port turns out to be an AirPlay server. You can deactivate it in System Preferences › Sharing, and unchecking AirPlay Receiver to release port 5000.

#### Stack configuration

no changes 

#### Docker setup

```console
❯ docker version
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```console
$ docker-compose version
Docker Compose version v2.6.1
```

**Comment by antoineco** [comment]
@binary-signal thanks for reporting 👍

Port 5000 for Logstash's TCP input was chosen arbitrarily, and I'm totally OK changing it to something else if it conflicts with reserved ports, especially on major operating systems supported by Docker Desktop.

TCP port 5000 is indeed [registered with IANA](https://en.m.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) for multiple things such as UPnP, Docker Registry, Apple AirPlay, etc.

For the time being, I suggest changing it in your config or simply disabling it if you don't need the TCP input (both the Logstash pipeline and the Compose file need to be modified accordingly).

Meanwhile, I'll think about a more suitable port to use as a default. Probably `50000` (one more zero), which is in the dynamic/private range:

> The range 49152–65535 [...] contains dynamic or private ports that cannot be registered with IANA.
>
> -- https://en.m.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

Feel free to send a pull request if you feel like contributing!

**Comment by binary-signal** [comment]
@antoineco sure thing happy to contribute, I have submited a pull request.
