### ISSUE TITLE
Kibana server is not ready yet.

### ISSUE THREAD

**Issue by alvynabranches** [deviantony/docker-elk#741]
Kibana server is not ready yet.

It takes a lot of time to start the server using the code in this repo. But anyways it never starts the Kibana service.

**Comment by antoineco** [comment]
Kindly referencing the [issue template](https://raw.githubusercontent.com/deviantony/docker-elk/main/.github/ISSUE_TEMPLATE/issue_report.md) (which you deleted):

> In order for us to be able to reproduce the problem and identify the root cause
quickly, we kindly ask you to include *all* the information requested below in
your issue report. It saves us a lot of effort and allows us to provide you
with a solution with as little delay as possible.
>
> 👉 **Issues submitted without the requested information will be closed.**

Thank you for your understanding.

---

By the way, we have automated tests in this repo to ensure that everything works correctly.
If you look at the logs, you can see that everything — including Kibana — usually starts in less than a minute on a [modest machine](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series) with 2 CPUs and 7 GiB of RAM: [CI run #521](https://github.com/deviantony/docker-elk/runs/7373391276?check_suite_focus=true)

Again, you didn't share *any log*, or *hardware specs*, or anything that could allow us to help you really, so the best I can do is guess; but to me it looks like your host doesn't have enough resources to run this stack.
