### ISSUE TITLE
Default elastic credentials not working

### ISSUE THREAD

**Issue by Guruleenyc** [deviantony/docker-elk#742]
The default elastic credentials are not working to login to Kibana. Also I followed the steps to change the passwords, but I cannot find the referenced .env file to update?

**Comment by antoineco** [comment]
Kindly referencing the [issue template](https://raw.githubusercontent.com/deviantony/docker-elk/main/.github/ISSUE_TEMPLATE/issue_report.md) (which you deleted):

> In order for us to be able to reproduce the problem and identify the root cause
quickly, we kindly ask you to include *all* the information requested below in
your issue report. It saves us a lot of effort and allows us to provide you
with a solution with as little delay as possible.
>
> 👉 **Issues submitted without the requested information will be closed.**

Thank you for your understanding.

---

In your case, I'd suggest checking the note about the minimum supported version of Compose in the **Requirements** section of the README.
