### ISSUE TITLE
Default credentials is not working 

### ISSUE THREAD

**Issue by chicofariasneto** [deviantony/docker-elk#743]
I just clone the project and run:

docker-compose up -d

Wait for built, go to Kibana in http://localhost:5601/ and use it:

Username: elastic
Password: changeme

Like the doc says, and it's not working

**Comment by antoineco** [comment]
Kindly referencing the [issue template](https://raw.githubusercontent.com/deviantony/docker-elk/main/.github/ISSUE_TEMPLATE/issue_report.md) (which you deleted):

> In order for us to be able to reproduce the problem and identify the root cause
quickly, we kindly ask you to include *all* the information requested below in
your issue report. It saves us a lot of effort and allows us to provide you
with a solution with as little delay as possible.
>
> 👉 **Issues submitted without the requested information will be closed.**

Thank you for your understanding.

---

In your case, I'd suggest checking the note about the minimum supported version of Compose in the **Requirements** section of the README.
