### ISSUE TITLE
Passing an encryption key to Kibana

### ISSUE THREAD

**Issue by grizzlycode** [deviantony/docker-elk#759]
### Problem description

When I load the Security app "Overview" dashboard I get the following error message:

> Unable to create actions client because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.

#### Stack configuration

Outside of the default configuration. 

- I changed password as prescribed in readme
- I tried fixing the issue myself...by adding a new variable to .env file (XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY) and editing the Kibana.yml to include the "encryptedSavedObjects.encryptionKey" with the value equal to the variable I created in .env file
- However, when I brought up the stack again Kibana wouldn't come up. So I had to comment out the variable and it came up. I'm sure I missed something simple

```
diff --git a/.env b/.env
index 36149ab..b4e608e 100644
--- a/.env
+++ b/.env
@@ -7,16 +7,18 @@ ELASTIC_VERSION=8.4.1
 #
 # Superuser role, full access to cluster management and data indices.
 # https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html
-ELASTIC_PASSWORD='changeme'
+ELASTIC_PASSWORD='password'
 
 # User 'logstash_internal' (custom)
 #
 # The user Logstash uses to connect and send data to Elasticsearch.
 # https://www.elastic.co/guide/en/logstash/current/ls-security.html
-LOGSTASH_INTERNAL_PASSWORD='changeme'
+LOGSTASH_INTERNAL_PASSWORD='password'
 
 # User 'kibana_system' (built-in)
 #
 # The user Kibana uses to connect and communicate with Elasticsearch.
 # https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-users.html
-KIBANA_SYSTEM_PASSWORD='changeme'
+KIBANA_SYSTEM_PASSWORD='password'
+
+XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="<32 character key>"
diff --git a/kibana/config/kibana.yml b/kibana/config/kibana.yml
index 9eb2099..0caaacb 100644
--- a/kibana/config/kibana.yml
+++ b/kibana/config/kibana.yml
@@ -11,3 +11,4 @@ monitoring.ui.container.elasticsearch.enabled: true
 #
 elasticsearch.username: kibana_system
 elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
+#xpack.encryptedSavedObjects.encryptionKey: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
```

#### Docker setup

Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:12:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:37 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

<!--
Please paste the full output of the `docker-compose version` command below.

Docker Compose version v2.10.2

#### Container logs

I don't know why but its not producing a log when I execute the `docker-compose logs` command

```
no configuration file provided: not found
```

**Comment by antoineco** [comment]
@grizzlycode Compose won't automatically inject the environment into all containers it creates, as that would be insecure (you could leak sensitive information into a container that is not supposed to access it).

If you want the encryption key to come from the environment (e.g. by using the `.env` file like you did), you have to explicitly pass it to the container inside the Compose file.

Example, forwarding an existing environment variable to Kibana by substitution:

https://github.com/deviantony/docker-elk/blob/fd33e7ccbb0ca2dc70f9516dbe64a0bc3cce4934/docker-compose.yml#L82-L83

**Comment by grizzlycode** [comment]
Thanks, I'm still learning docker and Elasticsearch. I tried again making sure it was in the proper container environment however, I got the following error: 

`docker-elk-kibana-1         | /usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:41
docker-elk-kibana-1         |     throw new Error(`Unknown environment variable referenced in config : ${envVarName}`);
docker-elk-kibana-1         |     ^
docker-elk-kibana-1         | 
docker-elk-kibana-1         | Error: Unknown environment variable referenced in config : XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
docker-elk-kibana-1         |     at /usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:41:11
docker-elk-kibana-1         |     at String.replace (<anonymous>)
docker-elk-kibana-1         |     at replaceEnvVarRefs (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:34:14)
docker-elk-kibana-1         |     at merge (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:51:71)
docker-elk-kibana-1         |     at merge (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:48:7)
docker-elk-kibana-1         |     at getConfigFromFiles (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/utils/read_config.js:66:20)
docker-elk-kibana-1         |     at loadConfiguration (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/config_loader.js:30:58)
docker-elk-kibana-1         |     at initApm (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target_node/init_apm.js:18:64)
docker-elk-kibana-1         |     at module.exports (/usr/share/kibana/src/cli/apm.js:27:3)
docker-elk-kibana-1         |     at Object.<anonymous> (/usr/share/kibana/src/cli/dist.js:10:17)
docker-elk-kibana-1 exited with code 1
`

When I have more time I'll see if I can get the environment stuff working. However, I decided to skip the .env route for now and just edit the kibana.yml directly and it's working now! I'll close out this issue.
