### ISSUE TITLE
How are Elasticsearch's certificates not generated?

### ISSUE THREAD

**Issue by pedroaugustofsilva** [deviantony/docker-elk#762]
Hey!

I know there is a branch tls that allow setting the certificate manually.

But I would to know how, in the branch main, the container of elasticsearch service, which uses the same image of [this guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode), doesn't have the folder /certs with the certificates auto-generated.

Thanks!

**Comment by pedroaugustofsilva** [comment]
I found the answer. [There are some cases when security auto-configuration is skipped](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/configuring-stack-security.html#stack-skip-auto-configuration).

**Comment by pedroaugustofsilva** [comment]
I think that other settings too: 

https://github.com/deviantony/docker-elk/blob/30cb8cb484a9b588350314c2aa63b1d25cc542f6/docker-compose.yml#L48

But I don't see a problem with the branch main doesn't generate the certificates. After all, it's better to work with tls branch if you need to use certificates.

**Comment by antoineco** [comment]
I believe so too.

I don't know what alternative names Elasticsearch includes in its default certificates, but these might not include "elasticsearch" (the DNS name resolvable by other containers). And certificates still need to be copied directly from the Elasticsearch container to other components (Kibana, Logstash) for these to be able to communicate over TLS.

On the `tls` branch, certificates are generated in place (with possible customizations) and don't need to be copied around. I think it's less error prone in a setup where everything should start with a single `up` command.
