### ISSUE TITLE
continuously index specific path on docker-elk

### ISSUE THREAD

**Issue by mehrdad2000** [deviantony/docker-elk#766]
Hi
I have unstructrual log file that need to import in docker-elk.
here is the path of log on server that docker-elk run on it:
/opt/logs/app.log    1GB

how can I import it, and is it possible to continuously index this path? I mean in case if file change or add another log file on this path automatically index in docker-elk.

Any idea?
Thanks

**Comment by antoineco** [comment]
@mehrdad2000 this is a job for the Filebeat extension, inside the `extensions` directory.

Mount your file inside the container (add it as a `volume`), add a [filestream input](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html) to the config file, and run Filebeat together with Elasticsearch and Kibana as instructed in the extension's documentation.

Your logs will be ingested by Elasticsearch and updates will continuously be ingested over time. Logs can be searched and turned into graphs using Kibana.

**Comment by mehrdad2000** [comment]
@antoineco is it possible to do this with fleet?

**Comment by antoineco** [comment]
1. Yes absolutely, but the configuration of Elastic Agents is a bit different from Filebeat's. Elastic's documentation is very comprehensive so I'm not going to detail that process here.
2. On the container that will read the file. In this case Filebeat (or Elastic Agent / Fleet if you go that route)

**Comment by mehrdad2000** [comment]
@antoineco Thanks issue resolved.
