### ISSUE TITLE
Can not start kibana step

### ISSUE THREAD

**Issue by Van-Tien** [deviantony/docker-elk#77]
Step 5 : RUN kibana plugin --install elastic/sense
 ---> Running in 0fec22fee790

 ERROR  unknown command plugin

  Usage: bin/kibana [command=serve] [options]

  Kibana is an open source (Apache Licensed), browser based analytics and search dashboard for Elasticsearch.

  Commands:
    serve  [options]  Run the kibana server
    help  <command>   Get the help for a specific command

  "serve" Options:

    -h, --help                 output usage information
    -e, --elasticsearch <uri>  Elasticsearch instance
    -c, --config <path>        Path to the config file, can be changed with the CONFIG_PATH environment variable as well. Use mulitple --config args to include multiple config files.
    -p, --port <port>          The port to bind to
    -q, --quiet                Prevent all logging except errors
    -Q, --silent               Prevent all logging
    --verbose                  Turns on verbose logging
    -H, --host <host>          The host to bind to
    -l, --log-file <path>      The file to log to
    --plugin-dir <path>        A path to scan for plugins, this can be specified multiple times to specify multiple directories
    --plugin-path <path>       A path to a plugin which should be included by the server, this can be specified multiple times to specify multiple paths
    --plugins <path>           an alias for --plugin-dir

ERROR: Service 'kibana' failed to build: The command '/bin/sh -c kibana plugin --install elastic/sense' returned a non-zero code: 64

**Comment by Van-Tien** [comment]
I run: docker-compose up (docker version 1.12.3)

**Comment by deviantony** [comment]
@Van-Tien which branch are you using?

**Comment by deviantony** [comment]
Oh ! That's it, Elastic just released the 5.0.0 !! Awesome :)

That means that the repository is broken for now, please switch on to the `x-pack` branch: https://github.com/deviantony/docker-elk/tree/x-pack

This branch will become the default soon.

**Comment by mskutin** [comment]
>This branch will become the default soon.
@deviantony any estimates?

**Comment by deviantony** [comment]
I'll work on it this week-end :)

**Comment by mskutin** [comment]
cool 😎

**Comment by vreuter** [comment]
Just ran into this issue as well and was glad to see that it had already been posted. Thanks for the info @deviantony

**Comment by sepe81** [comment]
IMO it would be better to choose a fixed version of kibana within the Dockerfile. Instead of `FROM kibana:latest` it could be `FROM kibana:4.6.2` or later FROM kibana:5.0.0`.

see https://hub.docker.com/_/kibana/

**Comment by pfichtner** [comment]
+1

**Comment by deviantony** [comment]
The repository has been updated ! 

`master` is now using `:5` images.

You also have access to the following branches:

* ELK 5 with X-Pack support: https://github.com/deviantony/docker-elk/tree/x-pack
* ELK 5 in Vagrant: https://github.com/deviantony/docker-elk/tree/vagrant
