### ISSUE TITLE
adding persistent volume for snapshot repo

### ISSUE THREAD

**Issue by veenone** [deviantony/docker-elk#788]
hi, 

Pardon for my lack of docker knowledge.
I would like to map the snapshot repo folder to a persistant volume.
However I couldn't change the ownership of the directory that I map.
in this case /opt/elasticsearch/backup

is there a way to attach the chown command in the docker-compose.yml?

Thank you

**Comment by antoineco** [comment]
@veenone are you mounting a directory local to the `docker-elk` project, such as `./elasticsearch/backup:/opt/elasticsearch/backup`?

If not, I would recommend doing so, this way you won't have permission issues doing a `chmod g+wr` on that directory.
This is much better than executing a container as root on the host to perform permission changes inside `/opt`.

**Comment by veenone** [comment]
Hi @antoineco ,

Thank you for your clear explanation (including the step-by-step guide) :)
I manage to run the snapshot backup with your direction.

Previously I was confused that the owner of /opt/elasticsearch/backup is not elasticsearch user but root instead.
I tried to execute snapshot backup from Kibana and it failed due to access restriction.

after following your guide it seems like the owner of backup folder is elasticsearch now.
I'm pretty sure I have tried your solution before asking but I might missed somewhere.

anyway thank you very much!

**Comment by antoineco** [comment]
@veenone you're welcome!

The Elasticsearch container runs as `elasticsearch:root`, so as long as the directory is group-writable Elasticsearch will be able to write to it.

In Linux, when you create a directory with `mkdir`, it is only group-readable by default. It's probably what happened in your first attempt.
