### ISSUE TITLE
Disable automatic execution of `setup` service via Compose profile

### ISSUE THREAD

**Issue by antoineco** [deviantony/docker-elk#798]
A thread to discuss whether or not it would make sense to guard the execution of the `setup` script using a Compose [profile](https://github.com/docker/docs/blob/72a3a45c0e09a7c101d66dca13c7fae3916c96f3/compose/profiles.md).

### Context

This mechanism allows excluding selected services from regular executions of `docker-compose up`, unless those services are explicily listed on the command line. It is particularly useful for one-offs (init scripts, ...), automated tests, etc.

We already leverage profiles on the `tls` branch for generating TLS certificates and private keys using `docker-compose up tls`:

https://github.com/deviantony/docker-elk/blob/1370c343f99e4e5288f1f88420a16385a4527f8f/docker-compose.yml#L14-L16

### Proposal

I've been thinking about using the same mechanism for the `setup` script.

Right now, `setup` runs on every execution of `docker-compose up` (and exits when done). This is fine because, upon successful execution, the script creates a lock file to prevent subsequent runs and avoid overriding existing roles and users on every startup.

However, creating this container every time isn't essential, and we could as well document the fact that people need to run `docker-compose up setup` the first time they spin up their stack.

| ✅ Pros | ❌ Cons |
|------|------|
| Explicit, clear intent  | Must be run manually (once)  |
| Setup output not tangled with verbose ES logs  | Requires Compose 1.28.0  |
| No unnecessary container creation  |      |
| No lock to [delete manually](https://github.com/deviantony/docker-elk/tree/8.2212.1#how-to-re-execute-the-setup) to re-execute the setup  |      |

**Comment by nikgame33** [comment]
Adding an additional setup profile seems worth the change, the added work of running an additional command the cleaner output and re executing is made easier. Therefore I'd say the Pros outweigh the Cons, at least from personal experience

**Comment by antoineco** [comment]
@nikgame33 appreciate the feedback, thanks!

The only thing I'm worried about is people who don't read the docs (there are very very many) and will open issues asking why things don't work when they clone the repository and run `docker compose up`.

I guess we could make it clear by adding a tl;dr with the commands to run at the very top of the README, and updating the demo GIF.
