### ISSUE TITLE
 Failed to connect to an external logstash

### ISSUE THREAD

**Issue by WHAZAZA** [deviantony/docker-elk#807]
### Problem description

Hello,
I'm trying to connect to a logstash instance that was installed with the .deb packages on a different server than docker and I can't connect

My question is, should I modify argo in docker compose to be able to connect an external logstash?

Circuit

Node 1 (new Logstash)   ---- >  Node2 Master Server (docker-elk)

#### Docker setup

```console
$ docker version

Docker version 20.10.21, build baeda1f
```

```console
$ docker-compose version

Docker Compose version v2.12.2
```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by antoineco** [comment]
@WHAZAZA I don't think you need to perform any change to your docker-elk config (besides disabling Logstash if you don't need it).

In your external Logstash pipeline, simply configure the Elasticsearch output to point to the IP address or hostname of the machine which runs docker-elk:

https://github.com/deviantony/docker-elk/blob/be973ec7397e7524579f74194a664811c3d7e2d9/logstash/pipeline/logstash.conf#L13-L18

For example:

```diff
- elasticsearch:9200
+ 192.168.0.123:9200
```

**Comment by WHAZAZA** [comment]
sol: 
 - elasticsearch:9200
+ 192.168.0.123:9200
