### ISSUE TITLE
FATAL CLI ERROR Error: EACCES: permission denied kibana/elasticsearch/logstash

### ISSUE THREAD

**Issue by taminhhieu31gl** [deviantony/docker-elk#810]
### Problem description
I cloned the master branch and run "docker-compose up -d", so I'm facing these issues below kibana, elasticsearch, logstash

#### Docker setup

```console
$ docker version

[OUTPUT HERE]
```
![image](https://user-images.githubusercontent.com/42288000/209233901-54ec30e1-6eaa-4081-b1b3-9a8b152b4655.png)

```console
$ docker-compose version
[OUTPUT HERE]
```
![image](https://user-images.githubusercontent.com/42288000/209233947-4f2c738f-95a8-49ff-814c-24c3af19d352.png)

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```
![image](https://user-images.githubusercontent.com/42288000/209234028-2c43c5c9-548d-40ac-9c81-468e4cae335a.png)
![image](https://user-images.githubusercontent.com/42288000/209234274-86ad5fb0-17f7-4556-a46f-3c514365ab63.png)

**Comment by taminhhieu31gl** [comment]
I tried a lot chmod 755, chown but still cannot do anything

**Comment by antoineco** [comment]
Looks like the configuration files aren't readable by the containers' user(s). Try to `chmod -v go+r` each problematic config file and see if that helps.

Read permissions should be present by default when you clone the repository, but maybe you're using a custom umask in your terminal session.

Also some heads up: docker-elk requires Compose 1.26 as indicated in the README. With Compose 1.23, the quotes inside the `.env` file are **included in the password** (it's a Compose bug).

**Comment by taminhhieu31gl** [comment]
Thanks @antoineco
