### ISSUE TITLE
Not a bug, just a nice to have / enhancement - show variable in docker compose file

### ISSUE THREAD

**Issue by rit001** [deviantony/docker-elk#821]
Hidden in the helpers.sh file of the setup container is the environment variable ELASTICSEARCH_HOST which is coded to default to 'elasticsearch' if no value is defined.

Currently, this is not shown/set witin the docker-compose.yml fine and so anyone getting started with the project who changes the default name of the containers has to 'discover' its existence. It would make sense to have it defined in docker-compose.yml as a way to document the fact that it is an option.

**Comment by antoineco** [comment]
That's a good suggestion, however this specific variable was meant as a "backdoor" for testing the script locally, and therefore applies **only** to the setup logic.

All stack services are pre-configured to connect to Elasticsearch using the `elasticsearch` name, so it's not advisable to change it:

https://github.com/deviantony/docker-elk/blob/159cfcd346697712303563711a4ed3cd9416f353/kibana/config/kibana.yml#L7

https://github.com/deviantony/docker-elk/blob/159cfcd346697712303563711a4ed3cd9416f353/logstash/pipeline/logstash.conf#L15

https://github.com/deviantony/docker-elk/blob/159cfcd346697712303563711a4ed3cd9416f353/extensions/filebeat/config/filebeat.yml#L29

Could you please share a bit more about the use case?

**Comment by rit001** [comment]
The use case is just the fact that our environment has a lot of containers and so they are named to allow them to be grouped when viewed in tools like lazydocker and Portainer. So my containers have been called

     elasticsearch_setup
     elasticsearch_engine
     elasticsearch_kibana

It also helps route issues to the right person, someone is likely to have heard of elasticsearch, but unlikely to link kibana to it, but by changing the container name this becomes a lot clearer.

The other areas that needed to be changed were simple as they are config files and so that is where I went looking to make config changes. A script named 'helpers.sh' is not somewhere you expect to find config control.

An additional complication for my environment is that the setup container built is not done at runtime, it is an independent CI-driven build so that the resulting container passes all the same build checks that all other built containers do. So the script file in question is not even available to me from within the environment I do deployment work. As I'm a single-person Ops team this was a non-issue, but a larger team could spend more time hunting down this value if integration/deployment was spread across team members.

**Comment by antoineco** [comment]
Regarding the container names, Compose doesn't translate the service name directly to a container name. Instead, it prepends the project name, such as `dockerelk1_elasticsearch`, `dockerelk1_kibana`, etc. Which is what Portainer or others tools are displaying, so telling installations apart should be granted.

Knowing this, do you still require renaming the services? If yes, what changes would you suggest to the project to address this with as little overhead as possible?

> helpers.sh' is not somewhere you expect to find config control

The `helpers.sh` file is a library of functions to be used by the setup entrypoint. I'm not sure I understood whether there was a suggestion for improvement here? Do you suggest renaming it to `lib_setup.sh` for example?

**Comment by rit001** [comment]
I would say just placing ELASTICSEARCH_HOST into the docker compose file would make it clear that the variable exists and so anyone who wants to make changes to the default naming would be able to see there is a variable that is involved. This seems far better than trying to rename script files or anything more complex.

**Comment by antoineco** [comment]
And use the env var everywhere including config files?

**Comment by rit001** [comment]
That may be complicating your setup more than needed. Maybe just a note about the fact that the config files are something to look at if someone wants to make changes.

**Comment by antoineco** [comment]
I agree about (not) complicating things. Renaming services sounds like a pretty unusual customization that not a lot of users may be tempted to perform, given the notion of project I mentioned earlier, which is built into Compose and lets you start as many stacks as you want from the same base config (see [`--project-name` flag](https://docs.docker.com/compose/reference/)).

Regarding config files, anything you would add to https://github.com/deviantony/docker-elk#configuration to clarify where/how things should configured?

**Comment by antoineco** [comment]
I don't think there is any actionable for us here unfortunately, so I'm going to close this issue for now.

I appreciate the suggestion 🙏  but, as discussed, the fact that `ELASTICSEARCH_HOST` is used in _one_ specific script inside this repo doesn't mean that it should to be exposed to the user (unlike actual config variables present in the `.env` file, for example).

Making the Elasticsearch host configurable inside the Compose file would only create confusion in a context where we _don't_ support renaming the `elasticsearch` service out of the box (due to the name `elasticsearch` being hardcoded in config files, some of which I liked above). Containers within a Compose project resolve internal names without the need for any customization. This is a core functionality of Compose which all our components leverage, and one of the reasons why docker-elk can remain so simple to run.

With that being said, if providing convenience to docker-elk for _renaming the `elasticsearch` service_ (and therefore host name) can benefit anybody, then let's draft that feature. But this requires a bigger effort than just exposing the internal of the `setup` container.
