### ISSUE TITLE
Fleet - Missing xpack encryption key in Kibana.yml

### ISSUE THREAD

**Issue by rnjava** [deviantony/docker-elk#827]
### Problem description

Fleet management features were not working until the following lines were added in kibana.yml file. 

xpack.encryptedSavedObjects.encryptionKey: "Add-more-than-32-characters-for-the-key-value"
xpack.fleet.agents.tlsCheckDisabled: true

Could you add the above lines in kibana.yml file?

#### Stack configuration
kibana.yml file in Kibana --> config folder

#### Docker setup

Docker version - 23.0.1

```console
$ docker version

[OUTPUT HERE]
```

```console
$ docker-compose version

[OUTPUT HERE]
```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by antoineco** [comment]
@rnjava thanks for reporting 👍 

Could you please elaborate on _management features_? (a series of steps to reproduce, for example)

We have automated tests which assert that both [Fleet Server and APM Server](https://github.com/deviantony/docker-elk/tree/8.2302.1/extensions/fleet) can join the Fleet management properly, and they ran successfully [yesterday](https://github.com/deviantony/docker-elk/actions/runs/4205018060/jobs/7296502784#step:8:65). It would be helpful to know what additional tests we could add to avoid regressions.

---

Demo

```
docker-compose -f docker-compose.yml -f extensions/fleet/fleet-compose.yml -f extensions/fleet/agent-apmserver-compose.yml up
```

<img width="1271" alt="Screenshot 2023-02-18 at 08 47 50" src="https://user-images.githubusercontent.com/3299086/219848558-2af21954-7326-43f1-9293-62b4e4b232fe.png">

**Comment by rnjava** [comment]
Hi Antoineco,

Thanks for maintaining this awesome repository.

Without adding these values in Kibana, I was not able to use the Alert feature under Security in Kibana.  

![image](https://user-images.githubusercontent.com/14116751/220005216-16f55019-3be0-4abb-88e7-07503f809853.png)

Please let me know if you need more details.
Thanks again,
Ram

**Comment by antoineco** [comment]
@rnjava you're right, some Kibana features require an encryption key.

Encryption keys are sensitive and should be kept secure (like user passwords) so I don't think we should set them to a default value, but we could [add instructions for generating them](https://github.com/deviantony/docker-elk/tree/8.2302.1/extensions/enterprise-search#generate-an-encryption-key) if that helps?
