### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by Bunny-Head** [deviantony/docker-elk#828]
Hello!

When I try to login I have this error message:

<html><body>

url | "/api/fgc.network/oauth/https%3A%2F%2Felk.zone"
-- | --
statusCode | 422
statusMessage | "Missing authentication code."
message | "Missing authentication code."
stack | ""

</body>
</html>

How can I solve this?

Thank you!

**Comment by antoineco** [comment]
What is `/api/fgc.network` and https://elk.zone?

**Comment by Bunny-Head** [comment]
> What is `/api/fgc.network` and https://elk.zone?

TLDR I just open [elk ](https://elk.zone/), Sign In write the url of the network I want to sign in and I get this error.

![image](https://user-images.githubusercontent.com/122626274/219857196-2a9e2a7a-61c6-4696-8a74-ae6826b749fc.png)

**Comment by antoineco** [comment]
You're looking at the wrong project: https://github.com/elk-zone/elk
