### ISSUE TITLE
Upgrade Elastic minor version - Documentation

### ISSUE THREAD

**Issue by sorcerb** [deviantony/docker-elk#832]
Hello, thanks for nice product.
Can you add some information how I can upgrade Elastic? For examle to minor version - from 8.5.3 to 8.6.2
I did this steps with no luck:

- git reset -hard
- git pull
- docker compose down
- docker compose -rm
- docker compose up -d

**Comment by antoineco** [comment]
Does this help? https://github.com/deviantony/docker-elk#version-selection

> To use a different version of the core Elastic components, simply change the version number inside the `.env` file. If you are upgrading an existing stack, remember to rebuild all container images using the `docker-compose build` command.

**Comment by sorcerb** [comment]
Yes, this it `docker compose build`. Thank you.

**Comment by antoineco** [comment]
After `docker compose build`, the next `docker compose up` will automatically detect that the images have changed, and re-create the containers accordingly.
