### ISSUE TITLE
Error failed to authenticate user [kibana_system]

### ISSUE THREAD

**Issue by WHAZAZA** [deviantony/docker-elk#833]
### Problem description

Hello, I get the following error, the caul prevents me from entering kibana since it tells me:
"Kibana server is not ready yet."

ERROR:
```console
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-09T14:59:55.449Z", "log.level": "INFO", "message":"Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[elasticsearch][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","trace.id":"9922eee5bdc566e48218825ce4a510b5","elasticsearch.cluster.uuid":"HhPXYWmJQi6Lgk8MZQnvYA","elasticsearch.node.id":"x6ibz5wqQ4Sx2YxR0POhQg","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}`
```
LOGS:  [docker-compose](https://drive.google.com/file/d/1SkSqe2a76DuIZO8oQ4hxImW8iH4PvFlk/view?usp=sharing)

### Extra information
File .env
[.env](https://docs.google.com/document/d/1BEY4Ln-KrHRLqxrM281zUuDISmdzDW8H6-pYg0GkjiI/edit?usp=sharing)

#### Stack configuration
```console
version: '3.7'

services:
  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 80:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  setup:
  elasticsearch:
```

#### Docker setup

```console
$ docker version

 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:49 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```console
$ docker-compose version

Docker Compose version v2.16.0
```

**Comment by WHAZAZA** [comment]
![image](https://user-images.githubusercontent.com/86791183/224101027-4c72e0d0-c19b-4b09-b29d-9125c96aba4a.png)


The mentioned variable is not found


What else could you validate?

**Comment by WHAZAZA** [comment]
I clarify just in case it is a server without access to the internet that is behind a proxy

and it only has ports 80 and 8080 open

**Comment by antoineco** [comment]
This shouldn't be a problem, Docker exposes some internal DNS resolver and the `setup` container only communicates with Elasticsearch's local IP address.

Let's check the IP `elasticsearch` resolves to.

Try adding these lines (in green, without the '+' sign) to [`setup/entrypoint.sh`](https://github.com/deviantony/docker-elk/blob/6db3e37334aa7033aeb7fd145b946bd46e860bcd/setup/entrypoint.sh) as follows:

```diff
 #!/usr/bin/env bash
 
 set -eu
 set -o pipefail
 
 source "${BASH_SOURCE[0]%/*}"/lib.sh
+
+getent hosts elasticsearch
+exit 0
```

What does `docker-compose up setup` print after this change?

**Comment by WHAZAZA** [comment]
this is the exit

![image](https://user-images.githubusercontent.com/86791183/224119303-f0c38732-1ab0-4ff7-b14e-af6b3f44139b.png)

**Comment by antoineco** [comment]
Interesting. The IP looks correct to me, it is an internal Docker IP, as expected.

What if you revert your change to the script, and run the setup again?

**Comment by WHAZAZA** [comment]
![image](https://user-images.githubusercontent.com/86791183/224123746-d30cbad2-1055-4ecb-8c09-a5152b66cf5d.png)


no progress from that point

**Comment by antoineco** [comment]
It's very likely that iptables is intercepting communications between containers on your server.

It's hard to suggest a general solution here, especially since this is unrelated to Docker, but those commands might be helpful for troubleshooting:

```
sudo iptables -L -n -v
sudo iptables -t nat -L -n -v
```

**Comment by WHAZAZA** [comment]
You can't help me to solve the problem or recommend an article to do it since I have no experience with iptables?

**Comment by joonaskaskisola** [comment]
Having the exact same issue. I'm using ufw. Disabling ufw and rerunning `docker-compose up setup` did not resolve the issue.

Any help appreciated.

**Comment by antoineco** [comment]
I doubt I can help because the issue can have multiple root causes which I can't possibly investigate over GitHub comments: iptables configuration, routing table, etc. None of which have much to do with docker-elk.

If the Docker host was set up by someone else (IT department, etc.) I'd recommend reaching out to those people for help. If not, I invite you to run Docker on a different machine.

**Comment by denbon05** [comment]
In additional to the above, there are some logs from `elasticsearch` container:
```sh
failed to retrieve password hash for reserved user [kibana_system]
at least one primary shard for the index [.security-7] is unavailable
Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]
security index is unavailable. short circuiting retrieval of user [logstash_internal]
```

**Comment by antoineco** [comment]
@denbon05 it would be helpful to see all the logs and the two issues don't seem connected to me (in the original issue, the setup container wasn't even reaching Elasticsearch).

One wild guess is that you're running into:
- https://github.com/deviantony/docker-elk/issues/795#issuecomment-1331918093
- #829

**Comment by denbon05** [comment]
@antoineco thanks for quick response.
Probably you're right, the issue is not the same as in a topic. 
However, I don't see in my logs any connected with disk space from provided links.
My logs:
[elasticksearch.txt](https://github.com/deviantony/docker-elk/files/11037677/elasticksearch.txt)
[setup.txt](https://github.com/deviantony/docker-elk/files/11037678/setup.txt)
[kibana.txt](https://github.com/deviantony/docker-elk/files/11037679/kibana.txt)

**Comment by antoineco** [comment]
@denbon05 the answer is in the setup logs: the setup is failing because it can't authenticate with Elasticsearch. This is because the stack was already initialized with a different password at an earlier time.

If you don't know the password and "changeme" doesn't work, the easiest solution is to reset the stack (erase all data and start over) as documented in the README.

Since this issue is indeed totally unrelated to the original issue, I invite you to open a new one in case your problem persists.
