### ISSUE TITLE
logstash not able to connect to elastic

### ISSUE THREAD

**Issue by welch27330** [deviantony/docker-elk#834]
Below is an error that I am getting when starting the docker-compose.yml. Not sure of the issue, both containers can talk to each other but I believe maybe there is a permissions issue with the logstash_internal user?

docker-elk-logstash-1       | [2023-03-13T17:24:56,704][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://logstash_internal:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::SocketException] Connect to elasticsearch:9200 [elasticsearch/172.19.0.2] failed: Connection refused"}

**Comment by antoineco** [comment]
Hard to reproduce without the information from the issue template. Could you please at least share the output of `docker-compose up setup`?

**Comment by welch27330** [comment]
My apologies. I have resolved the issue with updating xpack.management in logstash.yml. I meant to come back and update with the complete information.
