### ISSUE TITLE
Clone repository doesn't reflect TLS repository. 

### ISSUE THREAD

**Issue by grizzlycode** [deviantony/docker-elk#837]
### Problem description

When I git clone the TLS version of the ELK stack it's not the right version that includes TLS. 

When I download the zip file that verison is correct. 

I think the link for the TLS version is wrong as it matches the non-tls version. 

This is the link for TLS stack: https://github.com/deviantony/docker-elk.git 

It matches the non-tls stack: https://github.com/deviantony/docker-elk.git

**Comment by antoineco** [comment]
Without specific option Git will select the **default** branch, which is `main` in docker-elk. This is the default Git behavior, docker-elk has no control over this.

`git clone --branch tls` is what you want.

Here is some accessible literature on Git branches: https://www.freecodecamp.org/news/git-clone-branch-how-to-clone-a-specific-branch/amp/
