### ISSUE TITLE
Error with test suite workflow at "Execute core test suite" with clean template clone

### ISSUE THREAD

**Issue by AnonymousSmurf** [deviantony/docker-elk#839]
I am opening this issue because I still believe it is relevant, even though it may not be directly related to the stack itself.

### Problem description
I have created a repository using this template, but the CI workflows appear to be failing. Specifically, they all fail at the `Execute core test suite` step. To provide additional information, I have added some screenshots in the "Extra Information" section. However, I must admit that I am not yet very experienced with this code stack, so I apologize if I have overlooked a simple solution.

### Extra information
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/45464235/227715976-5e82720c-8759-40fa-841e-a6136a4573b7.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/45464235/227715999-bb901716-6d0c-43c5-8683-3ba4f3d3f1ae.png">

#### Stack configuration
I am using version 8.6.2, which should be the latest version as far as I know. I will leave these fields blank because all configurations and versions are set to default, and it seems that the issues are related more to the workflows of the stack than the stack itself.

**Comment by antoineco** [comment]
This is the faulty line:

https://github.com/deviantony/docker-elk/blob/b43620aee4146fbf947c44c9280cad9eb50e9b41/.github/workflows/scripts/lib/testing.sh#L74

If you clone the repository in a directory that is not named "docker-elk", or if you rename the "elk" network inside the Compose file, you also need to adjust the generated network name inside this command.
