### ISSUE TITLE
Feature request: Add Search Guard support

### ISSUE THREAD

**Issue by floragunncom** [deviantony/docker-elk#84]
If you're interested in adding Search Guard support (https://github.com/floragunncom/search-guard) to this project we're happy to provide a PR for that.

**Comment by deviantony** [comment]
Hi @floragunncom,

Yes this is interesting ! We could create another branch and link it in the master README as ELK 5 with Search Guard.

**Comment by floragunncom** [comment]
@deviantony sure, PR is here https://github.com/deviantony/docker-elk/issues/85

**Comment by deviantony** [comment]
@floragunncom I've pushed a new branch called `searchguard` could you rebase your PR to this branch? I'll update the master branch to give a link to it.

Also, I won't be maintaining this branch, so if any issues arise or it needs to be updating I'm couting on you to push the changes. I'll be there for the merge.

**Comment by floragunncom** [comment]
I changed the base branch to "searchguard". 

We will maintain this branch.

**Comment by deviantony** [comment]
Cool ! I've merged the PR and added a new link in the README of the `master` branch. I'll watch any issues/PR related to maintenance but you can also ping me on gitter if required.

**Comment by floragunncom** [comment]
Thx
