### ISSUE TITLE
ERROR with Kibana talking to elasticsearch

### ISSUE THREAD

**Issue by qravey** [deviantony/docker-elk#840]
I've cloned this a few times and worked through the readme, kibana fails to boot and it seems it can't connect to elasticsearch on port 9200. 

I have run the password change for kibana and set it in .env

[2023-03-26T21:10:56.488+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.20.0.2:9200
[2023-03-26T21:10:57.509+00:00][INFO ][plugins.screenshotting.chromium] Browser executable: /usr/share/kibana/x-pack/plugins/screenshotting/chromium/headless_shell-linux_x64/headless_shell
[2023-03-26T21:10:59.041+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]

**Comment by antoineco** [comment]
Chances are that an old password is still stored in Elasticsearch.

Cloning multiple times won't help resetting to a pristine state, because the Elasticsearch data is **persisted inside a Docker volume**. This is explained in the README.

`docker-compose down -v` will reset the stack (`-v` is critical). After that, passwords from the `.env` will be applied by the `setup` container during the initial startup.

**Comment by qravey** [comment]
So I pruned the entire docker system including volumes, deleted the directory and cloned again.

I was unable to use the logstash_user passwork change command. I get

ERROR: Failed to reset password for the [logstash_internal] user

**Comment by qravey** [comment]
Recreating docker-elk_elasticsearch_1 ... done
Recreating docker-elk_setup_1         ... done
Attaching to docker-elk_setup_1
setup_1          | -------- 2023-03-27 12:16:30+00:00 --------
setup_1          | [+] Waiting for availability of Elasticsearch. This can take several minutes.
setup_1          |
setup_1          | HTTP/1.1 401 Unauthorized
setup_1          | WWW-Authenticate: Basic realm="security" charset="UTF-8"
setup_1          | WWW-Authenticate: ApiKey
setup_1          | content-type: application/json;charset=utf-8
setup_1          | content-length: 409
setup_1          |
setup_1          | {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}
setup_1          |    ⠍ Failed to connect to host. Is Elasticsearch healthy?
docker-elk_setup_1 exited with code 7


I have reset elastic and kibana users, but it wont create the logstash user 
:~/elk/docker-elk$ docker-compose exec elasticsearch bin/elasticsearch-reset-password --batch --user logstash_internal

ERROR: Failed to reset password for the [logstash_internal] user

**Comment by Derekt2** [comment]
also in this state, it worked once, but subsequent runs fail with an auth failure. I've tried rm -rf the repo, recloning, and ```sudo docker system prune -f --volumes```

**Comment by antoineco** [comment]
@Derekt2 please open a new issue describing your situation.

A few important notes:

- Docker doesn't prune volumes which are still in use. The procedure to wipe the data is in the README.
- `docker-compose up setup` will reset the passwords of internal users to the values declared in the `.env`.
