### ISSUE TITLE
Filebeat fails to start with: exec: -e: invalid option

### ISSUE THREAD

**Issue by nesmaba** [deviantony/docker-elk#843]
### Problem description
I can't get Filebeat to work. I've configure it and I recreate all the container.
My filebeat.yml have the next configuration:
```yaml
## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/log/squid3/access.log
  #  stream: all # can be all, stdout or stderr

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0
```
I have other container, squidguard, and the file /var/log/squid3/access.log exists.

I ran this command `docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml up -d`

But I enter to Kibana and I can't see data about access.log. 

What can I do to see the access.log in Kibana???

#### Docker setup
Intact

```console
$ docker version

Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker-compose version

[OUTPUT HERE]
```

#### Container logs

```console
$ docker-compose logs

docker-elk-logstash-1  | Using bundled JDK: /usr/share/logstash/jdk
docker-elk-logstash-1  | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
docker-elk-logstash-1  | [2023-03-28T10:09:23,178][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
docker-elk-elasticsearch-1  | Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
docker-elk-logstash-1       | [2023-03-28T10:09:23,184][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"8.6.2", "jruby.version"=>"jruby 9.3.10.0 (2.6.8) 2023-02-01 107b2e6697 OpenJDK 64-Bit Server VM 17.0.6+10 on 17.0.6+10 +indy +jit [x86_64-linux]"}
docker-elk-logstash-1       | [2023-03-28T10:09:23,187][INFO ][logstash.runner          ] JVM bootstrap flags: [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djruby.compile.invokedynamic=true, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Dls.cgroup.cpuacct.path.override=/, -Dls.cgroup.cpu.path.override=/, -Xms256m, -Xmx256m, -Djruby.regexp.interruptible=true, -Djdk.io.File.enableADS=true, --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.nio.channels=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.management/sun.management=ALL-UNNAMED]
docker-elk-logstash-1       | [2023-03-28T10:09:23,196][INFO ][logstash.settings        ] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
docker-elk-logstash-1       | [2023-03-28T10:09:23,198][INFO ][logstash.settings        ] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
docker-elk-logstash-1       | [2023-03-28T10:09:23,434][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"624c8d4a-aadd-421a-8c20-eec58b614ae2", :path=>"/usr/share/logstash/data/uuid"}
docker-elk-logstash-1       | [2023-03-28T10:09:24,126][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
docker-elk-logstash-1       | [2023-03-28T10:09:24,491][INFO ][org.reflections.Reflections] Reflections took 138 ms to scan 1 urls, producing 127 keys and 444 values
docker-elk-logstash-1       | [2023-03-28T10:09:25,012][INFO ][logstash.javapipeline    ] Pipeline `main` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:16.534Z", "log.level": "INFO", "message":"version[8.6.2], pid[202], build[docker/2d58d0f136141f03239816a4e360a8d17b6d8f29/2023-02-13T09:35:20.314882762Z], OS[Linux/5.15.0-69-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.2/19.0.2+7-44]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
docker-elk-setup-1          | -------- 2023-03-28 10:09:05+00:00 --------
docker-elk-setup-1          | [+] Setup has already run successfully on 2023-03-24 08:59:02+00:00. Skipping
docker-elk-logstash-1       | [2023-03-28T10:09:25,023][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//elasticsearch:9200"]}
docker-elk-logstash-1       | [2023-03-28T10:09:25,121][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash_internal:xxxxxx@elasticsearch:9200/]}}
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:16.545Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:16.546Z", "log.level": "INFO", "message":"JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -Des.cgroups.hierarchy.override=/, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-3490117489030473759, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.distribution.type=docker, --module-path=/usr/share/elasticsearch/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:19.307Z", "log.level": "INFO", "message":"Package versions: jackson-annotations=2.13.2, jackson-core=2.13.2, jackson-databind=2.13.2.2, jackson-dataformat-xml=2.13.2, jackson-datatype-jsr310=2.13.2, azure-core=1.27.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"com.azure.core.implementation.jackson.JacksonVersion","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
docker-elk-logstash-1       | [2023-03-28T10:09:25,179][INFO ][logstash.outputs.elasticsearch][main] Failed to perform request {:message=>"Connect to elasticsearch:9200 [elasticsearch/172.25.0.2] failed: Connection refused", :exception=>Manticore::SocketException, :cause=>#<Java::OrgApacheHttpConn::HttpHostConnectException: Connect to elasticsearch:9200 [elasticsearch/172.25.0.2] failed: Connection refused>}
docker-elk-logstash-1       | [2023-03-28T10:09:25,181][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://logstash_internal:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::SocketException] Connect to elasticsearch:9200 [elasticsearch/172.25.0.2] failed: Connection refused"}
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:21.321Z", "log.level": "INFO", "message":"loaded module [aggregations]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"elasticsearch","elasticsearch.cluster.name":"docker-cluster"}
docker-elk-elasticsearch-1  | {"@timestamp":"2023-03-28T10:09:21.322Z", "log.level": "INFO", "message":"loaded module [aggs-matrix-stats]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.
```

**Comment by antoineco** [comment]
To use Filebeat you need to initialize the two users mentioned in the README: https://github.com/deviantony/docker-elk/tree/8.2302.1/extensions/filebeat#usage

**Comment by nesmaba** [comment]
Hello,
I'm a little confused. I think I have created those users... but when I try to log in with for example filebeat_internal through 5601 port, it says to me "You do not have permission to access the requested page".
I don't know what I have to do for using filebeat and monitor my access.log from squidguard. 
What information you need for helping me?

Thanks.

**Comment by nesmaba** [comment]
Ok, sorry for the tittle, thanks!

I need analyze access.log from squidguard which I have in other container inside Docker. But I'm trying different configurations but all of them failed.

The output of `docker-compose -f extensions/filebeat/filebeat-compose.yml logs filebeat`

`
WARN[0000] The "ELASTIC_VERSION" variable is not set. Defaulting to a blank string. 
service "filebeat" refers to undefined network elk: invalid compose project
`

**Comment by antoineco** [comment]
Sorry the correct command is `docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml logs filebeat`

**Comment by antoineco** [comment]
Another note:

`/var/log/squid3/access.log` will only be visible to Filebeat if it is mounted as a [volume](https://docs.docker.com/storage/volumes/) in the Filebeat container. If this file is inside the Squidguard container, and not on the host, it needs to be inside a volume itself in order to be shared with other containers.

You didn't share anything about the way you run the Squidguard container, but for the scenario described above you have to do the following:

- in Squidguard: create the container with `/var/log/squid3` declared as a volume (either in the Dockerfile or at the container creation time)
- in Filebeat: mount the Squidguard volume as an [external volume](https://docs.docker.com/compose/compose-file/compose-file-v3/#external)

**Comment by nesmaba** [comment]
Hello,
I'm trying it but I'm not be able to get it working.

When I run command `docker inspect -f "{{json .Mounts}}" 4389ab78c36f | jq .` where 4389ab78c36f is the id of the squidguard container, I obtain the next output:

`[
  {
    "Type": "volume",
    "Name": "1bc87bacdc9124d4cd5c0e34c9cb79fcd4c8cef6100110f3702d20db77f23594",
    "Source": "/var/lib/docker/volumes/1bc87bacdc9124d4cd5c0e34c9cb79fcd4c8cef6100110f3702d20db77f23594/_data",
    "Destination": "/var/spool/squid3",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "bind",
    "Source": "/home/tic/docker/squidguard/mylog",
    "Destination": "/var/log/squid3",
    "Mode": "rw",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "/home/tic/docker/squidguard/my-config",
    "Destination": "/custom-config",
    "Mode": "rw",
    "RW": true,
    "Propagation": "rprivate"
  }
]`

I'm trying configure a external volume in filebeat but there's no way.

My docker-compose.yml of Squidguard container is the next:

`services:
  squidguard:
    image: muenchhausen/docker-squidguard:latest
    environment:
      - SQUID_CONFIG_SOURCE=/custom-config
      # - SQUID_UID=1000          # only required if MAC OS is used: UserID for>
    ports:
      - "3128:3128"
      - "80:80"
      - "443:443"
    volumes:
      - ./my-config:/custom-config #carpeta local donde se encuentra squidGuard>
      - ./mylog:/var/log/squid3
    restart: always`

Can you help me???

Thanks a lot!

**Comment by antoineco** [comment]
I can't help you without logs no, sorry.

**Comment by nesmaba** [comment]
command `docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml logs filebeat`
OUTPUT
`docker-elk-filebeat-1  | /entrypoint.sh: line 37: exec: -e: invalid option
docker-elk-filebeat-1  | exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]`

**Comment by nesmaba** [comment]
I've deleted the previous docker container and I've created new one. I haven't modified any file, except .env for new passwords.

If I write the command docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml logs filebeat, I obtain this output:

docker-elk-filebeat-1  | /entrypoint.sh: line 37: exec: -e: invalid option docker-elk-filebeat-1  | exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...] 

And i attach my entrypoint.sh that it is inside of the setup folder. (I don't know how I can put it with correct format text)

[entrypoint.sh.pdf](https://github.com/deviantony/docker-elk/files/11150159/entrypoint.sh.pdf)

**Comment by antoineco** [comment]
I don't think I will be able to help you with this issue unfortunately. I've never encountered anything similar, haven't been able to reproduce based on your input, and our automated tests definitely pass with that exact configuration (including the `-e`) flag.

Could you please share the entire output of this command?:

```sh
docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml build filebeat
```

**Comment by nesmaba** [comment]
Thanks a lot for your help, thanks!

The entire output of `docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml build filebeat
` is the next:

`[+] Building 9.6s (5/5) FINISHED                                                                              
 => [internal] load build definition from Dockerfile                                                     0.0s
 => => transferring dockerfile: 115B                                                                     0.0s
 => [internal] load .dockerignore                                                                        0.0s
 => => transferring context: 129B                                                                        0.0s
 => [internal] load metadata for docker.elastic.co/beats/filebeat:8.7.0                                  2.2s
 => [1/1] FROM docker.elastic.co/beats/filebeat:8.7.0@sha256:dc8db6833dbce13e77f85a4118a924fa6146081b5f  7.4s
 => => resolve docker.elastic.co/beats/filebeat:8.7.0@sha256:dc8db6833dbce13e77f85a4118a924fa6146081b5f  0.0s
 => => sha256:b30b6dee943c7b3896e75dee0621d9b26230081fae15d25f571dde0a48510e60 8.80kB / 8.80kB           0.0s
 => => sha256:32803cade44f34806258415ebf3ec4c07464eab567ab5983c623a930524a92ef 31.79MB / 31.79MB         1.1s
 => => sha256:dc8db6833dbce13e77f85a4118a924fa6146081b5f2e11a5b770776d6625f7a0 710B / 710B               0.0s
 => => sha256:dab2047e2aa3c4e427a3981e4341858aba5381ba6819bab3a82c2323150b96d1 38.17MB / 38.17MB         2.1s
 => => sha256:55dc74a9d005abc168c00ce685c93ed49f0df3db37477db27737527f450eba55 2.21kB / 2.21kB           0.0s
 => => sha256:aedbe14abaf1f6abe1c53a2bfdbe4a8d3d85884282ea78da97ea59d8e273eb0f 10.15kB / 10.15kB         0.7s
 => => sha256:727faf6c00d0e1b0fc3baf1b50b3091b6a43f05b82bc0442ea33201b11ac0e3a 619B / 619B               0.9s
 => => sha256:912f489110bf03c59d47fa12a91f134c5dc18dfa5cf5835c6cd883d56abbc4e0 612B / 612B               1.5s
 => => sha256:395aeb0cc7c4f775217cc0608e6b7ab0d2ce50db85bb877d6c0b22a0cd2a00d8 49.78MB / 49.78MB         2.7s
 => => extracting sha256:32803cade44f34806258415ebf3ec4c07464eab567ab5983c623a930524a92ef                1.4s
 => => sha256:1bef55347b8967d8796d8567849d4f72c58329398accffebca67b7f4782fbf12 105B / 105B               2.1s
 => => sha256:b3b2d98acbebba505b8fb72ac2fbb89e93821b6f9e944e17ad4368e2650b715e 6.06kB / 6.06kB           2.7s
 => => sha256:58237e271964039ecfa18ad0b0d8dbece3622fc633e53b864dea5eba08de4952 349.68kB / 349.68kB       2.3s
 => => sha256:27472c17cf89aa91659bcd7c1e26635c7ddd2659c33cf1bc59e62eee0f97febd 694B / 694B               2.9s
 => => sha256:85c24cd6fd8dcef51c48f3ce8ea4b645de4117a1c8730a9eccd0c49ae8d5e0df 2.02kB / 2.02kB           3.2s
 => => sha256:89732bc7504122601f40269fc9ddfb70982e633ea9caf641ae45736f2846b004 39B / 39B                 2.9s
 => => extracting sha256:dab2047e2aa3c4e427a3981e4341858aba5381ba6819bab3a82c2323150b96d1                1.0s
 => => extracting sha256:aedbe14abaf1f6abe1c53a2bfdbe4a8d3d85884282ea78da97ea59d8e273eb0f                0.0s
 => => extracting sha256:727faf6c00d0e1b0fc3baf1b50b3091b6a43f05b82bc0442ea33201b11ac0e3a                0.0s
 => => extracting sha256:912f489110bf03c59d47fa12a91f134c5dc18dfa5cf5835c6cd883d56abbc4e0                0.0s
 => => extracting sha256:395aeb0cc7c4f775217cc0608e6b7ab0d2ce50db85bb877d6c0b22a0cd2a00d8                2.5s
 => => extracting sha256:1bef55347b8967d8796d8567849d4f72c58329398accffebca67b7f4782fbf12                0.0s
 => => extracting sha256:b3b2d98acbebba505b8fb72ac2fbb89e93821b6f9e944e17ad4368e2650b715e                0.0s
 => => extracting sha256:58237e271964039ecfa18ad0b0d8dbece3622fc633e53b864dea5eba08de4952                0.1s
 => => extracting sha256:27472c17cf89aa91659bcd7c1e26635c7ddd2659c33cf1bc59e62eee0f97febd                0.0s
 => => extracting sha256:85c24cd6fd8dcef51c48f3ce8ea4b645de4117a1c8730a9eccd0c49ae8d5e0df                0.0s
 => => extracting sha256:89732bc7504122601f40269fc9ddfb70982e633ea9caf641ae45736f2846b004                0.0s
 => exporting to image                                                                                   0.0s
 => => exporting layers                                                                                  0.0s
 => => writing image sha256:e6011921685fc8d8409d21e31e8fcd51d1d0c60588defb550be848cdff748c09             0.0s
 => => naming to docker.io/library/docker-elk-filebeat     `

**Comment by antoineco** [comment]
Did forcing a rebuild fix the error you were running into before?

**Comment by nesmaba** [comment]
Hello,
Sorry for delaying. I was on holiday. 
It seems if I forcing a rebuild fix the error, but I don't know why if I dont fonce the rebuild It fails. 
I will check the container but I didn't modify anything.

Thanks.

**Comment by nesmaba** [comment]
in this last time, 2 weeks ago, I didn't modify anything. I cloned the git repository and launched it, no more.
If you want to know more about something, tell me please. i would like use this container image.

Thanks.
