### ISSUE TITLE
Metricbeat won't start

### ISSUE THREAD

**Issue by grizzlycode** [deviantony/docker-elk#864]
### Problem description

Metricbeat won't start up due to an error in metricbeat.yml

> Exiting: error initializing publisher: can not convert 'object' into 'string' accessing 'output.elasticsearch.password' (source:'metricbeat.yml')

I have run the setup to make sure all user/passwords were setup. 

> docker-elk-setup-1  | [+] Waiting for availability of Elasticsearch. This can take several minutes.
> docker-elk-setup-1  |    ⠿ Elasticsearch is running
> docker-elk-setup-1  | [+] Waiting for initialization of built-in users
> docker-elk-setup-1  |    ⠿ Built-in users were initialized
> docker-elk-setup-1  | [+] Role 'heartbeat_writer'
> docker-elk-setup-1  |    ⠿ Creating/updating
> docker-elk-setup-1  | [+] Role 'metricbeat_writer'
> docker-elk-setup-1  |    ⠿ Creating/updating
> docker-elk-setup-1  | [+] Role 'filebeat_writer'
> docker-elk-setup-1  |    ⠿ Creating/updating
> docker-elk-setup-1  | [+] Role 'logstash_writer'
> docker-elk-setup-1  |    ⠿ Creating/updating
> docker-elk-setup-1  | [+] User 'filebeat_internal'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'kibana_system'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'logstash_internal'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'heartbeat_internal'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'metricbeat_internal'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'monitoring_internal'
> docker-elk-setup-1  |    ⠿ User exists, setting password
> docker-elk-setup-1  | [+] User 'beats_system'
> docker-elk-setup-1  |    ⠿ User exists, setting password

I have to hard code the passwords for the following users on metricbeat.yml for metricbeat container to start correctly. 

- monitoring_internal
- metricbeat_internal

**Comment by antoineco** [comment]
It looks like Metricbeat was started before the passwords were added to the `.env` file.

Now that you added them (and ran the setup to enable those users), the issue should disappear after recreating the `metricbeat` container:

```
docker-compose -f ... stop metricbeat
docker-compose -f ... rm metricbeat
docker-compose -f ... up
```

**Comment by antoineco** [comment]
You didn't fill in the issue template. What versions of Docker and Compose are you running?

This is what we do in our automated tests:

https://github.com/deviantony/docker-elk/blob/c6978b0e996adccb40ab74c26e04218279b895fd/.github/workflows/ci.yml#L42-L69

The result, with Metricbeat starting without issue and sending data to Elasticsearch: https://github.com/deviantony/docker-elk/actions/runs/4874413077/jobs/8695300021

**Comment by grizzlycode** [comment]
> You didn't fill in the issue template. What versions of Docker and Compose are you running?

Here is my Docker version; compose is now a built-in command:

> Client: Docker Engine - Community
>  Version:           24.0.1
>  API version:       1.43
>  Go version:        go1.20.4
>  Git commit:        6802122
>  Built:             Fri May 19 18:06:21 2023
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          24.0.1
>   API version:      1.43 (minimum version 1.12)
>   Go version:       go1.20.4
>   Git commit:       463850e
>   Built:            Fri May 19 18:06:21 2023
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.21
>   GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
>  runc:
>   Version:          1.1.7
>   GitCommit:        v1.1.7-0-g860f061
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> 

I wiped and reloaded the stack and it works now. Not sure where I went wrong before...anyways closing issue.

**Comment by antoineco** [comment]
Glad it worked in the end!
