### ISSUE TITLE
Support for 5.2?

### ISSUE THREAD

**Issue by laidig** [deviantony/docker-elk#87]
Would you accept a PR to move to the newly released 5.2 version? The images appear to be on dockerhub already.

**Comment by deviantony** [comment]
@laidig Images are using the tag `5` which point to `5.2`. Just do a `docker-compose pull` to update your stack.
Re-open this issue if you're still having problems.

**Comment by deviantony** [comment]
I'll re-open the issue as I just discovered that 5.2 introduced `logstash-plugin` https://www.elastic.co/guide/en/x-pack/5.2/monitoring-logstash.html. This is not available in the current `x-pack` setup. I'd accept a PR for that.

**Comment by antoineco** [comment]
Related to #95. Maybe enabling logstash-plugin should be the topic of another issue?

**Comment by deviantony** [comment]
5.2 support introduced via #95
