### ISSUE TITLE
Cannot Run In On A Headless Server DBUS / X11

### ISSUE THREAD

**Issue by macornwell** [deviantony/docker-elk#878]
### Problem description
I am trying to run this docker compose on a headless ubuntu server. I can get all the way up to the point where I am doing `docker compose up -d`.

I end up getting:
```
failed to solve: docker.elastic.co/logstash/logstash:8.8.1: error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```

I am trying to find out how to get this started. 

I have also did a x11 forwarding session to the server (not that it matters because its headless), and then did a dbus installation.
`sudo apt-get install dbus-x11 gnome-keyring libsecret-1-0`

Then logged into the keyring
```
echo PASSWORD  | gnome-keyring-daemon -d --unlock --login
```

Then when I do compose up I get...
```
failed to solve: docker.elastic.co/kibana/kibana:8.8.1: error getting credentials - err: exit status 1, out: `Error spawning command line "bus-launch --autolaunch=UUID --binary-syntax --close-stderr" : Child process exited with code 1`
```

#### Stack configuration
No changes to the default configuration.

#### Docker setup
```
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

``
Docker Compose version v2.18.1
```

#### Container logs
N/A


Thanks for any help. I'm totally blocked on this.

**Comment by antoineco** [comment]
That's very strange, Docker doesn't need any desktop environment to function. Did you maybe install _Docker for  Desktop_, or alias/symlink the `docker` command to some kind of script?

Please provide as many details as possible about your Docker installation.

**Comment by macornwell** [comment]
So, after playing around with it, (and purging my entire docker install, which included a postgres database with months worth of production data on it), I have fixed the issue.

I don't know WHY this was happening but I can say that it had something to do with having an old version of docker, and then installing a new one (without purging).

How I installed it on ubuntu to get it to work was the following:
```
sudo apt install docker-ce
```

This was after doing.. (use at one's own risk)
```
sudo apt remove docker*
```
