### ISSUE TITLE
Kibana usageCollection Plugin failed to load - Cloudflare Tunnel

### ISSUE THREAD

**Issue by spinnaker1** [deviantony/docker-elk#886]
### Problem description

I deployed the ELK stack as described:
1) git clone `https://github.com/deviantony/docker-elk.git`
2) `cd /opt/docker-elk/`
3) `docker compose up setup`
4) `docker compose up `

When I visit `http://<public-server-ip>:5601` it works without any issues.

However, when I visit via my Cloudflare Argo Tunnel `https://kibana.<my domain>.com`, I get the Kibana login screen and after login gives the error screen "usageCollection" Plugin failed to load.

I used the latest Docker and docker compose versions. Am I missing something to configure in ELK-Stack for the domain to work? I already tried with `publicBaseUrl: https://kibana.<my domain>.com` in /Kibana/config/kibana.conf - same results.

### Extra information

Go back
Definition of plugin "usageCollection" not found and may have failed to load.

```
Version: 8.8.2
Build: 63337
Error: Definition of plugin "usageCollection" not found and may have failed to load.
    at https://kibana.domain.com/63337/bundles/core/core.entry.js:1:347919
    at plugin_PluginWrapper.createPluginInstance (https://kibana.domain.com/63337/bundles/core/core.entry.js:1:348163)
    at plugin_PluginWrapper.setup (https://kibana.domain.com/63337/bundles/core/core.entry.js:1:347363)
    at plugins_service_PluginsService.setup (https://kibana.domain.com/63337/bundles/core/core.entry.js:1:350398)
    at core_system_CoreSystem.setup (https://kibana.domain.com/63337/bundles/core/core.entry.js:1:356087)
    at async Module.Ji (kibana.domain.com/63337/bundles/core/core.entry.js:1:362306)

```

#### Docker setup

```console
$ docker version

[OUTPUT HERE]
```

```console
$ docker-compose version

[OUTPUT HERE]
```

#### Container logs

```console
$ docker-compose logs

[OUTPUT HERE]
```

**Comment by antoineco** [comment]
An issue report without any log is going to take us nowhere I'm afraid.

**Comment by spinnaker1** [comment]
Kibana Container Logs:

**Comment by antoineco** [comment]
I'm a bit puzzled now. You mentioned an error earlier, but that error doesn't appear in those logs. In fact, it seems like the logs you shared are from a fresh start with to connection from clients.

**Comment by antoineco** [comment]
By the way, if Kibana is served at `/63337/`, the configured base URL needs to include that.

**Comment by spinnaker1** [comment]
> I'm a bit puzzled now. You mentioned an error earlier, but that error doesn't appear in those logs. In fact, it seems like the logs you shared are from a fresh start with no connection from clients.

Yes, its a fresh installation on a test machine.
It doesnt write any loglines when the error "usageCollection" appears right after login. I dont know why.

**Comment by spinnaker1** [comment]
> By the way, if Kibana is served at `/63337/`, the configured base URL needs to include that.

What do you mean? I didnt changed anything, to be served on specific path or something like that.

I can reach the URL from the error message with Chrome browser without problems:
`https://kibana.domain.com/63337/bundles/core/core.entry.js`

**Comment by antoineco** [comment]
What I mean is that `publicBaseUrl` needs to include that extra path in your URL:

```diff
- publicBaseUrl: https://kibana.domain.com/
+ publicBaseUrl: https://kibana.domain.com/63337/
```

Regardless, if the problem occurs only behind "Cloudflare Argo Tunnel", Cloudflare themselves will be in a better position to help because I'm not a Cloudflare user, which leaves me no change to troubleshoot what you're experiencing.

**Comment by spinnaker1** [comment]
I think the said plugin just takes its time to load. Because when I wait 15 minutes before visiting Kibana UI, after I do `docker compose up`, it works without any error.
