### ISSUE TITLE
Logstash Container not forwarding logs to ES Container

### ISSUE THREAD

**Issue by ChaitDevOps** [deviantony/docker-elk#89]
Hi,
I'm mapping a directory from my local machine onto the logstash container. In my logstash.conf i have logstash consuming the input but these logs are not being forwarded to ES container. Can you please let me know what is my mistake here.

I tried to replace the elasticsearch with I.P of server that containers are running on and still no luck.

    input {

	file {
                path => "/logstash/log/messages"`
                type => "sys"`
		start_position => "beginning"`
                }`
    }

    output {
        if [type] == "sys" {
        elasticsearch {
        hosts => [ "elasticsearch:9200" ]
        manage_template => false
        index => "syslog-%{+YYYY.MM.dd}"
       }
    }
    }

**Comment by deviantony** [comment]
What happens if you remove all the `type` related code from the configuration ?

**Comment by ChaitDevOps** [comment]
thank you for replying. i used a basic one as well like below and still same. I updated the kibana.yml and logstash.conf to use I.P of server where ELK containers are installed and no luck.
 `input {

file {
            path => "/logstash/log/messages"
	    start_position => "beginning"
            }`
}

output {
    elasticsearch {
    hosts => [ "elasticsearch:9200" ]
    manage_template => false
    index => "syslog-%{+YYYY.MM.dd}"
   }
}`

**Comment by deviantony** [comment]
What if you use the following configuration ?

```
input {
  file {
    path => "/logstash/log/messages"
    start_position => "beginning"
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}
```

**Comment by ChaitDevOps** [comment]
I get an error:

20:36:56.295 [LogStash::Runner] INFO  logstash.agent - No persistent UUID file found. Generating new UUID {:uuid=>"3ff3622a-41d0-4524-b68c-92b3e119aca9", :path=>"/var/lib/logstash/uuid"}
20:36:56.455 [LogStash::Runner] ERROR logstash.agent - fetched an invalid config 

{:config=>"input {\n  file {\n    path => \"/logstash/log/messages\"\n    start_position => \"beginning\"\n  }\n}\n\noutput {\n  elasticsearch {\n    hosts => \"elasticsearch:9200\"\n  }\n}}\n\n", :reason=>"Expected one of #, input, filter, output at line 12, column 2 (byte 162) after "}

**Comment by ChaitDevOps** [comment]
Please close this issue. I added the `index => "logstash-%{+YYYY.MM.dd}"` to the above config and it worked.

**Comment by deviantony** [comment]
Perfect, glad it works !
