### ISSUE TITLE
[problem]grok parse logs

### ISSUE THREAD

**Issue by tranthien1794** [deviantony/docker-elk#94]
hi Anthony,

i have a problem with grok parse logs

some logs grok can parse some not

<a href="http://imgur.com/fuwr0fe"><img src="http://i.imgur.com/fuwr0fe.jpg" title="source: imgur.com" /></a>

my logstash config
```
filter {
        if [type] == "nginx_access" {
                grok {
                        patterns_dir => ["/etc/logstash/conf.d/patterns/"]
                        match => { "message" => "%{GREEDYDATA:nginx_host}" }
                        overwrite => [ "message" ]
                }
        }
}
```
sorry for my bad english

**Comment by antoineco** [comment]
I think this question belongs to the logstash community.
