### ISSUE TITLE
bug in setup? filebeat

### ISSUE THREAD

**Issue by jurivrljicak** [deviantony/docker-elk#945]
### Problem description

I think the setup has a problem regarding filebeat extension

#### Stack configuration

default conf

#### Docker setup

Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker Compose version v2.10.2

filebeat password is not injected in resulting file in container.
I edited it by hand and comunication with elastic worked

**Comment by antoineco** [comment]
We have automated tests for all core components and extensions, including Filebeat. I haven't seen any issue with it: https://github.com/deviantony/docker-elk/actions/runs/7154433257/job/19481945101

Are you certain that you read the README in the extension's directory and set a password for all required users in the `.env` file? After doing so, did you re-execute the `setup` container to apply changes?

**Comment by antoineco** [comment]
By the way, passwords aren't "injected" inside configuration files in containers. Elastic software supports referencing environmental variables from within configuration files, which is [what we do](https://github.com/deviantony/docker-elk/blob/4cbf55c4d3d3c0d1a19086eaa553ce3f7908e827/extensions/filebeat/config/filebeat.yml#L26). But like I said, a environmental variable is only made available to containers if it is set inside the `.env` file.

**Comment by jurivrljicak** [comment]
Ok, didnt't know the exact mechanism of the setup.

But yes, i followed those steps. In fact its the only module that after
setup gets an unauthorized error.

Running on mac.

Anyway, thanks for all of this.

Regards

**Comment by antoineco** [comment]
If you set non-empty values for these two passwords, run `docker compose up setup`, then restart Filebeat, it will authenticates without issue:

https://github.com/deviantony/docker-elk/blob/4cbf55c4d3d3c0d1a19086eaa553ce3f7908e827/.env#L29

https://github.com/deviantony/docker-elk/blob/4cbf55c4d3d3c0d1a19086eaa553ce3f7908e827/.env#L42

If it doesn't, I recommend reverting your changes (e.g. manually edited config files), resetting the stack as explained in the README, and trying again.

**Comment by skwee** [comment]
unsubscribe

Am Do., 14. Dez. 2023 um 20:34 Uhr schrieb Antoine Cotten <
***@***.***>:
