### ISSUE TITLE
Add note to README regarding elasticsearch-reset-password

### ISSUE THREAD

**Issue by jorgegomzar** [deviantony/docker-elk#956]
I couldn't reset the password for the logstash user, apparently it is not using the right URL for elastic.

Running this works:
```
docker-compose exec elasticsearch bin/elasticsearch-reset-password --batch --user elastic --url http://localhost:9200
```

**Comment by antoineco** [comment]
What was the error? Maybe you tried the command before Elasticsearch was ready to service requests?

`localhost:9200` is the default already. We run this command in automated tests to initialize passwords, they would start failing if it wasn't the case.

**Comment by jorgegomzar** [comment]
Hi! I was getting this same error as the screenshot attached (now I am setting up filebeat)
![imagen](https://github.com/deviantony/docker-elk/assets/34076979/d106fcdf-af17-4f93-9a3a-aefa7ddee8ed)

Checking logstash container logs I saw "elasticsearch" was not accessible, but kibana was already set up (was able to set up password and log in).

Tried several times with no luck, but adding `--url http://localhost:9200` actually made the script run against elastic's API

**Comment by antoineco** [comment]
Did you perform any change to the `elasticsearch.yml` file? The URL is determined based on the content of this file.

If you pass the `-v` flag to your previous command you should be able to see what URL the tool is using.

**Comment by jorgegomzar** [comment]
Hi, no, I did not change anything. Elasticsearch had been up for 10 minutes when I tried to change the passwd.

**Comment by antoineco** [comment]
I wasn't able to reproduce and there is no output of failing communication with the `-v` flag in this thread, so I'm going to go ahead and close the issue.

If the problem ever occurs again, feel free to reopen!
