### ISSUE TITLE
Change nameserver

### ISSUE THREAD

**Issue by Kottare** [deviantony/docker-elk#959]
Hi,
So far i've configured ELK stack with Fleet server and its working but I have one question.
Is it possible to change hostnames?
I dont want to add to hosts.cfg ip and names for fleetserver/elasticserver I want to assign them address like elasticsearch.MYDOMAIN.

I have proxy-manager and will forward domain to this IP, but without domain name i cannot do it.

**Comment by antoineco** [comment]
@Kottare this question is very generic. Here are a few things that need to be clarified:

- Do you have a DNS infrastructure in place to resolve MYDOMAIN?
- Is `proxy-manager` running on the same host as the Elastic stack? If yes, just attach it to the docker-elk network and it will be able to resolve internal service names such as `elasticsearch` (check the output of `docker network ls` to get the network name and id)

**Comment by Kottare** [comment]
Hi,
1. Yes, I have.
2. No, my NPM is installed on other VM.

At this point I have figure how to change all stuff in fleet server settings and have correct FQDN.
Agents seems to connect to server, but in CPU/memory I have N/A - thats mean they still have problem to connect to elasticsearch even if in ouputs settings I have "https://elasticsearch.DOMAIN:9200:"

I've enrolled agents aswell.

**Comment by Kottare** [comment]
Thanks for your advise, I've fixed it with modification.
For people who will look for resolution:

1. Installed nginx on machine with docker-stack
2. Reverse proxy for ip from docker network to :9200
3. On Proxy-manager create record to elasticsearch.domain:9200
