### ISSUE TITLE
How to send a log to logstash

### ISSUE THREAD

**Issue by martinGM05** [deviantony/docker-elk#985]
Hello everyone, I have a question about the logstash, I don't know what configuration I need set in my client to send logs to get it in logstash.

I have this Server in Express
![image](https://github.com/deviantony/docker-elk/assets/63875704/8341f112-56e6-40de-addf-c7cd91aafc41)

I have this configuration
![image](https://github.com/deviantony/docker-elk/assets/63875704/b0694001-273a-4bb4-b0d9-c9d2564e94dd)

When I go into the port which Docker say is the logstashs I can see this.
![image](https://github.com/deviantony/docker-elk/assets/63875704/47c065cd-ce59-4ee7-a06a-85c5b9ef6485)

**Comment by antoineco** [comment]
I'm not familiar with winston, but the UDP input isn't enabled by default: 

https://github.com/deviantony/docker-elk/blob/4df8c50ba8a1891c2cb4cd502ffc11868aec8cf1/logstash/pipeline/logstash.conf#L6-L8

In case your client doesn't support TCP, your can enable the UDP input inside the pipeline configuration: https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v3.5.0-plugins-inputs-udp.html
